### ISSUE TITLE
Use CocoaPods to handle 3rd party SDK dependencies

### ISSUE THREAD

**Issue by staminajim** [braintree/braintree_ios#100]
Hi, I'm wondering if it would be possible to use CocoaPods to handle the 3rd party dependencies (eg. PayPal sdk) instead of just including a copy inside the braintree repo.

This means that CocoaPods will handle multiple dependency problems for us, and also make it easy to keep the 3rd party libs up-to-date.

This specific request is because we use parts of the Paypal SDK in our app, and because of this we can't use the latest Paypal SDK with all it's shiny new toys and bug-fixes, and have to use whichever version was bundled in with the BrainTree source code.  PayPal-iOS-SDK at the time of writing is v2.8.4, and the bundled version is 2.7.1-bt1.

CocoaPods was designed to take away the manual labor aspect of wrangling multiple dependencies and keep them up to date so it'd be great if everything was up to date (or at least as close as possible) each time we ran `pod update` :)

Thoughts?

**Comment by burnto** [comment]
:+1: this is great feedback.

**Comment by mickeyreiss** [comment]
I would love this too.

On the bright side, we are currently planing to upgrade to the latest PayPal-iOS-SDK in our next release.

**Comment by staminajim** [comment]
Cool, thanks guys for the response.

IMHO CocoaPods has been the best thing to happen to iOS development since ARC and is a **huge** time-saver for dependency management ;)

Looking forward to the PayPal SDK update too :)

**Comment by intelliot** [comment]
Just to follow up on this-- we've updated the PayPal SDK to v2.8.4-bt1 on `master` as of 80e9e05e921ff8fbb84ebef17d15a53a1bea4592.

I believe you can use master in your Podfile with:
```
pod 'Braintree', :git => 'https://github.com/braintree/braintree_ios.git'
```

Let us know if you encounter any issues. Thanks!

**Comment by staminajim** [comment]
Cool, no problems using master in the podfile here.  Good to see the Card.IO source files are gone from the Paypal source files too :+1:

**Comment by mickeyreiss** [comment]
3.7.0 is now released on CocoaPods trunk and Github. We'll continue to look into making the PayPal components smaller, more modular, and being imported by CocoaPods.

Thanks for great feedback!
