### ISSUE TITLE
Appstore Connect Uploaded with Warning

### ISSUE THREAD

**Issue by Anthony-Todd-CGI** [braintree/braintree_ios#1003]
### Braintree SDK Version

5.21.0

### Environment

Sandbox

### Xcode Version

14.3

### Integration type

Swfit Package Manager

### Development Processor

Intel

### Describe the bug

There is an issue with the Cardinal mobile framework referencing non-public selectors. When uploading the app to the app store we get the following warning.

```
The app references non-public selectors in Payload/<App Name>/Frameworks/CardinalMobile.framework/CardinalMobile: cancelled, completed:, timedout
```

We have only been using Sandbox and have not tried a production build as of yet but is suspected we will have the same problem.

### To reproduce

Archive a build
Upload Archive to the app store.

### Expected behavior

Complete with no errors or warnings

**Comment by scannillo** [comment]
Hi @Anthony-Todd-CGI thank you for opening this issue with us. I am able to replicate this warning on an M1 mac on Xcode 14.3 and Xcode 14.2.

We will raise this issue to our partners at CardinalMobile.

![Screenshot 2023-04-12 at 10 07 47 AM](https://user-images.githubusercontent.com/35243507/231500888-4545b91a-f651-4242-bcea-14ef6520ace9.png)

**Comment by scannillo** [comment]
Internal Braintree tracking ticket: DTBTSDK-2575. Cardinal ticket: 00156682.
