### ISSUE TITLE
BTPayPalDriver crash on CarPlay

### ISSUE THREAD

**Issue by SerhiiKovalenkoStuzo** [braintree/braintree_ios#1005]
### Braintree SDK Version

5.20.1

### Environment

Sandbox

### Xcode Version

Xcode 14.1

### OS Version & Device

iPhone 12 - iOS 16.3.1 + CarPlay

### Integration type

CocoaPods

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

We have a payment application, supporting CarPlay. 
We got a few crashes happening when device is connected to CarPlay with next crash log:
`Fatal Exception: NSInvalidArgumentException
-[CPTemplateApplicationScene windows] unrecognized selector sent to instance ...
0  CoreFoundation                 0x9e38 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw
2  CoreFoundation                 0x17e81c +[NSObject(NSObject) _copyDescription]
3  UIKitCore                      0xd58128 -[UIResponder doesNotRecognizeSelector:]
4  CoreFoundation                 0x1ff50 ___forwarding___
5  CoreFoundation                 0x88320 _CF_forwarding_prep_0
6  Braintree                      0x17b7c (Missing UUID c2acfa7e95de39898750bc283857f378)
7  AuthenticationServices         0x21198 -[ASWebAuthenticationSession _startDryRun:]
8  Braintree                      0x16938 (Missing UUID c2acfa7e95de39898750bc283857f378)
9  Braintree                      0x16638 (Missing UUID c2acfa7e95de39898750bc283857f378)
10 Braintree                      0x16360 (Missing UUID c2acfa7e95de39898750bc283857f378)`
During investigation we have found incorrect work with scenes in BTPayPalDriver.m 
in method - (ASPresentationAnchor)presentationAnchorForWebAuthenticationSession:(ASWebAuthenticationSession *)session. 
Specifically scenes are casted to UIWindowScene class, where windows selector is available, without checking type.
However, if application supports CarPlay, `UIApplication.sharedApplication.connectedScenes` can also contain CPTemplateApplicationScene instances, where such selector is not available.
Please tune the logic in corresponding method, add checking type, so this method won't lead to crash.

### To reproduce

We do not have exact steps to reproduce. The crash was cought in Crashlytics, full trace can't be shared.
Potential steps to reproduce:
1. App is launced from CarPlay (so CarPlay scene is the first one in the `UIApplication.sharedApplication.connectedScenes`)
2. User adds PayPal on iPhone.
3. `presentationAnchorForWebAuthenticationSession` is triggered which leads to crash

### Expected behavior

Logic inside `presentationAnchorForWebAuthenticationSession` takes a scene which has a type `UIWindowScene` instead of the first item from `UIApplication.sharedApplication.connectedScenes`. So crash does not happen in this method.

**Comment by scannillo** [comment]
Hi @SerhiiKovalenkoStuzo thank you for opening this issue! Currently, we only develop and test our SDK for iOS and iPadOS.

Our product team will take a look to determine if CarPlay is something we want to include on our roadmap to support. DTBTSDK-2576 is the ticket ID for tracking.

**Comment by scannillo** [comment]
Also @SerhiiKovalenkoStuzo - can you provide information about the merchant trying to use the Braintree SDK with CarPlay and their use case?

**Comment by jaxdesmarais** [comment]
Hey @SerhiiKovalenkoStuzo -

After discussing this further with our product team they have indicated that we do not plan to support CarPlay.
