### ISSUE TITLE
No module found Braintree on Xcode 14.2

### ISSUE THREAD

**Issue by HimanDhawan** [braintree/braintree_ios#1006]
### Braintree SDK Version

5.21.0

### Environment

Sandbox

### Xcode Version

Xcode 14.2

### OS Version & Device

iPhone 12 or Any

### Integration type

CocoaPods

### Development Processor

Intel

### Describe the bug

Unable to import the braintree module. When braintree is imported, we get "no module found for braintree" just after importing it in view controller file on intel Mac. This works fine on M1 Mac. 

Cocopods version : 1.11.2
Code link : https://github.com/HimanDhawan/BraintreeSDK

Note : Same steps is working for us in M1 chip by excluding arm64 settings. But on intel, it is not working and we have not excluded arm64 on intel. 

### To reproduce

1. Create Fresh project on Xcode 14.2 on intel Mac 
2. Pod init 
Add this text to pod file 
pod 'Braintree'
3. Pod install
4. Open workspace 
5. Import braintree on app delegate 
6. Error appears that "No module found for braintree"

### Expected behavior

The braintree should be imported successfully.

### Screenshots

![Screenshot 2023-04-12 at 3 36 12 PM](https://user-images.githubusercontent.com/16226329/231426301-00860d10-d7dd-41db-be50-6fb0eea3aae8.png)

**Comment by nrajput05** [comment]
Having the same issue with Intel Mac. Braintree please help?

**Comment by scannillo** [comment]
Hi @HimanDhawan, thanks for opening this issue! While we work to replicate this on an Intel machine, is this something you're able to replicate on an M1 Mac in Rosetta mode, or solely on Intel?

**Comment by scannillo** [comment]
👋 Still working through a few internal blockers getting an Intel test machine up and running. Working on it!

**Comment by scannillo** [comment]
Hi all. I am not able to replicate this using CocoaPods 1.12.1, Xcode 14.3, and Braintree 5.21.0 on an Intel.

Can you update to these latest versions?

**Comment by HimanDhawan** [comment]
@scannillo we are able to make it work. We need one more confirmation. Do we need to include arm64 from excluded architecture in my Mac.
**My configurations :** 
M1 chip
Xcode 14.2

**Comment by HimanDhawan** [comment]
@scannillo we can close this issue. I have raise another issue for swiftui previews.
