### ISSUE TITLE
Phone number is missing "/v1/payment_methods/paypal_accounts" 

### ISSUE THREAD

**Issue by huextrat** [braintree/braintree_ios#1007]
### Braintree SDK Version

5.21.0

### Environment

Both

### Xcode Version

Xcode 14.2

### OS Version & Device

iPhone 14 Pro

### Integration type

CocoaPods

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

When calling the `requestOneTimePayment` method, it returns an object of type `BTPayPalAccountNonce` which contains various information about the paypal account, including the phone according to the documentation and [code](https://github.com/braintree/braintree_ios/blob/25a1ca56d5a3ada45ef960dba5525107e335ec15/Sources/BraintreePayPal/BTPayPalDriver.m#L396).

On closer inspection of `BTPaypalDriver` I found that the API call [`/v1/payment_methods/paypal_accounts`](https://github.com/braintree/braintree_ios/blob/25a1ca56d5a3ada45ef960dba5525107e335ec15/Sources/BraintreePayPal/BTPayPalDriver.m#L584) does return information about the paypal account used, but the phone number was still missing.

### To reproduce

1. Call `requestOneTimePayment` from `BTPaypalDriver`
2. Expect an object of type `BTPayPalAccountNonce` (ie: `BTPayPalAccountNonce * _Nullable tokenizedPayPalAccount`)
3. `tokenizedPayPalAccount.phone` is not existing 

### Expected behavior

The phone number should be retrievable along with the paypal account information used.

1. Call `requestOneTimePayment` from `BTPaypalDriver`
2. Expect an object of type `BTPayPalAccountNonce` (ie: `BTPayPalAccountNonce * _Nullable tokenizedPayPalAccount`)
3. `tokenizedPayPalAccount.phone` is not null

**Comment by scannillo** [comment]
Hi @huextrat - I am able to replicate this issue on sand and prod. This is an issue with the underlying API ([/v1/payment_methods/paypal_accounts](https://github.com/braintree/braintree_ios/blob/25a1ca56d5a3ada45ef960dba5525107e335ec15/Sources/BraintreePayPal/BTPayPalDriver.m#L584) as you pointed out) not returning the phone number. We will work with that team and get back to you!

(Ticket DTBTSDK-2629 for internal tracking).

**Comment by scannillo** [comment]
👋 So I confirmed with your Pay with PayPal and Support teams that sending billing phone number is something that needs to be enabled on your merchant account.

Please reach out to [Support](https://developer.paypal.com/braintree/help) with your merchant IDs for sand & prod and they can help you get this ironed out!
