### ISSUE TITLE
Add Android like card-form on iOS as alternative to Drop-In UI

### ISSUE THREAD

**Issue by BhosaleNikhil** [braintree/braintree_ios#1029]
### Is your feature request related to a problem? Please describe.

Earlier we were using Stripe for adding cards. Stripe has their own generic UI to add card along with all the validation. We decided to switch to Braintree and started using Braintree Drop-In UI. But the problem with Braintree Drop-In is, it doesn't seem to be intuitive plus it is not unified experience when it comes to adding cards. Our designers didn't like it and due to this reason we decided to use custom UI on iOS. Since we are using CustomUI so many things we need to handle on our end. It;s like creating our own card inout library.

### Describe the solution you'd like.

When it comes to Android the `com.braintreepayments:card-form`: library provided by Braintree is exactly similar to regular generic add card screen which is more convenient. So wouldn't it be possible for Braintree to introduce same library for iOS as well?

**Comment by scannillo** [comment]
:wave: Hi @BhosaleNikhil - thank you for opening this feature request. This is really valuable feedback for our team.

However, can you instead open the issue in the corresponding [Drop-In repo](https://github.com/braintree/braintree-ios-drop-in) so we can appropriately get community interest for other folks with the same concerns?
