### ISSUE TITLE
Saving BTMutableCardPaymentMethod to Keycain

### ISSUE THREAD

**Issue by SolomonBier** [braintree/braintree_ios#104]
I'm unable to save `BTMutableCardPaymentMethod` to the Keychain because it does not respond to `encodeWithCoder`. Can this ability be added so default payment can be saved without having to be reloaded every time ?

**Comment by mickeyreiss** [comment]
Can you go into more depth as to why you would need to save this object in the keychain? 

`BTPaymentMethod`'s contain a nonce, which is a short-lived, single-use token that can be used to [save a payment method in the vault](https://developers.braintreepayments.com/ios/start/vault). There is no reason to persist them on the client.

**Comment by burnto** [comment]
This is a great question, and shows that we aren't sufficiently documenting payment method nonces and their properties of being short-lived and single-use. Part of the issue, I think, is simply our naming choice.

**Comment by SolomonBier** [comment]
@mickeyreiss ah I see. Well this complicates the issue further

The Drop in UI is not actually showing other cards on the screen (see this S.O. thread)
http://stackoverflow.com/questions/28826574/braintree-drop-in-ui-does-not-show-other-payment-methods

I'm manually pulling the CC info each time a user checks out. Some more tangential questions (I can open a new issue is necessary)

1.  Why are extra CC's being show in the drop-in UI as shown in the tutotrial.
2. The doesn't `BTPaymentMethod's` include its individual token? The documentation states in order to update a customers payment method, one must send the payment methods token. However `BTPaymentMethod's` only includes a `nonce` property, and trying to update with this property returns a validation error CVV not found.


    result = Braintree::PaymentMethod.update(
  "the_token",
  :options => {
    :make_default => true
  }
)
