### ISSUE TITLE
Unable to Update BTPaymentMethod on client side

### ISSUE THREAD

**Issue by SolomonBier** [braintree/braintree_ios#105]
The documentation states in order to update a customers payment method, one must send the payment methods `token`. However `BTPaymentMethod's` only includes a `nonce` property, and trying to update with this property returns a validation error CVV not found.

    result = Braintree::PaymentMethod.update(
      "the_token",
      :options => {
        :make_default => true
      }
    )

**Comment by burnto** [comment]
@SolomonBier OK so first, yes, a payment method _nonce_ is distinct from a payment method _token_, so you can't use a `nonce` as the value for the `token`. A nonce is a short-lived

As to updating, I suggest you approach vaulted payment methods as immutable resources, and [create a new payment method](https://developers.braintreepayments.com/ios+ruby/reference/request/payment-method/create) for that customer using a `payment_method_nonce`. In your server code:

```ruby
result = Braintree::PaymentMethod.create(
  :customer_id => "131866",
  :payment_method_nonce => "nonce-from-the-client",
  :options => {
    :make_default => true
  }
)
if result.success?
  # Use result.payment_method.token
else
  # Handle result.errors
end
```

You can then delete the old payment method, if you like:

```ruby
Braintree::PaymentMethod.delete("old-payment-method-token")
```

Does this help?

**Comment by SolomonBier** [comment]
@burnto this depends. Won't this create a duplicate card ? I.e. if I download all the users `BTPaymentMethod`'s methods and display them will it show these cards twice? 

Also, how would I know "old-payment-method-token" from `BTPaymentMethod`s `nonce` property? 

The goal is allow the user to see a visual interface that displays their `BTPaymentMethod`'s and allow them to click to make a payment method their new default. In the drop down UI- a user has to manually change their card EVERYTIME they checkout. 

I'll submit a pull request as I added the responsiveness to the visual interface, I just need to communicate this to the server

**Comment by mickeyreiss** [comment]
Hi @SolomonBier!

Unfortunately, `-[BTClient fetchPaymentMethodsWithSuccess:failure:]` does not support your use case yet. While I agree that it would be nice if it accounted for the customer's default payment method, it does not right now. Same goes for a method to update the default payment method directly from the client.

I think the easiest solution at this point would be to create your own "fetchPaymentMethods" API endpoint alongside your server-side integration. You could then use a combination of the server-facing methods as well as your own database/business logic to fetch the index and update the default. 

To update the customer, you'd send a request your server along with a client-safe identifier that can be dereferenced to a payment method token on your server.

We are going to continue to research how to improve our support for different types of client-side integrations—your feedback is appreciated!

**Comment by SolomonBier** [comment]
@mickeyreiss so to recap, you're saying use the following and save the `token` to my datebase? This seems do-able but is this safe? If so I'll go this route. Feel free to label as a question/feature request. I linked your answers to the documentation below. 

Create CC with method

     result = Braintree::PaymentMethod.create(
    :customer_id => "131866",
    :token => "the_token",  //specify so not a randomly generated token
    :payment_method_nonce => "nonce-from-the-client"
    )

Then found with this method

    search_results = Braintree::Customer.search do |search|
    search.payment_method_token.is "the_payment_method_token"
    end

Then update with method

      result = Braintree::PaymentMethod.update(
     "the_token",
     :options => {
      :make_default => true
      }
    )

**Comment by mickeyreiss** [comment]
In general, it is safe to save the `token` to your database.

> When a payment method is stored in the Vault, the information is encrypted by the Braintree gateway and associated with a unique payment method token. This token can be used to create transactions without the PCI compliance burden that comes with handling unencrypted data.

(From https://articles.braintreepayments.com/control-panel/vault/overview)

I don't see a specific reason why you'd want to specify the token. You can if it makes sense for your implementation—that's up to you.

In addition, if you have any API endpoints that accept a payment method token, make sure to validate the user input and/or scope on customers. You don't want to expose an attack vector where customers can charge other customers' payment methods. This is why usually suggest avoiding exposing payment method tokens outside of your server.

**Comment by hrehman200** [comment]
I also tried the following in php:

$result = Braintree_PaymentMethod::update($pm_token, array(
			'options' => array(
				'makeDefault' => true
			)
		));

but it says <b>Gateway rejected: cvv</b>. Note that I am using the proper payment method token which I copied from my account on https://sandbox.braintreegateway.com/

**Comment by mickeyreiss** [comment]
@hrehman200 I don't think this issue is related to our iOS SDK or to the original post (which was about updating a payment method from an iOS app directly).

Do you happen to have [Basic Fraud Rules](https://developers.braintreepayments.com/javascript+php/sdk/server/payment-method-management/verifications) enabled? I think it may be possible to bypass the cvv rejection by passing `'verifyCard' => false` into the `options`  `array`.

Please contact our [support team](support@braintreepayments.com) if you have any more questions about the server-side behavior.

**Comment by SolomonBier** [comment]
@mickeyreiss @burnto Shockingly, after much inspection, it turns out your backend does support this via the following:

Send in a payment method create call 

        result = Braintree::PaymentMethod.create(
            :customer_id => @customer.braintree_id.to_s,
            :payment_method_nonce => @session_detail.payment_nonce,
        )


If this is a duplicate method, this does NOT create a duplicate credit card if the card already exists. 

The resulting response object `result` param keys are apparently language dependent, but the token can be accessed via ruby:

 token_id = result.payment_method.token

And then updating with

    result = Braintree::PaymentMethod.update(
     "the_token",
     :options => {
       :make_default => true
      }
    )

**Comment by burnto** [comment]
@SolomonBier thanks. 

So to clarify (and to recap for future readers):

* The original issue you reported was that you expected to be able to update a `BTPaymentMethod` on the client-side, but didn't know how, which is because it isn't supported. 
* We pointed out that you can create a new payment method in your server code using the nonce, but your (valid) concern was that it would needlessly create a duplicate method when all you're really trying to do is just update.
* You've discovered (and are shocked! :scream:) that the `Braintree::PaymentMethod.create` invocation above does not actually create a new payment method if the provided `:payment_method_nonce` represents a card that already exists for that customer. I agree this seems like surprising behavior, and we should probably note this in our docs.
* Given the above behavior, you get back a token in the result, which you can use to make the payment method the default for that customer.

Sound right? Apart from the docs issue, anything else we could have done differently to make all this easier for you?

**Comment by SolomonBier** [comment]
@burnto 

1. There is absolutely no documentation on the response objects for creating a credit card of payment method. This must be added

 Also, according to the API support team, the response object `result` dictionary returns the payment method with either a `credit_card` key or a `payment_method` key, depending on the language. I believe Ruby and Python both use `payment_method`.

So clearly this was/is a documentation issue! 

1. A much smaller issue is that when defining your own token 

         result = Braintree::PaymentMethod.create(
           :customer_id => @customer.braintree_id.to_s,
           :payment_method_nonce => @session_detail.payment_nonce,
           :token => "your_token",
          )

If the payment method already exists, the `result` object will return a success as indicated in case 1, but there is no message that the `result.payment_method.token` returned is rightfully the original `token` (some `message` key could be useful). This can lead to errors if trying to reference `"your_token` and should be labeled as a warning.

**Comment by burnto** [comment]
Great feedback. Thanks again. We'll address these problems in the docs.
