### ISSUE TITLE
duplicate symbol BTError*

### ISSUE THREAD

**Issue by RolandasRazma** [braintree/braintree_ios#106]
I'm using cocoa pods to install braintree on empty project.
I do `#import <Braintree/Braintree.h>` in 2 files and I'm getting `duplicate symbol` errors for simulator but not for device.

```
duplicate symbol _BTErrorCode in:
    build/Objects-normal/x86_64/ViewController.o
    build/Objects-normal/x86_64/AppDelegate.o
duplicate symbol _BTAppSwitchErrorCode in:
    build/Objects-normal/x86_64/ViewController.o
    build/Objects-normal/x86_64/AppDelegate.o
duplicate symbol _BTPayPalErrorCode in:
    build/Objects-normal/x86_64/ViewController.o
    build/Objects-normal/x86_64/AppDelegate.o
duplicate symbol _BTPaymentProviderErrorCode in:
    build/Objects-normal/x86_64/ViewController.o
    build/Objects-normal/x86_64/AppDelegate.o
```

Am i missing something?

sample project:
https://www.dropbox.com/s/rzxbbv317yh3goy/braintree.zip

**Comment by SolomonBier** [comment]
@RolandasRazma can you try `#import "Braintree.h"` instead ?

**Comment by RolandasRazma** [comment]
same thing

**Comment by intelliot** [comment]
Which versions of Xcode and CocoaPods are you using?

**Comment by intelliot** [comment]
@RolandasRazma I did some investigation of your sample project and found the problem:

```GCC_NO_COMMON_BLOCKS = YES;```

This line/setting in your `xxx.xcodeproj` file is causing the error. If you remove it, the project compiles successfully. Did you set this flag intentionally?

**Comment by RolandasRazma** [comment]
@intelliot good find. I didn't set it myself. Xcode 6.3 beta sets it by default to new projects.

**Comment by intelliot** [comment]
We've fixed a bug in `master` so that you should be able to keep `GCC_NO_COMMON_BLOCKS = YES;` if you want.

Here's an example of using the `master` branch with your repo:
```
pod 'Braintree', :git => 'git@github.com:braintree/braintree_ios.git', :branch => 'master'
```
If you prefer, you can also specify a specific commit instead.

Thank you for letting us know about this issue!
