### ISSUE TITLE
Error tokenizing payment - Apple Pay decryption failed - no matching key found #684

### ISSUE THREAD

**Issue by piyush-bryj** [braintree/braintree_ios#1065]
### Braintree SDK Version

5.10.0

### Environment

Both

### Xcode Version

14.2

### OS Version & Device

iOS 16.4

### Integration type

CocoaPods

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

I'm getting the Error Domain=com.braintreepayments.BTHTTPErrorDomain Code=2 "Apple Pay decryption failed - no matching key found"

`{com.braintreepayments.BTHTTPURLResponseKey=<NSHTTPURLResponse:0x6000005c00a0> { URL: https://api.braintreegateway.com:443/merchants/mhgf8np8fsvknyp6/client_api/v1/payment_methods/apple_payment_tokens } { Status Code: 422, Headers {\n    \"Cache-Control\" =     (\n        \"no-cache\"\n    );\n    \"Content-Encoding\" =     (\n        gzip\n    );\n    \"Content-Security-Policy\" =     (\n        \"frame-ancestors \'self\'\"\n    );\n    \"Content-Type\" =     (\n        \"application/json; charset=utf-8\"\n    );\n    Date =     (\n        \"Tue, 27 Jun 2023 14:36:46 GMT\"\n    );\n    \"Strict-Transport-Security\" =     (\n        \"max-age=31536000; includeSubDomains\"\n    );\n    \"Transfer-Encoding\" =     (\n        Identity\n    );\n    Vary =     (\n        \"Accept, Accept-Encoding, Origin\"\n    );\n    \"X-BroxyId\" =     (\n        \"a9d8d904-8653-4b2f-b39e-c9a42635eb67\"\n    );\n    \"X-Content-Type-Options\" =     (\n        nosniff\n    );\n    \"X-Frame-Options\" =     (\n        SAMEORIGIN\n    );\n    \"X-XSS-Protection\" =     (\n        \"1; mode=block\"\n    );\n    \"paypal-debug-id\" =     (\n        5b599ab647ee4\n    );\n    \"referrer-policy\" =     (\n        \"strict-origin-when-cross-origin\"\n    );\n    \"x-download-options\" =     (\n        noopen\n    );\n    \"x-permitted-cross-domain-policies\" =     (\n        none\n    );\n    \"x-request-id\" =     (\n        \"a9d8d904-8653-4b2f-b39e-c9a42635eb67\"\n    );\n    \"x-runtime\" =     (\n        \"0.040114\"\n    );\n} }, com.braintreepayments.BTHTTPJSONResponseBodyKey=<BTJSON:0x6000005c8100 value:{\n    error =     {\n        message = \"Apple Pay decryption failed - no matching key found\";\n    };\n    fieldErrors =     (\n    );\n}>, NSLocalizedDescription=Apple Pay decryption failed - no matching key found, NSLocalizedFailureReason=client error}`

### To reproduce

App is not processing request successfully.

### Expected behavior

Both targets should process request successfully.

**Comment by scannillo** [comment]
👋 Hello @piyush-bryj - can you please update your SDK version to the latest and see if the issue still occurs?
