### ISSUE TITLE
Make BTPayPalLocaleCode a string enum, instead of Int

### ISSUE THREAD

**Issue by mikezaslavskiy** [braintree/braintree_ios#1079]
### Is your feature request related to a problem? Please describe.

Now in order to set the locale for `BTPayPalVaultRequest` we need to write a mapper from the device's locale code - which are defined as a string, to the Int value. 

E.g. previously it was as easy as:
`BTPayPalVaultRequest().localeCode = Locale.local.identifier`

### Describe the solution you'd like.

Can we just make `BTPayPalLocaleCode` a string enum instead? For easier locale setting?

**Comment by jaxdesmarais** [comment]
Hello @mikezaslavskiy -

> Can we just make BTPayPalLocaleCode a string enum instead?

We cannot make `BTPayPalLocaleCode` a string enum as our SDK supports both Objective-C and Swift. Enums need to be of the `Int` type to support our Objective-C merchants. We decided to move to an Enum for this value as previously it was not clear the exact formatting needed by the underlying PayPal APIs. This resulted in merchants passing the wrong value for the locale code whereas an enum allows the locale code to always be formatted as our APIs expect.

We can consider exposing the underlying [string value](https://github.com/braintree/braintree_ios/blob/2afdcd73611c5698379334ef4187e1d93c670868/Sources/BraintreePayPal/BTPayPalLocaleCode.swift#L34) if you feel that that would be helpful for this use case.

**Comment by mikezaslavskiy** [comment]
Can we maybe create a custom initializer that takes in the Locale code(string?) as an input? To avoid having a mapping logic on the client's side?

**Comment by jaxdesmarais** [comment]
I am curious how you were previously handling locales that were not supported by the SDK that were returned from `Locale.current.identifier`? I would expect in these cases there would be some logic and if not supported, provide a default value to our SDK? There are certainly options we can explore here, but wanting to fully understand how you're previously handling unsupported locales would be helpful.

**Comment by mikezaslavskiy** [comment]
It was just `BTPayPalVaultRequest().localeCode = Locale.local.identifier` before, we didn't default to anything in case of unsupported locale
