### ISSUE TITLE
Make errors public

### ISSUE THREAD

**Issue by mikezaslavskiy** [braintree/braintree_ios#1080]
### Is your feature request related to a problem? Please describe.

In 6.x.x release the errors become internal with a reference to use error codes instead from [this](https://github.com/braintree/braintree_ios/blob/main/SDK_ERROR_CODES.md) list. Meaning that developers who are using the SDK will probably need to compare the error codes. However, this might be a bit unsafe since the developers have no control over the internal processes and modifications to error codes and can't be sure that the error code won't change in the future, potentially causing an outage.

### Describe the solution you'd like.

Make error codes public

**Comment by jaxdesmarais** [comment]
Hello @mikezaslavskiy -

Similar to the [locale code issue](https://github.com/braintree/braintree_ios/issues/1079) we cannot expose the errors publicly as we support both Swift and Objective-C. Objective-C enums require a raw `Int` type. 

Could you share a bit more about how you're looking to use the error codes in the error enum? Our intent is to follow semantic versioning with our error codes, but we'd like to understand your use case a bit better to ensure we are coming up with the best solution.

**Comment by mikezaslavskiy** [comment]
So in our codebase, we will need to define the errors we need to handle ourselves and map them to the error codes provided in the documentation. However, the biggest fear here is for some reason error codes will change under the hood - our error-handling logic might be broken. How stable will be the error codes provided in the documentation? As far as I understand you don't plan to change them? If you will - will it be considered a breaking change?

**Comment by jaxdesmarais** [comment]
Hey @mikezaslavskiy -

I know this is quite an old issue but just wanted to let you know we moved forward with a decision to make our errors public (and equatable). This change was released in [version 6.11.0](https://github.com/braintree/braintree_ios/releases/tag/6.11.0) and should make it easier to compare errors without relying on the code documentation if desired. 🚀
