### ISSUE TITLE
PayPalDataCollector.h

### ISSUE THREAD

**Issue by alc-at-ae** [braintree/braintree_ios#1092]
### Braintree SDK Version

5.23.0

### Environment

Both

### Xcode Version

14.3.1

### Integration type

CocoaPods

### Development Processor

Intel

### Describe the bug

Getting `'PayPalDataCollector.h' file not found` when attempting to archive. Expanding the Braintree cocoapods project shows there is no such file.

### To reproduce

Select app > Any iOS Device for device
Product -> Archive

### Expected behavior

It archives!

### Screenshots

![image](https://github.com/braintree/braintree_ios/assets/43971222/0140f801-bc2d-46b1-ae6c-24708a510bda)

**Comment by jaxdesmarais** [comment]
Hello @alc-at-ae -

The file in your screenshot does not look like one of our header files from v5.23.0 of the Braintree SDK. Is this a custom header file? If so, since the `PayPalDataCollector` is a Swift module you will need to update your import to `PayPalDataCollector-Swift.h`.

**Comment by alc-at-ae** [comment]
it's a bridging file created by CocoaPods i think

**Comment by alc-at-ae** [comment]
Not sure what's going on, just going to revert what I've done and try to upgrade to 6.0 when I have time. Sorry for any confusion.

**Comment by jaxdesmarais** [comment]
@alc-at-ae -

Interesting, I have been unable to reproduce in a cocoapods project using 5.23.0. If you're able to provide a small sample project, we'd be happy to take a look! Otherwise please let us know if you run into issue when updating to version 6.
