### ISSUE TITLE
fetchPaymentMethodNonces in BTAPIClient return wrong nonce types

### ISSUE THREAD

**Issue by haojin2020** [braintree/braintree_ios#1099]
### Braintree SDK Version

6.6.0

### Environment

Sandbox

### Xcode Version

Xcode 14.3.1

### OS Version & Device

iOS 16.4

### Integration type

CocoaPods

### Development Processor

Intel

### Describe the bug

The fetchPaymentMethodNonces method in BTAPIClient always returns the nonce in the "Unknown" type.

Root cause: After the SDK migrated to Swift. The jsonParsingBlocks in BTPaymentMethodNonceParser is not get registered with different types.  

### To reproduce

1. Call fetchPaymentMethodNonces in BTAPIClient when there are saved nonce.
2. Debug the nonce values. (Check the screenshot)

### Expected behavior

1. The SDK should behave as the Objective-C version
2. The nonce type should be the correct type.

### Screenshots

![CleanShot 2023-09-14 at 09 07 13@2x](https://github.com/braintree/braintree_ios/assets/66354606/603c7615-a0e0-4dad-9160-7c204e935ea8)

**Comment by haojin2020** [comment]
In the Objective-C version of the SDK, the parsing blocks are registered in +load, as you can see in the below image. But I didn't see any place do the same thing in the Swift version.

<img width="874" alt="CleanShot 2023-09-14 at 09 10 12@2x" src="https://github.com/braintree/braintree_ios/assets/66354606/3508df4f-5b95-4f7c-9c75-f0ca06c74977">

**Comment by jaxdesmarais** [comment]
Hello @haojin2020 -

Thanks so much for reporting this issue! I was able to reproduce the behavior you are seeing and this is certainly a bug introduced in v6. I've opened PR #1100 to resolve this issue on our side. Please feel free to pull down that branch to ensure things are working as expected now on your side.

**Comment by jaxdesmarais** [comment]
🤔  we may actually have to get creative with our solution since the load method does not exist in Swift. Right now _some_ of the types work as expected but for example the credit card types aren't passed through as expected. We will dig into this a bit more and come up with a solution that can work in the same way it did in Obj-C. Thanks again for bringing this to our attention.
