### ISSUE TITLE
App Crash when call braintreeWithClientToken:

### ISSUE THREAD

**Issue by tuanphung** [braintree/braintree_ios#112]
Hi,

I tried to use BrainTree to process transactions for my application. Everything are setup completely (Client: iOS, Server: NodeJS). I could generate Client Token and use it to initialize BrainTree Object as well.
My code:
self.braintree = [Braintree braintreeWithClientToken:self.clientToken];

However, problem is that when I enabled "Accept Apple Pay", I re-generate Client Token (I see the new clientToken is longer than previous clientToken), then I got an error when initialize BrainTree Object.

2015-04-06 17:05:32.390 ApplePaySample[2999:158102] [BraintreeSDK] ERROR BTClient could not initialize because the provided clientToken was invalid
2015-04-06 17:05:32.423 ApplePaySample[2999:158102] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'BTClient could not initialize because the provided clientToken was invalid'

What's wrong? Could you please help me explain why?

Thanks,

**Comment by burnto** [comment]
Thanks @tuanphung.

- Which version of Braintree iOS are you using? You can get this out of your Podspec.
- Can you email your Braintree Merchant ID to support@braintreepayments.com, and include a link to this issue?

**Comment by tuanphung** [comment]
Thanks @burnto 

The version I'm using is 3.7.1. I email to Braintree Support Team too.
I wonder why the issue happen only I enabled "Accept Apple Pay"? It worked well when I disabled Apple Pay.
FYI: I'm using a sandbox account.

**Comment by burnto** [comment]
Thanks @tuanphung - I see you're communicating directly with our support team. We'll follow up when we learn more about what's happening. My hunch is that you've found a bug.

**Comment by tuanphung** [comment]
Hi @burnto ,
The problem was resolved without changes anything in source code. So, it's not a bug of iOS SDK. 
I think the bug come from API for generating clientToken. Anyway, the support team helped me fix that issue.
Thanks a lot,
