### ISSUE TITLE
Unable to Publish Build to App Store with Xcode 15.0

### ISSUE THREAD

**Issue by kunal30xi** [braintree/braintree_ios#1124]
### Braintree SDK Version

6.6.0

### Environment

Production

### Xcode Version

15.0

### Integration type

Carthage

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

We are getting ready to submit the app binary to the App Store this week and are encountering the following issue when submitting the build to the App Store (and it seems tied to the PPRiskMagnes.framework).

```
NSUnderlyingError = "Error Domain=IrisAPI Code=-19241 \"Asset validation failed\" UserInfo={status=409, detail=Invalid Bundle. The bundle <AppName>.app/Frameworks/PPRiskMagnes.framework does not support the minimum OS Version specified in the Info.plist., id=28349a7e-0559-4e38-bfd8-8b47cff4f9a5, code=STATE_ERROR.VALIDATION_ERROR.90208, title=Asset validation failed, NSLocalizedFailureReason=Invalid Bundle. The bundle <AppName>.app/Frameworks/PPRiskMagnes.framework does not support the minimum OS Version specified in the Info.plist., NSLocalizedDescription=Asset validation failed}
```

The minimum deployment target for the App is set to be 16.0 since we are supporting iOS 16 and 17 *only* with this build. Using `vtool` (Mach-O version number utility) I can tell that both the minos version in the PPRiskMagnes.framework and the app binary match (output is attached):

VTool output from App binary
```
Load command 11
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform IOS
    minos 16.0
      sdk 17.0
   ntools 1
     tool LD
  version 1015.7
Load command 12
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
```

VTool output from the PPRiskMagnes.framework
```
Load command 8
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform IOS
    minos 16.0
      sdk 17.0
   ntools 1
     tool LD
  version 1015.7
Load command 9
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
```

Any help in diagnosing the issue would be greatly appreciated.

### To reproduce

* Use Carthage to pull in Braintree Libraries (to support Venmo)
* Use Xcode 15.0
* Build IPA for Release
* Attempt submission to App Store

### Expected behavior

App should be able to be submitted to the App Store without any validation failures from the application loader tool (altool).

**Comment by jaxdesmarais** [comment]
Hello kunal30xi -

Thanks for reaching out and using the SDK. I was just able to successfully upload our [Demo app](https://github.com/braintree/braintree_ios/tree/main/Demo) to TestFlight with a minimum target of 16.0 without issue. Are you able to share additional details around your application setup? I was able to find a few StackOverflow issues related to this error and using Flutter, but am unsure if your application is built using Flutter.

We look forward to hearing back and troubleshooting further.

**Comment by kunal30xi** [comment]
Thanks @jaxdesmarais  -

We are not using Flutter. We do have a workaround in place for the time being which is to patch the Info.plist of PPRiskMagnes.framework' MinimumOSVersion key with the Minimum Deployment Target set for the App (16.0).

As an aside, when we build the IPA, in all cases (with the exception of PPRiskMagnes.framework) the MinimumOSVersion in the Info.plist and the minos value in the tool output of a framework match.

```
vtool -show PPRiskMagnes
PPRiskMagnes:
Load command 8
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform IOS
    minos 16.0
      sdk 17.0
   ntools 1
     tool LD
  version 1015.7
Load command 9
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
```

```
plutil -convert xml1 Info.plist
cat Info.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>BuildMachineOSBuild</key>
        <string>21G419</string>
        <key>CFBundleDevelopmentRegion</key>
        <string>en</string>
        <key>CFBundleExecutable</key>
        <string>PPRiskMagnes</string>
        <key>CFBundleIdentifier</key>
        <string>com.paypal.PPRiskMagnes</string>
        <key>CFBundleInfoDictionaryVersion</key>
        <string>6.0</string>
        <key>CFBundleName</key>
        <string>PPRiskMagnes</string>
        <key>CFBundlePackageType</key>
        <string>FMWK</string>
        <key>CFBundleShortVersionString</key>
        <string>1.0</string>
        <key>CFBundleSupportedPlatforms</key>
        <array>
                <string>iPhoneOS</string>
        </array>
        <key>CFBundleVersion</key>
        <string>1</string>
        <key>CORR_ID_HEADER_KEY</key>
        <string>paypal-debug-id</string>
        <key>DTCompiler</key>
        <string>com.apple.compilers.llvm.clang.1_0</string>
        <key>DTPlatformBuild</key>
        <string>20C52</string>
        <key>DTPlatformName</key>
        <string>iphoneos</string>
        <key>DTPlatformVersion</key>
        <string>16.2</string>
        <key>DTSDKBuild</key>
        <string>20C52</string>
        <key>DTSDKName</key>
        <string>iphoneos16.2</string>
        <key>DTXcode</key>
        <string>1420</string>
        <key>DTXcodeBuild</key>
        <string>14C18</string>
        <key>MinimumOSVersion</key>
        <string>11.0</string>
        <key>PAYLOAD_ENDPOINT</key>
        <string>https://api-m.paypal.com/AccessControl/LogRiskMetadata</string>
        <key>UIDeviceFamily</key>
        <array>
                <integer>1</integer>
                <integer>2</integer>
        </array>
        <key>UIRequiredDeviceCapabilities</key>
        <array>
                <string>arm64</string>
        </array>
</dict>
```

As you can see there is a difference between the MinimumOSVersion set in the Info.plist vs the vtool output.

**Comment by jaxdesmarais** [comment]
Hey @kunal30xi -

Are you able to provide a small sample app and steps we can take where we can reproduce this error? We also attempted to upload our [Carthage demo app](https://github.com/braintree/braintree_ios/tree/main/SampleApps/CarthageTest) with the same settings but were unable to replicate in that demo app as well.

**Comment by kunal30xi** [comment]
Hey @jaxdesmarais I'm able to reproduce this error with the Carthage demo app that you have available in the `braintree_ios` repo. The difference why you may not be getting the error is that the Carthage demo app is not setup to Embed & Sign the frameworks. Once you do that, the error is easily reproducible with Xcode 15. Attaching screenshots.

<img width="1355" alt="change-frameworks-embed-and-sign" src="https://github.com/braintree/braintree_ios/assets/5438564/dcd59a95-cc2b-4443-8fa9-532b4bb05e20">
<img width="743" alt="validation-error-xcode-15" src="https://github.com/braintree/braintree_ios/assets/5438564/fc1c0f11-3b80-4d65-b1e5-29028574aaf0">

Its important to note that this behavior seems to have changed with Xcode 15, we've not previously encountered this issue before.

**Comment by jaxdesmarais** [comment]
Hey @kunal30xi -

Thanks for sending over those reproducible steps! Since `PPRiskMagnes` is a static library in iOS v6 ([noted here in the CHANGELOG](https://github.com/braintree/braintree_ios/blob/main/CHANGELOG.md#600-beta3-2023-04-18)) so you should not "Embed and Sign" this framework. Switching this to "Do Not Embed" should allow you to archive as expected. 

I tested this locally by setting the demo app linked above to "Embed and Sign" and reproduced the error you are seeing on archive. Switching this to "Do Not Embed" archived the app as expected. I am not sure why the message reported by Xcode is so misleading as to what the actual issue is, but it may be worth reporting to Apple. I believe this message was much more clear in previous Xcode versions as to how the specific Mach-O type should be linked.

**Comment by kunal30xi** [comment]
@jaxdesmarais Thanks for your response. I can confirm that indeed was the issue. This issue can be closed.

**Comment by jaxdesmarais** [comment]
Happy to help, @kunal30xi and glad to hear things are now working as expected! If there are ways that we could make this change more clear for iOS v6, happy to more clearly note this for other merchants that may run into a similar issue.
