### ISSUE TITLE
SummaryTitle can overlap DisplayAmount and also run off the screen

### ISSUE THREAD

**Issue by bpollock-coursera** [braintree/braintree_ios#113]
Setting a long title for summaryTitle property of the braintree drop in UI causes the title text to overlap the displayAmount text.

Similarly, trying to work around the issue by not setting the display amount, the summaryTitle runs off the screen instead of truncating. 

This is also a problem on Android.

**Comment by burnto** [comment]
Hi @bpollock-coursera - the recently merged #107 should fix this for you. You'll need to update to version 3.7.1 to get this fix. Please reply if this does not address the problem, and we'll re-open.

/cc @lkorth @gbramwell re android.
