### ISSUE TITLE
V6 Migration guide has incorrect system requirement 

### ISSUE THREAD

**Issue by vivek-dtdl** [braintree/braintree_ios#1136]
### Braintree SDK Version

6.x.x

### Environment

Sandbox

### Xcode Version

14.2

### Integration type

Carthage

### Development Processor

Both

### Describe the bug

V6_MIGRATION.md#supported-versions

The Xcode & Swift version requirement mentioned is incorrect in the above mentioned guide.
This also affects https://developer.paypal.com/braintree/docs/guides/client-sdk/migration/ios/v6

It is correct in Readme and Podspec files.

### To reproduce

See https://github.com/braintree/braintree_ios/pull/1031

### Expected behavior

Both Readme and V6 Migration guide should specify same system requirements since these are applicable since 6.0.0.

More importantly since this guide provides a list of all breaking changes since last major version.

**Comment by scannillo** [comment]
Hi @vivek-dtdl - thank you for using the Braintree iOS SDK and for reporting this issue to us. We will work on getting both of those docs udpated!
