### ISSUE TITLE
Production Access

### ISSUE THREAD

**Issue by jackocyber** [braintree/braintree_ios#1137]
### Is your feature request related to a problem? Please describe.

I am currently using Braintree in sandbox mode and am ready to transition to production. Could you please guide me through the process of obtaining production access?

**Comment by scannillo** [comment]
Hello! Thank you for using the Braintree iOS SDK. This GitHub issue forum is for if you've founds bugs in our SDK or want to request a feature.

Please see our developer docs ["Go Live" section](https://developer.paypal.com/braintree/docs/start/go-live/ruby#get-a-production-account).

If you need help troubleshooting your integration, reach out to [Braintree Support](https://developer.paypal.com/braintree/help).
