### ISSUE TITLE
apple pay 

### ISSUE THREAD

**Issue by Appsteamvasant** [braintree/braintree_ios#114]
![img_0297](https://cloud.githubusercontent.com/assets/8267795/7087702/9e17b8a2-dfab-11e4-98c0-b9182524a743.PNG)

once payment success throw apple pay.  card save in drop view.

the card details are display not properly.

Can you please share Apple Pay screens?

**Comment by mickeyreiss** [comment]
Thanks for posting this!

Can you tell us more about your integration? 

Are you saving Apple Pay cards in the vault? Are you tokenizing a `PKPayment` with a client token that has a `customer_id` and then presenting Drop In?

How does the Apple Pay card end up being displayed inside of Drop In? Normally, we do not expect to see Apple Pay appear in Drop In.

**Comment by Appsteamvasant** [comment]
![ios_simulator_screen_shot_mar_23 _2015 _6 42 09_pm](https://cloud.githubusercontent.com/assets/8267795/7135147/69484998-e2c1-11e4-9384-d4fc11f8ba3c.png)

Thanks for your information!

once click on apple pay button payment process  is success using below code

my apple pay integration using the below code:

   // Create and retain a `Braintree` instance with the client token
    self.braintree = [Braintree braintreeWithClientToken:self.ClintToken];
    // Create a BTDropInViewController
    
    self.provider = [self.braintree paymentProviderWithDelegate:self];
    //
    if ([self.provider canCreatePaymentMethodWithProviderType:BTPaymentProviderTypeApplePay]) {
        
        self.provider.paymentSummaryItems = @[[PKPaymentSummaryItem summaryItemWithLabel:@"BOTTLE" amount:[NSDecimalNumber decimalNumberWithString:[NSString stringWithFormat:@"%@",self.FinalPrice]]]];
    }
    [self.provider createPaymentMethod:BTPaymentProviderTypeApplePay];

//payment methods

- (void)paymentMethodCreator:(id)sender requestsPresentationOfViewController:(UIViewController *)viewController {
    [self presentViewController:viewController animated:YES completion:nil];
}

- (void)paymentMethodCreator:(id)sender requestsDismissalOfViewController:(UIViewController *)viewController {
    [viewController dismissViewControllerAnimated:YES completion:nil];
}

- (void)paymentMethodCreator:(id)sender didCreatePaymentMethod:(BTPaymentMethod *)paymentMethod {
    
    if ([paymentMethod isKindOfClass:[BTApplePayPaymentMethod class]]) {
        BTApplePayPaymentMethod *applePayPaymentMethod = (BTApplePayPaymentMethod *)paymentMethod;
        
        NSString *nonce = applePayPaymentMethod.nonce;
        
        [self postNonceToServer:nonce];
    
    }
}
-(void)paymentMethodCreator:(id)sender didFailWithError:(NSError *)error
{
    [UIAlertView showCustomAlertWithTitle: @"Apple Pay" body:[NSString stringWithFormat:@"%@",error.localizedDescription]];
}

 Next time my payment is through Drop In .but apple pay payment cards are display in drop in view.

my Drop In integration using the below code:

         self.braintree = [Braintree braintreeWithClientToken:self.ClintToken];
    
         self.dropInViewController = [self.braintree dropInViewControllerWithDelegate:self];

         self.dropInViewController.summaryTitle = @"sample";
         self.dropInViewController.summaryDescription = [NSString stringWithFormat:@"Book last-minute deals on %@",self.selectedDeal.category];
         self.dropInViewController.displayAmount = [NSString stringWithFormat:@"%@",self.FinalPrice];
    
         self.dropInViewController.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel target:self action:@selector(userDidCancelPayment)];
    
        UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController: self.dropInViewController];
    
         self.dropInViewController.view.tintColor =[UIColor colorWithRed:0/255.0f green:122/255.0f blue:255/255.0f alpha:1.0f];
    
       [self presentViewController:navigationController animated:YES completion:nil];

//Drop In payment methods

- (void)userDidCancelPayment {
    [self dismissViewControllerAnimated:YES completion:nil];
}
- (void)dropInViewController:(__unused BTDropInViewController *)viewController didSucceedWithPaymentMethod:(BTPaymentMethod *)paymentMethod
{
    self.dropInViewController.navigationItem.leftBarButtonItem.enabled=NO;
    
    NSString *nonce = paymentMethod.nonce;
    
    [self postNonceToServer:nonce];
    
    
}
- (void)dropInViewControllerDidCancel:(__unused BTDropInViewController *)viewController {
    [self dismissViewControllerAnimated:YES completion:nil];
}

Screen Shot 

![9e17b8a2-dfab-11e4-98c0-b9182524a743](https://cloud.githubusercontent.com/assets/8267795/7135442/6a2e94ae-e2c4-11e4-9fdd-ba76e0e44858.PNG)

I am using Same ClintToken to both Apple pay and Drop In.

it is correct or not?

please help to integration of both Apple pay and Drop In.

**Comment by mickeyreiss** [comment]
Interesting. Thanks for posting these details. I'm curious about the implementation of `postNonceToServer:`.

I just did a parallel implementation of Apple Pay and Drop In and they do not intersect. I am not able to make a `BTApplePayPaymentMethod` method show up inside of Drop In.

Here's an assumption I made; maybe you can validate it:

 In my integration, either `BTDropInViewController` _or_ `PKPaymentAuthorizationViewController` is the last thing presented to the user before checkout is complete. In other words, Touch ID is the final step before payment; Drop In is never shown after Apple Pay.

**Comment by burnto** [comment]
@Appsteamvasant nudge.

Can you validate the assumption in @mickeyreiss's question above? Or shall we close this up?

**Comment by mickeyreiss** [comment]
@burnto regardless of the use case, we could always just add the icon and text formatting for Apple Pay payment methods. Do you think we should do that?

**Comment by burnto** [comment]
@mickeyreiss good suggestion. It's clearly not ideal behavior currently. I think we should either:

1. Do as you suggest, and support an Apple Pay payment method option in the Drop-In UI.
2. Not offer Apple Pay payment methods in Drop-In UI (basically filter Apple Pay out of the payment method list, probably client-side).

So, for me, the question is whether we should support payment experiences that don't line up with the [Apple Pay HIG](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/ApplePay.html). The intention of Apple Pay's design is that the user authorize and complete the payment via Touch ID, with a recommendation that a confirmation or thank you view should be presented immediately after. Offering an Apple Pay card as a stored payment method via Drop-In means that an Apple Pay purchase can be completed without Touch ID as the last step, meaning that we aren't strongly guiding folks to the recommended experience.

I would probably err towards option 2, but open to either.

**Comment by mickeyreiss** [comment]
I'm learning towards #1.

I think there are examples of Apple Pay implementations where the user requests and order with a Touch ID, but then has the opportunity to return to the app before the fulfillment is finalized to change their payment option. In this case, it is reasonable to display Apple Pay along-side other payment methods within Drop In.

The flow would be like this:

1. User browses app
2. User checks out with Apple Pay
3. Confirmation screen; user closes app
4. An hour later, user re-opens app, sees that order is "in progress" and changes payment method
5. A day later, order is fulfilled using the most recently selected, authorized payment method.
6. Upon fulfillment, merchant captures funds from Apple Pay payment method and then deletes all references to this Apple Pay payment method.

**Comment by burnto** [comment]
Hm, I guess I buy this as a possible use case, though changing payment methods on existing/pending orders seems a bit outside how we've designed and documented the current drop-in UI, since the selected payment method doesn't necessarily correspond to the payment method for any particular order. I suppose one could set the `paymentMethods` property on `BTDropInViewController` to achieve this though.

Perhaps a good combination solution that supports your use case while also steering us back towards the HIG is to both add Apple Pay display support AND remove Apple Pay options from the default drop-in UI. In this way, Apple Pay would only be a visible option in drop-in if `paymentMethods` is explicitly set.

**Comment by Appsteamvasant** [comment]
@mickeyreiss : "I just did a parallel implementation of Apple Pay and Drop In and they do not intersect. I am not able to make a BTApplePayPaymentMethod method show up inside of Drop In."

Here are few steps which I'm able to reproduce the issue at my end and I'm completely lost.

Step 1.Clean app with out any cards in both Drop in and Apple pay vault.
Step 2. Add a card to Drop in
Step 3. Add a CC to Apple pay Vault
Step 4. Purchase a item using Drop-in, all goes well here and I don't see any apple pay details or cards  
Step 5. then purchase another item using Apple pay, all goes well here and I get only 1 card displayed which is in the vault
6. Now try to purchase another item using the Drop-in, I see the Apple pay card showing up in Drop in

NOTE: If I repeat step 5 few times, say 10 time, in Drop-in I get to see 10 apple pay cards repeated followed by the CC I've added for Drop In. The above steps are done in a continuos process, by not closing the app or by not closing the app from back grounding.

Please suggest how I can resolve this issue.

**Comment by mickeyreiss** [comment]
That's a great description. I think I have a theory on the issue, and it could be a bug.

I'm curious if [this code](https://github.com/braintree/braintree_ios/blob/40cb37bb13a2aa2ac56474d2a17887dae7ab35da/Braintree/Drop-In/BTDropInViewController.m#L439-L441) runs when you do your Apple Pay flow. Can you put a breakpoint in `BTDropInViewController.m:439` and let me know if that code is executed during your Apple Pay flow?

**Comment by Appsteamvasant** [comment]
Nope, tried that and its not going to that break point.

**Comment by Appsteamvasant** [comment]
@mickeyreiss Hope you had a wonderful weekend. I've another question.

Right now what we have in the Drop-in are CC cards available (Visa/Master etc), PayPal to choose from as payment types. And we have separate implementation for Apple Pay.

Can we show Apple Pay as another payment method in Drop-in UI along with CC & Paypal?

**Comment by burnto** [comment]
Hi @Appsteamvasant. Thanks for this suggestion.

Apple Pay is designed for checkout. The Drop-In UI can be used for checkout, but can also be used to create and manage stored payment methods, deferring actual payment to later.

So we've been cautious about adding Apple Pay to Drop-In because it could put some integrating apps in conflict with Apple's HIG recommendations. 

I do think we can look into adding Apple Pay as an _option_ on Drop-In so that developers can use it in the use cases that make sense.

**Comment by pauldunstone** [comment]
Was there ever a resolution for this? I am getting the same behaviour. I set StoreInVaultOnSuccess to equal false on my Apple Pay method and the card still gets saved and shown to my user in the Drop In View Controller. 
Should I set StoreInVault to equal false as well? Is this true by default?

**Comment by demerino** [comment]
Take a look at `4.4.0`+. We've added a new Drop-In component and exposed our UI components (along with styling). More info [here](https://github.com/braintree/braintree_ios/blob/master/Docs/Drop-In-Update.md).

This new version includes support for displaying Apple Pay in Drop-In (see the docs mentioned above).
