### ISSUE TITLE
BTThreeDSecureClient.initializeChallenge never completes

### ISSUE THREAD

**Issue by Przeszaf** [braintree/braintree_ios#1154]
### Braintree SDK Version

6.10.0

### Environment

Sandbox

### Xcode Version

Xcode 15.0.1

### Integration type

Swfit Package Manager

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

Something I found while trying to debug an issue I had - not using that function at the moment so it's not high priority for me but thought I'd share it with you regardless.

`BTThreeDSecureClient.initializeChallenge` only completes if lookupResponse cannot be converted. 
Reason for that is - `completion` is not passed to `self.process(lookupResult: lookupResult, configuration: configuration)`. 

`private func process(lookupResult: BTThreeDSecureResult, configuration: BTConfiguration)` as well as `performV2Authentication` within it use `merchantCompletion` that is only set when calling `startPaymentFlow`.

I assume the `async` version would hang there forever, as it never calls `continuation.resume`.

### To reproduce

1. Call `btThreeDSecureClient.initializeChallenge`
2. Wait for `completion` to be called.

### Expected behavior

Completion should be called.

**Comment by scannillo** [comment]
👋 Hello @Przeszaf - thanks for bringing this to our attention.

The method `BTThreeDSecureClient.initializeChallenge()` should not be used by 99% of our merchants integrating with 3DS. Instead, follow our [developer docs](https://developer.paypal.com/braintree/docs/guides/3d-secure/client-side/ios/v6#custom-ui) for how to integrate. That method was added for a specific merchant with an edge-case, server-side integration. 

We will put up a PR addressing the callback issues you found as well as clarify the docstrings of that method!

**Comment by scannillo** [comment]
A fix for this was merged and will be released with the next braintree_ios v6 release!

**Comment by jaxdesmarais** [comment]
Hey @Przeszaf -

This was released in [version 6.11.0](https://github.com/braintree/braintree_ios/releases/tag/6.11.0).
