### ISSUE TITLE
Expose SDK struct definitions to consumer apps to enable overridability exclusively for writing unit tests. 

### ISSUE THREAD

**Issue by aarka116** [braintree/braintree_ios#1168]
### Is your feature request related to a problem? Please describe.

 While upgrading the SDK from v5+ -> v6+ and started consuming the swift struct definitions but noticed they are declared with `public` and `internal` access modifiers. 

This restricts the consumer apps to subclass the structs and/or override the initializers,properties to create mocks/stubs for the unit testing the SDK integration, wondering if this was an intentional design choice but upgrading to v6 would mean to reduce unit test coverage for consumer apps. 

Few such types:   

1. [BTThreeDSecureResult](https://github.com/braintree/braintree_ios/blob/main/Sources/BraintreeThreeDSecure/BTThreeDSecureResult.swift#L12) 
2. [BTThreeDSecureLookup](https://github.com/braintree/braintree_ios/blob/main/Sources/BraintreeThreeDSecure/BTThreeDSecureLookup.swift#L9)
3. [BTApplePayCardNonce](https://github.com/braintree/braintree_ios/blob/main/Sources/BraintreeApplePay/BTApplePayCardNonce.swift#L8)
4. [BTPayPalAccountNonce](https://github.com/braintree/braintree_ios/blob/main/Sources/BraintreePayPal/BTPayPalAccountNonce.swift#L8)
5. [BTPayPalNonce](https://github.com/braintree/braintree_ios/blob/main/Sources/BraintreePayPal/BTPayPalAccountNonce.swift)
6. [BTApplePayNonce](https://github.com/braintree/braintree_ios/blob/main/Sources/BraintreeApplePay/BTApplePayCardNonce.swift#L8)

### Describe the solution you'd like.

Straightforward fix:  If you could expose the types with `open` access modifier that'd would enable overridability from outside of the module for those classes.

Alternatively, exposing "TestDoubles" (a.k.a Mocks and stubs) for each those struct would allow consumer apps to use them instead for unit tests.

Please let me know if there are any other recommendations for enabling testability.

**Comment by scannillo** [comment]
Hi @aarka116 - thank you for bringing this to our attention. We definitely want our SDK to be easy to test.

Did you try using a `@testable` import? I am able to subclass those types like this:

```
@testable import BraintreeApplePay

class MockApplePayNonce: BTApplePayCardNonce { ... }
```

**Comment by aarka116** [comment]
That works, thanks @scannillo!

**Comment by jaxdesmarais** [comment]
Hey @aarka116 -

According to [this stackoverflow post](https://stackoverflow.com/questions/30787674/module-was-not-compiled-for-testing-when-using-testable) it indicates that by default Cocoapods sets `ENABLE_TESTABILITY` to `YES` only for Debug builds. You may find that post helpful for some steps as to troubleshooting the setup issue to allow you to use the `@testable import` in your project as there are several possible settings that could be misconfigured.

**Comment by scannillo** [comment]
Going to close out this issue since there doesn't seem to be an issue with the Braintree SDK here. In general, Debug builds are used for unit & UI testing, as opposed to release builds. Debugging symbols are usually stripped from Release builds to reduce app size.

We will close out this issue since there is no additional action for our team to take. If you run into any issues unit testing using the Braintree SDK in Debug mode, please let us know! Feel free to comment here or open a new issue.
