### ISSUE TITLE
ErrorCode 2 and ErrorMessage is 無法完成作業。forbidden

### ISSUE THREAD

**Issue by DoneLiu** [braintree/braintree_ios#1169]
### Braintree SDK Version

5.21.0

### Environment

Sandbox

### Xcode Version

14.1

### OS Version & Device

16.6.1

### Integration type

Swfit Package Manager

### Development Processor

Intel

### Describe the bug

I got an errorcode is 2 and error message is "無法完成作業。forbidden" when i used applepay and card, but I didn't known which api caused this error，i need help please!

### To reproduce

![image](https://github.com/braintree/braintree_ios/assets/15603425/04a6bf6c-f208-4f98-829a-dff4857490fb)
![image](https://github.com/braintree/braintree_ios/assets/15603425/1089e155-35de-4a80-b6c8-530a7a3ad815)

### Expected behavior

want to pay success

**Comment by scannillo** [comment]
Hi @DoneLiu - thank you for using the Braintree iOS SDK! This error is coming from the Braintree Gateway service and looks specific to your account, and not a bug in our SDK. 

For help troubleshooting your specific integration & account setup, please contact Developer Support - https://developer.paypal.com/braintree/help. This GitHub issue forum is for bugs found in the SDK & feature requests. Our Support team will be able to help you out!

**Comment by scannillo** [comment]
Also worth noting, [V5 of our SDK is inactive](https://github.com/braintree/braintree_ios?tab=readme-ov-file#versions) and will be moved to the deprecated status in June of 2024. We recommend upgrading to the latest version (V6) when possible.

**Comment by DoneLiu** [comment]
ok, i get it. thanks
