### ISSUE TITLE
"Library not found for -lPods-Braintree-Dev-AFNetworking"

### ISSUE THREAD

**Issue by antypang** [braintree/braintree_ios#118]
build , 1 issue:
(null): Library not found for -lPods-Braintree-Dev-AFNetworking

(null): Linker command failed with exit code 1 (use -v to see invocation)

How can we solve that?

**Comment by mickeyreiss** [comment]
Are you trying to build the demo app or integrate the SDK into your project?

**Comment by burnto** [comment]
It appears that this issue was encountered in building the demo app, and likely could be remedied with a `pod install` and opening the workspace file instead of the project file. 

@antypang please reply here if you wish to discuss further.
