### ISSUE TITLE
Maestro card number limit

### ISSUE THREAD

**Issue by marekswiecznik** [braintree/braintree_ios#120]
In BTUICardFormView, I can't enter 6304000000000000 (listed here https://developers.braintreepayments.com/ios+ruby/reference/general/testing), form accepts only 12 digits for MasterCard. From what I have found online, Maestro card number can be 12 or 19 (international debit cards) long.

**Comment by burnto** [comment]
Thanks @marekswiecznik - we'll fix this.

**Comment by burnto** [comment]
Thanks again @marekswiecznik. I've addressed this in #122. Any feedback?

**Comment by marekswiecznik** [comment]
Thank you! Works great. Should I close this issue now or wait till next release?

**Comment by burnto** [comment]
Great to hear, @marekswiecznik. 

Sorry I didn't respond before dropping off the grid for a week. :palm_tree:
