### ISSUE TITLE
payment to single user with some addon

### ISSUE THREAD

**Issue by farazhaider88** [braintree/braintree_ios#121]
i want to know if the following case is possible using braintree 

suppose i need to buy 2 tickets for 200 and person A bought this for me than i gave amount 220, means 20 extra to person A for facilitating me.

**Comment by mickeyreiss** [comment]
> Broadly speaking, yes, that sounds possible (probably using Stripe Connect). I don't think this is the best place to have this discussion, though, as it doesn't really pertain to our iOS SDK. I'd suggest emailing support@stripe.com and they'll be able to help you with the particulars of your integration.

Our answer is about the same answer as @jflinter. You can probably make this work with [Braintree Marketplace](https://developers.braintreepayments.com/ios+ruby/guides/marketplace/overview), and our friendly support team would be happy to help you. They're always available at support@braintreepayments.com.
