### ISSUE TITLE
How to set value to BTUICardFormView programatically

### ISSUE THREAD

**Issue by haojianzong** [braintree/braintree_ios#123]
I use cardIO to scan credit card infos. When I get the card information from the cardIO library, I wan to set the BTUICardFormView's textFields. 

However BTUICardFormView's fields (such as BTUICardNumberField) are private. Also, inside BTUICardNumberField there are no public method to set the textfield.

I did figure it out that in BTUIFormField_Protected there is a textField, which is also private to the field classes.

How may I set the textField programatically? Am I going the wrong direction? Thanks!

**Comment by intelliot** [comment]
This isn't officially supported right now, but we'll look into adding this feature. Thanks for asking the question!

**Comment by burnto** [comment]
Hi @haojianzong - as of 3.8.0, we've [added](https://github.com/braintree/braintree_ios/compare/3.8.0-rc3...3.8.0#diff-a5eb57e25472b96f95c71cfd7dafe0d5) the ability to set the field values on a `BTUICardFormView` instance.

See [example usage in the spec](https://github.com/braintree/braintree_ios/blob/fffc86e9cb758529924a7a83fd45f6af5f416a3f/Specs/Braintree-UI-Specs/BTUICardFormViewSpec.m#L66-L205) plus a [card.io example in our demo code](https://github.com/braintree/braintree_ios/blob/40cb37bb13a2aa2ac56474d2a17887dae7ab35da/Demos/Braintree-Demo/Features/UI%20Components/BraintreeDemoCreditCardEntryViewController.m#L74-L83).

I'm closing this issue on the assumption that these additions address your need, but please reply if you want to discuss further! Thanks.

**Comment by haojianzong** [comment]
@burnto @intelliot Thank you guys so much! Never expect this feature will come out that soon. It's life saving :)
