### ISSUE TITLE
Replace @import with #import to support projects where modules are disabled

### ISSUE THREAD

**Issue by tomersh** [braintree/braintree_ios#124]
Hi,

We are working on a project where modules are disabled (because it contains objc++ files). This forbids @import usage (and therefore generates error with Intercom). Could you replace these imports with regular #import. The compiler will automatically convert regular imports into module imports for Apple frameworks.
```objective-c
@import Foundation;
@import UIKit;
```
becomes

```objective-c
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
```
Thanks.

**Comment by intelliot** [comment]
I'm not familiar with Intercom. According to http://llvm.org/viewvc/llvm-project?view=revision&revision=218717 --
> C++ modules is not significantly less stable than C
modules any more.

What do you think of enabling modules?

Alternatively, I think that switching to #import would be fine. If it's really needed, let us know, and we can look into it.

**Comment by AlexDenisov** [comment]
jfyi: whenever the modules are enabled and preprocessor sees `#import <Foo/Foo.h>` it replaces it with `@import Foo;` if `Foo` module is available.
So switching 'back' to `#import`s is completely fine and doesn't have any disadvantages for those who's using modules.
