### ISSUE TITLE
Issue while running the demo project

### ISSUE THREAD

**Issue by hardikamal** [braintree/braintree_ios#125]
I have successfully installed pods...but getting this error while running the project... all the 3 errors are related to tapapplepay button action... any help will be appreciated...

![screen shot 2015-05-12 at 7 23 19 pm](https://cloud.githubusercontent.com/assets/6275562/7588774/d74b696c-f8dc-11e4-9811-d201476b6f2f.png)

**Comment by intelliot** [comment]
Which version of Xcode and which Base SDK are you using?

PKAddressFieldName is only available in iOS 8.3 and later; you may need to [update Xcode](https://developer.apple.com/xcode/downloads/).

**Comment by hardikamal** [comment]
@intelliot my xcode version is 6.1 will update and revert back... Thanks for the catch....
@intelliot can u please tell me how to create custom ui instead of dropin ui for paypal and credit card.... the given demo consist of lots of feature so its difficult to find which module should be used...

**Comment by mickeyreiss** [comment]
@hardikamal Take a look at [this example for credit cards](https://github.com/braintree/braintree_ios/blob/8956acad4d931d269c734338d784638f8e2ce389/Demos/Braintree-Demo/Features/Credit%20Card%20Tokenization/BraintreeDemoCardTokenizationViewController.m#L65-L90) with custom UI, and [this one for PayPal](https://github.com/braintree/braintree_ios/blob/8956acad4d931d269c734338d784638f8e2ce389/Demos/Braintree-Demo/Features/PayPal%20-%20Custom%20Button/BraintreeDemoCustomPayPalButtonViewController.m#L21-L27) with custom UI.

**Comment by hardikamal** [comment]
Solved :+1:
