### ISSUE TITLE
Make BTUICTAControl accessible

### ISSUE THREAD

**Issue by evgenyneu** [braintree/braintree_ios#126]
Hi, we are using KIF for integration tests. The "Purchase" button can not be tapped with KIF because it is not accessible.

To make BTUICTAControl accessible, one needs to do three things:

1. Set `isAccessibilityElement` to `true`.
1. Set `accessibilityTraits` to `UIAccessibilityTraitButton`.
1. Set `accessibilityLabel` to the text of the child label, for example "$315 - Purchase".

![braintree_accessibility](https://cloud.githubusercontent.com/assets/880411/7645324/c289d768-faf6-11e4-81f2-ffa2736cf9da.png)

**Comment by burnto** [comment]
Thanks for raising this, @evgenyneu.

**Comment by skunkworks** [comment]
@evgenyneu We made this change in df6a427, which is now merged into `master`. It should go out with the next release. Thanks.

**Comment by evgenyneu** [comment]
Thank you, this is very useful with XCTest UI tests now.
