### ISSUE TITLE
Make it possible to compile without linking Coinbase

### ISSUE THREAD

**Issue by welshm** [braintree/braintree_ios#128]
Perhaps ifdef out coinbase and enable it similar to how Apple pay is enabled.

**Comment by intelliot** [comment]
Why? Apple Pay can be excluded because Apple app review doesn't allow Apple Pay-related symbols in an app if the app doesn't support Apple Pay; but Apple app review doesn't care about Coinbase.

**Comment by welshm** [comment]
Because I'd like to integrate Braintree without needing to also bring Coinbase in if I don't support Bitcoin purchasing :)

No need to compile in sources and increase binary size with code that won't be used....

**Comment by intelliot** [comment]
This isn't supported. However, we did a bit of testing and found the following:

Using Braintree-iOS 3.8.1, which includes Coinbase, adds less than 1 MB to the size of your app versus using a version of Braintree-iOS that does not include Coinbase (e.g. Braintree-iOS 3.7.1).

Also, we'll be making other changes in the future which will have a greater size-reducing impact.

Thanks for the request, @welshm :)
