### ISSUE TITLE
Unable to run the application with braintree integration - App installation failed

### ISSUE THREAD

**Issue by daxpatel** [braintree/braintree_ios#129]
Hello,
I have integrated braintree ios sdk manually in my application.
I followed steps mentioned in this link :
https://github.com/braintree/braintree_ios/blob/master/Docs/Manual%20Integration.md

When I run the application, it is successfully running in the simulator but it is not running in the my real iPhone device. Please see below image for more details.
![screen shot 2015-06-06 at 6 19 14 pm](https://cloud.githubusercontent.com/assets/7902472/8019690/fee3f0b6-0c78-11e5-9b70-3f9e06200415.png)

I have set the bundle identifier same for all of them : Boomerang, BoomerangTests, Braintree, BraintreeTests. If it is not an issue than please guide me what I am doing wrong.

Hope to hear from you soon!!

**Comment by mickeyreiss** [comment]
I'm not sure I understand the problem exactly. Is it possible that you have multiple apps with the same bundle identifier installed on your device?

**Comment by remzr7** [comment]
The Bundle Identifier is the same, that is the issue. you'll need to make them unique @daxpatel

**Comment by daxpatel** [comment]
Hello,

Sorry for the late reply. I have solved this issue.
Yes, the bundle identifier should be different but if then if we select the specific provision profile then it will give us the error that the bundle identifier is not matching with the provisioning profile.

So we should select 'automatic' as a provisioning profile. I think we should include this point in the steps to manually integrate braintree payment SDK in iOS project.

**Comment by intelliot** [comment]
Glad to hear that you've solved this issue. I think 'automatic' should be the default provisioning profile, but if you'd still like to propose a change to [our manual integration docs](https://github.com/braintree/braintree_ios/blob/master/Docs/Manual%20Integration.md), please feel free to open a PR :)
