### ISSUE TITLE
How to hide Coinbase payment option using Drop-In Payment UI

### ISSUE THREAD

**Issue by kamarshad** [braintree/braintree_ios#130]
Hello @burnto @mickeyreiss ,

I am using braintree-iOS library.
I am using Drop-In Payment UI for payment and do not want to show Coinbase payment option.
I have not found any method or property which could hide it.

Any suggestion would be appreciated

**Comment by mickeyreiss** [comment]
We would expect the Coinbase button to display in Drop In only if your Braintree account is enabled for Coinbase. This configuration data is contained within the Client Token.

You can disable Coinbase in your Braintree [sandbox](https://sandbox.braintreegateway.com) /[production](https://braintreegateway.com) control panels (under Settings > Processing) if you are not using it.

There is not currently a way to override the set of payment options that are displayed in Drop In client-side, but we would be open to this feature.

**Comment by kamarshad** [comment]
thanks @mickeyreiss
