### ISSUE TITLE
duplicate symbol in libPayPalMobile-BT

### ISSUE THREAD

**Issue by glesage** [braintree/braintree_ios#134]
Seems to be related to https://github.com/braintree/braintree_ios/issues/53#issuecomment-58379403 as when I use 3.7.2 this issue is non-existent.

On my mac, local, I can run `xctool -workspace "MyApp.xcworkspace" -scheme MyScheme -configuration release build` with the latest version of braintree_ios (3.9.1 at the time of writting this) no problem.

However, on my build server (circle-ci https://circleci.com) I get the following error https://gist.github.com/glesage/ec766223aa042b5de37b.

Basicaly lots of `duplicate symbol` in libPayPalMobile-BT when linking the framework
```
duplicate symbol l036 in:
    /Users/distiller/customer-ios/Starchup White Label/Pods/Braintree/Braintree/PayPal/mSDK/libPayPalMobile-BT.a(PPPaymentMethodCell.o)
    /Users/distiller/customer-ios/Starchup White Label/Pods/Braintree/Braintree/PayPal/mSDK/libPayPalMobile-BT.a(PP2FAViewController.o)
```

I get the same error when I run this with `xcodebuild clean archive -workspace "MyApp.xcworkspace" -scheme MyScheme`

Anything I can do?

**Comment by mickeyreiss** [comment]
@glesage I'm curious if somehow libPayPalMobile-BT.a is being doubly linked into your app. Note that CocoaPods will automatically link the vendored library.

Can you double check on that, to make sure the static library is only "Checked" in one Xcode target? I'm not sure whether Circle CI does something automagical with static libraries. 

Seeing as the error only occurs when you `archive` or run in CI, is it possible that this issue only occurs in your `Release` build?

**Comment by glesage** [comment]
Hi @mickeyreiss thks for the quick response.

I've actually been archiving & releasing the app to Fabric/Crashlytics with my mac for the last few weeks while trying to figure this one out, so it definitely only happens on circle-ci...

As far as the linking, not too sure where I would check that, the actual libPayPalMobile-BT.a isn't even a member of any targets somehow (on my mac).

Otherwise, I've not linked braintree separately to my targets in any way, just Cocoapods plug and play (:

As a note, it might help to know that I have multiple targets (4) that I use for various configs for our different environments (dev, staging, production, demo)

**Comment by mickeyreiss** [comment]
> As a note, it might help to know that I have multiple targets (4) that I use for various configs for our different environments (dev, staging, production, demo)

Can you share your `Podfile` or excerpts of it to demonstrate how this config setup works?

Which of these is active on Circle CI?

**Comment by glesage** [comment]
Yea sure. Because all targets use the same pods I've actually got a simple Podfile:

```
source 'git@github.com:Starchup/StarchupIOS'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'OHAlertView', '~> 2.0.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'SSKeychain', '~> 1.2'
pod 'Braintree', '~> 3.7.2'
pod 'Mapbox-iOS-SDK'
pod 'TPKeyboardAvoiding', '~> 1.2.6'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.10'
pod 'SDWebImage', '~> 3.7.2'
pod 'StarchupAPI' 
```

But should I break them down per target? I may try that as well I guess... but the surprising bit is that the xcodebuild or xctools command works fine on my mac...

2 of the 4 targets are active on circle-ci, but the one I use for testing right now is called "Testing"

(note that the `source 'git@github.com:Starchup/StarchupIOS'` is for a private pod)

**Comment by psomaiya17** [comment]
Hello @mickeyreiss ,

I am also facing same issue. Please try following reproduction steps

1) Create an single view application in Xcode.
2) add Braintree using CocoaPods
3) set proper provisioning profiles and go for Archieve. U will see all these errors.

I hope this helps.

Thanks,
Pratik S.

**Comment by burnto** [comment]
This looks suspiciously like https://github.com/paypal/PayPal-iOS-SDK/issues/270 and https://github.com/paypal/PayPal-iOS-SDK/issues/269

@psomaiya17 and @glesage can you provide your Xcode versions and Braintree pod versions?

On a superficial perusal, I don't see any documentation on CircleCI about Xcode version, so it is possible they are using an older version. @glesage perhaps you would like to verify?

**Comment by glesage** [comment]
Hm indeed, this does look like it might be the issue, thanks @burnto!

Waiting on CircleCi for that xcode version

**Comment by psomaiya17** [comment]
I am currently using Xcode 6.2.0 and Braintree 6.9.1 with coinbase-official 2.1.4. I hope it helps.

Thanks,
Pratik S.

**Comment by burnto** [comment]
@psomaiya17 please update to Xcode 6.3 and let us know if this fixes the problem.

@glesage thanks for looking into CircleCI. Let us know what you find out!

[Our documented minimum Xcode version](https://developers.braintreepayments.com/ios+ruby/guides/client-sdk) is out of date. We'll shortly push an update that specifies Xcode 6.3+.

**Comment by glesage** [comment]
Ok yea circle-ci defaults to `Xcode 6.1.1` - https://circleci.com/docs/ios#xcode-version

I'm trying with the latest they provice (6.3.2) but am having a different issue right now...

I'll let you guys know

**Comment by psomaiya17** [comment]
@burnto Sure I will upgrade to 6.3.2 and will update you all on this thread. Thanks for quick support. I really appreciate. 
Happy coding guys. Cheers.

Thanks,
Pratik S.

**Comment by psomaiya17** [comment]
@burnto & @mickeyreiss Upgrading Xcode to latest version works. Thanks guys for incredible support.
