### ISSUE TITLE
Integration Without CocoaPods documentation : CoinBase is not optional as described

### ISSUE THREAD

**Issue by idave4u** [braintree/braintree_ios#135]
I have a compilation error when i am compiling after following the steps of "BrainTree integration without CocoaPod" : https://github.com/braintree/braintree_ios/blob/master/Docs/Manual%20Integration.md
This line #import <coinbase-official/CoinbaseOAuth.h> in BTCoinbase.h is generating a "file not found" exception. 
It seems that "coinbase-official" framework is required and the documentation is describing Coinbase as optional (bullet 11). Note that pod installation is installing coinbase-official.

**Comment by skunkworks** [comment]
Unfortunately, Coinbase is not optional. The documentation for manual integration will be corrected to reflect this. Thanks.
