### ISSUE TITLE
Crash in BTAnalyticsService

### ISSUE THREAD

**Issue by BhosaleNikhil** [braintree/braintree_ios#1371]
### Braintree SDK Version

6.21.0

### Environment

Sandbox

### Xcode Version

15.0.1

### OS Version & Device

iOS 18, Beta3, iPhone 14 Pro

### Integration type

Swfit Package Manager

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

Recently we updated Braintree SPM version to `6.21.0`. After update we have started to see random crash as soon as we launch app in debug mode. I am attaching screenshots here. We are afraid this might affect production users as well.

### To reproduce

No Specific steps to reproduce, I have attached screenshots of stack trace though.

### Expected behavior

There should not be any crash in Braintree sdk

### Screenshots

<img width="386" alt="Screenshot 2024-07-18 at 10 53 31" src="https://github.com/user-attachments/assets/48175059-9c4e-43b3-a7d5-d483b0a94291">
<img width="1343" alt="Screenshot 2024-07-18 at 10 53 42" src="https://github.com/user-attachments/assets/e55a2e93-518d-4cd5-81a5-1c803b2dd133">

**Comment by jaxdesmarais** [comment]
Hey @BhosaleNikhil -

Thanks for using the SDK! Please update to [version 6.22.0+](https://github.com/braintree/braintree_ios/blob/main/CHANGELOG.md#6220-2024-07-02) to resolve this crash.
