### ISSUE TITLE
Using BTDropInViewController how should i provide the payment amount

### ISSUE THREAD

**Issue by MeseeryNileCode** [braintree/braintree_ios#138]
From iOS app prospective, if i present a `BTDropInViewController` ,i need to specify the amount the user will have to pay, not a `displayAmount` label text, can you guide me how to provide the server with the amount of payment needed !

**Comment by mickeyreiss** [comment]
Can you tell us more about what you're trying to accomplish?

In general, it is not necessary to specify an amount client side when using drop in. Instead, you should determine the transaction amount when processing the order on your server, and pass it into the `transaction.sale` call.

**Comment by MeseeryNileCode** [comment]
So, if i am processing a payment on a mobile client side, i must callback the server for the amount he has to pay off ?!

**Comment by mickeyreiss** [comment]
That is correct. Braintree's Drop-in integrations always require a server-side component. You can find out more [on our docs site](https://developers.braintreepayments.com/ios+ruby/start/overview#how-it-works).

**Comment by MeseeryNileCode** [comment]
Well, so what's the appropriate order of sending the Amount of payment to server, after or before sending Payment nonce to the server ?

**Comment by mickeyreiss** [comment]
It's up to you how your architect that component of your system. I would recommend that you calculate the amount on your backend based on the order, rather than accepting an arbitrary `amount` via an API request.

**Comment by MeseeryNileCode** [comment]
Thanks @mickeyreiss for your quick response.
