### ISSUE TITLE
Using BTDropInViewController No back/cancel button !

### ISSUE THREAD

**Issue by MeseeryNileCode** [braintree/braintree_ios#139]
After i presented a  `BTDropInViewController` instance ,there's no cancel or back button !

here's my code :
``` 
self.braintree = [Braintree braintreeWithClientToken:clientToken];
BTDropInViewController *dropInViewController = [self.braintree dropInViewControllerWithDelegate:self];
        [dropInViewController fetchPaymentMethods];
        dropInViewController.shouldHideCallToAction=YES;
        dropInViewController.delegate =self;
        dropInViewController.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel   target:self
       action:@selector(userDidCancelPayment)];
    UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:dropInViewController];
        [self presentViewController:navigationController animated:YES completion:nil];
  ```

**Comment by mickeyreiss** [comment]
Please use `navigationItem` to add a cancel button to the `dropInViewController`. 

By default, there is no back or cancel button when drop in is pushed as a modal.

**Comment by MeseeryNileCode** [comment]
i already did :
`dropInViewController.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel   target:self
       action:@selector(userDidCancelPayment)]; `

**Comment by rishabhtayal** [comment]
I was having trouble adding a `rightBarButtonItem` to my `dropInViewController`. I tried adding the button in completion block of `presentViewController` like this:
```
 self.presentViewController(nav, animated: true) { () -> Void in
    var button = UIBarButtonItem(title: "Scan", style: UIBarButtonItemStyle.Plain, target: self, action: "scanCardTapped:")
    self.dropIn.navigationItem.rightBarButtonItem = button
}

```
and it worked. You should try it for `leftBarButtonItem`.
