### ISSUE TITLE
How to implement remember me feature using braintree iOS sdk

### ISSUE THREAD

**Issue by kamarshad** [braintree/braintree_ios#140]
Hello  @mickeyreiss,

I am using braintree iOS sdk for payment purpose in my iOS application and like to appreciate you for cool sdk.
Here I want to implement remember me feature,So that if same user try to make payment remember me could avoid the re-entering the details(debit/credit card) again.
As of now I have tested this braintree iOS sdk on Simulator, have not found such feature.
Could you please help me how can I implement remember me in braintree iOS sdk.

**Comment by rishabhtayal** [comment]
In the sample project, if you go into settings and set a 'Customer ID' to some value, it should store your payment information automatically.

**Comment by kamarshad** [comment]
@rishabhtayal Thanks but where In setting I should set "Customer ID' ?
Can you explain it in more detail

**Comment by rishabhtayal** [comment]
Like this. I haven't been able to successfully implement 'remember cards' feature in my app as of now but the demo project works when you set the Customer ID to anything.

![img_0133](https://cloud.githubusercontent.com/assets/2100166/8410942/d71c959e-1e46-11e5-947b-41382d31ae08.PNG)

**Comment by kamarshad** [comment]
@rishabhtayal  Thanks Will try it...  :+1: )

**Comment by burnto** [comment]
@kamarshad set the customer ID when you [generate your client token](https://developers.braintreepayments.com/ruby/reference/request/client-token/generate) on your server.

**Comment by rishabhtayal** [comment]
@burnto I am doing setting the customer_id param when creating a client token on my server, still the payment methods are not saved for that customer in my app. Here is the server code:

```
def client_token
	token = Braintree::ClientToken.generate(
	    :customer_id => params[:customer_id]
	)
    render :json => {"token" => token}
end 
```

**Comment by intelliot** [comment]
@rishabhtayal Are you using our [Drop-in Payment UI](https://developers.braintreepayments.com/ios/guides/drop-in)?

**Comment by rishabhtayal** [comment]
Yes.

**Comment by intelliot** [comment]
@rishabhtayal I couldn't reproduce this problem. Are you using the same `customer_id` for the customer, every time that customer fetches a client token from your server?

If so, please open a new ticket and include steps for reproducing the problem. Thanks!

**Comment by rishabhtayal** [comment]
Sorry I was able to solve the issue. It was on my end.
