### ISSUE TITLE
Vault doesn't store payment methods

### ISSUE THREAD

**Issue by rishabhtayal** [braintree/braintree_ios#141]
My sandbox account doesn't store payment methods for customer in their vault. I am creating a customer object using:

```
def create_customer
	result = Braintree::Customer.create(
		:first_name => params[:first_name],
		:last_name => params[:last_name],
		:email => params[:email],
		:phone => params[:phone]
		)
	if result.success?
		render :json => {'result' => result.customer.id}
	else
		render :json => {'errors' => result.errors}, :status => 400
	end
end
```

and then storing the ```customer_id``` in my database for later use.

When creating client_token I am sending the same ```customer_id``` to the API. Here is the code for creating client_token:

```
def client_token
	token = Braintree::ClientToken.generate(
		:customer_id => params[:customer_id]
		)
	render :json => {"token" => token}
end 
```

**Comment by mickeyreiss** [comment]
How and where do you attempt to add payment methods to the vault?

**Comment by rishabhtayal** [comment]
I am using Drop-in UI.

**Comment by mickeyreiss** [comment]
With Drop-in UI, payment methods are automatically added to the vault, as long as a non-nil and existing customer id is present. Can you post the parameters you are sending in to `ClientToken.generate`?

Please contact our support team for more personalized support. In general, Github issues is better suited for bugs and feature requests.

**Comment by rishabhtayal** [comment]
I believe I am passing a valid customer_id. I have contacted support team several times. No response.

**Comment by rishabhtayal** [comment]
I was able to fix the issue. The customer_id params was not passing to the API.
