### ISSUE TITLE
Braintree:AuthorizationError

### ISSUE THREAD

**Issue by rishabhtayal** [braintree/braintree_ios#142]
I am not sure if this should go in ruby repo or this one. Just going to post it here.

I have been getting ```Braintree::AuthorizationError``` in my ruby server side while calling ```Braintree::Transaction.sale``` API. I am using iOS client to call the api.

I couldn't find a pattern to reproduce the issue. Just keeps coming back. I have to delete the customer from the dashboard and create a new customer to overcome this.

**Comment by mickeyreiss** [comment]
Hi @rishabhtayal -

I think this is more likely to be an configuration issue than a bug in the Ruby or iOS libraries.

Can you please contact our [support team](https://support.braintreepayments.com/) at support@braintreepayments.com for more help? That way, they can ask you about your account-specific details without posting them online.

Thanks!

**Comment by seigel** [comment]
Anyway to share what was fixed about this?

**Comment by bluk** [comment]
@seigel Please contact the [Support Team](https://articles.braintreepayments.com/forms/contact) to get assistance. Depending on your setup, the solution may be unique to your issue.
