### ISSUE TITLE
Confirmation alert take time before appear without any call back function to alert that it will appear 

### ISSUE THREAD

**Issue by EslamGamalElsayed** [braintree/braintree_ios#1424]
### Braintree SDK Version

6.23.3

### Environment

Sandbox

### Xcode Version

15.0

### OS Version & Device

iphone 15 pro max 

### Integration type

CocoaPods

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

Confirmation alert which ask for acceptance to use "paypal.com" to sign in take time before appear without any call back function to alert that it will appear  for indication to hide the loading view which i show for user to prevent any interactions until complete payment process 

### To reproduce

- choose paypal as a payment gate way 

### Expected behavior

- call back function to indicate that alert will appear 

### Screenshots

![Screenshot 2024-10-02 at 7 59 24 PM](https://github.com/user-attachments/assets/110ea5dc-e1dd-4820-bcf7-e798891f07cd)

**Comment by KunJeongPark** [comment]
This dialog box is not controlled by our SDK but by iOS to protect user privacy. We don't have ability to add callback to this event.
What we do in our demo app is have loading indicator starting with press of button to start PayPal transactions.

**Comment by EslamGamalElsayed** [comment]
my issue is that after a call tokenize(request) function it take a few seconds before show the previous alert so i show a loading view to prevent user interactions but i want to hide it when the alert is appear

**Comment by KunJeongPark** [comment]
I don't think there is a way of doing this. In our demo app, we have loading indicator with start of tokenize and we just select an option in the dialog box when it appears. (the loading indicator on your app should prevent user interaction on rest of the app)

**Comment by scannillo** [comment]
@KunJeongPark is correct. The Braintree SDK displays the PayPal Checkout experience in an [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) which handles the presentment of that alert. Unfortunately, Apple doesn't provide any hook into when that alert finished displaying.

**Comment by KunJeongPark** [comment]
I will close this issue, if there is further questions, @EslamGamalElsayed you can file another issue. Thank you!
