### ISSUE TITLE
How to display customer billing address on Drop-In UI

### ISSUE THREAD

**Issue by kamarshad** [braintree/braintree_ios#143]
Hello @mickeyreiss @burnto 

I am using Braintree iOS sdk and want to display customer billing address detail on checkout screen.
But I did not find any such property which allow me to set customer billing address.

Can you please help me, how can I display billing address on Drop-In UI.

**Comment by mickeyreiss** [comment]
Billing address is not currently part of Drop-in UI. This is useful product feedback. Thanks for posting.

**Comment by andrii-lisovskiy** [comment]
Hi, is it still not part of Drop-in UI?

**Comment by scannillo** [comment]
Hi @andrii-lisovskiy - billing address is still not a feature of our Drop-In UI. Please open a feature request [here](https://github.com/braintree/braintree-ios-drop-in/issues/new/choose), so we can gauge community interest.
