### ISSUE TITLE
iOS SDK not saving customer's card

### ISSUE THREAD

**Issue by rishabhtayal** [braintree/braintree_ios#144]
I am using the following code. It doesn't save the card to customer's vault. It goes to the success block but doesn't actually stores the card info.

```
BTClientCardRequest* cardRequest = [[BTClientCardRequest alloc] init];
cardRequest.number = @"378282246310005";
cardRequest.expirationMonth = @"12";
cardRequest.expirationYear = @"2015";
cardRequest.shouldValidate = false;
[self.client saveCardWithRequest:cardRequest success:^(BTCardPaymentMethod *card) {
     NSLog(@"CArd saved");
} failure:^(NSError *error) {

}];
```

**Comment by burnto** [comment]
That's correct. The `BTCardPaymentMethod` includes a [`nonce` property](https://github.com/braintree/braintree_ios/blob/1eaf4a/Braintree/API/%40Public/BTPaymentMethod.h#L9-L13) that your client code should send to your server, where it may be used to create a [transaction](https://developers.braintreepayments.com/guides/transactions#sale), [customer](https://developers.braintreepayments.com/guides/customers#create-with-payment-method), or [payment method for an existing customer](https://developers.braintreepayments.com/guides/payment-methods#create).

**Comment by rishabhtayal** [comment]
So what does the saveCardWithRequest api does on the client sdk?

**Comment by mickeyreiss** [comment]
`saveCardWithRequest` creates a short-lived token, which we call a payment method nonce, that allows you to refer to the PCI sensitive credit card data without holding that data directly.

**Comment by mickeyreiss** [comment]
This wikipedia article does an OK job explaining tokenization as a data security strategy: https://en.wikipedia.org/wiki/Tokenization_(data_security)

**Comment by rishabhtayal** [comment]
@mickeyreiss @burnto I understand the concept of token/nonce. I believe the ```tokenizeCard``` method of ```Braintree``` class also does the same thing. It tokenizes the ```BTClientCardRequest``` to produce a nonce which can then be used to save the card data through server code. Is there any other reason ```saveCardWithRequest``` of ```BTClient``` class exists?

**Comment by mickeyreiss** [comment]
`BTClient` is a lower level of abstraction that requires more intimate
knowledge of the Braintree API. In this case (`tokenizeCard` vs.
`saveCard`), the behavior is very similar, with the exception of the
options.validate field.
