### ISSUE TITLE
How to Setup Google Pay in iOS

### ISSUE THREAD

**Issue by Navdeep2020** [braintree/braintree_ios#1442]
### Is your feature request related to a problem? Please describe.

I am currently integrating Braintree for advanced payment methods in my iOS app. While setting up different payment options, I noticed that Google Pay is not directly supported in iOS through Braintree.

I have referred to the documentation and various sources, but I could not find any clear instructions for integrating Google Pay on iOS. Could you provide any guidance or confirm if this feature is supported? If it is, what are the steps required to configure Google Pay in an iOS app using Braintree?

### Describe the solution you'd like.

**Steps Tried:**

Followed the Braintree Google Pay setup guide for Android, but no equivalent guide for iOS was found.

**Expected Outcome:**

Confirmation on whether **Google Pay can be integrated into iOS** via Braintree.
If supported, please share clear steps or a guide on how to set up Google Pay in an iOS app.

**Comment by jaxdesmarais** [comment]
Hey @Navdeep2020 -

Google Pay is only available for the [JavaScript v3 SDK](https://developer.paypal.com/braintree/docs/guides/google-pay/client-side/javascript/v3) and the [Android SDK](https://developer.paypal.com/braintree/docs/guides/google-pay/client-side/android/v4). For iOS devices instead you can integrate with [Apple Pay](https://developer.paypal.com/braintree/docs/guides/apple-pay/client-side/ios/v6/).
