### ISSUE TITLE
Attached Codesignature is for Team: changching chi?

### ISSUE THREAD

**Issue by devandanger** [braintree/braintree_ios#1448]
### Braintree SDK Version

6.24.0

### Environment

Both

### Xcode Version

Xcode 15.4

### Integration type

CocoaPods

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

Our developers had experienced the following build error.

![image](https://github.com/user-attachments/assets/a76d2233-c172-4ce6-b061-e0b4b3ee27a8)

The issue had nothing to do with the BrainTree SDK and we have since chalked to up to some of our build processes.
But we were kind of suspicious of the codesignature.  This is a newer type of requirement/capability but we were suspecting something that said Braintree maybe?

https://github.com/braintree/braintree_ios/commit/24f656ff04c98095e423f404a6f475859043bf2e

Do you have any commentary on this?

### To reproduce

Not reproducible really, just questioning the codesignature.

### Expected behavior

I would expect a codesignature associated to Braintree

### Screenshots

![image](https://github.com/user-attachments/assets/cdb8561d-41f6-4a0d-84dc-93e819abb726)

**Comment by agedd** [comment]
hi @devandanger - thanks for bringing up this concern! i just wanted to confirm that `PPRiskMagnes.xcframework` signed by the above signature `"AppleDeveloperProgram:XEZPTDFLAS:changching chi"` is valid and as expected
