### ISSUE TITLE
Objective-C sample for Braintree v6?

### ISSUE THREAD

**Issue by jmpdi** [braintree/braintree_ios#1450]
### Is your feature request related to a problem? Please describe.

Is an Xcode sample project available that exercises the Objective-C version of the Braintree v6 API?

I'm trying to incorporate Braintree v6.23.3 into a .NET 8 mobile app.  The app crashes at startup.  The problem relates to usage of `BTPaymentMethodNonce` via Objective-C from .NET.

Full details here: https://github.com/xamarin/xamarin-macios/issues/21546

Microsoft has indicated that an Objective-C sample app might help isolate the issue.  I looked for a sample in this repo and elsewhere, but I only found Swift samples.   So I thought I would ask.

Any advice/insight is appreciated. Thanks.

### Describe the solution you'd like.

Xcode project that demonstrates the Objective-C version of the Braintree v6 API.

**Comment by scannillo** [comment]
👋 Hi @jmpdi - we do not officially support Xamarin integrations and only fully-native iOS or Android applications. If you have any issues with a fully-native iOS application in Objective-C, please let us know!

**Comment by jmpdi** [comment]
Hello @scannillo.  Thanks for the response.  To clarify, I'm not asking for any support with the .NET integration.  I'm asking if Braintree has a sample app or knows of a sample app that uses Braintree v6 via the Objective-C APIs.  All the samples in this repo (and elsewhere) are Swift.  Thanks again!

**Comment by scannillo** [comment]
You're correct - our dev docs and sample app are only in Swift. But the SDK is still compatible with Objective-C.

We are considering dropping Objective-C in a future major version, but have not yet committed to it. We have an open discussion on it [here](https://github.com/braintree/braintree_ios/discussions/1431) if you'd like to leave feedback.

**Comment by jmpdi** [comment]
For future reference:  The root cause of the crash is stub class handling in .NET.  The workaround is to use dynamic registrar. A permanent fix to .NET is in the pipeline.  

Full details here: https://github.com/xamarin/xamarin-macios/issues/21546
