### ISSUE TITLE
Request new copy & translations for 'Add Card' in iOS

### ISSUE THREAD

**Issue by JohnnyWhiteSP** [braintree/braintree_ios#1483]
### Is your feature request related to a problem? Please describe.

Found this similar issue which describes our problem well, and appears to have solved the problem for Android, but not iOS: https://github.com/braintree/braintree-android-drop-in/issues/175

In iOS, when using the credit card details drop-in, the copy 'Add Card' ('Enregistrer une carte' in French) in the top-right is confusing & misleading - we have had customers contact us querying whether they are obliged to "save their card" before they can pay. In fact, we do not save our customer's card details, and the next action is really "next" or "proceed to payment" or similar, and the customer is only confirming their card details for a single payment of their basket.

Screenshot for iOS:
EN
![image](https://github.com/user-attachments/assets/6ab47b68-9914-4a70-8c79-9185dee81b2c)
FR
![image](https://github.com/user-attachments/assets/20bab0c7-1d8c-48f6-9029-6257211335a0)

Screenshot for Android:
FR
![image](https://github.com/user-attachments/assets/b1b94b83-653f-41ce-9e1e-10d00d2e83dc)

### Describe the solution you'd like.

As a customer, I would like to confirm my card details for payment of an individual card, without fear that my card details will be "saved", "registered", or "added" to my account with the website.

Suggested copy ideas: "Confirm card details", "Pay" (looks like Android uses this), "Next".

**Comment by scannillo** [comment]
Hi @JohnnyWhiteSP - thank you for bringing this issue to our attention. Do you mind instead opening it in the DropIn repo: https://github.com/braintree/braintree-ios-drop-in?
