### ISSUE TITLE
iOS9 url scheme

### ISSUE THREAD

**Issue by fattomhk** [braintree/braintree_ios#152]
In iOS9, we need to do whitelisting for those url schemes.
I find lots of url schemes in console and I can't Google what they are.

Attached what I got with BTUIPayPalButton 
![screen shot 2015-08-20 at 12 14 30 pm](https://cloud.githubusercontent.com/assets/1083049/9375590/2086def8-4735-11e5-8f49-f146031afb80.png)

Can anyone give a full list of url schemes that must be included in LSApplicationQueriesSchemes to make Braintree works on iOS9?

**Comment by burnto** [comment]
We are still waiting on an update to a certain paypal component that performs these scheme queries. We will update and close this issue once we have addressed this problem. You won't have to whitelist the above schemes. Thanks.

**Comment by fattomhk** [comment]
Noted that with thanks.

**Comment by intelliot** [comment]
Hi @fattomhk - this issue should be resolved in [our 3.9.3 release](https://github.com/braintree/braintree_ios/releases/tag/3.9.3).

There are a few URL schemes that you need to whitelist in order to support PayPal and Venmo app switch - we've listed these in the README here: https://github.com/braintree/braintree_ios/blob/master/README.md#updating-for-ios-9

Try this out, and let us know if there are any problems :)

**Comment by keith** [comment]
Is there any explanation of when those URL schemes will be used? We're using a subset of this SDK and assume we don't need all of these.

**Comment by skunkworks** [comment]
Hi @keith,

```
com.paypal.ppclient.touch.v1
com.paypal.ppclient.touch.v2
```

These are used for accepting PayPal payments via an app switch to the PayPal wallet app.

`org-appextension-feature-password-management`

This is for accepting PayPal payments via an in-app web view that prompts users to authenticate in a PayPal login web page. The login page has a 1Password link that allows users to switch to another app to autofill login details.

If your app integrates the PayPal component of the Braintree SDK for 3.x, you will need all three of these URL schemes in your whitelist.

`com.venmo.touch.v1`

This is for accepting payments via app switch to the Venmo app.

Hope that helps.

**Comment by keith** [comment]
Thanks for the explination!

**Comment by FurrukhRana** [comment]
Merchant account not found....

I got this error.I follow this tutorial 
 https://www.appcoda.com/braintree-ios-integration/

I also add com.paypal.ppclient.touch.v1
com.paypal.ppclient.touch.v2 in info plist..

but got error.

**Comment by demerino** [comment]
Please use our official docs found here: https://developers.braintreepayments.com/start/hello-client/ios/v4
