### ISSUE TITLE
pod files are not updating.

### ISSUE THREAD

**Issue by ashokgowd** [braintree/braintree_ios#154]
An error occurred while processing the post-install hook of the Podfile.

undefined method `project' for #<Pod::Installer:0x007f9ab403e110>

**Comment by burnto** [comment]
Hi @ashokgowd - could you provide a little more information about what you are doing that is yielding this error?

[The Podfile in the braintree_ios repo](https://github.com/braintree/braintree_ios/blob/master/Podfile) is used only for installing dependencies that we use for development/testing. In standard usage integrating Braintree into your iOS app, you won't need to `pod install` using that Podfile.

**Comment by intelliot** [comment]
We just fixed this in https://github.com/braintree/braintree_ios/commit/b3ad8f8473b234134a6a1843e058c1d37ee67978 - which is included in [yesterday's 3.9.3 release](https://github.com/braintree/braintree_ios/releases/tag/3.9.3).

If the problem persists, please feel free to open a new issue, and indicate the CocoaPods version and Braintree iOS SDK version that you're using. Thanks!
