### ISSUE TITLE
Code Signing issue in Example App

### ISSUE THREAD

**Issue by hsavit1** [braintree/braintree_ios#156]
Hi,

Normally this isnt much of an issue as you can just run the app on the simulator, however I want to be able to test apple pay 

Any chance you can resolve these code signing issues? Thanks

**Comment by burnto** [comment]
You'll need to just go ahead and update the demo app for your own team, profile, and code signing. 

Alternatively, just get Apple pay working in your own project up to the point where you get a PKPayment, then integrate Braintree iOS and use it to tokenize and complete the transaction. The handoff is pretty apparent in the API.
