### ISSUE TITLE
Limit Drop In UI to just credit card

### ISSUE THREAD

**Issue by hsavit1** [braintree/braintree_ios#157]
Hey

Im really confused as to how to limit the DropInUI so that a customer can only choose a credit card payment option. I dont want to see paypal or venmo. is this possible ? Thanks

**Comment by nirinchev** [comment]
You can control the enabled payment methods in the gateway: Settings -> Processing. If you don't have paypal and venmo enabled, they will no be shown in the DropIn controller. Keep in mind that for the live environment, you need to explicitly enable them, while in the sandbox, PayPal is enabled by default.

**Comment by skunkworks** [comment]
In the near future we will be adding more customizability to the drop-in UI, and we will consider adding this. Thanks!
