### ISSUE TITLE
iOS 9 - Xcode 7 GM Seed - linker command failed with exit code

### ISSUE THREAD

**Issue by wstenhouse** [braintree/braintree_ios#159]
After updating to the GM seed of xcode 7 and using Braintree 3.9.3, I'm getting this error.

/Users/Will/Desktop/App/Pods/Braintree/Braintree/PayPal/mSDK/libPayPalMobile-BT.a(PPZebraAnalyticsWidgetCategories.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by wstenhouse** [comment]
Tried updating to the 4.0 beta and got this error with Braintree/Apple-Pay

Analyzing dependencies
Pre-downloading: `Braintree` from `https://github.com/braintree/braintree_ios.git`, branch `4.0-beta`
[!] Unable to satisfy the following requirements:

- `Braintree/Payments (= 4.0.0-beta1)` required by `Braintree/Apple-Pay (4.0.0-beta1)`

**Comment by burnto** [comment]
@wstenhouse we don't yet have bitcode support for some of the closed source components. You'll need to disable bitcode in your target settings for now. 

How did you attempt to upgrade to the beta? We haven't released the beta to cocoapods yet, so you'll need to add explicit parameters to your `pod` entry to set the repo and branch or tag. Plus, it's a beta, so be prepared for API changes before the final 4.0.0 release.

**Comment by skunkworks** [comment]
The error re: `Braintree/Payments` when upgrading to the `4.0-beta` branch is related to Cocoapods having a stale cached copy of the podspec. Try manually removing the Braintree-related files under your `Pods/` folder and re-running `pod install`.

**Comment by mstorch** [comment]
+1.  I am also a bit confused since I am getting the same error as @wstenhouse and the README.md states that "The Braintree SDK works with apps that have bitcode enabled."

@burnto, can you confirm if apps built against the Braintree iOS SDK version 3.9.3 with bitcode enabled should work?

**Comment by apersaud** [comment]
+1 Any updates on when this fix would be available?

**Comment by skunkworks** [comment]
@mstorch and @apersaud, this should be on the `master` branch, we'll be doing a release shortly, possibly even today.

**Comment by nickbit** [comment]
@skunkworks any news on that?

**Comment by burnto** [comment]
@skunkworks is preparing and QAing a release. We'll reply here and close this issue once that release is out. 

In the meantime, you're welcome to kick the tires by pointing directly to `master` or to the specific commit, e.g.

```ruby
pod 'AFNetworking', 
    :git => 'https://github.com/braintree/braintree_ios.git', 
    :branch => 'master'
```

Let us know if the above makes sense, and if you continue to see problems with either the latest on `master` or the upcoming release. Thanks for your continued feedback. :cookie:

**Comment by mstorch** [comment]
Thanks @burnto, was able to build and install using this particular commit and will continue testing in anticipation of the official release.  Thanks for the quick turnaround!

**Comment by nickbit** [comment]
@burnto thank you for the quick response! Will test and report.

**Comment by skunkworks** [comment]
Bitcode support is now live with release 3.9.4!
