### ISSUE TITLE
Swift support without Cocoa Pods

### ISSUE THREAD

**Issue by ryan-blunden** [braintree/braintree_ios#161]
We're currently blocked on using the Braintree iOS project with Swift and we'd like to avoid using Cocoa Pods.

XCode 6.4
Swift 1.2

We're using the "Manual Integration without CocoaPods 
<https://github.com/braintree/braintree_ios/blob/master/Docs/Manual%20Integration.md>"  route as we're wanting to avoid CocoaPods if possible as it adds a ton of magic and voodoo to our project.

Our problem is that while we CAN import Braintree code from an Objective-C file in our project, we can't when using Swift. We've narrowed the problem down to an umbrella header issue and adding a bridging header for our project hasn't helped.

I've set up a repo simple project that shows the errors we've been getting. The setup here was the same as the actual project we're using Braintree in and we've got exactly the same issue, which gives me me tiny bit more confidence we didn't just get it wrong the first time

Check out the repo at https://github.com/mbusheikin/TestBraintree.

There was one compilation error because of a missing UIKit import. With the import added, you can run the project on a simulator. But when you try to import Braintree from a Swift file, it fails to build again.

There are 3 commits that show the steps we went through - read the commit messages for more info.

Ideally, you'll be able to get the project building and then make a PR for future ref.

**Comment by camstar** [comment]
+1

**Comment by szek** [comment]
+1

**Comment by burnto** [comment]
Have you tried removing the Braintree import from your Swift code and just using the import in your bridging header? That change works for me in your sample project, and would hopefully unblock you. 

I'd prefer to recommend this approach for now, versus making changes to the manual integration docs, since our 4.0 is coming soon and includes full framework-based swift compatibility from the get go.

**Comment by mickeyreiss** [comment]
This is similar to #162 and I think it will be solved in 4.x.

One trick that may be another good _workaround_, if you prefer to omit CocoaPods from your daily workflow: 

You can use CocoaPods in a temporary empty app to generate a Swift-compatible framework. Then, you can vendor the Pods-generated project in your app. 

This is a way to let CocoaPods do the heavy lifting when you first integrate, but vendor the result to avoid using CocoaPods.

**Comment by ryan-blunden** [comment]
> You can use CocoaPods in a temporary empty app to generate a Swift-compatible framework. Then, you can vendor the Pods-generated project in your app.
This is a great tip. Thanks. Looking forward to 4.x

**Comment by mickeyreiss** [comment]
> Thanks, that's a great tip. Looking forward to 4.x

You're welcome. Me too :)
