### ISSUE TITLE
Please add Carthage support

### ISSUE THREAD

**Issue by ryan-blunden** [braintree/braintree_ios#162]
Please add Carthage support! Cocoa Pods is very opinionated where as Carthage simply provides a way to satisfy listed dependencies and output a framework.

The Quora response from Carthage maintainer Justin Spahr-Summers does a great job of summarising why they build Carthage - https://www.quora.com/CocoaPods-is-opinionated-whereas-Carthage-is-not-Why-does-that-make-it-better

**Comment by schmico** [comment]
+1

**Comment by camstar** [comment]
+1

**Comment by szek** [comment]
+1

**Comment by mickeyreiss** [comment]
Thanks for the feedback, everybody! 

We're definitely on the same page about the simplicity of carthage, and intend to bring first-class support for swift, dynamic frameworks and carthage in an upcoming release. 

I'll leave it to @skunkworks, @intelliot or @burnto to give more concrete details about our plans.

**Comment by burnto** [comment]
The 4.0 version is framework-based and fully Carthage and CocoaPods compatible. 

Feel free to take the beta for a spin, with the caveat that a few bits of the API may change: https://github.com/braintree/braintree_ios/tree/4.0-beta

**Comment by intelliot** [comment]
Carthage is now supported. [See the CHANGELOG for details](https://github.com/braintree/braintree_ios/blob/master/CHANGELOG.md).
