### ISSUE TITLE
Crash TO PPRiskConfiguration knownAppURLSchemes

### ISSUE THREAD

**Issue by jason469618528** [braintree/braintree_ios#163]
Not CocoaPods,Click PayPal [PPRiskConfiguration knownAppURLSchemes]: unrecognized selector sent to instance 0x7fc3aba6edf0? what's this?

**Comment by jason469618528** [comment]
![77ee3194-14fa-4800-a5ab-f852927710ac](https://cloud.githubusercontent.com/assets/4940053/9870190/788302bc-5bbc-11e5-8980-4844431b0ad3.png)
'-[PPRiskConfiguration knownAppURLSchemes]: unrecognized selector sent to instance 0x7fd24ad1c4d0'

**Comment by skunkworks** [comment]
Hi,

Which version are you using for your manual integration (can you provide the git commit hash)? Can you confirm that your project/app is including the `libPayPalMobile.a` file?

**Comment by jason469618528** [comment]
Yeah,Thank You
