### ISSUE TITLE
Custom BTUI Theme doesn't transfer to sub-views

### ISSUE THREAD

**Issue by blakebyrnes** [braintree/braintree_ios#165]
If you have existing payment options on file in the BTDropInViewController and then go to add another payment option, the theme options are thrown out the window.  Looks like it just needs the theme copied over in  BTDropInViewController.m  -- addPaymentMethodDropInViewController  (line 655)

**Comment by coolbnjmn** [comment]
I am seeing this same issue. Any chance these settings can get carried through? Also the navigation controller theme is not continuing either.

**Comment by demerino** [comment]
Take a look at `4.4.0`+. We've added a new Drop-In component and exposed our UI components (along with styling). More info [here](https://github.com/braintree/braintree_ios/blob/master/Docs/Drop-In-Update.md).

We'd love feedback on whether this new Drop-In and UI customization could solve these issues for you. Feel free to open a new issue with any thoughts/suggestions.
