### ISSUE TITLE
Are there plans to support secure URLs?

### ISSUE THREAD

**Issue by Reflejo** [braintree/braintree_ios#166]
Right now the only exception we need in our app is this one (`api.braintreegateway.com`). Being payments such a sensitive matter, I'd love to see secure transport compliance on braintree domains. Thanks!

**Comment by skunkworks** [comment]
@Reflejo The SSL certificate is planned to be upgraded to SHA-256 on 9/30, so until that is in place, the ATS exception is a temporary workaround. Needless to say, we're all looking forward to compliance to better security practices :+1:

**Comment by Reflejo** [comment]
Thanks @skunkworks

**Comment by burnto** [comment]
Also, to be clear, the current SHA-1 cert scheme has not been compromised, so is not actually insecure. 

Recent cryptographic research has shown SHA-1 to be weaker than it was believed when designed and implemented. While not yet easily compromised, this weakness grows as computing power continues to improve, and industry best-practice now recommends moving away from SHA-1 to sign SSL certificates, in favor of SHA-256 before SHA-1 is easily broken.

**Comment by jksk** [comment]
@skunkworks Any update on this?

**Comment by skunkworks** [comment]
@jksk @Reflejo Thanks for your patience. The SSL certificate for `api.braintreegateway.com` has been upgraded, so there's no longer a need to add an exception for this domain. Our README and official documentation has been updated to reflect this.

**Comment by jksk** [comment]
Thanks a lot!
