### ISSUE TITLE
iOS9 Xcode 7 BT3.9.3 -lPaypalMobile-BT not found

### ISSUE THREAD

**Issue by kitetaka** [braintree/braintree_ios#167]
After upgrading to Xcode 7 with BT 3.9.3 ios (manual installation without cocoa pod) I get the following linker error:

ld: library not found for -lPayPalMobile-BT
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any idea how to fix this? thanks.

**Comment by skunkworks** [comment]
Hi @kitetaka ,

Can you double check that the `libPayPalMobile.a` file is included and linked by your project?

**Comment by Milan3792** [comment]
Hi,
I am facing the same issue. Also my project contains libPayPalMobile.a file. 
What else I can do to fix this?

**Comment by skunkworks** [comment]
@Milan3792 Can you confirm that the library is linked under `Xcode > Build Phases > Link Binary With Libraries`?

**Comment by Milan3792** [comment]
@skunkworks Yes I somehow missed it. I just removed Braintree pods from my project and installed it again. Now it works fine.

**Comment by skunkworks** [comment]
Glad to hear that worked!
