### ISSUE TITLE
Method override for the designated initializer of the superclass '-init' not found.

### ISSUE THREAD

**Issue by NoceloEder** [braintree/braintree_ios#168]
When I try to compile my project, generate this error:

`Method override for the designated initializer of the superclass '-init' not found.`

in **BTAPIResourceValueTypeError.m**

Everything was working fine but I upgraded Xcode (To Xcode 7) and this error occurred.

**Comment by intelliot** [comment]
Hi @NoceloEder - the file `BTAPIResourceValueTypeError.m` was removed in a previous version of the Braintree iOS SDK. For Xcode 7 compatibility, update to [version 3.9.3](https://github.com/braintree/braintree_ios/releases/tag/3.9.3) or later.

For example, if you're using CocoaPods, use:
```
pod update Braintree
```

If the error persists, please let us know which version of the Braintree iOS SDK you're using.

**Comment by NoceloEder** [comment]
Thanks for reply ! ... it's work now !! @intelliot

**Comment by intelliot** [comment]
:balloon:
