### ISSUE TITLE
libPayPalMobile-BT.a: Symbol(s) not found for architecture armv7

### ISSUE THREAD

**Issue by entrifis** [braintree/braintree_ios#169]
Trying to update my code for Xcode 7. Having installed the SDK via cocoapods pointing to this repo, I get the following when building

Undefined symbols for architecture armv7:
  "_vImageBoxConvolve_ARGB8888", referenced from:
      -[UIImage(ImageEffects) applyBlurWithRadius:tintColor:saturationDeltaFactor:maskImage:] in libPayPalMobile-BT.a(UIImage+ImageEffects.o)
  "_vImageMatrixMultiply_ARGB8888", referenced from:
      -[UIImage(ImageEffects) applyBlurWithRadius:tintColor:saturationDeltaFactor:maskImage:] in libPayPalMobile-BT.a(UIImage+ImageEffects.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks

**Comment by agrawalajay** [comment]
Hi Alex, 

I am facing same issue and not able to figure out how to fix it. 
Can you please point me how to fix it?

Thanks in advance :)

**Comment by intelliot** [comment]
@agrawalajay If the problem persists, feel free to open a new issue and indicate which version of the Braintree iOS SDK you're using. Thanks :)

**Comment by skunkworks** [comment]
Hi,

Can you try linking the Accelerate framework to your project? See here:

https://github.com/paypal/PayPal-iOS-SDK/issues/288

**Comment by agrawalajay** [comment]
I am doing manual integration of braintee, I just want to integrate Apple Pay. The project is pretty old and cocoa pod is not working (getting conflicts with project settings).

I have removed Accelerate framework and added it again but still getting error (I am running the code on iPhone6+), Please let me know if any other details required:

Undefined symbols for architecture arm64:
  "_vImageBoxConvolve_ARGB8888", referenced from:
      -[UIImage(ImageEffects) applyBlurWithRadius:tintColor:saturationDeltaFactor:maskImage:] in libPayPalMobile-BT.a(UIImage+ImageEffects.o)
  "_vImageMatrixMultiply_ARGB8888", referenced from:
      -[UIImage(ImageEffects) applyBlurWithRadius:tintColor:saturationDeltaFactor:maskImage:] in libPayPalMobile-BT.a(UIImage+ImageEffects.o)
  "_kUTTypePropertyList", referenced from:
      -[PPZebraOnePasswordExtension processExtensionItem:completion:] in libPayPalMobile-BT.a(PPZebraOnePasswordExtension.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by skunkworks** [comment]
Hi @agrawalajay, try adding `-ObjC` and `-lc++` to Other Linker Flags. If that doesn't work, please open a separate GitHub issue.

Thanks.
