### ISSUE TITLE
How to configure online environment

### ISSUE THREAD

**Issue by qiudushu** [braintree/braintree_ios#171]
How to configure online environment。  I need a test environment and an online environment And can be changed in the code can very good ，Please tell me the answer

**Comment by qiudushu** [comment]
I according to the demo of braintree official document just offline instead of online, and you really in the demo Don't understand how a choice environment will appear the corresponding is online or offline environment

**Comment by qiudushu** [comment]
![_2015-09-23_ 2_00_47](https://cloud.githubusercontent.com/assets/8954445/10038717/fdf7384c-61fb-11e5-8d34-af808177bd02.png)
How to   become  OnLine   Pay  environment????

**Comment by sornon1** [comment]
@qiudushu, the live environment is selected in [your server-side configuration](https://developers.braintreepayments.com/start/hello-server#install-and-configure), and depends on have a [production account](https://articles.braintreepayments.com/get-started/try-it-out).

**Comment by qiudushu** [comment]
@sornon1  what do  you  mean ?  you  mean that  the  environment  depends on service  or  userID  ??

**Comment by qiudushu** [comment]
@sornon1 what do you mean ? you mean that the environment depends on service or userID ??  Can you Tell me the detailed point, and the author's demo is can choose different development environment, but I can't find, in the example code defines the notice there is no listener pass that value


eg://此处传值设置
    [[NSNotificationCenter defaultCenter] postNotificationName:kIASKAppSettingChanged
                                                        object:[_specifier key]
                                                      userInfo:@{
                                                          _specifier.key: values[indexPath.row]
                                                      }];
but  I can't  find  the  kIASKAppSettingChanged  of The listener

**Comment by skunkworks** [comment]
The environment is encoded within the client token you use to set up Braintree. The client token is generated by your own server, and your server generates either sandbox or production client tokens based on its credentials.

Please see [Simple Server](https://developers.braintreepayments.com/ios+ruby/start/hello-server) for more information.

**Comment by qiudushu** [comment]
@skunkworks   Do  you mean that  According to the server to provide token in braintree code will then identify the current environment is online or offline? In my code I need to configure the Braintree payment environment?

**Comment by qiudushu** [comment]
@skunkworks   Do  you mean that  According to the server to provide token in braintree code will then identify the current environment is online or offline? In my code I need to configure the Braintree payment environment?

**Comment by qiudushu** [comment]
@skunkworks  I in Braintree code you can clearly see their pay set the current environment, the current environment can pay points the Sandbox and production environment, and now I want to be in my own code also to separate the two kinds of environment how should I do? In the demo code really can't understand, please advise thank you
