### ISSUE TITLE
How to perform make default Credit card once selected on Drop-In UI in objective-c

### ISSUE THREAD

**Issue by ramadhanfebbry** [braintree/braintree_ios#172]
I have multiple Credit card(CC A & CC B), and as default it used CC A. When I change it to CC B, the default Credit card  is changed but when I Refresh the page, it does not make any changes. Please help me. Thanks

**Comment by qiudushu** [comment]
I  want  to know  that yours  is  Online or Mock data???
![_2015-09-23_ 2_00_47](https://cloud.githubusercontent.com/assets/8954445/10041685/73a5347e-6218-11e5-9043-f9366448995c.png)

**Comment by skunkworks** [comment]
The drop-in UI does not currently support a way to designate a default payment method. We are planning on adding a lot of enhancements to Drop-In in the near future, so if this is something you need, please open a feature request. Thanks!

**Comment by tigerchen** [comment]
So I can add a second card, but i can't use it?  That seems very strange.  How do use drop-in UI to use CC B?
