### ISSUE TITLE
iOS9 Xcode 7 BT 3.9.3 canCreatePaymentMethodWithProviderType:ApplePay Always No

### ISSUE THREAD

**Issue by BlainEllis** [braintree/braintree_ios#173]
Whilst running Braintree 3.9.3 with Xcode 7

[self.provider canCreatePaymentMethodWithProviderType:BTPaymentProviderTypeApplePay]

Always returns no.

However when running Braintree 3.9.2 with Xcode 6, everything works as it should.

I’ve set the NSAppTransportSecurity as required for IOS9.

Any ideas? thanks.

**Comment by skunkworks** [comment]
Here's the code snippet that this performs:

```
/// In BTPaymentApplePayProvider.m
- (BOOL)canAuthorizeApplePayPaymentWithoutAnalytics {
#if BT_ENABLE_APPLE_PAY
    if (![PKPayment class]) {
        return NO;
    }

    if (self.client.configuration.applePayStatus == BTClientApplePayStatusOff) {
        return NO;
    }

    if (![self paymentAuthorizationViewControllerCanMakePayments]) {
        return NO;
    }

    return YES;
#else
    return NO;
#endif
}
```

So the things to check are:

1. Are you using Cocoapods? Please make sure that `pod "Braintree/Apple-Pay"` is explicitly added to your `Podfile`.
2. If you're not using Cocoapods, do you have the `BT_ENABLE_APPLE_PAY=1` preprocessor macro defined in your project?
3. Has Apple Pay been disabled in the Braintree Control Panel for your merchant account?
4. Are you trying to make a payment with an unsupported type of card?

Let me know if any of those apply.

**Comment by BlainEllis** [comment]
Cocoapods is setup as it should with the Apple-Pay extension:

![screen shot 2015-09-28 at 09 39 43](https://cloud.githubusercontent.com/assets/8177931/10131270/f24cef5e-65c6-11e5-96ae-09b8f8302db4.png)

I've double checked the preprocessor macro:

![screen shot 2015-09-28 at 09 40 19](https://cloud.githubusercontent.com/assets/8177931/10131285/0a21401c-65c7-11e5-8ffc-0da259947eff.png)

As this is a client application, I don't have direct access to their BT account but i've just retested in Xcode 6 with BT 3.9.2 and apple pay is working fine.

![screen shot 2015-09-28 at 09 59 12](https://cloud.githubusercontent.com/assets/8177931/10131350/9e82a4b2-65c7-11e5-9894-150585c123e7.png)

Output:
[3815:204326] Yes

![screen shot 2015-09-28 at 09 53 19](https://cloud.githubusercontent.com/assets/8177931/10131386/dd790e54-65c7-11e5-9ccb-3dddb42dde26.png)


Same code in Xcode 7 with BT 3.9.3 and the output is No.

The only difference being the new BT version and NSAppTransportSecurity.

![screen shot 2015-09-28 at 10 03 07](https://cloud.githubusercontent.com/assets/8177931/10131455/4028785a-65c8-11e5-9367-8dcbfd2b7c05.png)

**Comment by skunkworks** [comment]
Hi,

Can you add a breakpoint in Xcode to `canAuthorizeApplePayPaymentWithoutAnalytics` and step through to see which part is returning false?

**Comment by BlainEllis** [comment]
Hi Richard,

I’ve just re-installed BT 3.9.3, disabled bitcode as I did before, and canCreatePaymentMethodWithProviderType is now returning yes.

Is there anything that has changed with BT 3.9.3? otherwise I’m unsure as to why this is working now as I haven’t changed any of the core code.

Thanks for all your help,

Blain


On 28 Sep 2015, at 17:11, Richard Shin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Can you add a breakpoint in Xcode to canAuthorizeApplePayPaymentWithoutAnalytics and step through to see which part is returning false?

—
Reply to this email directly or view it on GitHub<https://github.com/braintree/braintree_ios/issues/173#issuecomment-143792050>.



[http://email2inbox.co.uk/2014/txd/signature/logo.jpg]

Blain Ellis - iOS Developer
blain.ellis@txdlimited.co.uk<mailto:blain.ellis@txdlimited.co.uk>
01785 257777<tel:01785257777> |  www.txdlimited.co.uk<http://www.txdlimited.co.uk>

[http://email2inbox.co.uk/2014/txd/signature/BE.jpg]<https://www.behance.net/txddesign>[http://email2inbox.co.uk/2014/txd/signature/IG.jpg]<http://instagram.com/txdltd>[http://email2inbox.co.uk/2014/txd/signature/LI.jpg]<http://www.linkedin.com/company/txd-ltd>[http://email2inbox.co.uk/2014/txd/signature/FB.jpg]<https://www.facebook.com/txddigitalmarketing>[http://email2inbox.co.uk/2014/txd/signature/TW.jpg]<https://twitter.com/txdltd>[http://email2inbox.co.uk/2014/txd/signature/YT.jpg]<https://www.youtube.com/user/txdltd>




[http://email2inbox.co.uk/2014/txd/signature/zonal.jpg]

PART OF THE ZONAL FAMILY


TXD Limited, 1 Cheshire House, Hurricane Close, Stafford, ST16 1GZ
Registered in England & Wales No. 5326496 | VAT Reg. No. 861 7358 04    [http://email2inbox.co.uk/2014/txd/signature/dma.jpg]


This email is intended solely for the addressee(s). Access to this email by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution, or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful. If you are not the intended recipient please contact us immediately.

**Comment by skunkworks** [comment]
Blain, this is a bit puzzling, as the only changes between 3.9.3 and 3.9.4 were to add support for the new Apple Pay `shippingContact` and `billingContact` properties (which use `PKContact` instead of `ABRecordRef`).

Can you try adding a breakpoint to `canAuthorizeApplePayPaymentWithoutAnalytics` and stepping through the Braintree SDK code line by line to see what's happening in 3.9.4?

**Comment by intelliot** [comment]
@BlainEllis Based on the small screenshot of your code, it looks like you're storing the client token in `NSUserDefaults`. This is not recommended, and may cause Braintree authentication to fail if the client token expires or becomes invalid. Instead, for each session, could you generate a fresh client token on your server?

The value of `self.client.configuration.applePayStatus` comes from the client token, so I imagine the problem could be related.

**Comment by BlainEllis** [comment]
@skunkworks Thank you for your help, I think Elliot has found the issue.

@intelliot  The initial client token is used to just check for Apple Pay and then I generate a new token for each payment. 

I'm implementing it this way to prevent any delay for the user when going to the checkout screen as we are expecting our users to be using our application with cellular data.

Is there a specific expiration time or an expiration check available so that I can only send out for a new token if the current token has expired?

**Comment by skunkworks** [comment]
@BlainEllis Our recommendation is that a fresh client token is generated once per session. I understand why you're caching the token -- I think we have a good solution for you in our next major release that should allow you to check your Apple Pay status with less delay.

**Comment by orinmurphy** [comment]
@skunkworks I am having a problem with this too, however my token is definitely valid.

At `canAuthorizeApplePayPaymentWithoutAnalytics `, mine returns NO here:
`    if (![self paymentAuthorizationViewControllerCanMakePayments]) {
        return NO;
    }
`
............
Going deeper, at `paymentAuthorizationViewControllerCanMakePayments`, it returns NO here:

`return [PKPaymentAuthorizationViewController canMakePaymentsUsingNetworks:self.paymentRequest.supportedNetworks];`

I am using:
pod 'Braintree', '~> 3.9'
pod 'Braintree/Apple-Pay', '~> 3.9'
