### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_Braintree"

### ISSUE THREAD

**Issue by arifmc** [braintree/braintree_ios#174]
Hello,

I'm currently trying to integrate braintree to an existing project, but when I tried the tutorial with code '[Braintree setReturnURLScheme:@"com.your-company.Your-App.payments"];' and 'self.braintree = [Braintree braintreeWithClientToken:clientToken];' I got an error message when I tried to compile the app.

if I remark those two line of code, the project can be build successfully.

Here is some info about the xcode I use:

XCode ver : 7.0
Install platform : Cocoapod
Braintree series : 3.9.4
Minimum App iOS : 8.0

I hope you can help me with this issue, thanks :)

Best Regards,
Arif MC

**Comment by skunkworks** [comment]
Hi,

Can you confirm that you are importing `Braintree.h`?

`#import <Braintree/Braintree.h>`

**Comment by arifmc** [comment]
Yes I did import the braintree.h

I'm using '#import <Braintree/Braintree.h>' in my AppDelegate.m

**Comment by arifmc** [comment]
Sorry, I meant #import <Braintree/Braintree.h>

**Comment by skunkworks** [comment]
Are you using the `.xcworkspace` file and not the `.xcproj` file?

**Comment by arifmc** [comment]
Yes, I'm using the xcworkspace

**Comment by skunkworks** [comment]
It's possible that your project's header search paths may not be configured correctly. It should look like this:

<img width="518" alt="screen shot 2015-09-27 at 11 01 32 pm" src="https://cloud.githubusercontent.com/assets/563375/10128776/c2dc184a-656b-11e5-9be0-8b210e19fb35.png">

Try creating a throwaway project and importing Braintree.

**Comment by arifmc** [comment]
I checked the header search path, and it's the same as yours

![screen shot 2015-09-28 at 1 10 53 pm](https://cloud.githubusercontent.com/assets/3960207/10128906/6cfb1a8a-65e2-11e5-94c0-6478f1ad7a79.png)

I tried creating a new project and it works fine, maybe you have some pointer about things that I should check?

**Comment by arifmc** [comment]
Hi,

I fix this problem by adding $(inherited) to the other linker flags.

Thanks for the support @skunkworks :)

**Comment by alicooke** [comment]
I am having the same issue described here only the error is slightly different:

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_Braintree", referenced from:
      objc-class-ref in PaymentViewController.o
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have checked all of the current suggestions and tried adding $(inherited) to the Pods 'other linker flags' but to no avail.

I understand that the error is to do with the class no being properly added to the project but cannot see any of the usual issues.

Any help?

**Comment by skunkworks** [comment]
Hi @alicooke, can you open a new issue? Please include which integration method you're using. If you're using Cocoapods, can you verify that in Project > Build Phases > Link Binary with Libraries you see the Cocoapods `.a` file? You can try removing it and re-running `pod install`.

**Comment by alicooke** [comment]
Hi Richard,

I have opened a new issue, #186, on GitHub. I would appreciate it if you could take a look when you have time.

Thanks,

Ali

**Comment by miteshkhatri** [comment]
I am also getting similar error:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_BTAPIClient", referenced from:
      objc-class-ref in VCSearch.o
  "_OBJC_CLASS_$_BTAppSwitch", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
