### ISSUE TITLE
Application build fails when using Carthage (4.0 beta)

### ISSUE THREAD

**Issue by lukef** [braintree/braintree_ios#176]
The change in made PR #170 breaks builds when using Carthage. The Carthage build appears to work fine, but linking to the frameworks will fail.

The `BraintreeCore.h` header file cannot be found as it is looking for the file locally (in the framework) and not as part of a separate framework. The problem manifests when you try to import any framework that is not BraintreeCore (i.e.: BraintreeCard).

I've tried adding the Carthage build folder to the `User Headers` section in the project. Any suggestions appreciated.

I think this could be related/similar to #161 where the comment was that it will be fixed in 4.0, but it still appears to be an issue.

**Comment by skunkworks** [comment]
Thanks for reporting this to us. As you can see, it's getting more complex supporting so many integration methods. I'll take a look at this today.

**Comment by burnto** [comment]
@skunkworks @intelliot let's talk about setting up some hosted automated smoke tests for each integration method.

**Comment by lukef** [comment]
Let me know what you need. We're using it on a fairly large (soon to be upcoming) production build that **does not** (read: will not/ can not) use cocoapods, so whatever we can do to get it working in an upgradeable manner is definitely in our benefit also.

FWIW - referencing all of the BTCore headers as `#import <BraintreeCore/...>` is the prescribed solution here, but I understand how it breaks other things.

**Comment by skunkworks** [comment]
@lukef I've got a pull request on our internal repo that should address this issue. It involves using `#if __has_include(...)` to check which `#import` style to use (angle brackets vs. double quotes).

I'll update this issue when it's merged.

**Comment by lukef** [comment]
Awesome. Thanks!

**Comment by skunkworks** [comment]
@lukef Just pushed some changes that should fix Carthage. Let us know if things are still wonky!

**Comment by lukef** [comment]
One side issue, the framework projects refer to a development team that is unavailable to the build environment. I had to manually remove the Team ID and then re-run `carthage build`.
