### ISSUE TITLE
method override for the designated initializer of the superclass '-init' not found

### ISSUE THREAD

**Issue by alphahelixius** [braintree/braintree_ios#177]
Hey guys, 

I am encountering issue compiling with Xcode 7 iOS 9 SDK and Braintree 3.9.4.
Error says "method override for the designated initializer of the superclass '-init' not found" in BTAPIResponseParser.m

Any suggestion? Thanks.

**Comment by skunkworks** [comment]
Hey @alphahelixius,

You're using Cocoapods, right? Can you try blowing away your old copy of the Braintree pod? Most likely Cocoapods is caching some old copy of the BTAPIResponseParser.m. It should look like this:

https://github.com/braintree/braintree_ios/blob/master/Braintree/API/Client/BTAPIResponseParser.m

**Comment by alphahelixius** [comment]
@skunkworks Thanks! It's working now.

**Comment by skunkworks** [comment]
Happy to hear you're unblocked :)
