### ISSUE TITLE
3.9.4 with Apple Pay subspec does not build with Xcode 6

### ISSUE THREAD

**Issue by eager** [braintree/braintree_ios#178]
I believe this is because `PKContact` was added in the iOS 9 SDK.

![screen shot 2015-10-01 at 6 34 24 pm](https://cloud.githubusercontent.com/assets/4656/10235876/2c5a346e-6855-11e5-9cbf-1296b517701d.png)

**Comment by skunkworks** [comment]
Hi @eager,

We've bumped our requirements to Xcode 7 and iOS SDK 9 as of version 3.9.4.

**Comment by eager** [comment]
@skunkworks Oops—I now see that in README.md. It might be worth calling out in CHANGELOG.md, like you did with Xcode 6.3 in the [3.9.2 update](https://github.com/braintree/braintree_ios/blob/2f7f237b95e1d377f3b85df5fc1bad436bc8519c/CHANGELOG.md#392-2015-07-08).

**Comment by skunkworks** [comment]
Good call! Sorry about that.
