### ISSUE TITLE
tokenizeApplePayPayment always fails

### ISSUE THREAD

**Issue by pauldunstone** [braintree/braintree_ios#180]
Hi there

We are integrating Apple Pay into our app. The method tokenizeApplePayPayment is called successfully after the Apple pay pop-up but I get the following error message every time which crashes the app:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Braintree tokenizeApplePayPayment:completion:]: unrecognized selector sent to instance 0x13652e680'

I am using Braintree version 3.7.0. The braintree object is not nil when the method is called and I get a PKPayment payment object with a token. 

Any ideas?

**Comment by jksk** [comment]
Looking at the implemention, it seems the method is only included if BT_ENABLE_APPLE_PAY is defined. If it isn't, that's the sort of error you'd see. In the discussion for #173, you can see some steps to take to make sure this the case (include the Apple Pay subspec in the Podfile, etc).

**Comment by pauldunstone** [comment]
Thanks for your feedback.
I looked at link and can confirm that the BT_ENABLE_APPLE_PAY=1 preprocessor macro is defined in the project file and the targets. Apple pay is also enabled in the Braintree Control Panel.
Any other ideas?

**Comment by pauldunstone** [comment]
BT_ENABLE_APPLE_PAY=1 is definitely set, the following code runs in the didAuthorizePayment method before tokenizeApplePayPayment: 

    #if BT_ENABLE_APPLE_PAY
        NSString *test = @"test";
    #endif

**Comment by skunkworks** [comment]
@pauldunstone It sure seems like `BT_ENABLE_APPLE_PAY` isn't being respected. Can you tell us if the error message changes if you edit `Braintree.m` to remove the `#if BT_ENABLE_APPLE_PAY` preprocessor macro?

**Comment by pauldunstone** [comment]
Thanks @skunkworks. Yep we tried that. Removed the preprocessor from the method so it just looks like this:

- (void)tokenizeApplePayPayment:(PKPayment *)payment
                     completion:(void (^)(NSString *, NSError *))completionBlock {
    [self.client postAnalyticsEvent:@"custom.ios.tokenize.apple-pay"];

    [self.client saveApplePayPayment:payment
                             success:^(BTApplePayPaymentMethod *applePayPaymentMethod) {
                                 if (completionBlock) {
                                     completionBlock(applePayPaymentMethod.nonce, nil);
                                 }
                             }
                             failure:^(NSError *error) {
                                 if (completionBlock) {
                                     completionBlock(nil, error);
                                 }
                             }];
}

And we get exactly the same error message.

**Comment by skunkworks** [comment]
That's very bizarre. Are you using Cocoapods? If so, can you try removing the `Braintree` and `Braintree/Apple-Pay` pods, running `pod install`, then adding them back in again?

**Comment by pauldunstone** [comment]
Yes using Cocoapods. I removed both and installed again. Here is the pods file:

xcodeproj 'App'

target "App" do
    
    pod 'Braintree'

    pod 'Braintree/Apple-Pay'

    pod 'SBJson', '~> 4.0.0'
    
    pod 'QR-Code-Encoder-for-Objective-C'

end

target "App" do

end

Exactly the same error.

**Comment by pauldunstone** [comment]
Any further ideas? We have tried everything we can think of.

**Comment by skunkworks** [comment]
Hey @pauldunstone, we're a bit out of theories, based on the information you've provided.

However, I have a wild feeling your project is messed up such that the version of `Braintree.m` that you've been looking at is not the one that's actually being used by your app. One thing that could confirm this is:
* Remove the `#if BT_ENABLE_APPLE_PAY` from `Braintree.m`
* Add a breakpoint to `Braintree.m` in `initWithClient:`
* Run your app, wait for it to hit the breakpoint you've set
* Double check in the debugger that Braintree.m is still missing the `#if BT_ENABLE_APPLE_PAY`

**Comment by pauldunstone** [comment]
Hi all, thanks for your help. So it appears to be an odd bug when we updated the new version of XCode. We tried on a new Mac and all worked as expected so the Pod wasn't updating on our existing Mac. We went back to the old Mac and cleared out all cached copies of Braintree, updated Cocoapods, removed and installed the Pod file again and it worked.

**Comment by skunkworks** [comment]
Glad to hear it's working again -- Cocoapods does a lot of aggressive caching, so frequently the solution is to clear out `Pods/`.
