### ISSUE TITLE
3D-Secure SSLHandshake failed in iOS 9

### ISSUE THREAD

**Issue by arbitur** [braintree/braintree_ios#181]
When trying to verify a credit card using the `verifyCardWithNonce` method, after presenting the `BTThreeDSecureAuthentificationViewController` which is passed with the `requestsPresentationOfViewController` delegate method I get these error messages only in iOS 9

> CFNetwork SSLHandshake failed (-9824)

> NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)

This has something to do with the new network security configurations of iOS 9 with the `NSAppTransportSecurity` key in `info.plist`.

What is the domain I need to add into that key?

I tried adding `secure5.arcot.com` but that didn't resolve the error.

**Comment by arielpollack** [comment]
what did you do to fix this eventually?

**Comment by arbitur** [comment]
@arielpollack I just added the wrong values in the .plist.

Correct ones I got from Facebook SDK iOS 9 update x)

    <key>secure5.arcot.com</key>
        <dict>
	<key>NSIncludesSubdomains</key>
	<true/>
	<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
	<false/>
    </dict>
