### ISSUE TITLE
No way to handle switching back to the app from Safari/PayPal app via the iOS task manager or dismissing of SFSafariViewController via Done button

### ISSUE THREAD

**Issue by corristo** [braintree/braintree_ios#182]
I think there should be a way to be notified about these things, to be able to notify backend about payment cancellation, for example.

I'm using 4.0 beta branch.

**Comment by corristo** [comment]
Well, I've found the following in doc comments:

```
/// @note During the app switch authorization, the user may switch back to your app manually. In this case, the caller
/// will not receive a cancellation via the completionBlock. Rather, it is the caller's responsibility to observe
/// `UIApplicationDidBecomeActiveNotification` and `UIApplicationWillResignActiveNotification` using `NSNotificationCenter`
/// if necessary.
```

This explains app switching, but SFSafariViewController is still an issue.

**Comment by skunkworks** [comment]
Hi @corristo, I've merged in a pull request that should take care of this. Thanks for reporting the issue!

**Comment by corristo** [comment]
@skunkworks :+1:
