### ISSUE TITLE
BrainTree Cocoapods causing errors

### ISSUE THREAD

**Issue by Devendranath** [braintree/braintree_ios#183]
I am suing XCode7 beta.
Im my project i am using AMSlideMenu from cocoapods. Working fine.
Now I just added Braintree pod.
Whenever I am writing #import "Braintree.h" to my bridging file fausing lot of errors related to AMSlidemenu.
<img width="1128" alt="screen shot 2015-10-15 at 7 29 35 am" src="https://cloud.githubusercontent.com/assets/12444810/10502944/dcd5989c-730e-11e5-826a-341023a58139.png">

Image Link: https://cloud.githubusercontent.com/assets/12444810/10502944/dcd5989c-730e-11e5-826a-341023a58139.png

Errors:
Duplicate interface definition of  AMSlidemenuViewController.
Duplicate declaration of emums etc.

**Comment by skunkworks** [comment]
Hi,

It is unlikely that the Braintree SDK is causing this issue. This is most likely a misconfiguration with your Xcode project and/or CocoaPods. Check Project > Build Phases > Link Binary with Libraries for duplicates.

**Comment by Devendranath** [comment]
I tried different ways but I couldn't resolve them. Finally I removed AMSlideMenu from podfile and Added manually. Braintree added as cocoapod
