### ISSUE TITLE
Method override for the designated initializer....

### ISSUE THREAD

**Issue by mattfiocca** [braintree/braintree_ios#184]
After trying to build a project that hasn't been built in a while, after having updated to XCode 7, i'm getting this build error now:

`Method override for the designated initializer of the superclass '-init' not found`

in `BTAPIResponseParser.m`

**Comment by skunkworks** [comment]
Are you running > 3.9.3? If so, try removing and reinstalling the Braintree pod.

**Comment by intelliot** [comment]
Also, if you're using CocoaPods, you should be able to update Braintree by running this on the command line:
```
pod update Braintree
```

**Comment by mattfiocca** [comment]
Ah,`pod update Braintree`, good call. I had 3.9.1
