### ISSUE TITLE
Undefined symbols for architecture i386:   "_OBJC_CLASS_$_Braintree"

### ISSUE THREAD

**Issue by alicooke** [braintree/braintree_ios#186]
I'm currently trying to integrate braintree to an existing project, but when I tried the tutorial with code '[Braintree setReturnURLScheme:@"com.your-company.Your-App.payments"];' I got an error message when I tried to compile the app.
![screen shot 2015-10-20 at 14 38 52](https://cloud.githubusercontent.com/assets/8394721/10608769/5a7cf394-7738-11e5-966c-1cc9bee38e00.png)

If I remove the line of code the app compiles correctly.

I am using Xcode 7.0.1.
I added braintree (3.9.6) to the "app name" target but not to the "app name"Tests using Cocoapods. I did not set a global platform version of iOS.
![screen shot 2015-10-20 at 11 29 14](https://cloud.githubusercontent.com/assets/8394721/10604681/e5d943e0-771d-11e5-8f90-4930c0afdc0b.png)
I came across this small error when installing Cocoapods however I don't think it is relevant: "unable to convert "\x84" from ASCII-8BIT to UTF-8 for lib/active_support/values/unicode_tables.dat, skipping"
![screen shot 2015-10-19 at 12 15 20](https://cloud.githubusercontent.com/assets/8394721/10612495/f7035a36-7748-11e5-83b8-9d626ea908da.png)

I am importing Braintree/Braintree.h in AppDelegate.h.
I am using the .xcworkspace file.
The header files are configured correctly.
![screen shot 2015-10-20 at 09 30 28](https://cloud.githubusercontent.com/assets/8394721/10601952/3af3ce38-770d-11e5-9f3c-d24f4a8120fe.png)
I have added $(inherited) to the other linker flags as was the issue in issue #174. 
![screen shot 2015-10-20 at 09 31 34](https://cloud.githubusercontent.com/assets/8394721/10601989/8c81b468-770d-11e5-97ea-11d825d7739c.png)
The Cocoapods .a library has been added (I removed and ran "pod install") with no errors in Terminal. (I really wanted this to be the issue :( )
![screen shot 2015-10-20 at 09 33 45](https://cloud.githubusercontent.com/assets/8394721/10602116/5a788554-770e-11e5-9333-a5f421240cb5.png)

The i386 architecture is what is used by the simulator however trying to run the app on my iOS device results in the same error but with architecture arm7.

Frustratingly I have made a new project and following the same steps it works! Unfortunately the app I am working is quite mature so copying files across to a new project is something I would really rather avoid.

Comparing the Build Settings I found that my app didn't include an entry into the Library Search Paths for the PayPal/mSDK. I added that to my app but it didn't fix the problem.
![screen shot 2015-10-20 at 09 57 46](https://cloud.githubusercontent.com/assets/8394721/10602629/5a5959a6-7711-11e5-9048-960484c7b31d.png)

As good as Xcode is, I feel it may have just lost the plot. Any help?

**Comment by skunkworks** [comment]
Thank you for providing this much information! :+1:  It's pretty clear that the Braintree pod is not being linked, and that it's most likely an Xcode project configuration issue.

I can think of a few things to try:

1. Can you check Project > Configurations and make sure that the correct configuration file is set? These can get messed up, so what I'd recommend is setting your app target's configuration to "None" and re-running `pod install`, which should set it back to the correct `Pods-<TargetName>.debug` and `Pods-<TargetName>.release` configurations.

<img width="852" alt="screen shot 2015-10-20 at 12 13 59 pm" src="https://cloud.githubusercontent.com/assets/563375/10618309/14f4a3da-7724-11e5-8b0b-5a9dcc82f636.png">

2. Try adding an explicit `link_with` statement in the `Podfile`, e.g.

```
target 'My Application Target' do
  link_with 'My Application Target'
  pod 'Braintree'
end
```

3. If these don't work, do you think it'd be possible to zip up your project and send it to me for debugging?

**Comment by alicooke** [comment]
Thank you for taking the time to help me.

I have followed the steps for setting the target configuration to 'None' and then re-running pod install. This was the result:
![screen shot 2015-10-21 at 09 20 27](https://cloud.githubusercontent.com/assets/8394721/10632404/27bd7ede-77dc-11e5-936a-5afaf5f7fb03.png)
This unfortunately didn't work.

I also tried adding the explicit link statement, again for no gain.

I will email richard@richardshin.com about getting a zipped copy of the app to @skunkworks . For anyone else reading this I will update this thread if a fix is found.

**Comment by skunkworks** [comment]
Good news! It's an issue with the "Other Linker Flags" in the Xcode build settings. Delete the "Any Architecture | Any SDK" entries under Debug and Release, and your project will compile.

I think you can also clean up the Other Linker Flags to only include $(inherited), but the big issue was that the "Any Architecture | Any SDK" entry was overriding the correct entries one level up.

**Comment by miteshkhatri** [comment]
I am also getting similar error:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_BTAPIClient", referenced from:
      objc-class-ref in VCSearch.o
  "_OBJC_CLASS_$_BTAppSwitch", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
