### ISSUE TITLE
BTAppSwitchDelegate methods are called by PayPal driver even if Safari View Controller is used

### ISSUE THREAD

**Issue by corristo** [braintree/braintree_ios#188]
In general, `-appSwitcherWillPerformAppSwitch:` looks like a good place to subscribe for `UIApplicationDidBecomeActiveNotification` (to handle possible user cancelation later), but behaviour mentioned in issue title is a bit misleading, because no app switches are actually performed with Safari View Controller.

**Comment by skunkworks** [comment]
This is a salient point! We will remove this notification when `SFSafariViewController` is presented.

**Comment by skunkworks** [comment]
This has been fixed in c7ee6748a1ce4c2b528dcb1cd52642b36602763d

**Comment by burnto** [comment]
:sunglasses:
