### ISSUE TITLE
Unable to switch to PayPal

### ISSUE THREAD

**Issue by pnuts2** [braintree/braintree_ios#189]
I had PayPal app installed, however, using Drop in UI and tapping on PayPal always bring up safari instead of the PayPal app.

This is in relation to v4-beta.

**Comment by skunkworks** [comment]
Hi @pnuts2 ,

Can you confirm that the PayPal URL schemes are added to the [URL Query whitelist](https://github.com/braintree/braintree_ios#url-query-scheme-whitelist)?

**Comment by pnuts2** [comment]
Yes, I have. See attached.
<img width="633" alt="screen shot 2015-11-04 at 11 15 05 am" src="https://cloud.githubusercontent.com/assets/2722800/10925791/59c3c6d6-82e5-11e5-8bd8-c1ec9d1f018a.png">

**Comment by skunkworks** [comment]
@pnuts2 Sorry it took so long to get back to you. iOS 9's default app switch behavior is to always use the `SFSafariViewController` and not switch to the PayPal wallet app. This will be changed in early 2016 when PayPal fully supports Universal Links. Sorry for the confusion -- we'll add documentation that makes this clearer.
