### ISSUE TITLE
ABRecordRef causing compile error in xCode7.1

### ISSUE THREAD

**Issue by johnscode** [braintree/braintree_ios#190]
I have an iOS app that compiles and runs fine under ios9 and xcode 7. We've recently updated one of the build boxes to xcode 7.1 and we are now getting the following error:

/Users/john/dev/unow/ios/Pods/Headers/Private/Braintree/BTApplePayPaymentMethod.h:8:33: error: 'ABRecordRef' is deprecated: first deprecated in iOS 9.0 - use CNContact, CNGroup, or CNContainer [-Werror,-Wdeprecated-declarations]
@property (nonatomic, readonly) ABRecordRef billingAddress;

Kind of unusual since deprecation usually causes warnings rather than errors. 

Note, that we are still compiling for deployment target ios9, so I'm not sure what is happening. Has anyone else gotten this error? I've looked through the headers and found the AB_DEPRECATED and 
AB_IGNORE_DEPRECATION macros. I'll try this but wanted to ask here since I can't be the only developer experiencing this.

Thanks in advance.

**Comment by skunkworks** [comment]
Hi @johnscode ,

The Braintree podspec adds a `-Werror` compiler flag, which elevates warnings to errors. My suggestion is to update to the latest version, which suppresses these deprecation warnings:

```
#if BT_ENABLE_APPLE_PAY
#import "BTApplePayPaymentMethod.h"

@interface BTApplePayPaymentMethod ()
@property (nonatomic, copy, readwrite) NSString *nonce;

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
@property (nonatomic, readwrite) ABRecordRef billingAddress;
@property (nonatomic, readwrite) ABRecordRef shippingAddress;
#pragma clang diagnostic pop
@property (nonatomic, readwrite, strong) PKContact *billingContact;
@property (nonatomic, readwrite, strong) PKContact *shippingContact;
@property (nonatomic, strong, readwrite) PKShippingMethod *shippingMethod;

@end
#endif
```

Barring that, you can also look into removing that flag.

**Comment by intelliot** [comment]
This compile error shouldn't occur in the latest version of the SDK. I'll close this issue now, but please let us know if the error recurs.
