### ISSUE TITLE
How to use SDK with Carthage in Swift project?

### ISSUE THREAD

**Issue by evgenyneu** [braintree/braintree_ios#192]
Hi, is there any documentation on how to use Braintree SDK with Carthage in a Swift iOS project? Before I used [a separate project](https://github.com/exchangegroup/braintree-framework-builder) to build a single Braintree framework file with Carthage. Everything worked with just a single include in the bridging header `#import <Braintree/Braintree.h>`.

Now I want to try your 4.0 beta repository instead. This is what I did. First, I have run `carthage update` with this line in the Cartfile.

```
github "braintree/braintree_ios" "4.0-beta"
```

Carthage built the following frameworks:

1. Braintree3DSecure.framework
1. BraintreeApplePay.framework
1. BraintreeCard.framework
1. BraintreeCore.framework
1. BraintreeDataCollector.framework
1. BraintreePayPal.framework
1. BraintreeUI.framework
1. BraintreeVenmo.framework

Which of those frameworks do I need to include in the project? I am just using the drop-in view controller.

I tried including Core, UI, Card and PayPal frameworks but it did not compile:

1. I got `'Braintree/Braintree.h' file not found` error on `#import <Braintree/Braintree.h>` line in my bridging header. I did not have this error before with my previous Carthage build.
1. In the source file I tried doing `import BraintreeCore` and `import BraintreeUI` but it complained:

```
"...Carthage/Build/iOS/BraintreeUI.framework/Headers/BTPaymentRequest.h:2:9: 'BTPostalAddress.h' file not found"
```

Which frameworks do I need to import in the Swift source files if any? Sorry for dumping all those questions here. Thanks.

**Comment by skunkworks** [comment]
Seems we have a bug in `BTPaymentRequest`! I'll get that fixed up.

One more thing: if you choose to use the bridging header, the umbrella
headers look like this:

```
#import <BraintreeCore/BraintreeCore.h>
#import <BraintreePayPal/BraintreePayPal.h>
#import <BraintreeUI/BraintreeUI.h>
```

etc.

**Comment by skunkworks** [comment]
I've merged in a commit that should fix the Carthage build. We're working on getting our CI set up to catch these issues, so thanks for reporting this!

**Comment by evgenyneu** [comment]
Thank you, that fixed the  `'BTPostalAddress.h' file not found` error.

I still can not build my project.

1) Initialising the Braintree object produces following error

> Use of unresolved identifier 'Braintree'

2) Using BTPaymentMethod class results in the error

> Use of undeclared type 'BTPaymentMethod'

Which frameworks do I need to include in my source code file?

I am currently including to following

```Swift
import BraintreeCore
import BraintreeUI
import BraintreePayPal
import BraintreeCard
```

I am not including anything in the Bridging header. And as I am embedding these frameworks: Core, UI, Card and PayPal currently. Thank you.

**Comment by skunkworks** [comment]
Hi @evgenyneu,

Those objects have been renamed. Instead of `Braintree`, you'll be using `BTAPIClient` and `BTCardClient`, `BTDropInViewController`, etc. directly.

`BTPaymentMethod` has become `BTPaymentMethodNonce`.

**Comment by evgenyneu** [comment]
Got it, thanks, is there documentation on this yet?

**Comment by skunkworks** [comment]
We're working on getting the documentation updated for 4.0, but you can see what we have in place already [on our docs site](https://developers.braintreepayments.com). Some of the code snippets are out-of-date (e.g. still using `Braintree`), but that should be updated within a few days.

**Comment by evgenyneu** [comment]
Thank you very much for your help @skunkworks!
