### ISSUE TITLE
Integrating Braintree iOS SDK using CocoaPod causing compiler error with paypal

### ISSUE THREAD

**Issue by huhxtt** [braintree/braintree_ios#194]
I installed Braintree using pod 'Braintree' but at compilation my project gives the following error:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PayPalTouch", referenced from:
      objc-class-ref in libBraintree.a(BTPayPalAppSwitchHandler.o)
ld: symbol(s) not found for architecture x86_64

Need help on that.

**Comment by intelliot** [comment]
Hi @huhxtt -

I wasn't able to reproduce this problem.

We released a new version of our SDK today: 4.0.0. Could you try it and let me know if the error persists?

With CocoaPods, you can update with `pod update Braintree`.

**Comment by huhxtt** [comment]
I had previous installed paypal library before and therefore pod ignored paypal library when installing braintree.

**Comment by intelliot** [comment]
@huhxtt - I'm not quite sure what you mean. Were you able to resolve the error by removing the PayPal library from your project?

**Comment by intelliot** [comment]
We recommend removing any previously-installed PayPal library from your project and using `BraintreePayPal` instead.

If you're still seeing compile errors, feel free to create a new issue along with steps for reproducing the problem. Thanks!
