### ISSUE TITLE
Cast from BTJSON! to unrelated type String always fail 4.0.0

### ISSUE THREAD

**Issue by nicpro85** [braintree/braintree_ios#195]
okay I've updated to Braintree 4.0.0 but now when accessing NSDictionary  in an NSArray coming from a json parsed with alamofire and accessed using subscript in swift they are considered as BTJSON... wtf

**Comment by nicpro85** [comment]
Basically now using responseJSON from Alamofire in swift return BTJSON! object  so I guess you changed the behavior of the JSON parsing library used by alamofire.

**Comment by intelliot** [comment]
Braintree iOS does not change the behavior of any other JSON parsing library. I believe you may be in touch with Braintree Support and that this issue is now resolved. If the problem persists, it would be helpful if you could provide steps for reproducing the problem (or even better, create a demo project that exhibits the problem). Thanks!

**Comment by nicpro85** [comment]
Yes its the same issue. well i dont have the time to replicate the issue as i just say « as! NSDictionary » to solve the problem. I think it might be linked to swift itself or Xcode. no big deal just useless warning appearing.

Thank you for your answer.

regards,

nicolas

**Comment by ninh-dws** [comment]
BTJSON conflicted with SwiftyJSON

**Comment by galu08** [comment]
Hi, I have the same problem. I'am using swift 2.0 braintree and Alamofire.


```swift
if responseJSON.result.isSuccess {

                //This have and Alert "Cast from BTJSON to unrelated type 'String' always fails"
                if let response = responseJSON.result.value as? [String: AnyObject] {
                    
                    if let text = response["locale"]?["en_US"]?["s_text"] as? String {
                        terms = text
                    }
                    
                    // This work
                    if let locale = response["locale"] as? [String: AnyObject] {
                        if let en_us = locale["en_US"] as? [String: AnyObject] {
                            if let text = en_us["s_text"] as? String {
                                terms = text
                            }
                        }
                    }
                }
}
```

**Comment by skunkworks** [comment]
After getting another report of this issue, we're taking a look at this again.

**Comment by skunkworks** [comment]
We've made a preliminary discovery as to the issue -- seems that the Swift compiler is doing strange things due to `BTJSON`'s implementation of `objectForKeyedSubscript`. We're hoping to have a fix/workaround shortly.

**Comment by skunkworks** [comment]
To everyone who has been affected by this issue, please upgrade to 4.1.2. Thanks for your patience.

**Comment by nicpro85** [comment]
I did suspected the subscript issue... swift is definitely still work in progress...
