### ISSUE TITLE
Optimizing BTUIJCBVectorArtView

### ISSUE THREAD

**Issue by superarts** [braintree/braintree_ios#198]
I know it's not your fault to put so many constants into `BTUIJCBVectorArtView` since that's what is required, but would you optimize it when there's a chance please? Compiler always spends quite a long time on this file and it's not even used in my product. Thanks in advance.

**Comment by skunkworks** [comment]
@superarts, does your app use anything in the UI component of our SDK? If not, you can omit that component by explicitly specifying the CocoaPods components you use in your Podfile. For example, if you only use cards and PayPal:

```
pod 'Braintree/Card', '~> 4.0.0'
pod 'Braintree/PayPal', '~> 4.0.0'
```

**Comment by skunkworks** [comment]
@superarts, the logo has been optimized in 56060cb489fefef6223e6ce710a7ea594e0137d7 and will be a part of our version `4.1.0` release. Thanks for reporting this!

**Comment by superarts** [comment]
Thank you @skunkworks !
