### ISSUE TITLE
Braintree/Braintree.h not found

### ISSUE THREAD

**Issue by filipajdacic** [braintree/braintree_ios#201]
Hello,

I am trying to install Braintree v4.1.2 iOS SDK to a fresh new iOS project and now when I am all done I think that I have a problem with headers.

My steps was:
1. Open xcode (7.2) and created a iOS Objective-C project
2. Opened Terminal and created Podfile with the following contents:
````
platform :ios, '9.0'
pod 'Braintree'
pod 'MBProgressHUD', '~> 0.9.1'
````
3. Run: ` pod install `, and installation finished with following messages:
````
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Braintree (4.1.2)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `braintreetest.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total
pod installed.
````

4. Opened my xcode project by clicking on a .xcworkspace file
5. Successfully configured and tested URL Schemes
6. Updated my AppDelegate.m file
7. Tried to build my project but got following error:
` 'Braintree/Braintree.h' file is not found `

![screen shot 2015-12-15 at 3 44 15 pm](https://cloud.githubusercontent.com/assets/4216693/11813621/c267b47c-a342-11e5-8f96-fb507631be23.png)

After that I have tried various ways to solve this problem by changing "User Header Search Paths" and similar but I did not managed to solve this problem.. :/

Also I need to mention that MBProgressHud is working properly.
And one strange thing is that libPods.a file is marked as red.

So, does anyone have idea how can I solve this problem and where I am wrong?

Thanks in advance,
Filip

**Comment by skunkworks** [comment]
Hi @filipajdacic, in version 4, we've removed `Braintree.h`. Instead, you can import the components you need individually. Check out our [migration guide](https://developers.braintreepayments.com/reference/general/client-sdk-migration/ios/v4#project-reorganization) for more details.

For example, in your app delegate, you'll need to import `BraintreeCore.h`.

**Comment by filipajdacic** [comment]
@skunkworks Thank you very much! This solved my problem.
I didn't see this migration guide because I just followed steps for integration from website.

**Comment by xManson** [comment]
try import #import <Braintree/BraintreeCore.h>

**Comment by xManson** [comment]
#import < Braintree/BraintreeCore.h >

**Comment by williamli** [comment]
for me, I had to replace

`#import "BraintreeCore.h`

with 

`#import "BraintreeCore/BraintreeCore.h"`
