### ISSUE TITLE
paypal 2.4.0

### ISSUE THREAD

**Issue by syedrazackimran** [braintree/braintree_ios#204]
![screen shot 2015-12-29 at 11 00 14 am](https://cloud.githubusercontent.com/assets/15051045/12029918/cbdc5bfa-ae1b-11e5-8955-955e64de04cd.png)

herewith i attached screen shot of my issues .. before a week its works fine .. now i getting crash report like this . kindly solve it ASAP. xcode 7.0 ios 9.0

**Comment by skunkworks** [comment]
Hi,

Can you provide more context, e.g. what the view controller is presenting, how often it crashes, what conditions might cause this. It will help us to isolate the underlying issue. Thanks!

**Comment by syedrazackimran** [comment]
![screen shot 2015-12-29 at 11 11 14 am](https://cloud.githubusercontent.com/assets/15051045/12029985/e91f2822-ae1c-11e5-9505-250af2f3fc3b.png)
 kindly check it.. i passing data to my controller static only

**Comment by skunkworks** [comment]
If you're still dealing with this issue, then we need a lot more information, like a crash report with a stack trace. Thanks.
