### ISSUE TITLE
Paypal in Sandbox does not work

### ISSUE THREAD

**Issue by hash3r** [braintree/braintree_ios#207]
I can not believe that it so hard to connect Braintree SDK to app.
Documentation and examples are so inconsistent and useless.

Any way  I can not event submit proper issue because I do not have any logs or description of errors that SDK returns me.

Like this one:
![img_3229](https://cloud.githubusercontent.com/assets/1092925/12381558/e040f262-bd94-11e5-98b1-81c16fbfbbe3.PNG)

I added schemes to app and tapped on PayPal and got just "client error"... excellent!

**Comment by skunkworks** [comment]
Hi,




Sorry that you're having problems with PayPal. That error is a HTTP 4xx error in our gateway -- I've asked someone to look into it, and I'll let you know when I have more information.




We are always trying to improve our documentation. Where do you think we can improve? What are you trying to do that isn't covered by the docs?



—

**Comment by skunkworks** [comment]
Hi @hash3r,

Can you post the code you're using to initialize and present the `BTDropInViewController`?

You can also clone our git repo and run the Demo app in the project (use `Braintree.xcworkspace`), and you can compare your implementation to the one we're using [here](https://github.braintreeps.com/braintree/braintree-ios/blob/master/Demo/Features/Drop%20In/BraintreeDemoDropInViewController.m). Our Demo app currently does not have this issue.
