### ISSUE TITLE
Cannot scan my card - Terminating app due to uncaught exception 'NSRangeException', reason: '-[NSTaggedPointerString getCharacters:range:]: Range {0, 7} out of bounds; string length 6'

### ISSUE THREAD

**Issue by tringmani** [braintree/braintree_ios#210]
*** Terminating app due to uncaught exception 'NSRangeException', reason: '-[NSTaggedPointerString getCharacters:range:]: Range {0, 7} out of bounds; string length 6'
*** First throw call stack:
(0x182df1900 0x18245ff80 0x182df1848 0x182dd8e88 0x182ce3994 0x182dd9634 0x1003feb50 0x182d29a04 0x1003fe89c 0x1003ff354 0x1003ff500 0x1003d560c 0x187ae40c0 0x187ae3cc4 0x187e84930 0x187e41930 0x187e3e340 0x187d94b70 0x187da2030 0x187ad5c24 0x182da8588 0x182da632c 0x182da675c 0x182cd5680 0x1841e4088 0x187b4cd90 0x10005b270 0x1828768b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

This issue has been fixed by paypal in latest release and it looks like not updated in braintree. Can you please help me to escape from this?

Please do refer this link https://github.com/card-io/card.io-iOS-SDK/issues/125

**Comment by skunkworks** [comment]
Hi @tringmani, which version of the Braintree SDK are you using? This should not occur if you're using `3.9.4` or newer.

**Comment by tringmani** [comment]
FYI, I have updated to v4

**Comment by skunkworks** [comment]
The error you're seeing has been fixed in a newer version of card.io. If this problem persists, please open a GitHub issue in the card.io repo. Thanks.
