### ISSUE TITLE
Customize appearance of BTUICardFormView

### ISSUE THREAD

**Issue by orinmurphy** [braintree/braintree_ios#211]
Is it possible to customize the appearance of the BTUICardFormView.

Specifically, i'm looking to have a transparent background, with white text for credit card, date, cvv and postal code fields, and white backgrounds for the cardHint views.
Screenshot below of what im trying to achieve, but the cardHint and textField colors are wrong.

thanks

![cardform](https://cloud.githubusercontent.com/assets/3251360/12765881/b93426a8-c9ce-11e5-938d-ae68b8c2db9d.png)

**Comment by skunkworks** [comment]
Hey Orin, let me see what we can do.

**Comment by skunkworks** [comment]
Right now, the Drop-in doesn't support theming to this extent. We are gearing up to start overhauling Drop-in very soon, and there should be a greater level of customizability.

To achieve this look, you'll either need to roll your own UI, or you can try hacking/monkey patching the BraintreeUI source.

**Comment by orinmurphy** [comment]
@skunkworks ok cool. Thanks
