### ISSUE TITLE
ios : Integrate both BrainTree SDK and Paypal SDK in one app

### ISSUE THREAD

**Issue by ankits16** [braintree/braintree_ios#214]
I am trying to integrate both braintree and paypal native in my application. I user cocoapods to integrate braintree and manual integration for paypal, but when I compile the code I see

91 duplicate symbols for architecture x86_64
I tried integrating these library individually in different project and they are working fine if I integrate them in one project I get this error please help me out to resolve this.

Thanks Ankit

**Comment by skunkworks** [comment]
Can you post your `Podfile`? Thanks.

**Comment by ankits16** [comment]
def shared_pods
pod 'Braintree'
end

target 'Linuxdev' do
    shared_pods
end

target 'Beta' do
    shared_pods
end

target 'Staging' do
    shared_pods
end

and then I manually integrated Paypal

**Comment by demerino** [comment]
Depending on your use cases, you might want to remove the PayPal SDK (Braintree supports paypal payments). 

However, if you want to keep the PayPal SDK then you can exclude PayPal from the Braintree integration by modifying your Podfile to cherry pick the other features you want:
```
def shared_pods
   pod 'Braintree/Core'
   pod 'Braintree/Card'
   # etc...
end
```

**Comment by skunkworks** [comment]
The Braintree SDK already supports PayPal future payments, billing agreements, and checkout, so depending on what your app is trying to do, you can either remove the Braintree/PayPal subspec from your project, or you can remove the PayPal SDK.
