### ISSUE TITLE
Add PayPal Safari view controller will not load on iOS 9.2, iPhone 6+, Braintree pod 4.1.3

### ISSUE THREAD

**Issue by rsaunders100** [braintree/braintree_ios#215]
Safari view controller fails to load.
Opening in safari works
Works on other devices.

More details to follow, has anyone seen this before?

**Comment by demerino** [comment]
Just to confirm...
Have you add the `BTViewControllerPresentingDelegate` protocol to your presenting class?
You must also set the `viewPresentingDelegate` on your PayPalDriver.
```
driver.viewControllerPresentingDelegate = self;
```

Then you can add the delegate methods:
```
- (void)paymentDriver:(__unused id)driver requestsPresentationOfViewController:(UIViewController *)viewController {
    [self presentViewController:viewController animated:YES completion:nil];
}

- (void)paymentDriver:(__unused id)driver requestsDismissalOfViewController:(UIViewController *)viewController {
    [viewController dismissViewControllerAnimated:YES completion:nil];
}
```

If that doesn't work, please paste in a snippet of the code you're using to start the payment.

**Comment by rsaunders100** [comment]
Thanks for your help. It turned out to be an issue with the device. safari view controllers has the same issue on other apps. Restarting the device fixed this.

**Comment by skunkworks** [comment]
:+1:
