### ISSUE TITLE
Credit card issue activity indicator

### ISSUE THREAD

**Issue by cafuni** [braintree/braintree_ios#222]
When I pay with credit card, the activity indicator on PAY button stops loading before response....

**Comment by skunkworks** [comment]
Can you verify that your implementation of `dropInViewController:didSucceedWithTokenization:` dismisses the view controller before sending the payment method nonce to your server?

For example:

```
func dropInViewController(viewController: BTDropInViewController,
    didSucceedWithTokenization paymentMethodNonce: BTPaymentMethodNonce)
{
    dismissViewControllerAnimated(true, completion: nil)

    // Send payment method nonce to your server for processing
}
```

**Comment by cafuni** [comment]
I'm not agree with this implementation... If receive a network issue,what should I do???

**Comment by skunkworks** [comment]
Once the payment method has been tokenized, the view controller has finished and your app has received a nonce. How you handle sending the nonce is up to you.

For example, the app might display a loading indicator (HUD) and present a `UIAlertController` with a retry button if it fails.
