### ISSUE TITLE
4.2.1 prints huge logs in the Xcode debug output. PLEASE no such verbose mess!

### ISSUE THREAD

**Issue by bkrakowski** [braintree/braintree_ios#223]
Using default JSON config {
  "os": "iOS",
  "file_timestamp": "2016-01-11T16:42:00Z",
  "1.0": {
    "oauth2_recipes_in_decreasing_priority_order": [
      {
        "target": "wallet",
        "protocol": "3",
        "supported_locales": [
          "da_DK",
          "de_AT",
          "de_BE",
          "de_CH",
          "de_DE",
          "de_DK",
          "de_LU",
          "en_AE",
          "en_AR",
          "en_AT",
          "en_AU",
          "en_BE",
          "en_BG",
          "en_BH",
          "en_BR",
          "en_CA",
          "en_CH",
          "en_CN",
          "en_CZ",
          "en_DE",
          "en_DK",
          "en_DZ",
          "en_EE",
          "en_ES",
          "en_FI",
          "en_FR",
          "en_GB",
          "en_GR",
          "en_HK",
          "en_HU",
          "en_IE",
          "en_IL",
          "en_IT",
          "en_JO",
          "en_JP",
          "en_KW",
          "en_KZ",
          "en_LT",
          "en_LU",
          "en_LV",
          "en_MA",
          "en_MX",
          "en_MY",
          "en_NL",
          "en_NO",
          "en_NZ",
          "en_OM",
          "en_PH",
          "en_PL",
          "en_PT",
          "en_QA",
          "en_RO",
          "en_RU",
          "en_SA",
          "en_SE",
          "en_SG",
          "en_SI",
          "en_SK",
          "en_TN",
          "en_TR",
          "en_US",
          "en_YE",
          "es_AE",
          "es_AR",
          "es_BH",
          "es_CZ",
          "es_DZ",
          "es_EE",
          "es_ES",
          "es_FI",
          "es_GR",
          "es_HU",
          "es_JO",
          "es_KW",
          "es_KZ",
          "es_LT",
          "es_LU",
          "es_LV",
          "es_MA",
          "es_MX",
          "es_NZ",
          "es_OM",
          "es_PT",
          "es_QA",
          "es_RO",
          "es_SA",
          "es_SI",
          "es_SK",
          "es_TN",
          "es_US",
          "es_YE",
          "fr_AE",
          "fr_BE",
          "fr_BH",
          "fr_CA",
          "fr_CH",
          "fr_CZ",
          "fr_DZ",
          "fr_EE",
          "fr_FI",
          "fr_FR",
          "fr_GR",
          "fr_HU",
          "fr_JO",
          "fr_KW",
          "fr_KZ",
          "fr_LT",
          "fr_LU",
          "fr_LV",
          "fr_MA",
          "fr_NZ",
          "fr_OM",
          "fr_PT",
          "fr_QA",
          "fr_RO",
          "fr_SA",
          "fr_SI",
          "fr_SK",
          "fr_TN",
          "fr_US",
          "fr_YE",
          "it_IT",
          "iw_IL",
          "ja_JP",
          "nb_NO",
          "nl_BE",
          "nl_NL",
          "no_NO",
          "pl_PL",
          "pt_BR",
          "pt_PT",
          "ru_EE",
          "ru_LT",
          "ru_LV",
          "ru_RU",
          "se_SE",
          "sv_SE",
          "tr_TR",
          "zh_AE",
          "zh_BH",
          "zh_CN",
          "zh_CZ",
          "zh_DZ",
          "zh_EE",
          "zh_FI",
          "zh_GR",
      ....

**Comment by skunkworks** [comment]
Thanks for bringing this up. We will try to do a better job not to spam the console logs. Thankfully, this log output only occurs if the app is built as debug.

**Comment by bkrakowski** [comment]
Thanks for looking into it. After seeing the console output; i tried to switch to prev 4.1.3 version and it was crashing. 4.2.2 says that maybe has fix for it, but it is not pod available. So, kind of in a bad state here.

**Comment by burnto** [comment]
4.2.2 is now available on CocoaPods, as of 2 days ago. Thanks again for your collaboration on this.

**Comment by burnto** [comment]
Actually, I don't think 4.2.2 addressed the logging issue. Re-opening. There is a fix on the way. Thanks.

**Comment by skunkworks** [comment]
Hi, version [4.2.3](https://github.com/braintree/braintree_ios/releases/tag/4.2.3) has addressed this. Thanks!

**Comment by bkrakowski** [comment]
Lovely! thanks!
