### ISSUE TITLE
dropIn.summaryTitle 

### ISSUE THREAD

**Issue by cafuni** [braintree/braintree_ios#224]
Where is the method in the V4?

dropIn.summaryTitle = "1 Yellow T-Shirt"

**Comment by skunkworks** [comment]
This can be found in `BTPaymentRequest`. Take a look at our [demo app code](https://github.com/braintree/braintree_ios/blob/master/Demo/Features/Drop%20In/BraintreeDemoDropInViewController.m#L48) to see an example.

**Comment by cafuni** [comment]
and for Swift 2.0?
