### ISSUE TITLE
`NSLog` calls after updating Braintree 

### ISSUE THREAD

**Issue by Reflejo** [braintree/braintree_ios#226]
There are a few `NSLog` calls that are being triggered on `-DDEBUG` from Braintree after linking. 

Example: https://github.com/braintree/braintree_ios/blob/master/BraintreePayPal/PayPalOneTouch/Configuration/PPOTConfiguration.m#L438

We try to keep our console as clean as possible to avoid missing real problems while debugging, it'd be greatly appreciated if you guys can suppress those logs.

We can always compile braintree without `DEBUG` I guess but would be nice if we can keep `-DDEBUG` on every third party and still get (only) relevant logging or not logging at all, what do you guys think?

**Comment by burnto** [comment]
This is a known deficiency, and we have a fix in progress. Thanks. See also #223

**Comment by skunkworks** [comment]
Hi, version [4.2.3](https://github.com/braintree/braintree_ios/releases/tag/4.2.3) has addressed this. Thanks!
