### ISSUE TITLE
Can't pay with PayPal (Production), iOS SDK v3, Swift

### ISSUE THREAD

**Issue by polis80cy** [braintree/braintree_ios#228]
As you can see, my URL Scheme DOES start with the bundle ID and yet I keep getting an error about it:

![screen shot 2016-02-27 at 01 20 05](https://cloud.githubusercontent.com/assets/14854276/13368111/58dff068-dcf0-11e5-8fc0-01f1223adb0a.png)

Here's the same info.plist as XML:

![screen shot 2016-02-27 at 01 22 43](https://cloud.githubusercontent.com/assets/14854276/13368162/b3a6e6be-dcf0-11e5-816c-68865820139e.png)

Error received:
_PayPal SDK: URL scheme must start with PP.ChopChop 
2016-02-27 01:18:50.262 ChopChop[7650:2459945] [BraintreeSDK] INFO PayPal Touch is not available. Reason: "Can not app switch to PayPal. Verify that the return URL scheme (<#PP.ChopChop.Payments#>) starts with this app's bundle id, and that the PayPal app is installed."_

Is this a bug? What am I missing? Is it a misleading error and real cause is my merchant account being in a non supported country? In that case, how come I was eligible for PayPal payments?

Thanks.

**Comment by skunkworks** [comment]
Can you confirm that you're setting the app switch URL scheme? It should look something like this:

```
    [Braintree setReturnURLScheme:@"PP.ChopChop.Payments"];
```

This can be called anywhere before initiating app switch, but we recommend you do it in your app delegate.

**Comment by polis80cy** [comment]
Thanks for your prompt reply.

Turns out it was my bad. But I still think the documentation could do with an update. Documentation says:

BTAppSwitch.setReturnURLScheme("<#com.your-company.Your-App.payments#>")

This actually implies that I should use the "<#" symbols. This was to blame, apologies! :)

**Comment by skunkworks** [comment]
Oops, yes, the `<#some_string#>` notation when copy-pasted into Xcode are transformed into code placeholders. Perhaps it's more of an inconvenience than we thought to have this in our docs! Thanks for understanding though.
