### ISSUE TITLE
Braintree Compile Errors

### ISSUE THREAD

**Issue by bngoofy** [braintree/braintree_ios#230]
I updated my Xcode to 7.2.1 and did a pod install which delivered 3.9.2 I get the following error

@implementation BTAPIResponseParser
Method override for the designated initializer of the superclass '-init' not found

I saw this was referenced in a post that closed in September but didn't see any real resolution other then try 3.9.3.

I am new to pods and have no idea how to get 3.9.3 to install via the terminal commands

Any help would be appreciated

**Comment by skunkworks** [comment]
Hi @bngoofy, you can update to 3.9.3 (or to 3.9.7, which is the latest v3 release) by specifying a version in your `Podfile`:

```
pod 'Braintree', '3.9.7'
```

then run `pod install`.

Optionally, you can specify an optimistic version:

```
pod 'Braintree', '~> 3.9.7'
```

then run `pod update Braintree`.

Let me know if that fixes your issues!

**Comment by bngoofy** [comment]
Thanks I currently have is nodded to

`pod 'Braintree', '~> 3.9'`

with the thought it would be get the latest

**Comment by bngoofy** [comment]
The Update worked thanks!!

**Comment by skunkworks** [comment]
:+1: :rocket:

**Comment by bngoofy** [comment]
can you define "optimistic version"?

**Comment by skunkworks** [comment]
[CocoaPods documentation](https://guides.cocoapods.org/using/the-podfile.html) describes it, but in a nutshell, I think of it like the last number is a wildcard, i.e. `~> 3.9` means "Get me the latest version that matches 3.*", `~> 3.9.7` means "Get me the latest version that matches 3.9.*", etc.

**Comment by bngoofy** [comment]
so if I had done`pod 'Braintree', '~> 3.9.3'` it would have installed 3.9.7?

**Comment by skunkworks** [comment]
Correct, but only if you did `pod update` or `pod update Braintree`. If you just did `pod install`, it won't update.

**Comment by bngoofy** [comment]
Thanks!!
