### ISSUE TITLE
-canOpenURL: failed for URL: "com.venmo.touch.v2://x-callback-url/vzero/auth" - error: "(null)"

### ISSUE THREAD

**Issue by pvenkatakrishnan** [braintree/braintree_ios#231]
Hey,
I just want to tryout the 'Pay with Paypal' option. Running the Demo out-of-the-box I keep running into the above error(i am using Paypal Sandbox Login). I am not trying to test venmo, so a little unclear what i need to do.
It seems like the deep linked url for BT/Paypal payments are already setup on the demo.

**Comment by skunkworks** [comment]
Hi @pvenkatakrishnan, these messages are a bit of chatter from the OS when we check to see whether Venmo is installed on the device/simulator. They are harmless. Let me know if you have any other questions!

**Comment by baisani** [comment]
I got this Error Domain=com.braintreepayments.BTVenmoAppSwitchReturnURLErrorDomain Code=-1004 "Unexpected error, please retry later." UserInfo=0x171279000 {NSLocalizedDescription=Unexpected error, please retry later.} when i authorize the venmo app. How can i fix this issue. This problem happened in ios.

**Comment by ajeetcody** [comment]
I am also getting same issue in my iOS app when I am integrating Venmo in Braintree payment. Please give some solution of this.

**Comment by hoschkara** [comment]
I know it's harmless, but I agree that this is actually super annoying. It's not a warning relevant to the sdk user, so it should be avoided to prevent unnecessary noise.

**Comment by sestevens** [comment]
@hoschkara As mentioned above, this log comes from the OS, not the Braintree SDK. To the best of my knowledge, there's no way for the SDK to suppress this log.

**Comment by hoschkara** [comment]
Thanks for the response. Yes the warnings is from iOS, but the question would be why does the sdk needs to try to open a venmo url scheme if a PayPal billing agreement is requested on a PayPal driver object?

**Comment by sestevens** [comment]
It's being checked for analytics purposes.

**Comment by sestevens** [comment]
Hi @hoschkara, we just released a [beta version](https://github.com/braintree/braintree_ios/releases/tag/5.0.0-beta1) of the SDK with the fix I mentioned above. I'll leave this issue open until these changes are in GA.

Resources:
- [SPM integration instructions](https://github.com/braintree/braintree_ios/tree/5.0.0-beta1#swift-package-manager-v5-beta)
- [Version 5 migration guide](https://github.com/braintree/braintree_ios/blob/5.0.0-beta1/V5_MIGRATION.md)

**Comment by hoschkara** [comment]
Thanks a lot!

**Comment by sestevens** [comment]
This has been fixed in [version 5.0.0](https://github.com/braintree/braintree_ios/releases/tag/5.0.0). Please see our [migration guide](https://github.com/braintree/braintree_ios/blob/5.0.0/V5_MIGRATION.md) for steps to upgrade your integration.
