### ISSUE TITLE
Pod Loading in Apple Git

### ISSUE THREAD

**Issue by bngoofy** [braintree/braintree_ios#232]
We have an apple git server OSX10.10.5 and each time that we push a new version and it's pulled down by another developer, the braintree pods need to be reloaded. So we have to go through terminal and reload them. Is there any way around this?

**Comment by danoli3** [comment]
No this is standard? Just write a command script to make this process easy as double click go:

I.E.
```
#!/bin/sh

scriptdirectory=$(dirname $0)
cd $scriptdirectory
pwd
pod setup
echo "Pods Setup. "
pod install
echo "Pods Installed. "
pod update
echo "Pods Updated. "
```
Save as PodsInstall.command for example with 755 chmod.

**Comment by skunkworks** [comment]
This is more of a CocoaPods issue than a Braintree-specific one. There's lots of opinions about whether the `Pods` folder should be checked into source control, and based on your issue, it seems like you are not checking them in but are checking in the `Podfile.lock` file. The [CocoaPods guides](https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control) talks about this.
