### ISSUE TITLE
bundle: No such file or directory

### ISSUE THREAD

**Issue by GuillemetS** [braintree/braintree_ios#235]
Hi 

I'm using Braintree v3.9.7 with CocoaPods.
When I update from CocoaPods v0.39  to  v1.0.0 beta6.
Then the build fails with the following errors:
```
error: /Users/[USER_NAME]/Library/Developer/Xcode/DerivedData/[PROJECT]-bpfpjouguirywefwutwdjwuvhyns/Build/Products/Debug-iphonesimulator/Braintree/Braintree-UI-Localization.bundle: No such file or directory
error: /Users/[USER_NAME]/Library/Developer/Xcode/DerivedData/[PROJECT]-bpfpjouguirywefwutwdjwuvhyns/Build/Products/Debug-iphonesimulator/Braintree/Braintree-Drop-In-Localization.bundle: No such file or directory
```

other people have a same problems 
http://stackoverflow.com/questions/36317741/errors-while-implementing-braintree-sdk-in-ios-app-swift-2-2-xcode-7-3

Are you supporting CocoaPods 1.x? If not, when do you plan to support it?

Thank you

**Comment by skunkworks** [comment]
Hi @GuillemetS, I'll take a look at this today.

**Comment by skunkworks** [comment]
@GuillemetS, I think this is an issue with CocoaPods 1.0.0 beta 6, based on [this issue](https://github.com/CocoaPods/CocoaPods/issues/5034). I was able to work around this issue by reverting to 1.0.0 beta 5. Can you let me know if that fixes the issue?

**Comment by robski05** [comment]
I had the same issue - going back to beta 5 solves the issue.

**Comment by GuillemetS** [comment]
My team and I have decided to wait for CocoaPods 1.0.0 release but thanks for your answers.
