### ISSUE TITLE
Clear history

### ISSUE THREAD

**Issue by JSONValidator** [braintree/braintree_ios#236]
I want that after every payment user have to login and history (payment method) was removed. Is it possible?
![1puywuvumye](https://cloud.githubusercontent.com/assets/5711059/14527661/1d85a33a-0254-11e6-8bc0-4c75e0091d95.jpg)

**Comment by skunkworks** [comment]
Hi, if you're using v4 of the SDK, an easy way to do this would be to use a [tokenization key](https://developers.braintreepayments.com/guides/authorization/tokenization-key/ios/v4) as authorization.

**Comment by skunkworks** [comment]
One more way to do this would be to authorize Braintree with a client token that does *not* specify a customer ID. Let us know if you have any follow-up questions.
