### ISSUE TITLE
Payment Button only works upon long press

### ISSUE THREAD

**Issue by Chris-Sipe** [braintree/braintree_ios#240]
I'm using Braintree 4.2.3 in Swift. I wanted to embed my Drop-in View controller into a scroll view for a nice flow, and it all works fine, except the payment button only gets activated when I do a really long (about 2 seconds) press. The button darkens at a normal time (almost instantly after I press down) but when I lift the touch, nothing happens. This bug doesn't happen when I use the default modal-VC pop up, but it does when I add it inside a UIView in a scrollView.

**Comment by skunkworks** [comment]
Hi Chris,

The Drop-in view controller only supports full-screen modal presentation (`presentViewController:animated:`) or presentation in a navigation view controller.

It's hard to debug these sorts of issues without an example project, so if you can provide one, that'd be helpful. If it's taking two seconds to detect a gesture, my first suspicion might be that some piece of code somewhere -- either in the Drop-in view controller or in the Drop-in delegate callbacks -- is doing some UI work not on the main thread.
