### ISSUE TITLE
 "_OBJC_CLASS_$_BTApplePayClient", referenced from:

### ISSUE THREAD

**Issue by choiway** [braintree/braintree_ios#242]
I'm getting this issue whenever I try to instantiate a BTApplePayClient: 

    let applePayClient = BTApplePayClient(APIClient: braintreeClient!)

I get the following error whenever I try to compile:

> Undefined symbols for architecture arm64:
>   "_OBJC_CLASS_$_BTApplePayClient", referenced from:
>       type metadata accessor for __ObjC.BTApplePayClient in AddCreditViewController.o
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by skunkworks** [comment]
Looks like the `BTApplePayClient` isn't being linked to by your app. How are you integrating the Braintree SDK (CocoaPods | Carthage | Manual | Static Library)? My first instinct would be to verify under `Project > Build Phases > Link Binary With Libraries` that Braintree is there. If you're using CocoaPods with `use_frameworks!`, check that the `Pods<something>.framework` is linked, otherwise you'll be looking for a `.a` file.

**Comment by choiway** [comment]
@skunkworks thanks for the response!

How are you integrating the Braintree SDK (CocoaPods | Carthage | Manual | Static Library)?

I'm using CocoaPods. I am using it with use_frameworks! and Link Binary With Libraries does include Pods<>.framework. Should I add the Braintree framework as well?

**Comment by skunkworks** [comment]
@choiway Can you confirm that your `Podfile` contains `pod 'Braintree/Apple-Pay'`?

**Comment by choiway** [comment]
@skunkworks Yes it does include 'Braintree/Apple-Pay'. I ran pod install three times just to see if I was missing something.

**Comment by skunkworks** [comment]
Can you confirm that your Pods project looks like the following?

<img width="257" alt="screen shot 2016-05-26 at 2 28 13 pm" src="https://cloud.githubusercontent.com/assets/563375/15590769/2a90cb66-234e-11e6-8ede-9a61e3399900.png">

If not, you may want to try manually deleting the `Pods/Braintree` folder and re-running `pod install`.

**Comment by choiway** [comment]
Yeah...Apple-Pay is in the pods project. I was hoping I was missing something and it was a quick fix. I'm going to dig around a bit and report back. 

![screen shot 2016-05-26 at 2 54 49 pm](https://cloud.githubusercontent.com/assets/546436/15592219/d493acb6-2356-11e6-8fd4-f86c0cdb9595.png)

**Comment by skunkworks** [comment]
Hmm strange, feel free to send me a copy of your project if you can and I can help debug.

**Comment by cyuket** [comment]
I am facing this issue currently while I am building a better version please any fix?

**Comment by scannillo** [comment]
Hi @cyuket - can you provide us with SDK version information, XCode & iOS version information, as well as steps to replicate?
