### ISSUE TITLE
version : 3.9.3 #import <PayPalMobile.h> file not found

### ISSUE THREAD

**Issue by jason469618528** [braintree/braintree_ios#245]

**Comment by skunkworks** [comment]
Hi, can you give us some more detail on how you are integrating the SDK? Are you using CocoaPods?

**Comment by jason469618528** [comment]
Yes,Cocoapods

**Comment by skunkworks** [comment]
This might be a CocoaPods integration issue. Can you verify that your Xcode project has `$(inherited)` under `Project` ->`Build Settings` -> `Header Search Paths`?

**Comment by jason469618528** [comment]
![image](https://cloud.githubusercontent.com/assets/4940053/15699209/e9feb400-27fd-11e6-946a-cf01556bdb96.png)

**Comment by jason469618528** [comment]
"Always Serch User Paths" is Yes?

**Comment by jason469618528** [comment]
![image](https://cloud.githubusercontent.com/assets/4940053/15699318/a17c455c-27fe-11e6-957b-df112cf5d6ef.png)

**Comment by skunkworks** [comment]
Can you verify that `$(inherited)` is also under `Library Search Paths`?

**Comment by jason469618528** [comment]
![image](https://cloud.githubusercontent.com/assets/4940053/15699359/e3b7ecb4-27fe-11e6-9d06-2674251c49df.png)

**Comment by skunkworks** [comment]
Does `Build Phases` -> `Link Binaries With Libraries` contain the `libPods-<something>.a` static library file?

It really just looks like the Xcode project is horribly out of sync with CocoaPods. If you continue to have issues, you may have to resort to blowing away your `Pods/` folder and/or de-integrating CocoaPods from your project and doing a fresh `pod install`. CocoaPods 1.0 has a `pod deintegrate` command that may be useful.

**Comment by skunkworks** [comment]
If Xcode *still* can't link to Braintree, please contact our [support team](mailto:support@braintreepayments.com), they can assist further.

**Comment by jason469618528** [comment]
![image](https://cloud.githubusercontent.com/assets/4940053/15699893/269df470-2803-11e6-82d8-63204af21c4a.png)
what's this?

**Comment by jason469618528** [comment]
reference [Braintree setReturnURLScheme:xxx] error

**Comment by skunkworks** [comment]
Your app can't resolve any of the Braintree SDK symbols (e.g. `Braintree`, `BTData`) due to a CocoaPods integration/configuration issue. You can try verifying that `Other Linker Flags` also lists `$(inherited)` ([source](http://stackoverflow.com/questions/27286226/undefined-symbols-for-architecture-armv7-for-cocoapods-libraries)).

**Comment by jason469618528** [comment]
Yeah,Now is PayPalMobile.h> file not found

**Comment by jason469618528** [comment]
$(inherited) All Add! run Also no problem

**Comment by jason469618528** [comment]
![image](https://cloud.githubusercontent.com/assets/4940053/15701834/23814772-280f-11e6-8cab-431804139ec0.png)

**Comment by jason469618528** [comment]
Is OK! thanks!

**Comment by skunkworks** [comment]
I'm glad you fixed it! 🚀
