### ISSUE TITLE
requestBillingAgreement takes seconds to call requestsPresentationOfViewController

### ISSUE THREAD

**Issue by everhardt** [braintree/braintree_ios#246]
Calling requestBillingAgreement is very slow: it takes multiple seconds before the SFSafariViewController is ready and requestsPresentationOfViewController is called. Is there anything I can do to speed this up?

As a mitigating measure, I thought to add a loader viewController on top of the viewController before calling requestBillingAgreement. That way, the user cannot press any other buttons. That loader would then be hidden at requestsPresentationOfViewController and the right methods of BTAppSwitchDelegate. This doesn't work either, as the braintree pod is referring to "self" in the construction of the SFSafariViewController, which results in a blank screen if I hide the loader ViewController in requestsPresentationOfViewController. Is there anything I can do to still show a loader view?

**Comment by skunkworks** [comment]
Hi @everhardt, it shouldn't take that long to initiate a billing agreement request. I have a few questions:

* Is this in production?
* Which version of the Braintree iOS SDK are you using?
* Does this happen consistently?

**Comment by everhardt** [comment]
- Sandbox
- 4.3.1
- Yes, tried it today at two different locations (both in Amsterdam)

**Comment by skunkworks** [comment]
Interesting -- [I tried this out with our Demo app](https://gfycat.com/HighlevelZigzagGannet), and it doesn't seem to have too much delay. 

Can you try cloning the `braintree_ios` repo to run the Demo app? You must first run `pod install`, then open `Braintree.xcworkspace`, and select the `Demo` app target.

**Comment by everhardt** [comment]
That is indeed faster, say 1 sec instead of 2 to 3. Not sure what causes it though: our app is doing nothing special at that time. Would, alternatively, a loader view be possible?

**Comment by skunkworks** [comment]
Can you post a code snippet from where you request the billing agreement and also what you're doing to present the Safari view controller?

Alternatively, yes, you can display a loader and then dismiss it in the delegate callbacks when the `BTPayPalDriver` is about to app switch or present a view controller.

**Comment by everhardt** [comment]
In `viewDidLoad`:

```
#!Swift
      if let path = NSBundle.mainBundle().pathForResource("Info", ofType: "plist"), dict = NSDictionary(contentsOfFile: path) as? [String: AnyObject], let key = dict["braintree_key"]?[keyType] as? String {
            braintreeClient = BTAPIClient(authorization: key)
        }
```

In the function called after pressing the custom button:
```
#!Swift
func customPayPalButtonTapped() {
  if let btC = braintreeClient {
      let payPalDriver = BTPayPalDriver(APIClient: btC)
      payPalDriver.viewControllerPresentingDelegate = self
      payPalDriver.appSwitchDelegate = self
      
      let request = BTPayPalRequest()
      request.billingAgreementDescription = "[XXX]"
      payPalDriver.requestBillingAgreement(request) { (tokenizedPayPalAccount, error) -> Void in
          //Stuff to do at time of callback
      }
  }
} 
```

And then the regular for `BTViewControllerPresentingDelegate` and `BTAppSwitchDelegate`:
```
#!Swift
    func paymentDriver(driver: AnyObject, requestsPresentationOfViewController viewController: UIViewController) {
        presentViewController(viewController, animated: true, completion: nil)
    }
    
    func paymentDriver(driver: AnyObject, requestsDismissalOfViewController viewController: UIViewController) {
        dismissViewControllerAnimated(true, completion: nil)
    }
    
    // MARK: - BTAppSwitchDelegate
    
    // Optional - display and hide loading indicator UI
    // Will only work without SFSafariViewController, see https://github.com/braintree/braintree_ios/issues/188
    func appSwitcherWillPerformAppSwitch(appSwitcher: AnyObject) {
        showLoadingUI()
        
        NSNotificationCenter
            .defaultCenter()
            .addObserver(self, selector: #selector(PaymentMethodFormViewController.hideLoadingUI), name: UIApplicationDidBecomeActiveNotification, object: nil)
    }
    
    func appSwitcher(appSwitcher: AnyObject, didPerformSwitchToTarget target: BTAppSwitchTarget) {
        hideLoadingUI()
    }
    
    func appSwitcherWillProcessPaymentInfo(appSwitcher: AnyObject) {
        hideLoadingUI()
    }
    
    // MARK: - Private methods
    
    func showLoadingUI() {
        //show alert that paypal payment is loading based on nonce
    }
    
    func hideLoadingUI() {
        //hide alert that paypal payment is loading based on nonce
    }
```

If I do show a loader before calling `customPayPalButtonTapped`, and assume I should hide it first thing in `requestsPresentationOfViewController`? That doesn't work though: the SFSafariViewController does pop up, but remains completely blank (not even the navigation bar on top).

ps. Thanks for all the quick replies, much appreciated!

**Comment by skunkworks** [comment]
Your code looks solid, so we're a bit puzzled. To dive into implementation details, there are some expensive things that happen when you request a billing agreement:

1. The configuration for your Braintree merchant account is fetched (e.g. to make sure that PayPal is enabled). This may or may not be cached already, so it can cause a network request to be made.
2. Another network call is made to create a payment resource for your billing agreement.

One thing you can do to optimize performance is to pre-fetch your merchant account configuration, which will "warm" the cache so that when your user taps the PayPal button, it can make one less network call:

```
if let path = NSBundle.mainBundle().pathForResource("Info", ofType: "plist"), dict = NSDictionary(contentsOfFile: path) as? [String: AnyObject], let key = dict["braintree_key"]?[keyType] as? String {
    braintreeClient = BTAPIClient(authorization: key)
    braintreeClient.fetchOrReturnRemoteConfiguration() { _ -> Void in }
}
```

Once the configuration has been fetched once for your app, it should be cached up until your app is terminated, so all other Braintree-related things that require a configuration call (which is almost everything) should be snappier.

However, ultimately, I think your instinct to display a loader is correct, since there will always be a network call that's required before you can present the Safari view controller or perform an app switch.

Let me know if the cache warming speeds things up for you, this is very good feedback for us 👍

**Comment by everhardt** [comment]
That didn't make a noticeable difference. I did notice though, that (with the `fetchOrReturnRemoteConfiguration`-trick in place) the second time the SFSafariViewController is opened, it is quite a bit faster than the first time. First time: 4-6 seconds, second time: 2 seconds.

So I'll go for the loader. On that note, how can I realise that without the `SFSafariViewController` turning up blank (see my last post above)?

**Comment by demerino** [comment]
Hi @everhardt - I wanted to follow up with your issue. I do think the loader is a good idea if you're seeing consistent delays.

Regarding the loader, you'll want to display the loader at the top of your `customPayPalButtonTapped` function. The delay is most likely in the networking calls when creating the billing agreement - not during presentation (you likely have no issues presenting other view controllers). You'll then want to hide your loader in the `requestsPresentationOfViewController` delegate function (SFSafariViewController) and  `appSwitcherWillPerformAppSwitch` (app switching to Safari or PayPal app).

Ex:

```
func customPayPalButtonTapped() {
  if let btC = braintreeClient {
     showLoadingUI()
     // create and request billing agreement...
  }
} 
```

```
  func paymentDriver(driver: AnyObject, requestsPresentationOfViewController viewController: UIViewController) {
        hideLoadingUI()
        presentViewController(viewController, animated: true, completion: nil)
    }
```

```
    func appSwitcherWillPerformAppSwitch(appSwitcher: AnyObject) {
        hideLoadingUI()
    }
```

**Comment by Gautam117** [comment]
@demerino Hi, this is not working in iOS 13. I integrated the same but when requesting payment method the delegates of payment driver is not calling.
Is there any help will be appreciated.

**Comment by scannillo** [comment]
Hi @Gautam117. The callback on the [`requestBillingAgreement` method](https://github.com/braintree/braintree_ios/blob/1a6d73a4b70b35f13903f88ec4de08e339129bdd/BraintreePayPal/Public/BTPayPalDriver.h#L224-L228) is properly being called in our Demo app within this repo, on iOS 13.

Contact [Braintree Support](https://help.braintreepayments.com/) to help troubleshoot your integration.

**Comment by demerino** [comment]
Apologies, this solution is quite old. For consistent behavior across all iOS versions, you'll want to use the `context` callbacks: https://github.braintreeps.com/team-sdk/braintree-ios/blob/master/BraintreeCore/Public/BTAppSwitch.h#L174-L189

`appContextWillSwitch` and `appContextDidReturn`.
