### ISSUE TITLE
Why postal code is not validated ?

### ISSUE THREAD

**Issue by namanhams** [braintree/braintree_ios#247]
I wonder why front-end validates every form field except postal code, but Braintree backend does validates postal code.

**Comment by demerino** [comment]
Unlike the card number (luhn validation), expiration (date can't be in the past) - real time validation of the postal code is ambiguous. At the moment - the only requirement for a `valid` postal code is that it is `length >= 1`. Not validating the postal code on the client also reduces the risk of carding abuse - meaning the client won't verify that a postal code is associated with a card. 

If you still have questions or suggestions on how we might improve this - feel free to open another issue.
