### ISSUE TITLE
Sandbox is not enabled with sandbox client token

### ISSUE THREAD

**Issue by diomidispapas** [braintree/braintree_ios#248]
Setup:
Braintree SDK 3.9.3 that uses the 2.11.4-bt1 PayPal SDK

The application is presenting the `BTPayPalViewController` in order to retrieve the PayPal payment method `BTPayPalPaymentMethod`.

As far as I can understand the environment is automatically configured depending on the client token that we receive from our backend. 

We initialize a Braintree instance using the `Braintree braintreeWithClientToken:` selector and we are presenting the `BTPayPalViewController` after the initialization of the braintree instance. 

The flow completes successfully using the Mock client token provided in the documentation and the following delegate method is invoked 
`- (void)payPalViewController:(BTPayPalViewController *)viewController didCreatePayPalPaymentMethod:(BTPayPalPaymentMethod *)payPalPaymentMethod`

![screen shot 2016-06-17 at 11 23 52 am](https://cloud.githubusercontent.com/assets/2880248/16147894/00d5c448-347e-11e6-8831-9be5d2a454a5.png)

but when we are using the Sandbox client token that we receive from our backend the environment is still set to Mock by the SDK and as a result we receive the following error from the delegate method:
`- (void)payPalViewController:(BTPayPalViewController *)viewController didFailWithError:(NSError *)error
`

Error:
```
Error Domain=BTBraintreeAPIErrorDomain Code=0 "(null)" UserInfo={NSUnderlyingError=0x7ffe427f8110 {Error Domain=BTBraintreeAPIErrorDomain Code=2 "Error communicating with PayPal" UserInfo={error=<CFBasicHash 0x7ffe44dabd20 [0x107e5ea40]>{type = immutable dict, count = 1,
entries =>
	0 : message = <CFString 0x7ffe42276d30 [0x107e5ea40]>{contents = "Error communicating with PayPal"}
}
, fieldErrors=(
), NSLocalizedDescription=Error communicating with PayPal}}}
```

**Comment by demerino** [comment]
Hi diomidispapas,

Can you share a sandbox client token that you're using from your server? We can use that to debug your issue. I'll also suggest that you look into using the newest version of the Braintree iOS SDK (4.3.2) if possible.

**Comment by diomidispapas** [comment]
Hello @demerino,
I am sharing a sample Sandbox client token below:
`eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0aW9uRmluZ2VycHJpbnQiOiI3NTE3ZTEwYTVkMWEyNWZhZTRhZDQ0ZWQ5YWJjNjdmODk0ZDNlYWQ3NzhkMjEwZmFjYmZlN2FhMjBjMTM4YzdmfGNyZWF0ZWRfYXQ9MjAxNi0wNi0xOVQxMDoyODo1My44ODMwNjkyODgrMDAwMFx1MDAyNm1lcmNoYW50X2FjY291bnRfaWQ9aGFpbG9DYWIyXHUwMDI2bWVyY2hhbnRfaWQ9emQzcmRkdnh2Y213cTVxc1x1MDAyNnB1YmxpY19rZXk9cDN3Y242M3poOTIyaHhjNCIsImNvbmZpZ1VybCI6Imh0dHBzOi8vYXBpLnNhbmRib3guYnJhaW50cmVlZ2F0ZXdheS5jb206NDQzL21lcmNoYW50cy96ZDNyZGR2eHZjbXdxNXFzL2NsaWVudF9hcGkvdjEvY29uZmlndXJhdGlvbiIsImNoYWxsZW5nZXMiOlsiY3Z2Il0sImVudmlyb25tZW50Ijoic2FuZGJveCIsImNsaWVudEFwaVVybCI6Imh0dHBzOi8vYXBpLnNhbmRib3guYnJhaW50cmVlZ2F0ZXdheS5jb206NDQzL21lcmNoYW50cy96ZDNyZGR2eHZjbXdxNXFzL2NsaWVudF9hcGkiLCJhc3NldHNVcmwiOiJodHRwczovL2Fzc2V0cy5icmFpbnRyZWVnYXRld2F5LmNvbSIsImF1dGhVcmwiOiJodHRwczovL2F1dGgudmVubW8uc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbSIsImFuYWx5dGljcyI6eyJ1cmwiOiJodHRwczovL2NsaWVudC1hbmFseXRpY3Muc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbS96ZDNyZGR2eHZjbXdxNXFzIn0sInRocmVlRFNlY3VyZUVuYWJsZWQiOnRydWUsInBheXBhbEVuYWJsZWQiOnRydWUsInBheXBhbCI6eyJkaXNwbGF5TmFtZSI6IkhhaWxvIiwiY2xpZW50SWQiOiJBWVVhUlVjRjF1Smlhb3Fqb195YnRIbmFKcnJpTVhteU51dTZZb1IwYkJCTGFSR3ZEeVF2MXJKZENEdW5JSkRiRENaN0N2NFZSaFdTRnl0bCIsInByaXZhY3lVcmwiOiJodHRwOi8vZXhhbXBsZS5jb20vcHAiLCJ1c2VyQWdyZWVtZW50VXJsIjoiaHR0cDovL2V4YW1wbGUuY29tL3RvcyIsImJhc2VVcmwiOiJodHRwczovL2Fzc2V0cy5icmFpbnRyZWVnYXRld2F5LmNvbSIsImFzc2V0c1VybCI6Imh0dHBzOi8vY2hlY2tvdXQucGF5cGFsLmNvbSIsImRpcmVjdEJhc2VVcmwiOm51bGwsImFsbG93SHR0cCI6dHJ1ZSwiZW52aXJvbm1lbnROb05ldHdvcmsiOmZhbHNlLCJlbnZpcm9ubWVudCI6Im9mZmxpbmUiLCJ1bnZldHRlZE1lcmNoYW50IjpmYWxzZSwiYnJhaW50cmVlQ2xpZW50SWQiOiJtYXN0ZXJjbGllbnQzIiwiYmlsbGluZ0FncmVlbWVudHNFbmFibGVkIjp0cnVlLCJtZXJjaGFudEFjY291bnRJZCI6IkhhaWxvQ2FiMiIsImN1cnJlbmN5SXNvQ29kZSI6IlVTRCJ9LCJjb2luYmFzZUVuYWJsZWQiOmZhbHNlLCJtZXJjaGFudElkIjoiemQzcmRkdnh2Y213cTVxcyIsInZlbm1vIjoib2ZmIiwiYXBwbGVQYXkiOnsic3RhdHVzIjoibW9jayIsImNvdW50cnlDb2RlIjoiVVMiLCJjdXJyZW5jeUNvZGUiOiJVU0QiLCJtZXJjaGFudElkZW50aWZpZXIiOiJtZXJjaGFudC5jb20uaGFpbG9jYWIuY3VzdG9tZXJzdGFnZSIsInN1cHBvcnRlZE5ldHdvcmtzIjpbInZpc2EiLCJtYXN0ZXJjYXJkIiwiYW1leCJdfSwibWVyY2hhbnRBY2NvdW50SWQiOiJoYWlsb0NhYjIifQ==`

Currently we are unable to to update to the fourth version of your SDK due to some technical issues. So it would be good if we found a solution using the 3.9 version of your SDK.

**Comment by diomidispapas** [comment]
@demerino Do we have any news about this issue ? Thank you in advance

**Comment by demerino** [comment]
We're doing a bit more research. In sandbox, the mode is supposed to be `Mock`. I'll take a look with this client token right now.

Are there any technical issues we can address in the 4.x version of the SDK? We're making an effort to understand what technical issues are out there that we aren't aware of.

**Comment by demerino** [comment]
Following up: We haven't identified anything specific - but it appears your configuration has `billingAgreements` set to `true` which might be an issue. Billing Agreements are not supported in `3.x`. Are you still experiencing this issue? It sounds like it might be more of a misconfiguration in the Braintree Control Panel? Also, try updating to `3.9.7` if you can't update to `4.x`.

**Comment by diomidispapas** [comment]
@demerino We have migrated into the `4.x` version of the iOS SDK as advised. We haven't faced this issue there.

**Comment by demerino** [comment]
Great! Closing this issue. Feel free to let us know if you have any other issues/questions.
