### ISSUE TITLE
ld: library not found for -lPPRiskComponent

### ISSUE THREAD

**Issue by gopalakrishnanvarun** [braintree/braintree_ios#249]
I am using Brain Tree latest SDK for our company Project.

Our team is working on SVN and we all have the latest SDK from Braintree downloaded on GitHub.

https://github.com/braintree/braintree_ios/blob/master/Docs/Manual%20Integration.md

Out of 3 members me and other guy getting a strange error which I have attached in the screenshot.

My Development Environment: 

Mac OS X El Captain
Xcode 7.3

Please advice.

**Comment by gopalakrishnanvarun** [comment]
![error](https://cloud.githubusercontent.com/assets/13256554/16169601/5314d468-3552-11e6-93c2-2a39e32c7ef9.png)

Screenshot attached

**Comment by skunkworks** [comment]
The PayPal Risk/Fraud library doesn't seem to be linked. How are you integrating the Braintree SDK?

**Comment by demerino** [comment]
It appears that the guide you are looking at is out of date, we'll look into updating it. For now, I suggest taking a look at our static library integration guide: https://github.com/braintree/braintree_ios/blob/master/Docs/Braintree-Static-Integration-Guide.md

We also support Carthage and Cocoapods which might be easier for you.
