### ISSUE TITLE
PayPal web site is always in German by default, no matter which locale code I set for BTPayPalRequest

### ISSUE THREAD

**Issue by nikolaykasyanov** [braintree/braintree_ios#250]
Application language doesn't seem to be affecting the web site language too.

I guess PayPal determines language by IP?

**Comment by skunkworks** [comment]
@nikolaykasyanov, it seems that the PayPal website uses the IP location to determine language. Let me follow up with the PayPal team to see if there's a way to override this behavior.

**Comment by skunkworks** [comment]
@nikolaykasyanov, here's what the PayPal team mentioned:

> If the user has used the device to log into PP, then the user’s lang preference is used as the default locale for subsequent attempts

That may not answer your original question exactly, but you are correct that the locale in the `BTPayPalRequest` will not be used for the website language. I think you can assume that your users will see the right language based on their IP location.

**Comment by nikolaykasyanov** [comment]
@skunkworks: thanks for the update
