### ISSUE TITLE
Hungarian language support

### ISSUE THREAD

**Issue by balazsgerlei** [braintree/braintree_ios#252]
Hi!
We are planning to use the Braintree SDK in an app with Hungarian language support and we wondered if it is possible to add Hungarian language to the UI of the Braintree SDK as well. We are willing to translate it ourselves via Pull request, I just wanted to ask it first.

Thank you in advance!

**Comment by lkorth** [comment]
Noted along with the [Android issue](https://github.com/braintree/braintree_android/issues/111)
