### ISSUE TITLE
Unable to test apple pay in simulator using DropIn-UI v4.4.1

### ISSUE THREAD

**Issue by gauravds** [braintree/braintree_ios#253]
I'm not able to see apple pay option in iPhone 6 simulator using dropin-ui as shown in [screenshots](https://github.com/braintree/braintree_ios/blob/master/Docs/no-payment-methods.png). 
```objectivc-c
- (void)usingDropIn {
    BTDropInRequest *request = [[BTDropInRequest alloc] init];
    //    request.displayCardTypes = @[@(BTUIKPaymentOptionTypeVisa), @(BTUIKPaymentOptionTypeMasterCard), @(BTUIKPaymentOptionTypeApplePay)];
    
    [request setShowApplePayPaymentOption:[PKPaymentAuthorizationViewController canMakePaymentsUsingNetworks:@[PKPaymentNetworkVisa, PKPaymentNetworkMasterCard, PKPaymentNetworkAmex]]];
    
    self.dropInController = [[BTDropInController alloc] initWithAuthorization:punchhBraintreePayment.clientToken
                                                                      request:request
                                                                      handler:^(BTDropInController * _Nonnull controller, BTDropInResult * _Nullable result, NSError * _Nullable    error) {
                                                                          
                                                                          if (error != nil) {
                                                                              NSLog(@"ERROR : %@", error.localizedDescription);
                                                                          } else if (result.cancelled == true) {
                                                                              NSLog(@"Cancelled");
                                                                          } else if (result) {
                                                                              NSLog(@"%@", result);
                                                                          }
                                                                          [self dismissViewControllerAnimated:controller completion:nil];
                                                                          
                                                                      }];
    [self presentViewController:self.dropInController animated:YES completion:nil];
}
```

Where passkit tokenization works fine for us
```objective-c
- (void)paymentAuthorizationViewController:(PKPaymentAuthorizationViewController *)controller
                       didAuthorizePayment:(PKPayment *)payment
                                completion:(void (^)(PKPaymentAuthorizationStatus))completion {
    BTApplePayClient *applePayClient = [[BTApplePayClient alloc]
                                        initWithAPIClient:punchhBraintreePayment.braintree];
    [applePayClient tokenizeApplePayPayment:payment
                                 completion:^(BTApplePayCardNonce *tokenizedApplePayPayment,
                                              NSError *error) {
}];
}
```
How can we test dropin-ui with apple pay option?

**Comment by demerino** [comment]
Make sure that Apple Pay is enabled in the Braintree `Control Panel`. That is still required.

You should also make sure that 
```
[PKPaymentAuthorizationViewController canMakePaymentsUsingNetworks:@[PKPaymentNetworkVisa, PKPaymentNetworkMasterCard, PKPaymentNetworkAmex]]
```
returns `true`

Let me know if that helps.

**Comment by gauravds** [comment]
Please send the link where to enable apple pay in dashboard. It would great help.

**Comment by bluk** [comment]
In the [Control Panel](https://sandbox.braintreegateway.com/login), you can hover over `Settings` (in the top menu) then select `Processing` in the menu drop down. There is an `Accept Apple Pay` section which you can Enable. You will need to follow the instructions on that page. More information is available on the [Braintree Developers Documentation Apple Pay page](https://developers.braintreepayments.com/guides/apple-pay/configuration/ios/v4).

I linked to the Sandbox Control Panel, but you would need to do this in your [Production](https://www.braintreegateway.com/login) account when you're ready to go live.

**Comment by gauravds** [comment]
Thanks @bluk, I want to know that always result of `result.paymentMethod` will be nil then what is the use of drop-in apple pay option.

**Comment by demerino** [comment]
@gauravds The goal was to allow merchants to use `Drop-In AND Apple Pay` while making the Apple Pay integration flexible so that it can be displayed whenever the merchant wants (usually as the final step of the checkout process). 

_This is different from the other payment methods._ All you need to do is check the `result. paymentOptionType` and then show a `PKPaymentViewController` to collect the information and tokenize as you did above.

We're open to suggestions (and pull requests) on how we can improve the Apple Pay support in Drop-In. And thanks again for taking the time to try the new Drop-In!
