### ISSUE TITLE
Question about version 4.3.2 & BTPayPalRequest's intent property

### ISSUE THREAD

**Issue by nikolaykasyanov** [braintree/braintree_ios#254]
Which value should I start using after upgrading to 4.3.2? Am I safe with default one or should I discuss it with my fellow backend developers to clarify which intent should I use on the client side?

**Comment by skunkworks** [comment]
You should be safe with the default value `authorize`.

The PayPal intent can be either `authorize` or `sale`. The major difference between the two is when the funds are actually captured: `authorize` works like a traditional credit card "auth-and-capture" flow where the payment is first authorized for an amount and captured afterwards, whereas `sale` will immediately capture funds in one step.

Most merchants will use the default `authorize` intent. A few merchants that deliver their goods instantly may want to opt into `sale` to receive immediate payment.

**Comment by nikolaykasyanov** [comment]
@skunkworks thanks for the detailed reply!
