### ISSUE TITLE
iOS 10 deprecated method.

### ISSUE THREAD

**Issue by euwars** [braintree/braintree_ios#255]
Hey there, 

in the latest iOS 10 beta update, application(_:open:sourceApplication:annotation:) has been decrypted and it's replaced by application(_:open:options:), which means BTAppSwitch requires some changes on how it detects incoming requests of url opening.
i'm trying to see if it's still possible to detects the source application but no luck yet.

**Comment by nirinchev** [comment]
Decrypted or deprecated? :)

**Comment by euwars** [comment]
i blame autocorrect for that.

**Comment by bluk** [comment]
@euwars Can you use the [`BTAppSwitch`'s `+ (BOOL)handleOpenURL:(NSURL *)url options:(NSDictionary *)options;`](https://github.com/braintree/braintree_ios/blob/2d4e85271e2705d630759042e051a24c678f7a98/BraintreeCore/Public/BTAppSwitch.h#L43) instead?

Both convenience `handleOpenURL...` methods are provided in case you need to support iOS 8 via `application(:open:sourceApplication:annotation:)` and want to use iOS 9's ` application(:open:options:)`.

Note that in the options dictionary, you can use the [`UIApplicationOpenURLOptionsSourceApplicationKey `](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/#//apple_ref/doc/constant_group/URL_Handling_Keys) to get the source application if you want to get it for another purpose.

**Comment by euwars** [comment]
@bluk unfortunately BTAppSwitche's openURL with options doesn't work. 

but passing the `UIApplicationOpenURLOptionsSourceApplicationKey` value from options to `handleOpen(_ url: URL, sourceApplication: String?)` as sourceApplication does the job.

**Comment by bluk** [comment]
Just as a quick follow up, this appears to be an issue in Xcode 8 GM as well. It seems to be a bug with the Swift 3 compiler where this dictionary type loses its values as it is passed from Swift to Objective-C. There is an Apple bug report open for this ( 27992351 ).

As a workaround, you can extract the `UIApplicationOpenURLOptionsSourceApplicationKey ` value out of the options dictionary as @euwars has done and use the `handleOpen(_ url: URL, sourceApplication: String?)` method for now.

**Comment by bluk** [comment]
For those interested, https://github.com/apple/swift/pull/4953 should fix this in a future Swift release.
