### ISSUE TITLE
BTPayPalRequest currency

### ISSUE THREAD

**Issue by jernejrus** [braintree/braintree_ios#256]
Is it possible to set currency to BTPayPalRequest, similarly as for android:
PayPalRequest request = new PayPalRequest(amountStr).currencyCode(currency);

**Comment by skunkworks** [comment]
Yes, please take a look at [BTPayPalRequest.h](https://github.com/braintree/braintree_ios/blob/master/BraintreePayPal/Public/BTPayPalRequest.h#L38) or our [CocoaDocs reference](http://cocoadocs.org/docsets/Braintree/4.5.0/Classes/BTPayPalRequest.html#//api/name/currencyCode).
