### ISSUE TITLE
 Undefined symbols for architecture i386 when building

### ISSUE THREAD

**Issue by imdadahad** [braintree/braintree_ios#259]
So I followed the steps as described. When attempting to build after adding the code for the DropIn controller, I receive the following error:

ld: warning: ignoring file /Users/dev-acc/Library/Developer/Xcode/DerivedData/sadapp-cgvdjwgyikqpzqazpsrxtzdqeqvd/Build/Products/Debug-iphonesimulator/libBraintree.a, file was built for archive which is not the architecture being linked (i386): /Users/dev-acc/Library/Developer/Xcode/DerivedData/sadapp-cgvdjwgyikqpzqazpsrxtzdqeqvd/Build/Products/Debug-iphonesimulator/libBraintree.a
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_BTAPIClient", referenced from:
      objc-class-ref in BraintreeBookingsService.o
  "_OBJC_CLASS_$_BTDropInViewController", referenced from:
      objc-class-ref in BraintreeBookingsService.o

Any idea what's wrong?

**Comment by skunkworks** [comment]
Hi @imdadahad, are you using Cocoapods or some other method to integrate the SDK? Which version of the Braintree SDK are you using?

**Comment by imdadahad** [comment]
Hi @skunkworks 

I am using the static library and the v.zero SDK.

**Comment by skunkworks** [comment]
The error message seems to indicate that the Braintree static library file `libBraintree.a` was not built for the correct architecture.

Can you try [cleaning out your Derived Data folder](http://stackoverflow.com/a/30701881/766491) and rebuilding?

If that doesn't work, can you share the Architecture build settings for your Braintree static library and for your app?

<img width="764" alt="screen shot 2016-09-04 at 1 31 02 pm" src="https://cloud.githubusercontent.com/assets/563375/18233738/fbecd67e-72a3-11e6-8af7-5bd45b18df43.png">

**Comment by imdadahad** [comment]
Yeah I tried to clean the derived data earlier but that didn't seem to work.

Here are the architecture settings:

**Braintree.xcodeproj**

![image](https://cloud.githubusercontent.com/assets/5855115/18233774/f448be6c-72e7-11e6-883e-909f7ce031e8.png)

**sadapp.xcodeproj**

![image](https://cloud.githubusercontent.com/assets/5855115/18233777/00550bac-72e8-11e6-8768-60120ad8d86a.png)

Thanks

**Comment by sdcoffey** [comment]
Hey @imdadahad,

Thanks for posting your settings. It looks like you may have skipped a step in integrating the static library. Make sure in your target's `Build Phases`, you've added `Braintree` under the `Target Dependencies` section, and added `libBraintree.a` under the `Link Binary with Libraries` section. For further reference, check out our [Static Library Integration guide](https://github.com/braintree/braintree_ios/blob/master/Docs/Braintree-Static-Integration-Guide.md).

Let us know if this fixes the problem.

**Comment by sdcoffey** [comment]
Hey @imdadahad, 

I'm going to close this issue since there's been no movement on it in several days. Feel free to reopen if you're still running into this problem.
