### ISSUE TITLE
AdSupport Requirement

### ISSUE THREAD

**Issue by nfox513** [braintree/braintree_ios#26]
Lately apps have been getting rejected for using the AdSupport framework (and IFA) without serving ads:
http://stackoverflow.com/questions/21489097/my-app-was-just-rejected-for-using-the-ad-support-framework-which-library-is-re

The podspec requires the AdSupport framework. Is this necessary, or can it be removed in the next version of the Braintree SDK?

**Comment by pmrajani** [comment]
I am using latest braintree 4.24.0.
It's still showing my app is using IDFA. 
Can we have official document that mansion braintree sdk use IDFA without Apple TOS?

**Comment by scannillo** [comment]
Hey @pmrajani . The latest release of Braintree iOS SDK (4.24.0) includes support for 3DS 2.0. We include the CardinalMobile framework to enhance our 3DS 2.0 experience, and it looks like their framework has introduced the AdSupport framework. We will go ahead and escalate this concern to Cardinal.

**Comment by demerino** [comment]
@pmrajani  Release 4.25.0 should have removed the use of IDFA. Let us know if you're still having issues.

**Comment by pmrajani** [comment]
thank you @demerino @scannillo
