### ISSUE TITLE
Warnings in XCode 8

### ISSUE THREAD

**Issue by mkassoff** [braintree/braintree_ios#260]
I'm seeing two warnings in XCode 8 which say

`Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'.`

This occurs in BTConfiguration.h for the line:
`- (nullable instancetype)init __attribute__((unavailable("Please use initWithJSON: instead.")));`

And BTClientToken.h for the line:

`- (nullable instancetype)init __attribute__((unavailable("Please use initWithClientToken:error: instead.")));`

**Comment by sdcoffey** [comment]
Ah, fun new XCode 8 stuff! 

Thanks for pointing this out, we'll address this and other remaining XCode 8 bugs in the coming days. I'll close this issue when this specific bug has been resolved.

**Comment by sdcoffey** [comment]
Fixed and released in [4.6.0](https://github.com/braintree/braintree_ios/releases/tag/4.6.0)
