### ISSUE TITLE
Warning issue.

### ISSUE THREAD

**Issue by kevinlee85** [braintree/braintree_ios#263]
I just init my Braintree object, then get below warn messages, 
canOpenURL: failed for URL: "com.paypal.ppclient.touch.v1://" - error: "(null)"
canOpenURL: failed for URL: "com.paypal.ppclient.touch.v2://" - error: "(null)"
canOpenURL: failed for URL: "com.venmo.touch.v2://x-callback-url/vzero/auth" - error: "(null)"

Does any expert any how to deal with it?
Thank you in advanced.

**Comment by bluk** [comment]
These messages are coming from iOS and are expected if you do not have the PayPal or Venmo apps installed. They are only worth noting if you are debugging a PayPal or Venmo payment flow and are experiencing an issue. Unfortunately, I don't believe there is a way to turn the log messages off.

Just in case anyone else runs into this issue, if you encounter a `- error: "(null)"` it means there is no app that can handle the custom URL. If you encounter a `- error: "This app is not allowed to query for scheme ..."`, then you must [whitelist the custom URL schemes](https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4) first.

Hope that helps!
