### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by kamendo** [braintree/braintree_ios#264]
I have the following linker issue when added braintree as a static library:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BTDropInUIUtilities", referenced from:
      objc-class-ref in libBraintree.a(BTCardFormViewController.o)
      objc-class-ref in libBraintree.a(BTEnrollmentVerificationViewController.o)
ld: symbol(s) not found for architecture x86_64

I tried the cleaning the derived data, as suggested in issue 259.
I added all the steps suggested in [Braintree-Static-Integration-Guide.md](https://github.com/braintree/braintree_ios/blob/master/Docs/Braintree-Static-Integration-Guide.md)

**Comment by sdcoffey** [comment]
Hey @kamendo,

Thanks for lettings us know! I was able to reproduce this issue, we'll be pushing a release shortly that fixes this issue. If you need a fix in the short term, open up `BTDropInUIUtilities.m`, and check `Braintree` under the `Target membership` in the right-hand panel like so:

![](https://cloud.githubusercontent.com/assets/3506415/18444095/ac9f20ca-78cc-11e6-9e72-59aeec67371d.png)

I'll close this issue when the fix has been released.
