### ISSUE TITLE
App rejection due to "updateLayout"

### ISSUE THREAD

**Issue by jpmhouston** [braintree/braintree_ios#265]
"Your app uses or references the following non-public APIs: ... updateLayout: 

... If you have defined methods in your source code with the same names as the above-mentioned APIs, we suggest altering your method names so that they no longer collide with Apple's private APIs to avoid your application being flagged in future submissions."

BTDropInContentView.m was the only occurrence of "updateLayout" within our app. One of our 2 apps submitted at the same time and using your cocoapod was rejected, the other wasn't, go figure.

I know its ridiculous to do so, but can you please rename this method in your next release to avoid the chance of this rejection in the future.

Thanks!

**Comment by jpmhouston** [comment]
To followup: after submitted another build with all occurrences of this method name changed in BTDropInContentView.m, app review no longer listed "updateLayout:" as a non-public API issue. This indicates that this method was indeed triggering the false positive.

**Comment by sdcoffey** [comment]
Ahh that's interesting. We've never seen this specific rejection before, that's really interesting. Yes, I believe that method is private to `BTDropinContentView`, we'll go ahead and update it. Thanks for letting us know!
