### ISSUE TITLE
[BraintreeSDK] WARNING Failed to send analytics event. Remote configuration fetch failed. The operation couldn’t be completed. forbidden

### ISSUE THREAD

**Issue by nhatlee** [braintree/braintree_ios#266]
I integrated BraintreeSDK into iOS app (use Swift). After get clientToken from server then run the command: `self.braintreeClient = BTAPIClient(authorization: _clientToken)` . And I got the warning: `[BraintreeSDK] WARNING Failed to send analytics event. Remote configuration fetch failed. The operation couldn’t be completed. forbidden`.
And got the error: `The operation couldn't be completed. forbitdden`. When tried to presented: `BTDropInViewController`.
Please help me to fix it.

**Comment by bluk** [comment]
I believe this is because your account that you're using to generate the client token does not have the correct permissions. Can you please contact the [Support Team](https://articles.braintreepayments.com) at [support@braintreepayments.com](mailto:support@braintreepayments.com) ?
