### ISSUE TITLE
not building on ios 10

### ISSUE THREAD

**Issue by IbrahimalKhayat** [braintree/braintree_ios#267]
there are a few issues with deprecated methods on new xcode 8 and ios10
UIApplication openURL
OSAtomicCompareAndSwapInt @ PPOTConfiguration.m

**Comment by bluk** [comment]
Thank you for reporting the issue. We will fix this in the next release.

**Comment by bluk** [comment]
This should be resolved in [4.6.1](https://github.com/braintree/braintree_ios/releases/tag/4.6.1). Thanks for your patience.
