### ISSUE TITLE
Add Braintree as a framework

### ISSUE THREAD

**Issue by kamendo** [braintree/braintree_ios#268]
Please add support for this option.

I have a custom build script that is not compatible with pods and carthage.

In order to add the sdk I had to build with carthage, copy the frameworks and add them as Embedded binaries

**Comment by bluk** [comment]
@kamendo Are you asking for framework binaries to be released as well or something else? Sorry, I don't fully understand the request.

**Comment by kamendo** [comment]
Yes, it will be the most easy setup in my case

**Comment by demerino** [comment]
It sounds like your Carthage approach is the right one - we'll consider additional installation methods as demand grows.
