### ISSUE TITLE
Getting a "OSStatus error -10814"

### ISSUE THREAD

**Issue by howardhwtam** [braintree/braintree_ios#269]
I added `com.paypal.ppclient.touch.v1`, `com.paypal.ppclient.touch.v2`, and `com.venmo.touch.v2` in my app's `info.plist` but instead of getting an error that says `This app is not allowed to query for scheme com.paypal.ppclient.touch.v1` I am getting an `OSStatus error -10814`. How do I properly add URLs to my app's whitelist?

**Comment by skunkworks** [comment]
Hi @howardhwtam,

It sounds like you've set up your app's whitelist correctly. That error message seems to occur when the app is not installed on the device (see [here](http://stackoverflow.com/a/38799196/766491) and [here](https://www.osstatus.com/search/results?platform=all&framework=all&search=-10814)).

Are you seeing this on a hardware device with the app installed? Can you try rebooting the device to see if it's an iOS glitch?

**Comment by howardhwtam** [comment]
@skunkworks - I don't see any error messages when I run the app on an actual iPhone. Does it mean I can ignore the error messages when I run the app on a simulator? Thanks for your help!

**Comment by skunkworks** [comment]
I would double check that everything works as intended on the iPhone device when the app is present and when it is not. If it works well, I think you can safely chalk it up to being a quirk of testing on the Simulator.

Please reopen the issue if you see anything strange. Thanks!
