### ISSUE TITLE
BTCard shouldValidate explanation

### ISSUE THREAD

**Issue by bencallis** [braintree/braintree_ios#270]
We are using the Braintree SDK with our custom payment UI. When the user enters their card details and hits the done button we tokenise the card details (but do not use to token at this point to take payment) with the following code:

```
    BTAPIClient *braintreeClient = [[BTAPIClient alloc] initWithAuthorization:_braintreeToken];
    BTCardClient *cardClient = [[BTCardClient alloc] initWithAPIClient:braintreeClient];
    BTCard *card = [[BTCard alloc] initWithNumber:cardNumber
                                  expirationMonth:expiryMonth
                                   expirationYear:expiryYear
                                              cvv:nil];
    card.shouldValidate = NO; // TODO: Decide if we should do this?
    [cardClient tokenizeCard:card completion:completion];
```

If the user enters an invalid card number and we have `shouldValidate` set the NO (the default value) a token is returned with no error message. However, we would like braintree to return an error at this point if the card details are invalid.
Setting `shouldValidate` to YES returns an error as expected. However, the documentation for this property contains the following warning.

```
/// Controls whether or not to return validations and/or verification results. By default, this is
/// not enabled.
///
/// @warning Use this flag with caution. By enabling client-side validation, certain tokenize card
/// requests may result in adding the card to the vault. These semantics are not currently documented.
```

Please can you explain why this may result in adding the card to the vault as this is not the behaviour which we want?

**Comment by skunkworks** [comment]
Hi @bencallis,

When tokenizing a card with `shouldValidate = YES`, the card will be vaulted if:

* You are using [client tokens](https://developers.braintreepayments.com/start/hello-client/ios/v4#get-a-client-token) as your Braintree authentication mechanism
* The [generated client token from your server](https://developers.braintreepayments.com/start/hello-server#generate-a-client-token) contains a `customerId`

If you do not plan on vaulting cards, you can generate client tokens without a customer ID and it will not be vaulted. Alternatively, you may be able to use a tokenization key to authenticate with Braintree, which is a static key that does not allow vaulting or card verification.
