### ISSUE TITLE
fbinfer warnings

### ISSUE THREAD

**Issue by rocketnik** [braintree/braintree_ios#271]
Hello,

i ran infer (fbinfer) on our project, which included this sdk and it resulted in a few warnings. You might want to fix them. You can use the following command to install the static analyzer:
brew install infer

I will attach the list of warnings (the sdk I use is not of the latest version, you have fixed some issues already).

The mentioned problems are no real issue for us - and we are also excluding your library from the infer check now, but you still might want to have a look.

Kind regards,
Nikolas

Pods/Braintree/BraintreeCore/BTClientToken.m:109: error: NULL_DEREFERENCE
  pointer JSONError last assigned on line 94 could be null and is dereferenced at line 109, column 47
  107.               *error = [NSError errorWithDomain:BTClientTokenErrorDomain
  108.                                            code:BTClientTokenErrorInvalid
  109. >                                      userInfo:@{ NSUnderlyingErrorKey: JSONError,
  110.                                                    NSLocalizedDescriptionKey: @"Invalid client token. Please ensure your server is generating a valid Braintree ClientToken.",
  111.                                                    NSLocalizedFailureReasonErrorKey: @"Invalid JSON" }];
  112.   

Pods/Braintree/BraintreePayPal/PayPalUtils/PPOTEncryptionHelper.m:98: error: MEMORY_LEAK
   memory dynamically allocated to cipherData by call to malloc() at line 79, column 27 is not reachable after line 98, column 5
  96.   
  97.       // concat nonce and cipher for signing
  98. >     NSData *encryptedBlob = [NSData dataWithBytesNoCopy:cipherData length:dataMoved freeWhenDone:YES];
  99.       NSMutableData *signData = [NSMutableData dataWithCapacity:encryptedBlob.length + nonce.length];
  100.       [signData appendData:nonce];
  101.   

Pods/Braintree/BraintreePayPal/PayPalUtils/PPOTEncryptionHelper.m:181: error: MEMORY_LEAK
   memory dynamically allocated to plainText by call to malloc() at line 163, column 50 is not reachable after line 181, column 89
  179.           return nil;
  180.       }
  181. >     resultData = [NSData dataWithBytesNoCopy:plainText length:dataMoved freeWhenDone:YES];
  182.       return resultData;
  183.   }
  184.

**Comment by bluk** [comment]
@rocketnik Thanks for the report. We'll try to fix these static analysis issues soon.

**Comment by demerino** [comment]
We've pushed a fix in `4.7.1` - let me know if that fixes the issue.
