### ISSUE TITLE
BTDropInViewController Change Payment Method Dismiss Issue

### ISSUE THREAD

**Issue by rksaraf** [braintree/braintree_ios#272]
I have recently updated the Braintree SDK in an app I am working on from 3.9.x to 4.x (currently 4.6.0, but have tested 4.4.0 and 4.5.0) and the behavior when changing a payment method has caused a bug with the UI.

When presenting an instance of BTDropInViewController (within a  UINavigationController - known from here as the "1st") with an existing payment method(s) you are presented with a view that displays the currently (last) selected payment method with a button to "Change payment method". Pressing the "Change payment method" button presents a modal view controller that is another instance of BTDropInViewController within another UINavigationController (known as the "2nd"). Within this UI you can tap from a list of existing payment methods and it will dismiss this UINavigationController to reveal the updated selected payment method in the 1st UINavigationController. However, if you select the "+" button to add a new payment method, a new view controller gets pushed onto the 2nd UINavigationController to add a new card or Paypal/Venmo. Adding a new card also properly dismisses the 2nd UINavigationController but adding Paypal (SafariViewController) or Venmo (app switch) does not dismiss the 2nd UINavigationController upon successful authorization of either of those methods. Instead, after I have authorized Paypal or Venmo, I return to the create new payment method screen. This bug is reproducible in the sample code provided to me by Braintree support: https://github.com/orcunkeskin/Braintree-Drop-In-UI-Objective-C

Reply if you need more details.

**Comment by bluk** [comment]
Hello @rksaraf . I believe you've been in contact with support about your issue and that it was resolved. If that's not the case, please leave a comment or contact support again. Thanks!
