### ISSUE TITLE
adding Braintree-ios/Braintree, there are only read.me file on that folder

### ISSUE THREAD

**Issue by biotechpro7** [braintree/braintree_ios#274]
i try adding Braintree folder to the app but the app automatically create Braintree folder with Header.h and info.plist file inside it. do i have to rename the Braintree folder?. 

Update: i delete the Braintree folder that is automatically created when i create new framework and add the Braintree folder from the github. but it does not change anything and when i check there are only README.md inside it.

**Comment by demerino** [comment]
Have you considered/tried using Cocoapods or Carthage for your installation?
