### ISSUE TITLE
(Apple) Non-public API usage

### ISSUE THREAD

**Issue by pedrosilva88** [braintree/braintree_ios#279]
I uploaded a version of my App to iTunes Connect I receive an email from Apple to remove some selectors because they are private.

Non-public API usage:
    The app references non-public selectors in ***: setPaymentRequest:, setSummaryDescription:, setSummaryTitle:

Does anyone have this problem?

**Comment by demerino** [comment]
Hmm, I have not seen this before. Can you paste in your Drop-In code? Are you calling those methods yourself? Also, if you're targeting iOS9+ you can look into our new Drop-In: https://github.com/braintree/braintree-ios-drop-in

**Comment by skunkworks** [comment]
Hi @pedrosilva88, I would try appealing the rejection. I think this is an instance of Apple's code scanner doing a less-than-thorough job of vetting exactly what your code is doing.

And just to be thorough, I would make sure your code is not using selectors unconventionally, since that may induce some false positives, e.g.

```
[paymentRequest performSelector:@selector(setSummaryDescription:) withObject:@"My summary description];
```

**Comment by pedrosilva88** [comment]
```
- (void)setupDropInUI {
	self.braintreeClient = [[BTAPIClient alloc] initWithAuthorization:self.paymentToken.clientToken];
	
	BTDropInViewController *dropInViewController = [[BTDropInViewController alloc] initWithAPIClient:self.braintreeClient];
	dropInViewController.delegate = self;
	dropInViewController.paymentRequest = [self setupPaymentRequest];
	
	[self addDropInUIToContainer:dropInViewController];
}
```

When I set the paymentRequest.

**Comment by pedrosilva88** [comment]
@skunkworks the problem is that I'm getting this error in the processing of the app, so I can't upload the app to the iTunes connect.

**Comment by skunkworks** [comment]
@pedrosilva88 These are actual errors and not warnings? What version of Xcode are you using? If it's actually blocking you from uploading your binary to the App Store, you may also want to try using Application Loader to upload the app binary as a workaround.

**Comment by pedrosilva88** [comment]
@skunkworks this is not an error, in fact the upload has success, but when the app is Processing in the iTunes Connect (you can see in the Activity Tab), I receive an email with this issues. 
And the version uploaded simply disappears.

**Comment by skunkworks** [comment]
I think you will have to appeal the App Store rejection with Apple directly, as this is clearly a mistake on their part. You should be able to submit an appeal [here](https://developer.apple.com/support/app-review/).
