### ISSUE TITLE
Method override for the designated initializer of the superclass '-init' not found

### ISSUE THREAD

**Issue by memodev07** [braintree/braintree_ios#280]
Hi guys, every time I try to run my project I get an error message in the BTAPIResponseParser.m file telling `Method override for the designated initializer of the superclass '-init' not found`. The project was working fine until I upgraded to Sierra and Xcode 8.

**Comment by demerino** [comment]
Sounds similar to https://github.com/braintree/braintree_ios/issues/230

What version of `Braintree` are you using and how are you integrating (Cocoapods, Carthage, other...)? To be compatible with Xcode8 - ensure that you're using the most recent releases of `Braintree` and your preferred integration method.

For example: You'll want to be using `Cocoapods 1.1.1` and have `pod 'Braintree'` in your `Podfile` to ensure the best Xcode8 compatibility.

**Comment by memodev07** [comment]
Yeah it was similar to #230 now is fixed, thanks :)
