### ISSUE TITLE
BTPayPalDriver is incompatible with iOS 7 since 4.6.0

### ISSUE THREAD

**Issue by nikolaykasyanov** [braintree/braintree_ios#283]
`queryItems` is iOS 8+ API: https://github.com/braintree/braintree_ios/blob/65fe17bf78efb5f4dbea4ae66fd1e80ead04c4d5/BraintreePayPal/BTPayPalDriver.m#L807

**Comment by demerino** [comment]
Thanks @nikolaykasyanov 

We have a fix ready to go - it should be published by the end of the week.

**Comment by demerino** [comment]
`4.7.3` should solve this issue. Let us know if you are still having problems.
