### ISSUE TITLE
[question] Using as an alternative to PayPal-iOS-SDK

### ISSUE THREAD

**Issue by vondiplo** [braintree/braintree_ios#284]
Hi,

I'd like you BraintTree iOS sdk to enable a single checkout from Paypal similar to how PayPal-iOS-SDK works. I don't have a braintree account (I'm not from a supported country), I only have a paypal merchant account with the relevant api keys. 

Can I still use this BrainTree iOS sdk to successfully charge paypal accounts and retrieve the charged user shipping address? If so, how?

**Comment by demerino** [comment]
We do support the `single checkout` flow.

We have some docs here: https://developers.braintreepayments.com/guides/paypal/checkout-with-paypal/ios/v4

Let me know if you still need additional information.

**Comment by demerino** [comment]
**Note**: You'll need a `Braintree` account to follow the linked docs above. Sorry for the confusion.

Otherwise, you'll probably want to stick with the `PayPal-iOS-SDK` for now.
