### ISSUE TITLE
[Warning] Incorrect @param causing compiler warning in BTAPIClient.h

### ISSUE THREAD

**Issue by adomanico** [braintree/braintree_ios#285]
Seeing a compiler warning regarding 'completionBlock' rather then 'completion in the param comment

/<directory>/Carthage/Build/iOS/BraintreeCore.framework/Headers/BTAPIClient.h:67:12: Parameter 'completionBlock' not found in the function declaration

```swift
/// @param completionBlock Callback that returns an array of payment method nonces.
- (void)fetchPaymentMethodNonces:(BOOL)defaultFirst
                      completion:(void(^)(NSArray <BTPaymentMethodNonce *> * _Nullable paymentMethodNonces, NSError * _Nullable error))completion;
```

Both fetchPaymentMethodNonces functions have this issue

**Comment by adomanico** [comment]
Deployment target is 10.0.

Not seeing this warning on a 9.0 deployment target

**Comment by demerino** [comment]
Thanks @adomanico 

We'll review the issue and PR.
