### ISSUE TITLE
NSInvalidArgumentException on UIColor bt_colorWithBytesR:G:B:

### ISSUE THREAD

**Issue by jbrodulfo** [braintree/braintree_ios#288]
016-11-16 16:56:22.236 Mojo[44035:2268451] +[UIColor bt_colorWithBytesR:G:B:]: unrecognized selector sent to class 0x10384f948
2016-11-16 16:56:22.422 Mojo[44035:2268451] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[UIColor bt_colorWithBytesR:G:B:]: unrecognized selector sent to class 0x10384f948'

This error occurs on initalization of the BTDropInViewController. In this line  BTDropInViewController `*dropInViewController` = [[BTDropInViewController alloc]
                                                    `initWithAPIClient:self.braintreeClient];`

Here is the full stack error

`2016-11-16 16:56:22.236 Mojo[44035:2268451] +[UIColor bt_colorWithBytesR:G:B:]: unrecognized selector sent to class 0x10384f948
2016-11-16 16:56:22.422 Mojo[44035:2268451] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[UIColor bt_colorWithBytesR:G:B:]: unrecognized selector sent to class 0x10384f948'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001051e2f45 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001044d0deb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001051eb46d +[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000105138eea ___forwarding___ + 970
	4   CoreFoundation                      0x0000000105138a98 _CF_forwarding_prep_0 + 120
	5   Mojo                                0x00000001007f15b0 -[BTUI borderColor] + 64
	6   Mojo                                0x00000001007d2bf4 -[BTDropInContentView initWithFrame:] + 964
	7   UIKit                               0x0000000102be3e3d -[UIView init] + 62
	8   Mojo                                0x00000001007fb29e -[BTUIThemedView init] + 62
	9   Mojo                                0x00000001007ddfed -[BTDropInViewController initWithAPIClient:] + 285
	10  Mojo                                0x000000010064198b __51-[MJNewRegistrationViewController basicPlanClicked]_block_invoke + 411
	11  Mojo                                0x00000001005f9a66 __59-[MJDownloadManager getJson:andEndpointString:WithHandler:]_block_invoke + 214
	12  CFNetwork                           0x000000010102db3d __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
	13  CFNetwork                           0x000000010103ffb6 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 302
	14  Foundation                          0x00000001041443b8 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	15  Foundation                          0x00000001040800e5 -[NSBlockOperation main] + 101
	16  Foundation                          0x0000000104063036 -[__NSOperationInternal _start:] + 646
	17  Foundation                          0x0000000104062c47 __NSOQSchedule_f + 194
	18  libdispatch.dylib                   0x000000010593e49b _dispatch_client_callout + 8
	19  libdispatch.dylib                   0x00000001059262af _dispatch_main_queue_callback_4CF + 1738
	20  CoreFoundation                      0x00000001051432e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	21  CoreFoundation                      0x00000001051048a9 __CFRunLoopRun + 2073
	22  CoreFoundation                      0x0000000105103e08 CFRunLoopRunSpecific + 488
	23  GraphicsServices                    0x0000000105dc9ad2 GSEventRunModal + 161
	24  UIKit                               0x0000000102b5730d UIApplicationMain + 171
	25  Mojo                                0x00000001006e06bf main + 111
	26  libdyld.dylib                       0x000000010597392d start + 1
	27  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

**Comment by bluk** [comment]
@jbrodulfo Did you use CocoaPods or Carthage to integrate with this project? It seems like you are missing the `BraintreeUI` framework which adds a [category to `UIColor`](https://github.com/braintree/braintree_ios/blob/6f1ea0c7524d4a385ff9ef64941f60e37ad08c1c/BraintreeUI/Public/UIColor%2BBTUI.h).

**Comment by jbrodulfo** [comment]
@bluk I used CocoaPods. I re-integrated it with CocoaPods and still having the issue.

**Comment by demerino** [comment]
@jbrodulfo In Build Settings, make sure you have $(inherited) in Other Linker Flags.

If you're using the most recent versions of Cocoapods and Xcode, this should be done automatically for you. Do you see any warnings when running `pod update`?

If that doesn't work, can you share the versions of `Braintree SDK`, `cocoapods` and `Xcode` that you are using?

**Comment by demerino** [comment]
If you continue to have problems, feel free to reopen this issue with additional information.
