### ISSUE TITLE
Braintree VectorArt 

### ISSUE THREAD

**Issue by civocr** [braintree/braintree_ios#289]
Hey,

I'm upgrading my project to Braintree 4.x and I have a custom implementation to collect card details. My project needs access to BTUIKCVVFrontVectorArtView & BTUIKCVVBackVectorArtView

I have BraintreeDropIn in my pod, trying to make these 2 public using the manual process leaves me with the following error: duplicate interface definition for class 'BTUIKVectorArtView'

**Comment by demerino** [comment]
Thanks for the feedback @civocr 

We'll make these public/accessible in an upcoming release.

**Comment by demerino** [comment]
See https://github.com/braintree/braintree-ios-drop-in/pull/7

**Comment by demerino** [comment]
We merged in the PR but have not done a release. We will likely publish the update next week.
