### ISSUE TITLE
Core not compatible with app extensions

### ISSUE THREAD

**Issue by bsmith11** [braintree/braintree_ios#290]
Currently, the core framework is not compatible with app extensions because it uses APIs that are unavailable to app extensions. Namely, `[UIApplication sharedApplication]`.

**Comment by demerino** [comment]
Thanks for pointing out this use case.  We'll review your PR.

**Comment by skunkworks** [comment]
We've merged this into a separate branch for now and will update you when this makes it into `master`. Thanks!

**Comment by demerino** [comment]
`4.7.3` has been released and should include the changes you need. Let us know if you have any issues.
