### ISSUE TITLE
kill swift 2.3 code

### ISSUE THREAD

**Issue by eventomer** [braintree/braintree_ios#294]
Xcode 8.2 is showing warnings for swift 2.3 code

Braintree has swift 2.3 in the unit tests target and the ui tests target

please migrate to swift 3 in order to clear this warnings 

Thanks

**Comment by sdcoffey** [comment]
Hey @eventomer - so sorry for the delayed response here. We're currently working on porting our test code to swift 3. I'll keep you posted on the progress and close this issue when the work is released.

**Comment by demerino** [comment]
We will hopefully be releasing the update to Swift3 (UnitTests) next week.

**Comment by demerino** [comment]
Should be fixed in `4.7.4`
