### ISSUE TITLE
BrainTree can not build on Xcode8.1 and Cocoapod 0.39.0

### ISSUE THREAD

**Issue by vemahendran** [braintree/braintree_ios#295]
#### Developer Info
Venkatesan Mahendran

- Braintree SDK version:
4.3.2

- Integration type and version:
Xcode 8.1
CocoaPods 1.1.1

- Environment:
Both Sandbox and Production

#### Issue Details
The issue is same as [an existing issue](https://github.com/braintree/braintree_ios/issues/277) reported a month back. Our app can only run on CocoaPods 0.39.0. We have a hard dependency with the pod version. It would be really great if you guys fix this issue on 0.39.0 too?

**Comment by demerino** [comment]
Resolved by excluding the UI subspec.
