### ISSUE TITLE
ERROR that i cant understand about _BTAppSwitch

### ISSUE THREAD

**Issue by adriansalim** [braintree/braintree_ios#298]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BTAppSwitch", referenced from:
      objc-class-ref in bidAppDelegate.o
ld: symbol(s) not found for architecture x86_64

someone can help me?
i already upadate the pods for the newest
![screen shot 2016-12-23 at 1 24 18 pm](https://cloud.githubusercontent.com/assets/24728715/21448257/27c737ce-c913-11e6-9cc7-b5193e4f50c5.png)

when i call this method
`[BTAppSwitch setReturnURLScheme:@"beautyful.lol.payments"];`
my app cant build

**Comment by skunkworks** [comment]
It looks like your Xcode project settings are slightly misconfigured. Try going to the build settings for your app target and make sure to add the `$(inherited)` flag to both `HEADER_SEARCH_PATHS` and `OTHER_LDFLAGS`:

![screen shot 2016-12-23 at 2 36 17 am](https://cloud.githubusercontent.com/assets/563375/21451998/9bc700b0-c8b8-11e6-9efd-809d54670fc0.png)

![screen shot 2016-12-23 at 2 33 11 am](https://cloud.githubusercontent.com/assets/563375/21451963/38fd9cdc-c8b8-11e6-8590-8b08b87434cd.png)

This allows the build of your app target to inherit these settings that are specified by the CocoaPods you've integrated (in this case, Braintree).

Let us know if that worked!

**Comment by adriansalim** [comment]
@skunkworks thank you sir, but i already add that sir and didn't work for me
need more advance answer sir.
![1](https://cloud.githubusercontent.com/assets/24728715/21454006/6cbfe306-c947-11e6-810d-1d9e664d1d1a.png)
![2](https://cloud.githubusercontent.com/assets/24728715/21454007/6de40e24-c947-11e6-8d23-ab44af98d37b.png)

**Comment by skunkworks** [comment]
@adriansalim Can you try running `pod deintegrate` and `pod install`? Also, in your app delegate, how are you importing the Braintree header files?

**Comment by adriansalim** [comment]
@skunkworks i tried `pod deintegrate` and `pod install`, i get same error
in my delegate i just #import "BraintreePayPal.h"
and call `BTAppSwitch` in void `didFinishLaunchingWithOptions`
`[BTAppSwitch setReturnURLScheme:@"beautyful.lol.payments"];`

**Comment by skunkworks** [comment]
@adriansalim Would it be possible to get a copy of the project to debug?

**Comment by adriansalim** [comment]
@skunkworks i cant give you project beacuse i had agreement with my company
how about teamviewer?

**Comment by Seanmclem** [comment]
> @skunkworks i already fix it today and the problem i must add manual the library to my project.
> i dont know why that happend but its worked for me
> thanks you in advance @skunkworks

what was the problem?

**Comment by ananthauppangala** [comment]
If you are using Braintree v5 use the following line
[BTAppContextSwitcher setReturnURLScheme:self.paymentsURLScheme];
