### ISSUE TITLE
install pod 'Braintree/PayPal' in my project and error when i try to run my project IOS

### ISSUE THREAD

**Issue by adriansalim** [braintree/braintree_ios#300]
"_OBJC_CLASS_$_PPRCClientMetadataIDProvider", referenced from:
      objc-class-ref in libBraintree.a(PPDataCollector.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by demerino** [comment]
Can you share the relevant lines from your `Podfile` and `Cocoapods Version` along with anything else that might help us reproduce and solve the issue?

**Comment by marcelomogrovejo** [comment]
We are experimenting the same issue here, could you please share what you did to solve it? it would be really appreciated.
Thanks.
