### ISSUE TITLE
Delegate method -paymentDriver:requestsDismissalOfViewController: doesn't make sense for SFSafariViewController

### ISSUE THREAD

**Issue by nikolaykasyanov** [braintree/braintree_ios#301]
#### Developer Info
- Braintree SDK version: 4.7.0
- Integration type and version: CocoaPods 1.1.1
- Environment: not applicable

#### Issue Details

`BTPayPalDriver` invokes this delegate method when `SFSafariViewController` invokes the following method of its delegate: `safariViewControllerDidFinish:`.

`BTViewControllerPresentingDelegate` method name suggests that view controller is supposed to be dismissed in the implementation, but that's not the case for `SFSafariViewController`, as per documentation:

>You can perform any necessary cleanup here. The view controller is dismissed afterwards.

Dismissing `SFSafariViewController` in the delegate method implementation leads to two subsequent calls to `-[UIViewController dismissViewControllerAnimated:completion:]`. Generally, it doesn't seem to be an issue, though it breaks things when one expects dismissal completion block of the second dismissal call to execute.

**Comment by demerino** [comment]
Thanks for submitting the issue @nikolaykasyanov 

Where are you finding the documentation for `You can perform any necessary cleanup here. The view controller is dismissed afterwards.`?

You should only need two delegate methods to handle the presentation/dismissal of the `SFSafariViewController`:

```
- (void)paymentDriver:(__unused id)driver requestsPresentationOfViewController:(UIViewController *)viewController {
    [self presentViewController:viewController animated:YES completion:nil];
}

- (void)paymentDriver:(__unused id)driver requestsDismissalOfViewController:(UIViewController *)viewController {
    [viewController dismissViewControllerAnimated:YES completion:nil];
}
```

I'm only seeing `one` call to the delegate method `requestsDismissalOfViewController` when testing on iOS9 (BT `4.7.3` &  Cocoapods `1.1.1`).

Also, make sure your `AppDelegate` isn't calling the handle method more than once:
```
[BTAppSwitch handleOpenURL:url options:options];
```

**Comment by nikolaykasyanov** [comment]
@demerino here it is: https://developer.apple.com/reference/safariservices/sfsafariviewcontrollerdelegate/1621214-safariviewcontrollerdidfinish

**Comment by nikolaykasyanov** [comment]
Thanks for your reply!

`requestsDismissalOfViewController` is invoked only once, that's totally correct.

The problem is that `dismissViewControllerAnimated:completion:` is called twice: once per system and onece per delegate implementation.

**Comment by demerino** [comment]
Got it. I looked into it a bit more and it looks like `safariViewControllerDidFinish:` is called when the `Done` button is tapped (in the upper corner of the SFSafariViewController UI).

However, when clicking the links on the webpage itself for the PayPal flow - `safariViewControllerDidFinish:` is not called. This means that the `requestsDismissalOfViewController` is still required for the happy paths.

I'll look into a solution to bypass the call to `requestsDismissalOfViewController` if the SFSafariViewController is already dismissed/being dismissed.

**Comment by nikolaykasyanov** [comment]
@demerino 

>I'll look into a solution to bypass the call to `requestsDismissalOfViewController`

I believe this might break backward compatibility because I can imagine people using this method for various cleanups, not only for dismissal. What do you think?

**Comment by demerino** [comment]
@nikolaykasyanov 

> I believe this might break backward compatibility because I can imagine people using this method for various cleanups, not only for dismissal. What do you think?

Great point. This delegate method was never intended for cleanup - but you are correct that this would be a breaking change. We'll have to push the fix to the next major version. We'll also need to look into additional delegate methods that are specifically for setup/cleanup for developers.
