### ISSUE TITLE
How to change Monk Sandbox Purchase Flow to Paypal login page

### ISSUE THREAD

**Issue by adriansalim** [braintree/braintree_ios#304]
![screen shot 2017-01-04 at 12 27 28 pm 1](https://cloud.githubusercontent.com/assets/24728715/21637766/06acb85c-d29b-11e6-8c0c-eaf5ee9981eb.png)

so user can login with him user id and password

**Comment by demerino** [comment]
You'll need to setup your production account and use production credentials. Learn more here: https://developers.braintreepayments.com/start/go-live/ruby

(select your appropriate server language)
