### ISSUE TITLE
Done button inside PayPal's vault flow dismisses parent view controller too

### ISSUE THREAD

**Issue by apascual** [braintree/braintree_ios#308]
#### Developer Info

- Braintree SDK version: 4.7.3

- Integration type and version: COCOAPODS: 1.0.1

- Environment: Sandbox and Production

#### Issue Details
Hi,

I am using the Braintree library for with PayPal support. I have followed the official integration guide for the Vault flow (https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4).

After calling:

```
payPalDriver.viewControllerPresentingDelegate = self;

[payPalDriver authorizeAccountWithCompletion:^(BTPayPalAccountNonce *tokenizedPayPalAccount, NSError *error) {
        ...
    }];
```

I get presented the PayPal view controller and the flow works fine when either cancelling or completing the account details, the problem happens when clicking the upper **Done** button, in that case the PayPal's view controller gets dismissed, but also the view controller defined as **viewControllerPresentingDelegate**.

Thanks.

![simulator screen shot 13 jan 2017 09 23 21](https://cloud.githubusercontent.com/assets/3491658/21923392/234876b0-d974-11e6-9cd9-b908e3ce117d.png)

**Comment by apascual** [comment]
This was actually due to a wrong delegate method implementation on the guide...

```
- (void)paymentDriver:(id)paymentDriver
requestsDismissalOfViewController:(UIViewController *)viewController {
    [self dismissViewControllerAnimated:YES completion:nil];
}
```

Should actually be:

```
- (void)paymentDriver:(id)paymentDriver
requestsDismissalOfViewController:(UIViewController *)viewController {
    [viewController dismissViewControllerAnimated:YES completion:nil];
}
```

**Comment by alper** [comment]
Thanks a bunch for this. I spent way too long digging around for this.
