### ISSUE TITLE
Mis-capitalized import causes error in Xcode 8.3 beta 1

### ISSUE THREAD

**Issue by keith** [braintree/braintree_ios#309]
#### Developer Info

- Braintree SDK version: 4.7.4

- Integration type and version: CP 1.1.1

- Environment: not relevant

#### Issue Details

With Xcode 8.3 beta 1 braintree fails to compile because [this mis-capitalization](https://github.com/braintree/braintree_ios/blob/612551af2c0bdf11356f17bfdf30a2e04047b823/BraintreeCore/BTAnalyticsMetadata.m#L1) in the import. Changing this fixes the problem.

**Comment by skunkworks** [comment]
@keith Thanks for catching this. It's interesting that Xcode <=8.2 allowed this to import previously. We'll fix this shortly.

**Comment by demerino** [comment]
This is now fixed on `master` and will be included in the next release.

**Comment by keith** [comment]
Thanks! We can close this now, or when the release ships, doesn't matter to me.

**Comment by charlieMonroe** [comment]
@skunkworks - this in preparation for APFS (Apple File System) which will not be case-insensitive in the beginning.

**Comment by demerino** [comment]
fixed in `4.7.5`
