### ISSUE TITLE
Documentation: Set up your Apple Pay button

### ISSUE THREAD

**Issue by scott4arrows** [braintree/braintree_ios#311]
#### Developer Info

- Braintree SDK version:#define BRAINTREE_VERSION (@"4.7.4")

- Integration type and version: CocoaPods 1.1.1

- Environment:

#### Issue Details
> Please include as many details (logs, images, steps to reproduce) as you can to help us reproduce this issue faster.

Swift documentation at https://developers.braintreepayments.com/guides/apple-pay/client-side/ios/v4#set-up-your-apple-pay-button

> import PassKit
> // Add #import "BraintreeApplePay.h" to bridging header

Adding import as "BraintreeApplePay.h will cause Xcode debugger problems due to incorrectly importing into Swift.

It should be:
// Add #import <Braintree/BraintreeApplePay.h> to bridging header

**Comment by skunkworks** [comment]
Hi @scott4arrows,

You are correct that `#import "BraintreeApplePay.h"` may not work, depending on how the Braintree iOS SDK is integrated, e.g. when integrating via a single bundled CocoaPods framework (`use_frameworks!`). For others who are still using static libraries or Carthage frameworks, the import might be different.

We'll update the docs to be more agnostic. Maybe something like:

```
// Add BraintreeApplePay.h to bridging header
```

Does that seem reasonable?

**Comment by scott4arrows** [comment]
Yes. That seems reasonable. It bit us cause we did a straight copy/paste.

Thanks for quick reply.

**Comment by skunkworks** [comment]
We should have this fixed shortly.
