### ISSUE TITLE
How can I subscribe a plan on a mobile phone?

### ISSUE THREAD

**Issue by c060604** [braintree/braintree_ios#315]
#### Developer Info

- Braintree SDK version: 4.7.5

- Integration type and version: CocoaPods 1.1.1

- Environment: Sandbox

#### Issue Details

How can I subscribe a plan on a mobile phone? I can't find any developer document about this.

**Comment by skunkworks** [comment]
Hi @c060604, it seems like you are looking to learn more about [recurring billing](https://developers.braintreepayments.com/guides/recurring-billing/overview).
