### ISSUE TITLE
Detect when 'Add Card' view controller opens so that status bar color can be changed

### ISSUE THREAD

**Issue by meismyles** [braintree/braintree_ios#316]
#### Developer Info

- Braintree SDK version: 4.7.5

- Integration type and version: N/A

- Environment: N/A (Both)

#### Issue Details
Currently, when the 'Add Card' view controller is presented when using the drop-in UI, there seems to be no way to detect that this has shown, and this means that if using the default light theme, if using a white status bar style, it cannot be seen since it blends in with the nav bar.

I know you also offer a dark theme but it seems like there should either be a way of being notified that the 'Add Card' flow has opened so we can change the status bar style ourselves manually, or in the drop-in framework, maybe in the `BTUIKAppearance` customisation options, an option should be given to set the status bar style.

Apologies if this should be posted within the [ios drop-in repo](https://github.com/braintree/braintree-ios-drop-in) instead. I can move it there if you prefer.

**Comment by demerino** [comment]
@meismyles Thanks for pointing this out. We'll look into the different options.

And yes, can you move this card over?

**Comment by meismyles** [comment]
_**Closing as moved to [braintree-ios-drop-in issue tracker](https://github.com/braintree/braintree-ios-drop-in/issues/27).**_
