### ISSUE TITLE
3DSecure web view completion functions may be called twice if there is an error

### ISSUE THREAD

**Issue by meismyles** [braintree/braintree_ios#318]
#### Developer Info

- Braintree SDK version: 4.7.5

- Integration type and version: N/A

- Environment: N/A

#### Issue Details
Please see [this comment](https://github.com/braintree/braintree-ios-drop-in/issues/26#issuecomment-287100427) for longer description.

Test card from Cardinal used to recreate this:
* **PAN:** 4000 0000 0000 0028
* **Expiry:** 01/20
* **CVV:** 111

**Comment by demerino** [comment]
@meismyles we're investigating this a bit more. Thanks for the report along with the other issues that have been raised.

**Comment by demerino** [comment]
Fixed in `4.8.0`. Thanks again for the bug report(s).
