### ISSUE TITLE
ApplePay payment networks hard coded in documentation - should they be?

### ISSUE THREAD

**Issue by meismyles** [braintree/braintree_ios#321]
#### Developer Info

- Braintree SDK version: 4.7.5

- Integration type and version: N/A

- Environment: Production

#### Issue Details
In the documentation, [here](https://developers.braintreepayments.com/guides/apple-pay/client-side/ios/v4#set-up-your-apple-pay-button), in the code block you pass in an array of payment networks:

```swift
PKPaymentAuthorizationViewController.canMakePayments(usingNetworks: [PKPaymentNetwork.visa, PKPaymentNetwork.masterCard, PKPaymentNetwork.amex])
```

This array seems hardcoded here, but in the SDK itself within the `JSON` configuration that is fetched, it actually contains the `PKPaymentNetwork`s that are supported by Braintree (maybe specifically for each merchant).

Within `BTConfiguration+ApplePay` there is a function:

```objc
- (NSArray<PKPaymentNetwork> *)applePaySupportedNetworks {
```

that extracts these networks. Should we not be using this supported list of networks to pass into the  `canMakePayments` function so that the ApplePay popup displays when networks aren't available, rather than possibly an error being returned from Braintree?

<br>

We have made a function currently that we are using to get this information ourselves:

```swift
func getBraintreeApplePaySupportedNetworks(completion: @escaping (_ supportedNetworks: [PKPaymentNetwork]?) -> ()) {
   self.braintreeClient?.fetchOrReturnRemoteConfiguration({ (configuration, error) in
        completion(configuration?.applePaySupportedNetworks)
    })
}
```

**Comment by skunkworks** [comment]
@meismyles You're 100% correct -- I've been working on updating the developer docs to reflect the preferred method of fetching the supported networks from Braintree configuration. Those should be coming soon.

**Comment by meismyles** [comment]
Hey, this issue has been closed, but I'm looking at the commit history on the Drop-in and it seems to have my commit in it that removes this check. [See here](https://github.com/braintree/braintree-ios-drop-in/commit/10c7f4c96fada1f238ccd5bc36e156643049031e).

I'm confused though as I don't think I submitted this in a pull request so not sure how it's in there?

Regardless, the documentation doesn't seem to have been updated to tell users to do this check manually yet? But the check has been removed from the Drop-in code base per my commit.

This is fine for me since I fetch the payment networks from the Braintree config JSON manually myself (as above) - but for other users it's now not being done at all?

**Comment by meismyles** [comment]
@demerino @skunkworks @sdcoffey

**Comment by demerino** [comment]
@meismyles Thanks for your concern.

Correct, we merged this change in. I believe it might have been merged in with your 3DS PR. The goal for `Drop-in + Apple Pay` is to display it as an option _only_ and rely on the merchant for executing on that choice. This is why we don't attempt to **tokenize** Apple Pay in Drop-in.

We'll continue working on the docs to make them as clear as possible.

**Comment by skunkworks** [comment]
@demerino Was it our intent to also drop the iOS platform to 8.3? See f86cd058a3b9a7622529d2bec4ecfd80c91115de

**Comment by meismyles** [comment]
Ok so long as you are aware that the user is now hard coding the supported Apple Pay payment networks and it will attempt to process a payment even if their chosen payment network is not in Braintree's supported payment networks list. I'm assuming Braintree will return an error at this point anyway?

With regards to the iOS platform version, I had to drop our fork to 8.3 (actually then further to 8.2) because it won't let you install the framework through CocoaPods at 9.0 unless your Podfile platform version is 9.0 or greater. However, since our app deployment target is 8.2, we need our Podfile platform version to be 8.2 or else all our other Pods are updated to versions that potentially don't support iOS 8.2. To then rectify any potential issues the Drop-in may have being installed in an app supporting 8.2, we do manual checks in our code and only show the Drop-in if the user is on 9.0 or greater. With all the fixes you guys have done recently this is now the only difference in our fork to the actual Braintree framework. I wonder if there is a solution that allows the Drop-in to be installed on < 9.0, with users performing the check ourselves so we can still install the Drop-in in apps supporting older versions?

**Comment by demerino** [comment]
@skunkworks No - we don't want to make that change at this time. It was reverted before the release: https://github.com/braintree/braintree-ios-drop-in/commit/ff3e27ca38607c9190f76f80521127fa9d221492

**Comment by demerino** [comment]
@meismyles I was wondering how you would use Drop-in on `<9.0`. This might be a reason to just drop it to `8.0` so that developers can do something similar (or leave it blank and make it clear in the docs). 

Hmmm....

Glad we've gotten most of the issues patched up for you. Keep the suggestions rolling in.

**Comment by meismyles** [comment]
We don't use it on < 9.0. We default to a web view based payments systen on < 9.0. But we still need it installed in case the customer is on 9.0 or greater. If platform version in your podspec is set to 9.0, we cant even install it, so we have to fork it and change it to our minimum required version.
