### ISSUE TITLE
Maestro not working

### ISSUE THREAD

**Issue by ir-fuel** [braintree/braintree_ios#322]
#### Developer Info
- Braintree SDK version: 4.7.4

- Integration type and version: CocoaPods 1.2.0

- Environment: Production

#### Issue Details

Maestro cards are not working in the Dropin UI. 

I type in the card number of a Belgian Maestro card (starting with 6703), tap "next" and I simply get "card not accepted"

![screen-shot-2017-03-28-at-11 09 36](https://cloud.githubusercontent.com/assets/1573715/24397645/36e7ac8c-13a7-11e7-855c-8a6225a67fc3.png)

Podfile:
```
    pod 'BraintreeDropIn'
    pod 'Braintree/PayPal'
```

Credit cards and Paypal work fine

**Comment by demerino** [comment]
@ir-fuel This looks like a bug. We're working on a release right now - we'll try to get this in there. Thanks for the feedback.

**Comment by demerino** [comment]
Update: https://github.com/braintree/braintree-ios-drop-in/pull/38 should fix the issue.

**Comment by ir-fuel** [comment]
Thanks! Any idea when I can get this fix through Cocoapods?

**Comment by demerino** [comment]
Hopefully by Friday. We're working on a few more features for the release.

**Comment by demerino** [comment]
Should be fixed in Drop-in `5.2.0`.
