### ISSUE TITLE
Warning: Non-portable path to file "BTAnalyticsMetaData.h"

### ISSUE THREAD

**Issue by apri22** [braintree/braintree_ios#324]
Xcode 8.3 introduces new warning checks, including nonportable-include-path which warns when imports use different case than the actual files.

This warning is triggered in the BTAnalyticsMetaData.h file:
```
BTAnalyticsMetadata.m:1:9: Non-portable path to file '"BTAnalyticsMetadata.h"'; specified path differs in case from file name on disk
```
in case from file name on disk
Looks like it's because the import of the header file uses a lowercase h, I'm assuming this fix is just:
```
-#import "BTAnalyticsMetaData.h"
+#import "BTAnalyticsMetadata.h"
```

another file have this problem too
```
-#import "BTDropinViewController.h"
+#import "BTDropInViewController.h"
```

**Comment by brunobar79** [comment]
In my case this is not a warning, It's an error:

<img width="470" alt="screen shot 2017-03-30 at 11 28 00 am" src="https://cloud.githubusercontent.com/assets/1247834/24512258/1625206a-153c-11e7-9acd-cc329f21b533.png">

So I can't build at all.   (and I've made sure that I have the setting "Treat errors as warnings: NO")

**Comment by intelliot** [comment]
Looks like this PR fixes the issue: https://github.com/braintree/braintree_ios/pull/323

**Comment by brunobar79** [comment]
@intelliot  Yeah, thanks. I've made those changes myself in the project in order to be able to build again.

**Comment by demerino** [comment]
This should be fixed on `master` (v4) now. We'll work on pushing out the `3.x` fix shortly.

**Comment by btelintelo** [comment]
Would love to see a fix for this soon in 3.x.  Causing some headaches

**Comment by demerino** [comment]
Working on this today (Monday). Thanks again for your patience on this.

**Comment by demerino** [comment]
`3.9.9` is now available with this fix.
