### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by kevinlee85** [braintree/braintree_ios#327]
### General information

* SDK/Library version: 4.8.0
* Environment: Sandbox
* iOS Version and Device:  iOS10.3
* Integration type and version: CocoaPods 1.2

### Issue description
My Xcode report one of documentation compile issue:
Under: BTUICardFormView.h
![screen shot 2017-04-05 at 11 33 57 am](https://cloud.githubusercontent.com/assets/6616311/24688643/cdaa820a-19f3-11e7-9de0-783754902942.png)

**Comment by demerino** [comment]
Thanks for the report. We'll use the `1.2.0` Cocoapods linter next time to resolve these issues.

**Comment by demerino** [comment]
`4.8.1` should resolve this.

**Comment by MrNoobody** [comment]
the sample issue was reproduced on  CocoaPods 1.2.1 and Library version: 4.8.1
![image](https://cloud.githubusercontent.com/assets/24671637/25481440/da9ef176-2b55-11e7-8d3b-01de5de3cf95.png)

**Comment by demerino** [comment]
These appear to be fixed in the most recent version of `braintree-ios-drop-in`: https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeUIKit/Public/BTUIKViewUtil.h#L54-L66
