### ISSUE TITLE
Empty Postal Code Has Validation Error

### ISSUE THREAD

**Issue by HaloZero** [braintree/braintree_ios#330]
### General information

* SDK/Library version: 4.7.5
* Environment: Production
* iOS Version and Device: All Devices
* Integration type and version: 4.7.5 through cocoapods

### Issue description

We've been discussing with Braintree Support and we've been getting a validation error from the server saying the Postal Code for BTCard cannot be an empty string. If this is the server behavior on Braintree's side, I'm hoping the client SDK behavior should reflect that change instead of us having to check that behavior. This behavior is already there for the Drop in UI Libraries apparently.

This conversation is happening in your support system with Ticket #1467489

**Comment by sdcoffey** [comment]
Hey @HaloZero,

Great catch. Although we think you're right, and that we should perform this validation client-side, we're concerned that it might be a breaking change. Additionally, this behavior differs from what our [Android SDK](https://github.com/braintree/braintree_android/blob/master/Braintree/src/main/java/com/braintreepayments/api/models/BaseCardBuilder.java#L193-L200) does.

We'll take another look at this when we do our next major version. Closing this issue for now.

**Comment by HaloZero** [comment]
@sdcoffey it seems the Android SDK does the behavior I was hoping to have. If the String is `""` it makes the postal code null.
