### ISSUE TITLE
Error in #import "BTAnalyticsMetaData.h" line

### ISSUE THREAD

**Issue by lotfyahmed** [braintree/braintree_ios#331]
### General information

* SDK/Library version: 4.7.4
* Environment: Sandbox
* iOS Version and Device: iOS 10.3
* Integration type and version: 1.2.0

### Issue description

After I installed "pod 'Braintree/PayPal'". I found an error in `"#import "BTAnalyticsMetaData.h" `line: non-portable path to file `'"BTAnalyticsMetadata.h"`'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]

![screen shot 2017-05-04 at 3 06 35 pm](https://cloud.githubusercontent.com/assets/3439991/25705088/4f8f1f48-30dc-11e7-9ef0-d0e6842480e2.png)

I thought we should update "BTAnalyticsMetaData" to be "BTAnalyticsMetadata"
I couldn't run my project now.

Thanks

**Comment by lkorth** [comment]
This [was fixed in 4.7.5](https://github.com/braintree/braintree_ios/blob/32b6b4e32bd2488533e104bbe4a1ff54164e3948/CHANGELOG.md#475-2017-02-22). Please upgrade to the latest version.
