### ISSUE TITLE
Payment using PayPal app

### ISSUE THREAD

**Issue by aimtechnology** [braintree/braintree_ios#333]
### General information

* SDK/Library version: 4.8.2
* Environment: Sandbox
* iOS Version and Device: iOS 10.2 on an iPhone 6
* Integration type and version: CocoaPods 1.2.1

### Issue description

We use the Braintree iOS SDK for payments via PayPal using Checkout flow with our custom button. We implement it as described [here](https://developers.braintreepayments.com/guides/paypal/checkout-with-paypal/ios/v4). We have installed on device PayPal application.
But when we call method:
 - (void)requestOneTimePayment:(BTPayPalRequest *)request completion:(void (^)(BTPayPalAccountNonce * _Nullable tokenizedPayPalAccount, NSError * _Nullable error))completionBlock ,

web-version of PayPal opens (in SFSafariViewController). Is it possible to make payment via PayPal application?
All API setting were made according to [this manual](https://developers.braintreepayments.com/guides/client-sdk/setup/ios/v4#register-a-url-type).
Installed PayPal app version is 6.11.0.

**Comment by demerino** [comment]
Hi @aimtechnology 

Currently, the Braintree SDK does not switch to the PayPal app. Let us know if you have any other questions.

**Comment by idave4u** [comment]
Hi @aimtechnology,

The documentation is really confusing because we have to insert in the info.plist the following lines, so we are expecting to launch the Paypal application.
```
<key>LSApplicationQueriesSchemes</key>
<array>
        <string>com.paypal.ppclient.touch.v1</string>
        <string>com.paypal.ppclient.touch.v2</string>
        <string>com.paypal.ppclient.touch.v3</string>
</array>
```
Maybe can you ask an update on this page: 
https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4

PS: I have lost hours trying to understand why the Paypal application wasn't launched ^^'

Best,

**Comment by demerino** [comment]
@idave4u Sorry to hear about the confusion regarding the expected behavior for PayPal. We're actively working to update that section of the documentation.

Let us know if you hit any other snags or have suggestions to improve the docs - we appreciate it.

**Comment by kamrankhan-chilindo** [comment]
Is the status changed on this or its still not supported?

**Comment by kamrankhan07** [comment]
Can anyone open the paypal app using this SDK? Its not working for me. I checked the code and it doesn't seem that its supported still, Venmo is the only one that seems to be supported now.

**Comment by aodhol** [comment]
@demerino this would be a great feature to support. The current SFSafariViewController mechanism is slow, laggy and bug prone. Opening the PayPal App on the other hand allows the user to use TouchID which is a big convenience..
