### ISSUE TITLE
Apple Pay Tokenization error

### ISSUE THREAD

**Issue by antons81** [braintree/braintree_ios#334]
### General information

* SDK/Library version: 4.8.3
* Environment: Sandbox
* iOS Version and Device: iOS 10.3 (Simulator)
* Integration type and version: Cocoapods 1.2.1

### Issue description

Hi, trying to implement payment tokenezation after I've touched on apple pay and getting error with getting token using BTApplePayClient

- (void)paymentAuthorizationViewController:(PKPaymentAuthorizationViewController *)controller
                       didAuthorizePayment:(PKPayment *)payment
                                completion:(void (^)(PKPaymentAuthorizationStatus status))completion {

  ```

self.braintree including BTAPIClient with my server app token
  BTApplePayClient * applePayClient = [[BTApplePayClient alloc] initWithAPIClient:self.braintree];

    [applePayClient tokenizeApplePayPayment:payment
                                 completion:^(BTApplePayCardNonce *tokenizedApplePayPayment,
                                              NSError *error) {
                                     
                                     if (error) {
                                         [error show]; // here is error (Apple pay description failed - no matching key found)
                                         completion(PKPaymentAuthorizationStatusFailure);
                                     }
       
                                    NSLog(@"nonce = %@", tokenizedApplePayPayment.nonce);
                                    completion(PKPaymentAuthorizationStatusSuccess);
                                     
    }];
```

**Comment by demerino** [comment]
Hi @antons81 

Can you verify that you've followed these steps when generating your Apple Pay Certificate (specifically the part about using Braintree's CSR)? 

https://developers.braintreepayments.com/guides/apple-pay/configuration/ios/v4#apple-pay-certificate-request-and-provisioning

Also, ensure that you're using this Apple Pay Merchant ID when creating your PKPaymentRequest: https://developers.braintreepayments.com/guides/apple-pay/client-side/ios/v4#create-a-pkpaymentrequest

If you're still having issues, let us know.

**Comment by antons81** [comment]
Hello, @demerino. Thanks for your answer. I'd like to inform you the issue has been solved by myself. There was some issue with generated token. Currently everything working as expected :). Thanks for your help.

**Comment by John-Xavier** [comment]
Hi, @antons81 , if you could explain how you fixed the issue, it will be helpful to every one. Thanks

**Comment by VishalS-avasoft** [comment]
@John-Xavier and @antons81 , Iam currently facing this same issue. It would be of great help if you can tell me the steps to fix this
