### ISSUE TITLE
Invalid address exception in KCollectorTaskBase

### ISSUE THREAD

**Issue by shlomnissan** [braintree/braintree_ios#335]
### General information

* SDK/Library version: 4.8.3
* Environment: Production
* iOS Version and Device: Any
* Integration type and version: CocoaPods 1.2.1

### Issue description

I'm getting an invalid address exception in KCollectorTaskBase. It seems like Kount have patched this in version 3.2 but Braintree SDK still running 3.1.

**Comment by demerino** [comment]
@shlomnissan Thanks for bringing this to our attention. We'll work on getting Kount updated to `3.2` in the next release.

**Comment by demerino** [comment]
Update: We're aiming to update this early next week.

**Comment by shlomnissan** [comment]
@demerino thanks for the update :)

**Comment by demerino** [comment]
Release `4.8.4` includes Kount 3.2. Let us know if you're still having issues.
