### ISSUE TITLE
Invalid bitcode version

### ISSUE THREAD

**Issue by timroesner** [braintree/braintree_ios#340]
### General information

* SDK/Library version: Xcode 8.2.1 Latest Braintree version
* Environment: Production
* iOS Version and Device: iOS target 9.0
* Integration type and version: CocoaPods

### Issue description

Trying to archive our project I get the following error: 
`Invalid bitcode version (Producer: '802.0.42.0_0' Reader: '800.0.42.1_0')`

I know this is because we are still using Xcode 8.2.1 (due to neglected Swift migration), my question to you is what is the latest Version of Braintree I can use that still supports Xcode 8.2.1, GitHub tag number is fine then I can pull it with CocoaPods

**Comment by demerino** [comment]
@timroesner Can you try `4.8.3`? I'm not sure which version is the highest version that should work in this case. But here are some suggestions:

- Which version of Cocoapods are you using? 1.3.0 was released today. Even if you're not using 1.3.0 - try an older version of Cocoapods.
- Xcode 8.2.1 was released on _December 19, 2016_, so try [4.7.4](https://github.com/braintree/braintree_ios/releases/tag/4.7.4)

Let us know if any of this helps.

**Comment by timroesner** [comment]
I tried 4.7.5 which seems to work, had to fix a couple of header bugs, but it compiled.

I'll try 4.8.3 and will update this if it works
