### ISSUE TITLE
Status Bar hardly visible - Drop In UI

### ISSUE THREAD

**Issue by timroesner** [braintree/braintree_ios#341]
### General information

* SDK/Library version: 4.7.2
* Environment: Sandbox
* iOS Version and Device: iOS 9.0+ iPhone 6s
* Integration type and version: CocoaPods 1.1.1

### Issue description

When using the Drop In UI the status bar is not visible because it is presented from a view where it is set to white. As you provide this view you should also make sure that the status bar is visible in your context as you can not expect that from the presenting view. This should be a quick fix.

**Comment by demerino** [comment]
@timroesner Thanks for bringing up this UI issue.

Could you share a screenshot? And is this for our new version of Drop-In located here: https://github.com/braintree/braintree-ios-drop-in

**Comment by timroesner** [comment]
Yes, no problem and yes it is, didn't find that repo at first, but if you like I can open it there to bring it to attention there as well.

![img_3522](https://user-images.githubusercontent.com/13894518/29301518-9338237a-8131-11e7-91d7-ebfc99ac395b.PNG)

**Comment by demerino** [comment]
We're looking into the issue of auto detecting and altering the `status bar style`.

In the meantime, you should manually change or hide the status bar when you show Drop-In _or_ you could use the dark theme (or create your own color scheme to match your app). Let me know if either of these options works for you while we investigate other solutions.

**Comment by timroesner** [comment]
Thank you for looking into it. 

I'll manually change the appearance for now, but it should really be handled by the view itself.
