### ISSUE TITLE
Fail to add Paypal as payment 

### ISSUE THREAD

**Issue by wengkeong94** [braintree/braintree_ios#342]
### General information

* SDK/Library version: <3.9.4>
* Environment: <Sandbox & Production>
* iOS Version and Device: <iOS 10.3.2, 10.3.3>
* Integration type and version: <Cocoapods>

### Issue description

I have created a method that executes this` [_provider createPaymentMethod:BTPaymentProviderTypePayPal];` where `_provider` is derived from `BTPaymentProvider`. So, my problem now is that once I typed my email and password for PayPal. It just stuck at the login PayPal page. And it calls the delegate of `- (void)paymentMethodCreator:(id)sender didFailWithError:(NSError *)error`. 

The error logs is written as:
`Error Domain=BTBraintreeAPIErrorDomain Code=0 "(null)" UserInfo={NSUnderlyingError=0x6000004464b0 {Error Domain=BTBraintreeAPIErrorDomain Code=2 "Invalid metadata.source value" UserInfo={error={
    message = "Invalid metadata.source value";
}, fieldErrors=(
), NSLocalizedDescription=Invalid metadata.source value}}}`

So, is there any way that this issue can be solved because previously this method works perfectly but now it keeps jumping into the failure delegate method. FYI, the `Braintree` version is 3.9.4 that I'm using.

**Comment by demerino** [comment]
Can you try now? An issue was impacting older iOS (3.x) clients on the backend.

**Comment by wengkeong94** [comment]
@demerino Thanks ! Its working fine right now :)
