### ISSUE TITLE
BTAppSwitchDelegate no longer necessary?

### ISSUE THREAD

**Issue by alper** [braintree/braintree_ios#343]
I'm following the documentation over here: https://developers.braintreepayments.com/guides/paypal/checkout-with-paypal/ios/v4

But it looks like I can do everything there without the BTAppSwitchDelegate? Things seem to work but I want to know if I'm not missing anything. I can't find much documentation on it either.

Can it be safely left out and should the documentation be changed to reflect that?

**Comment by skunkworks** [comment]
@alper You're not missing anything! `BTAppSwitchDelegate` is an optional delegate for receiving lifecycle notifications about the progress of PayPal payments, in case your app needs to update some UI in response. If you are already happy with the user experience as-is, then you can safely omit it.
