### ISSUE TITLE
Consider providing a universal iOS framework

### ISSUE THREAD

**Issue by gk-brown** [braintree/braintree_ios#346]
The Braintree iOS SDK is currently only available via Cocoapods and Carthage. This is inconvenient for projects that don't use a dependency manager. 

It would be ideal if you could include a pre-compiled universal framework with each release. An example of how to build such a framework can be found here:

https://gkbrown.org/2015/12/17/creating-a-universal-ios-framework-in-xcode-7/

I originally wrote the script for Xcode 7, but it works in Xcode 8 and 9 as well.

**Comment by demerino** [comment]
Thanks for the suggestion and the link. We've looked into this a few times, but we'll take it into consideration once more.

**Comment by demerino** [comment]
Closing for now, we will revisit this topic for our next major update.

**Comment by volcano619** [comment]
any update on this ??, would be deeply appreciated if you could provide this
