### ISSUE TITLE
Braintree paymentgetway canOpenURL failed

### ISSUE THREAD

**Issue by BRLOKESH** [braintree/braintree_ios#347]
My Project in Swift 3.1 
-canOpenURL: failed for URL: com.paypal.ppclient.touch.v1:// - error: The operation couldn’t be completed. (OSStatus error -10814.)
-canOpenURL: failed for URL: com.paypal.ppclient.touch.v2:// - error: The operation couldn’t be completed. (OSStatus error -10814.)
-canOpenURL: failed for URL: com.venmo.touch.v2://x-callback-url/vzero/auth - error: The operation couldn’t be completed. (OSStatus error -10814.)

**Comment by skunkworks** [comment]
Hi,

These debug console error warnings are expected and will not affect your app. They are from the Braintree SDK initialization as it determines whether PayPal or Venmo integrations are enabled for your app.
