### ISSUE TITLE
Xcode 9 & iOS 11 Main Thread Checker 

### ISSUE THREAD

**Issue by xuaninbox** [braintree/braintree_ios#350]
### General information

* SDK/Library version: 4.9.0
* Environment: Sandbox
* iOS Version and Device: iOS 11 on iPhone 7 Plus
* Integration type and version: CocoaPods

### Issue description

Got Main Thread Checker warning when jumping to venmo app.

--------------
Main Thread Checker: UI API called on a background thread: -[UIApplication backgroundTimeRemaining]
PID: 2548, TID: 779146, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   Braintree                           0x00000001040f54f0 __40-[PPRiskComponent appDidEnterBackground]_block_invoke.184 + 168
5   libdispatch.dylib                   0x0000000105f0d49c _dispatch_call_block_and_release + 24
6   libdispatch.dylib                   0x0000000105f0d45c _dispatch_client_callout + 16
7   libdispatch.dylib                   0x0000000105f1956c _dispatch_queue_override_invoke + 980
8   libdispatch.dylib                   0x0000000105f1eb54 _dispatch_root_queue_drain + 616
9   libdispatch.dylib                   0x0000000105f1e880 _dispatch_worker_thread3 + 136
10  libsystem_pthread.dylib             0x000000018085b130 _pthread_wqthread + 1268
11  libsystem_pthread.dylib             0x000000018085ac30 start_wqthread + 4

**Comment by bluk** [comment]
Thank you for reporting the issue. We hope to get a fix released as soon as possible.

**Comment by demerino** [comment]
Release 4.9.1 should resolve this issue. Let us know.

**Comment by crookedneighbor** [comment]
Gonna close this, but feel free to comment here if you're still having issues.
