### ISSUE TITLE
Venmo App switch returns error even when the user approved

### ISSUE THREAD

**Issue by vipinjohney** [braintree/braintree_ios#351]
* SDK/Library version: Braintree -4.9.0 and Braintree/Venmo
* Environment: Sandbox and Production 
* iOS Version and Device: iOS 10 iPhone 6
* Integration type and version:  CocoaPods 1.2.1

We use only the Venmo as our Payment option and hence use the app switch.

In iOS app integration to get the Venmo nounce, which is done using the app switch, when the user click “Allow” in Venmo app and the app switched back , we get this error “Failed to store Venmo Account in vault”. Can you tell me why I get this error ?

Even thought the app switched and returned the above mentioned error the Merchant gets added into Venmo. I can see the merchant in the Connected Merchants session in Venmo.

Please tell me if you need more inputs on this.

Here some portions of the code in Swift :
```
//Venmo integration
var venmoDriver : BTVenmoDriver?
var apiClient : BTAPIClient!
||
// Creating objects
self.apiClient = BTAPIClient(authorization: kBraintreeClientToken)
self.venmoDriver = BTVenmoDriver(apiClient: self.apiClient)
||
// App switch
self.venmoDriver?.authorizeAccountAndVault(true, completion: { (venmoAccount, error) in	
   if let err = error {	
        print(error!.localizedDescription)	//Here we get - Failed to store Venmo Account in vault	
   } else if !venmoAct.nonce.isEmpty {                         	
        self.sendToServer(strNonce: venmoAct.nonce)	
   }
})
```

**Comment by cbjoseph** [comment]
Vipin,
Looks like support got back to you on this. To provide clarity on this forum as well:

You'll want to see if you're setting self.venmoDriver?.authorizeAccountAndVault to `true` and not passing a customer ID into the client token. This will fail as it's looking for a customer to vault with. Instead, you'll want to pass the value as false and make sure to vault on the server-side.

**Comment by cbjoseph** [comment]
Vipin,

Looks like support got back to you on this. To provide clarity on this forum as well:

You'll want to see if you're setting self.venmoDriver?.authorizeAccountAndVault to `true` and not passing a customer ID into the client token. This will fail as it's looking for a customer to vault with. Instead, you'll want to pass the value as false and make sure to vault on the server-side.

**Comment by vipinjohney** [comment]
Yes, support team had replied on this and now its working fine.

Please close this issue.

**Comment by cbjoseph** [comment]
close 351
