### ISSUE TITLE
Not able to update Braintree to 4.9.x for PayPal from cocoapods (iOS)

### ISSUE THREAD

**Issue by ReddySanthosh** [braintree/braintree_ios#352]
Hi All,

Facing an issue for installing the latest version of Braintree(4.9.1).

When I do pod update from my project it installs Brain 4.7.5(which is my current version), I have tried the following commands from podfile.

1.  pod 'Braintree'

2. pod 'Braintree/PayPal'

Both the ways it is installing 4.7.5 not the latest 4.9.1

Need help to understand and resolve, please provide input.

PFA for reference 

<img width="591" alt="screen shot 2017-09-22 at 1 32 59 pm" src="https://user-images.githubusercontent.com/6426852/30735473-d432f47a-9f9c-11e7-84bb-fce08b46f3c3.png">

**Comment by bluk** [comment]
Have you tried running [`pod repo update`](https://guides.cocoapods.org/terminal/commands.html#pod_repo_update) to grab the latest specs locally? Then try the `pod update`.

**Comment by bluk** [comment]
If this is still an issue, please leave a comment, and we'll reopen. Thanks!
