### ISSUE TITLE
Can't build in XCode 9

### ISSUE THREAD

**Issue by ivanmkc** [braintree/braintree_ios#353]
### General information
I can't build BrainTree due to BTAPIClient.m

I searched online and found another person with this issue: https://stackoverflow.com/questions/46382149/braintree-error-with-xcode-9

* SDK/Library version: 4.9.1
* Environment: Both
* iOS Version and Device: Simulator iPhone 8.0
* Integration type and version: Cocoapods 1.4.0.beta.1

### Issue description
There is a build error in BTAPIClient.m.
Specifically: 
Object of type 'NSNumber *' is not compatible with dictionary value type 'NSString *'

<img width="1280" alt="screen shot 2017-09-25 at 11 55 51 am" src="https://user-images.githubusercontent.com/1586049/30818084-952b289e-a1e8-11e7-87a1-9eacc8541967.png">

**Comment by TheCodeBender** [comment]
Experiencing the same issue as well.

**Comment by demerino** [comment]
We have a fix for this coming out shortly.

**Comment by demerino** [comment]
Release `4.9.2` is now available - let us know if you're still having similar issues.

**Comment by mdelamata** [comment]
I was experimenting the same problem and after updating to `4.9.2` I am getting a new error.

![screen shot 2017-09-27 at 14 30 37](https://user-images.githubusercontent.com/1991706/30916124-7e65d0c4-a390-11e7-8f58-22c8b215fee8.png)

My deployment target is 9.0.

**Comment by bluk** [comment]
@mdelamata Thanks for the report. We will fix this.

**Comment by plevetsky** [comment]
I encountered the same as above with XCode 9.

After updating to 4.9.2 I also get this error:

![screen shot 2017-09-27 at 21 32 02](https://user-images.githubusercontent.com/1992329/30936310-5423428e-a3cb-11e7-93d4-333f84d7efe3.png)

**Comment by d4rkd3v1l** [comment]
@mdelamata Can you provide more information on how you did this in the post_install phase in the Podfile? I didn't get this flag applied for the Project (just for the Targets, which is meaningless).

**Comment by mdelamata** [comment]
Sure @d4rkd3v1l , I just I did this.

``` 
 post_install do |installer|
      installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                if target.name == "Braintree"
                  config.build_settings['CLANG_WARN_UNGUARDED_AVAILABILITY'] = 'NO'
                end
           end
      end
  end
```

**Comment by saudeonhonest** [comment]
@plevetsky I created a PR and issue for this! #356 and #357

**Comment by demerino** [comment]
These issues should be cleared up in `4.9.3`. Let us know if you're still having problems.

**Comment by demerino** [comment]
Closing - please reopen/create issue if you're still having problems. Thanks to everyone who pointed out these issues.
