### ISSUE TITLE
Dictionary value type error on Cocoapods build

### ISSUE THREAD

**Issue by jbelkins** [braintree/braintree_ios#354]
### General information

* SDK/Library version: 4.9.1
* Environment: All
* iOS Version and Device: iOS 11, Xcode 9.0
* Integration type and version: Cocoapods 1.4.0.beta.1

### Issue description

When building my app with Braintree integrated via Cocoapods, the following error is thrown:
```
(path omitted)/Pods/Braintree/BraintreeCore/BTAPIClient.m:190:45: error: object of type 'NSNumber *' is not compatible with dictionary value type 'NSString *' [-Werror,-Wobjc-literal-conversion]
             parameters:@{@"default_first": @(defaultFirst),
```

Looks like that parameter is declared to be of type `NSDictionary<NSString *, NSString *> *` here:
https://github.com/braintree/braintree_ios/blob/4.9.1/BraintreeCore/Public/BTAPIClient.h#L91

Thanks!  Let me know if you need more info.

**Comment by demerino** [comment]
We are working on a release to fix this. It should be coming out shortly.

**Comment by demerino** [comment]
`4.9.2` has been released with fixes for Xcode9. Let us know if you're still having problems.

**Comment by codeafterdark** [comment]
Sorry for the newbie question.  How do I update to 4.9.2 or 4.9.4 with cocoapods

**Comment by skunkworks** [comment]
@codeafterdark `pod 'Braintree', '4.9.4'` in your `Podfile`, then run `pod update`

**Comment by codeafterdark** [comment]
Thanks.. I was doing '~> 4.9.4'. and just realized I need to to a repro upgrade, sorry should have seen that first

**Comment by arvd** [comment]
I am still faching same issues in Xcode 9. I was do all the step but not working for me :(
