### ISSUE TITLE
Completion Never Called When Tokenizing a Credit Card on iOS 10

### ISSUE THREAD

**Issue by mattbanach** [braintree/braintree_ios#355]
### General information

* SDK/Library version: 4.9.0
* Environment: Sandbox and Production
* iOS Version and Device: iOS 10.3.3, All Devices
* Integration type and version: Carthage 0.25.0

### Issue description

When attempting to tokenize a credit card as follows...
```
 BTCardClient(apiClient: btAPIClient).tokenizeCard(card) { tokenizedCard, _ in
    completion(tokenizedCard?.nonce)
 }
```
without an internet connection, the completion block never gets called. We're only seeing this on iOS 10 devices. This is reproducible by either disconnecting from Wifi/Cellular, or by using the Network Link Conditioner set to 100% packet loss. We use the client side tokenization key method.

**Comment by demerino** [comment]
@mattbanach I used `Network Link Conditioner` and iOS 10.1 (Simulator). I received a callback after the default timeout of 60 seconds. Did you wait 60 seconds for the timeout? And does this occur on a simulator?

**Comment by mattbanach** [comment]
Hey! Thanks for the quick reply. Went ahead and double checked just now-- when the network is entirely unreachable _or_ we set the network link conditioner to 100% loss, we're not seeing the callback even after 60s. We've tried on a few devices, but not on a simulator.

**Comment by demerino** [comment]
Okay, we'll investigate on a device.

**Comment by MikeSilvis** [comment]
@demerino any update on this?

**Comment by bluk** [comment]
We have identified one possible issue and are working towards a fix.

**Comment by mattbanach** [comment]
@bluk just checking in-- can we expect a fix soon or should we consider building our own workaround?

**Comment by demerino** [comment]
@mattbanach We're planning a release this week 🤞 

Maybe we can push the branch public tomorrow and you can verify that it fixes your issue? Would that be something you'd be interested in verifying? If not, the fixes should be going out in the upcoming release.

Thanks again for your patience and for bringing this to our attention.

**Comment by demerino** [comment]
@mattbanach 

🎉  I just pushed the branch: https://github.com/braintree/braintree_ios/tree/timeout-ios10

You'll need to update your Carthage integration to point at the branch. Let us know if this solves the issue.

**Comment by mattbanach** [comment]
💥 Can confirm that the `timeout-ios10` branch resolves the issue. Thanks so much @demerino +  @bluk!

**Comment by demerino** [comment]
💯  Thanks @mattbanach 

We're preparing for the next release and this will be included.

**Comment by demerino** [comment]
@mattbanach `4.9.5` is out with the fix. Thanks for helping track this down and solve it.

🥇
