### ISSUE TITLE
BTConfiguration+ApplePay.m Compilation Issue

### ISSUE THREAD

**Issue by saudeonhonest** [braintree/braintree_ios#356]
### General information

* SDK/Library version: 4.9.2
* Environment: All
* iOS Version and Device: All
* Integration type and version: CocoaPods 1.3.1

### Issue description

When trying to compile v4.9.2 using Xcode 9, we are receiving the following error.
```
Comparison of address of 'PKPaymentNetworkDiscover' not equal to a null pointer is always true
```
**Line 39 of BTConfiguration+ApplePay.m**

We have the following rules in our Podfile post_install script specifically for Braintree.

```
target.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    config.build_settings['CLANG_WARN_UNGUARDED_AVAILABILITY'] = 'NO'
end
```

Unlocking the file and removing the check results in successful compilation.

**Comment by saudeonhonest** [comment]
Just submitted a pull request.

#357

**Comment by demerino** [comment]
Thanks for issuing the PR. This should be fixed in `4.9.3`.

**Comment by saudeonhonest** [comment]
Any idea on when we'll see ```4.9.3``` released?

**Comment by demerino** [comment]
https://github.com/braintree/braintree_ios/releases/tag/4.9.3
