### ISSUE TITLE
Xcode 9, NSNumber is not compatible with dictionary value type NSString

### ISSUE THREAD

**Issue by lucacasula91** [braintree/braintree_ios#360]
### General information

* SDK/Library version: 4.9.1
* iOS Version and Device: iOS 11 on iPhone 7
* Integration type and version: CocoaPods 1.3.1

### Issue description

After call pod update with Xcode 9 i get an error in BTAPIClient.m file at row 190.

<img width="1033" alt="screenshot 2017-10-02 17 20 51" src="https://user-images.githubusercontent.com/5367453/31084943-127c06da-a796-11e7-9830-4f87bdac8322.png">

**Comment by bluk** [comment]
For this specific issue, please see https://github.com/braintree/braintree_ios/issues/353 . In short, I think `pod repo update` and `pod update Braintree` should fix this with the 4.9.3 release.

**Comment by bluk** [comment]
If this issue isn't resolved with `4.9.3`, please leave a comment and we can re-open or open a new issue. Thanks.

**Comment by arvd** [comment]
I got same issues in XCode 9 and I also try this code
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                if target.name == "BraintreeSample"
                    config.build_settings['CLANG_WARN_UNGUARDED_AVAILABILITY'] = 'NO'
                end
            end
        end
    end

**Comment by bluk** [comment]
@arvd Can you please try running `pod repo update` and then `pod update Braintree` (or just `pod update`) to make sure you are using the latest release (4.9.4 currently)? You can check your `Podfile.lock` as a quick check to see that CocoaPods is using the right version.

**Comment by chandani412** [comment]
i am also facing this issue with xcode 9.1 and braintree 4.7.5
can't integrate braintree latest version
please help to resolve this issue

**Comment by demerino** [comment]
Can you share more info on what error you are experiencing when updating to the latest version? 

If you're still having issues you can try:
- Using the latest version of CocoaPods and Xcode
- Follow the directions above after updating (`pod repo update` and `pod update Braintree`)

**Comment by chandani412** [comment]
I have xcode9.1 and cocoapods 1.0 then which braintree version supports

And i can't update braintree it show error that git is down

**Comment by skunkworks** [comment]
@chandani412 Please open a separate issue and provide more details. Thanks.

**Comment by chandani412** [comment]
i can't update Braintree
 it show error like this

[!] CocoaPods could not find compatible versions for pod "Braintree":
  In Podfile:
    Braintree (~> 4.9.4)

None of your spec sources contain a spec satisfying the dependency: `Braintree (~> 4.9.4)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.


how can i use latest version of braintree?
`pod repo update` doesn't work
