### ISSUE TITLE
iOS11 does not respond to viewControllerPresentingDelegate

### ISSUE THREAD

**Issue by mengzhihoing** [braintree/braintree_ios#361]
### General information

* SDK/Library version: 4.9.2
* Environment:  Sandbox and Production
* iOS Version and Device: iphone8 plus
* Integration type and version: CocoaPods 1.3.1

### Issue description
Today I test iOS11,iOS9 and iOS10, iOS9 iOS10 work well, but iOS11 does not respond to :<pre>viewControllerPresentingDelegate</pre> The device and the simulator are all the same issue. detail: http://www.wenjian.ml/paypal.mov

Thx for your help!

**Comment by bluk** [comment]
As of version [4.9.0](https://github.com/braintree/braintree_ios/releases/tag/4.9.0), the SDK uses [SFAuthenticationSession](https://developer.apple.com/documentation/safariservices/sfauthenticationsession) for iOS 11 for PayPal payments. It is Apple's recommended 3rd party authentication flow. SFAuthenticationSession does not provide a view controller to present/dismiss, so the presentation delegate calls are not made. Hope that helps. If you have another question, feel free to leave a comment or open a new issue. Thanks.
