### ISSUE TITLE
BTPaymentSelectionViewController.m Block declaration is not a prototype

### ISSUE THREAD

**Issue by lucacasula91** [braintree/braintree_ios#362]
### General information

* SDK/Library version: 4.9.4
* iOS Version and Device: iOS 11 and iPhone 7
* Integration type and version: CocoaPods 1.3.1

### Issue description
After updated to Braintree 4.9.4 i can't build the project.

<img width="844" alt="screenshot 2017-10-03 12 59 21" src="https://user-images.githubusercontent.com/5367453/31122104-e38a2366-a83a-11e7-9c57-bd27834bfdef.png">

**Comment by bluk** [comment]
You will need to update the [BraintreeDropIn](https://github.com/braintree/braintree-ios-drop-in) CocoaPod. `pod repo update` and then `pod update BraintreeDropIn` should work. Version [5.2.3] of BraintreeDropIn (https://github.com/braintree/braintree-ios-drop-in/releases/tag/5.2.3) should have fixed this. If you still have an issue, please leave a comment and we can reopen, or open a new issue. Thanks.
