### ISSUE TITLE
No such module 'Braintree' 

### ISSUE THREAD

**Issue by AbhibusKiranYasala** [braintree/braintree_ios#363]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version: 

### Issue description

Steps we followed :
1) Install pod " pod 'Braintree' " 
2) We checked in pods folder 
3) Register a URL type as "com.Abhibus.abhibus1.payments" 

after the integration, we got the below errors when we are trying to run the app

4) No such module 'Braintree' 
5) framework not found  

Current Issues:

We are unable to integrate PayPal SDK in iOS because of the above issues mentioned, please find the screenshots attached.

![1 pod installaion terminal](https://user-images.githubusercontent.com/32484444/31126450-75b2cd00-a869-11e7-916f-35219c77b0dc.png)
![2 framework_not_showing_pods_folder](https://user-images.githubusercontent.com/32484444/31126455-764412b0-a869-11e7-9ae5-d6d673dc75ea.png)
![3 register a url type](https://user-images.githubusercontent.com/32484444/31126454-763e8ef8-a869-11e7-8803-915a2e5b562b.png)
![4 error_no_such_ module](https://user-images.githubusercontent.com/32484444/31126453-763d2e96-a869-11e7-8864-916be47a8db1.png)
![5 error_framework_not_found](https://user-images.githubusercontent.com/32484444/31126452-763ae9ec-a869-11e7-83a6-6ac5539f535a.png)

Could you please mention the process of integrating PayPal SDK Via Braintree using GitHub without any issue

**Comment by demerino** [comment]
Can you share your `Podfile`? I would recommend deleting your `/Pods` directory and doing a `pod update` to get the latest version of Braintree.

Then you can follow these directions to get setup: https://developers.braintreepayments.com/guides/client-sdk/setup/ios/v4

**Comment by AbhibusKiranYasala** [comment]
Hi,

Thank you for your reply.

Please find the attached pod file. We followed the steps from mentioned
link setup: https://developers.braintreepayments.com/guides/
client-sdk/setup/ios/v4 and we are unable to run the app after integration
due to getting errors. Could you please mention the steps to integrate
PayPal SDK Via Braintree.

**Comment by demerino** [comment]
Have you solved your problem? Those directions are correct. Ensure you're using the latest version of Xcode and Cocoapods.

**Comment by AbhibusKiranYasala** [comment]
Hi,

Thank you for your reply. Now the problem is solved after pod update

**Comment by demerino** [comment]
Great, closing the issue.

**Comment by aodhol** [comment]
Same problem here. BT 4.9.6, iOS 11. Min deployment target 10.3.x. Deleted Pods/ resinstalled. Same error: Cannot call value of non-function type 'module<Braintree>'

**Comment by RomeHein** [comment]
Not sure if it's the same issue. But when installing via cocoapod, the module can't be found. Even after deletion of pods, reinstall/update.
Braintree version 4.11.0
Xcode 9.2

**Comment by waris117** [comment]
Facing same issue, any one solved this?
framework not found Braintree

**Comment by NiteshSrivastav** [comment]
Hi can you please suggest me for Braintree integration without using pod in ios

**Comment by scannillo** [comment]
You can use either CocoaPods or Carthage to integrate the Braintree SDK into your app. Check out the resources under "Installation" here https://github.com/braintree/braintree_ios

**Comment by prasenraj** [comment]
# Includes Cards and PayPal
pod 'Braintree'


Xcode version 11.2
error :  ../Build/Products/Debug-iphoneos/Braintree.framework: No such file or directory

how to resolve this error

**Comment by Stewie-19** [comment]
pod 'Braintree'
Xcode : 11.5
Unable to Compile 
error: Build input file cannot be found: '.../Xcode/DerivedData/PayPalWithBrainTree-hiqukgqrgvyotkamtzdilsfvxtex/Build/Products/Debug-iphonesimulator/PayPalWithBrainTree.app/PayPalWithBrainTree' (in target 'PayPalWithBrainTree' from project 'PayPalWithBrainTree')

**Comment by sestevens** [comment]
@Stewie-19 This error sounds like an issue with your project not being able to find certain files, rather than an issue with the Braintree SDK. If you think this is a problem with the SDK, please open a new GitHub issue with more details (including steps to reproduce, if possible).
