### ISSUE TITLE
Invalid bitcode version (Producer: '802.0.42.0_0' Reader: '800.0.42.1_0')

### ISSUE THREAD

**Issue by ganjinni** [braintree/braintree_ios#365]
### General information
* SDK/Library version:  4.9.4
* Environment: Production 
* iOS Version and Device: iOS 11 on all iPhones 
* Integration type and version:  CocoaPods 1.1.1 

### Issue description

Despite changing the "Enable bitcode" settings to "No", keep encountering the error below when trying to archive so that the app can be submitted to app store.

error: Invalid bitcode version (Producer: '802.0.42.0_0' Reader: '800.0.42.1_0')
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please help, as the previous SDK version is causing the ios 11 users not able to make payment!
The latest SDK can work but can't upload to app store because of this bitcode issue.

**Comment by bluk** [comment]
@ganjinni Which version of Xcode are you using? You will need to use Xcode 8.3.3 or 9 to upload to the App Store.

**Comment by ganjinni** [comment]
Thanks bluk, issue is resolved now. Took so much effort to upgrade to MacOS 10.12.6 and then only able to update to Xcode 9...
