### ISSUE TITLE
SSL error with tokenizeApplePayPayment

### ISSUE THREAD

**Issue by mbarashkov** [braintree/braintree_ios#366]
### General information

* SDK/Library version: 4.9.4
* Environment: sandbox
* iOS Version and Device: ios 11.0.1 iPhone 6s+
* Integration type and version: CocoaPods 1.31

### Issue description

Calling [BTApplePayClient tokenizeApplePayPayment:payment] (as in the iOS client integration guide)
results in the following SSL error:

Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." 
UserInfo={_kCFStreamErrorCodeKey=-9836, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x6000004464b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9836, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9836}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://api.sandbox.braintreegateway.com:443/merchants/ckvnw9fdxhrpptdc/client_api/v1/payment_methods/apple_payment_tokens, NSErrorFailingURLStringKey=https://api.sandbox.braintreegateway.com:443/merchants/ckvnw9fdxhrpptdc/client_api/v1/payment_methods/apple_payment_tokens, _kCFStreamErrorDomainKey=3}

**Comment by bluk** [comment]
There was a temporary issue earlier with sandbox (and only sandbox). Please try again. If you encounter this issue again, please leave a comment and we can reopen.

**Comment by mbarashkov** [comment]
It works now, thanks.

**Comment by mbarashkov** [comment]
@bluk 
The error just reappeared

Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9836, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x608000452870 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9836, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9836}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://api.sandbox.braintreegateway.com:443/merchants/ckvnw9fdxhrpptdc/client_api/v1/payment_methods/apple_payment_tokens, NSErrorFailingURLStringKey=https://api.sandbox.braintreegateway.com:443/merchants/ckvnw9fdxhrpptdc/client_api/v1/payment_methods/apple_payment_tokens, _kCFStreamErrorDomainKey=3}

**Comment by mbarashkov** [comment]
This issue is constantly appearing and disappearing throughout the day, making it practically impossible to work with the Sandbox.

**Comment by bluk** [comment]
@mbarashkov There should have been no changes to the sandbox environment since my last message. I tested on a device and in a simulator and did not encounter any errors. If you used a different network, do you get any different results? Or are you using any sort of proxy or anything that is modifying the connection?

**Comment by mbarashkov** [comment]
No proxy.
Direct Internet connection.

21 окт. 2017 г. 7:09 PM пользователь "Bryant Luk" <notifications@github.com>
написал:

**Comment by Yotzee** [comment]
@bluk i am getting this issue again, and have been since friday 11/15/2019


`Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x60000059d950>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=(
    "<cert(0x7fc6a090d800) s: gateway-sand.sandbox.braintree-api.com i: DigiCert SHA2 High Assurance Server CA>",
    "<cert(0x7fc6a0847a00) s: DigiCert SHA2 High Assurance Server CA i: DigiCert High Assurance EV Root CA>"
), NSUnderlyingError=0x600003884840 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x60000059d950>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x7fc6a090d800) s: gateway-sand.sandbox.braintree-api.com i: DigiCert SHA2 High Assurance Server CA>",
    "<cert(0x7fc6a0847a00) s: DigiCert SHA2 High Assurance Server CA i: DigiCert High Assurance EV Root CA>"
)}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://gateway-sand.sandbox.braintree-api.com:443/merchants/rc8rswrnr2wmgnyc/client_api/v1/payment_methods/credit_cards, NSErrorFailingURLStringKey=https://gateway-sand.sandbox.braintree-api.com:443/merchants/rc8rswrnr2wmgnyc/client_api/v1/payment_methods/credit_cards, NSErrorClientCertificateStateKey=0}`

**Comment by devandanger** [comment]
@bluk We are experiencing errors with this again I think.

An SSL error has occurred and a secure connection to the server cannot be made., ,NSLocalizedDescription: An SSL error has occurred and a secure connection to the server cannot be made.,_kCFStreamErrorDomainKey: 3,NSErrorClientCertificateStateKey: 0,NSLocalizedRecoverySuggestion: Would you like to connect to the server anyway?,_kCFStreamErrorCodeKey: -9802,NSErrorPeerCertificateChainKey: ( "<cert(0x106238000) s: api.sandbox.braintreegateway.com i: DigiCert SHA2 High Assurance Server CA>", "<cert(0x106258200) s: DigiCert SHA2 High Assurance Server CA i: DigiCert High Assurance EV Root CA>" ),NSErrorFailingURLStringKey: https://api.sandbox.braintreegateway.com:443/merchants/kmz2j4q33htt5r2f/client_api/v1/payment_methods/apple_payment_tokens,NSUnderlyingError: Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x282f1afd0>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=( "<cert(0x106238000) s: api.sandbox.braintreegateway.com i: DigiCert SHA2 High Assurance Server CA>", "<cert(0x106258200) s: DigiCert SHA2 High Assurance Server CA i: DigiCert High Assurance EV Root CA>" )},NSErrorFailingURLKey: https://api.sandbox.braintreegateway.com:443/merchants/kmz2j4q33htt5r2f/client_api/v1/payment_methods/apple_payment_tokens,NSURLErrorFailingURLPeerTrustErrorKey: <SecTrustRef: 0x282f1afd0>
--

**Comment by scannillo** [comment]
Hi @devandanger, what version of the Braintree iOS SDK are you using?

**Comment by devandanger** [comment]
OK - we are at 4.8.5.  We are planning to update it next month though.  We haven't heard anything from our vendor support on moving this.  Can we please hold off until we can make the change and get some adoption in Production?

**Comment by scannillo** [comment]
You will be receiving email communications about this early next week if you have been impacted. It will have comprehensive timeline information. The long story short though - is you will need to update your integration if you are on 4.8.5.

I would suggest at least updating to 4.10.0 as soon as possible - until you are able to prioritize updating to the latest version. Seeing as 4.8.5 is almost 3 years old, we definitely suggest more frequent updates!

Stay on the lookout for that email early next week, and if you end up not getting it/ still have concerns, let me know.

**Comment by devandanger** [comment]
I agree we'll move it to our core libraries to keep a closer eye.  Since it's not a swift based library, it didn't come up in our last migration to Swift 5.1.  We do look for specific breaking changes especially in respect to Apple Pay changes.  We do attempt to look over the changelogs though and this doesn't really suggest anything associated to SSL certificates.  Can you explain what that update entails?

**Comment by scannillo** [comment]
@devandanger Our Support email that will come out to you early next week will do the best job giving you a thorough answer. So, look out for that! And then feel free to use the contacts it provides to answer further questions.

**Comment by raviprajapat1** [comment]
@demerino, @scannillo  I am also experiencing the same issue while tokenizing the credit card

SDK/Library version: 4.7.1
Environment: Production
iOS Version and Device: iOS 13.1 iPhone 7
Integration type: Manual integration

**Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9858, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x282b68d50 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9858, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9858}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://api.braintreegateway.com:443/merchants/jrsbgtbktxsfwvrq/client_api/v1/payment_methods/credit_cards, NSErrorFailingURLStringKey=https://api.braintreegateway.com:443/merchants/jrsbgtbktxsfwvrq/client_api/v1/payment_methods/credit_cards, _kCFStreamErrorDomainKey=3}**



```
[self.apiClient POST:@"v1/payment_methods/credit_cards"
              parameters:parameters
              completion:^(BTJSON *body, __unused NSHTTPURLResponse *response, NSError *error)
     {
         if (error != nil) {
             NSHTTPURLResponse *response = error.userInfo[BTHTTPURLResponseKey];
             NSError *callbackError = error;

             if (response.statusCode == 422) {
                 callbackError = [NSError errorWithDomain:BTCardClientErrorDomain
                                                     code:BTCardClientErrorTypeCustomerInputInvalid
                                                 userInfo:[self.class validationErrorUserInfo:error.userInfo]];
             }

             if (request.enrollmentID) {
                 [self sendUnionPayAnalyticsEvent:NO];
             } else {
                 [self sendAnalyticsEventWithSuccess:NO];
             }

             completionBlock(nil, callbackError);
             return;
         }
         
         BTJSON *cardJSON = body[@"creditCards"][0];

         if (request.enrollmentID) {
             [self sendUnionPayAnalyticsEvent:!cardJSON.isError];
         } else {
             [self sendAnalyticsEventWithSuccess:!cardJSON.isError];
         }

         // cardNonceWithJSON returns nil when cardJSON is nil, cardJSON.asError is nil when cardJSON is non-nil
         completionBlock([BTCardNonce cardNonceWithJSON:cardJSON], cardJSON.asError);
     }];
```

**Comment by scannillo** [comment]
@raviprajapat1, please see our official note on this in our docs - https://developers.braintreepayments.com/guides/client-sdk/setup/ios/v4#requirements.

You must upgrade to minimum v4.10.0, though more frequent updates are encouraged since 4.7.1 is ~4 years old.

**Comment by raviprajapat1** [comment]
Thanks @scannillo for clarifying things!

Just a question: If we upgrade with the latest Braintree SDK then we will able to use our existing 'Hosted Field' checkout flow?

**Comment by scannillo** [comment]
The JS SDK was not impacted by our SSL cutover. But regardless, it is always best to be on the most up-to-date version possible.

**Comment by harsh-bacancy** [comment]
@scannillo ,

I'm still facing issue
```Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9858, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x6000007dc510 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9858, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9858}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://api.braintreegateway.com:443/merchants/jbbx8249br69k8t5/client_api/v1/paypal_hermes/setup_billing_agreement, NSErrorFailingURLStringKey=https://api.braintreegateway.com:443/merchants/jbbx8249br69k8t5/client_api/v1/paypal_hermes/setup_billing_agreement, _kCFStreamErrorDomainKey=3}
```

As everyone facing above.
I am using the latest version of Braintree IOS SDK(4.34.0). Also all required versions of XCode and IOS. This issue occurs suddenly from last week, Before its working well.


I am using this package
[react-native-braintree-xplat](https://github.com/kraffslol/react-native-braintree-xplat)
to use all functionality of Braintree.

NOTE :: In this npm package there are the old version of the Braintree SDK, I have changed it to latest(4.34.0)

**Comment by sestevens** [comment]
Hi @harsh-bacancy, I'm unable to reproduce this issue on my end. Everything seems to be working OK. To the best of my knowledge, no changes were made regarding SSL certs since early June.

If you continue to experience this issue, I would recommend reaching out to our Support Team: https://help.braintreepayments.com/.
