### ISSUE TITLE
Invalid mastercard number starting with 2

### ISSUE THREAD

**Issue by veeamd** [braintree/braintree_ios#368]
### General information

* SDK/Library version: 4.9.1
* Environment: N/A
* iOS Version and Device: iOS 10
* Integration type and version: Carthage 0.26.2

### Issue description

When testing the `BTUICardFormView` on iOS devices, according to https://developers.braintreepayments.com/guides/credit-cards/testing-go-live/ruby#no-credit-card-errors, 2223000048400011 matercard number should be valid. But right after I entered the first 2, it gave me the red color treatment.
![image](https://user-images.githubusercontent.com/583443/32063648-bb607b98-ba45-11e7-9cd4-17232aa366af.png)

**Comment by demerino** [comment]
@veeamd 

Thank you for pointing this out. This old version of Drop-in is deprecated. Please use the new version of Drop-in located here: https://github.com/braintree/braintree-ios-drop-in

That card number (`2223000048400011`) should work correctly in the new version. Let us know if you run into any issues or if you still have questions.

**Comment by veeamd** [comment]
@demerino Thanks, Though the new drop-in won't work for our design.

**Comment by veeamd** [comment]
@demerino I found `BTCardFormViewController` https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeDropIn/Public/BTCardFormViewController.h.
This will work. Thanks again.
