### ISSUE TITLE
i am a learner, pls help how to run demo project?  i followed as readme mentioned, build is successful, but no app is being installed in my simulator.

### ISSUE THREAD

**Issue by dileepbolisetti** [braintree/braintree_ios#369]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version:

**Comment by bluk** [comment]
Have you selected the Demo target for the project to build in the upper left for Xcode?

<img width="347" alt="screen shot 2017-11-01 at 3 17 42 pm" src="https://user-images.githubusercontent.com/94150/32295671-f9941902-bf17-11e7-904c-852502584774.png">

**Comment by demerino** [comment]
@dileepbolisetti 

👍  Great that you're learning and trying Braintree! 

As @bluk suggested, ensure that you have the `Demo` selected and `run` the project. Simply `building` the project won't install it on the simulator. You can either press the `Play` (arrow) button to `run` the project or use the `COMMAND + R` keyboard shortcut.

Let us know if that works for you and feel free to ask any additional questions.

**Comment by dileepbolisetti** [comment]
hey, thanks for the support, now that i am able run both android and ios demo projects.
next stop is to build native bridges for react-native , ill be needing you guys help! once again thanks for the support.... (Y)

**Comment by wkwyatt** [comment]
Hey @dileepbolisetti, I had the same issue!  And any luck on the RN bridge yet??  I was about to work on the same thing.  Do you need any help?

**Comment by wkwyatt** [comment]
Oh yea @dileepbolisetti how did you get the demo to run, mine still isn't r

**Comment by dileepbolisetti** [comment]
@wkwyatt so far i am able to make a bridge in android, and ios both are working good, i am having problems with native ios writing modules to access the methods, reason is lack of knowledge in ios development. thats great, i can use some help regarding  ios native code to access these methods and get callbacks to js...

**Comment by wkwyatt** [comment]
@dileepbolisetti Cool, I can definitely handle the iOS part.

**Comment by dileepbolisetti** [comment]
super, i will create a repo with the progress till now, and i'll comment the link (y)

**Comment by wkwyatt** [comment]
Send me an email really quick
wkwyatt1@gmail.com

**Comment by dileepbolisetti** [comment]
https://github.com/dileepbolisetti/react-native-braintree-payments-test/ 
@wkwyatt
