### ISSUE TITLE
Row Height In Drop In Controller.

### ISSUE THREAD

**Issue by RexNexstream** [braintree/braintree_ios#370]
### General information

* SDK/Library version: Braintree 4.9.4
* Environment: Sandbox
* iOS Version and Device: iOS, Simulator iPhone 7 , xcode 9.1
* Integration type and version: CocoaPods 1.3.1

### Issue description

The payment method in DropInController is hard to tap due to the cell height. 
![screen shot 2017-11-02 at 4 31 39 pm](https://user-images.githubusercontent.com/12932221/32316601-e63ce972-bfeb-11e7-9103-28dea13f30fc.png)

How to increase the cell height?

**Comment by bluk** [comment]
Hello, version 5.2.1 of [iOS Drop-In](https://github.com/braintree/braintree-ios-drop-in/releases) had a few UI fixes so the payment methods weren't so close to one another. Can you please check if you're using the latest version of Drop-In? For CocoaPods, this might require a `pod repo update` and a `pod update BraintreeDropIn` or a general `pod update`.

**Comment by skunkworks** [comment]
@RexNexstream I'm closing this issue for now. If you continue to have UI problems after updating to the latest version of Braintree iOS Drop-in, please open an issue [here](https://github.com/braintree/braintree-ios-drop-in/issues). Thanks!
