### ISSUE TITLE
Hi,I use the brainTree iosv4 in my app,But I don't know how to display the paypal cell  in BTDropInController

### ISSUE THREAD

**Issue by CheungTieZhu** [braintree/braintree_ios#372]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version:

**Comment by demerino** [comment]
@CheungTieZhu 

It sounds like you are using our _new_ version of Drop-in: https://github.com/braintree/braintree-ios-drop-in

If you're using `cocoapods` for your integration, then you should just need to add the `PayPal` dependency to your `Podfile`.

```
pod 'BraintreeDropIn'
pod 'Braintree/PayPal'
```

Let us know if that works.
