### ISSUE TITLE
BTAppSwitchDelegate not working as intended?

### ISSUE THREAD

**Issue by hugobgranja** [braintree/braintree_ios#373]
### General information

* SDK/Library version: 4.9.6
* Environment: Sandbox and Production
* Integration type and version: CocoaPods 1.3.1

### Issue description

I'm trying to use BTAppSwitchDelegate to present/dismiss a loading indicator as per instructions [here](https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4) but in some devices the delegates aren't called at all, not even the BTViewControllerPresentingDelegate delegates are called.

Works in iPhone 5, 10.3.3
Does not work in iPhone 5S, 11.1.1 and iPhone 7 11.1.1

**Comment by demerino** [comment]
Which payment method are you testing with? BTAppSwitchDelegate won't be called when SFSafariViewController or AuthenticationSession are used (ex: PayPal on iOS 9 and up).

**Comment by hugobgranja** [comment]
I'm using Paypal as a payment method. If SFSafariViewController is used shouldn't the BTViewControllerPresentingDelegate delegates be called?

**Comment by demerino** [comment]
Sorry I was a bit confused, `BTViewControllerPresentingDelegate` should be called for <iOS11.

On iOS11 we use SFAuthenticationSession for PayPal which no longer requires the presentation delegate, that is handled by the OS.

**Comment by demerino** [comment]
We can look into a fix to add `BTAppSwitchDelegate` support to both `SFSafariViewController` and `SFAuthenticationSession`

**Comment by hugobgranja** [comment]
Alright, thank you for the info, In the end i solved my problem some other way.

**Comment by demerino** [comment]
🎉  Do you mind sharing your solution incase someone else has a similar question? I was going to suggest listening for a change to background/new view controller.

**Comment by hugobgranja** [comment]
Sure, what happened was that at first I was using an AlertController to display a progress dialog, but with Braintree and Paypal, i couldn't launch the SFSafariViewController if the main controller was already presenting the alert controller, so i decided to use a UIView for showing progress instead. With a UIView, for it to take the space of the whole screen i set it as a subview of UIApplication.shared.keyWindow, but like this it would show up on top of SFSafariViewController, if i could dismiss it and show it again when the safari view appears and disappears it would work but since there's no way of knowing that i had to make the UIView a subview of the current view, not the window, that also made it necessary for me to create another UIView as a subview to the navigation bar to dim it. That was it, now the safari view controller just shows on top of it and i don't even need to stop the progress dialog.

**Comment by demerino** [comment]
💯 Thanks for sharing!

**Comment by liamjdouglas** [comment]
Is the work still planned to have BTAppSwitchDelegate support both SFSafariViewController and SFAuthenticationSession?

**Comment by aodhol** [comment]
@hugobgranja What do you do if the user chooses not to 'Continue' on the UIAlertView that appears after tapping the PayPal button? i.e. there's no way of telling afaik that the user cancels, so the progress indicator would remain right?

**Comment by hugobgranja** [comment]
@aodhol 

``
payPalDriver.requestOneTimePayment(request) { (tokenizedPayPalAccount, error) in
            if let tokenizedPayPalAccount = tokenizedPayPalAccount {
                print("Got a nonce: \(tokenizedPayPalAccount.nonce)")

                // Access additional information
                let email = tokenizedPayPalAccount.email
                let firstName = tokenizedPayPalAccount.firstName
                let lastName = tokenizedPayPalAccount.lastName
                let phone = tokenizedPayPalAccount.phone

                // See BTPostalAddress.h for details
                let billingAddress = tokenizedPayPalAccount.billingAddress
                let shippingAddress = tokenizedPayPalAccount.shippingAddress
            } else if let error = error {
                // Handle error here...
            } else {
                // Buyer canceled payment approval
            }
}
``

**Comment by aodhol** [comment]
@hugobgranja this doesn't handle the delay between tapping the PayPal button and the SafariViewController appearing. I guess it's tolerable and we have no other choice anyway. Thanks!

**Comment by hugobgranja** [comment]
I made a custom loading view that is a subview to the controller which shows the SafariViewController, when the SafariViewController is shown it shows on top of that loading view so it's ok.
