### ISSUE TITLE
how to import BTUICardNumberField.h in my own class

### ISSUE THREAD

**Issue by smilydronavalli** [braintree/braintree_ios#376]
Hi

How to import BTUICardNumberField.h this class in my own class.Please suggest me how can you import that.

Thanks
smily

**Comment by demerino** [comment]
You'll want to use our new UI components located here: https://github.com/braintree/braintree-ios-drop-in

You can then develop your own card form. You can use the Drop-in card form to understand how to use the components: https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeDropIn/BTCardFormViewController.m
