### ISSUE TITLE
PayPol Disable option 

### ISSUE THREAD

**Issue by mohanrajmca** [braintree/braintree_ios#378]
How disable paypol  payment option in latest version in Ios Sdk

**Comment by demerino** [comment]
Disabling PayPal is applicable for Drop-in integrations: https://github.com/braintree/braintree-ios-drop-in

You can disable PayPal in Drop-in using this property: https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeDropIn/Public/BTDropInRequest.h#L40

If you're still having issue, you can create a new issue in the Drop-in repo.
