### ISSUE TITLE
Is it possible to retrieve saved/vaulted payment methods for a customer using custom UI (not the drop-in)?

### ISSUE THREAD

**Issue by meismyles** [braintree/braintree_ios#380]
Struggling to figure out if this is possible from the documentation and can't find a relevant function in the codebase at first glance.

Is it possible to retrieve saved/vaulted payment methods for a customer using a custom UI (not the drop-in)? If so, could you direct me to the relevant functions please.

Thanks!

**Comment by skunkworks** [comment]
Take a look at the [`fetchPaymentMethodNonces:`](https://github.com/braintree/braintree_ios/blob/master/BraintreeCore/Public/BTAPIClient.h#L67) method. You'll need to be using a client token with a customer ID for your authorization.

**Comment by demerino** [comment]
Reference to the suggested method: https://github.com/braintree/braintree_ios/blob/master/BraintreeCore/Public/BTAPIClient.h#L58-L67

**Comment by meismyles** [comment]
Hmm. I guess the 2 places we were looking were:

1. In the Client Token subsection of the Client Authorization section: https://developers.braintreepayments.com/guides/authorization/client-token

**Reasoning**
Since it uses the client token to retrieve the payment methods. In the Overview subsection of that same Client Authorization section it even implies this in the second bullet point - see here: https://developers.braintreepayments.com/guides/authorization/overview#types-of-authorization it says:
>A client token is a single use value that authorizes payment method tokenization, **payment method retrieval**, and client-side vaulting.
----

2. In the Client-side subsection of the Credit Cards section:
https://developers.braintreepayments.com/guides/credit-cards/client-side/ios/v4

**Reasoning**
Well I'd say this is just down to simple deduction. If a person wants to figure out how to retrieve stored credit card information, they are probably going to go to the credit card section of the documentation 😂. If the information is actually better suited to the Client Token area, then possibly this area should link back to there as well as it just seems logical that this where people are going to try first.
