### ISSUE TITLE
Test cards for CVV

### ISSUE THREAD

**Issue by Minishlink** [braintree/braintree_ios#382]
### General information

* SDK/Library version: v3 (using drop-in)
* Environment: Sandbox
* iOS Version and Device: *
* Integration type and version: *

### Issue description

Hello, do you have sandbox test cards for different test cases?
We found some buried in the [braintree_android](https://github.com/braintree/braintree_android/blob/44e20eed28af498e980202f9f12579911be6e249/TestUtils/src/main/java/com/braintreepayments/testutils/CardNumber.java) project, but there aren't any for wrong CVV. Also, will the SDK give an error if the user doesn't enter the correct CVV?

**Comment by bluk** [comment]
@Minishlink [This page](https://developers.braintreepayments.com/reference/general/testing/#credit-card-numbers) has various testing cards and other test data for sandbox. If you have any questions, feel free to contact [Braintree Support](https://developers.braintreepayments.com/forms/contact) or another issue.
