### ISSUE TITLE
Delegate method not invoked

### ISSUE THREAD

**Issue by aodhol** [braintree/braintree_ios#383]
### General information

* SDK/Library version: 4.10.0
* Environment: Sandbox
* iOS Version and Device: 11.2 iPhone 7 simulator / device.
* Integration type and version: Cocoapods 1.4.0 b2

### Issue description

Delegate methods not getting invoked even though the SafariViewController is shown and dismissed via the big blue button.

`
   
     func paypalButtonTapped(_ sender: UIButton) {

        guard let braintreeClient = braintreeClient else {
            return
        }
        
        let payPalDriver = BTPayPalDriver(apiClient: braintreeClient)
        payPalDriver.viewControllerPresentingDelegate = self
        payPalDriver.appSwitchDelegate = self
        let payPalRequest = BTPayPalRequest(amount: "29.99")
        payPalDriver.requestOneTimePayment(payPalRequest) { (tokenizedPayPalAccount, error) -> Void in
             // do stuff...
        }
     }
`

**Comment by demerino** [comment]
@aodhol 
See: https://github.com/braintree/braintree_ios/issues/361#issuecomment-333869471

On iOS11+ a [SFAuthenticationSession](https://developer.apple.com/documentation/safariservices/sfauthenticationsession) is used for PayPal payments and does not require the delegate methods for presentation/dismissal.

Let us know if you have additional questions or feedback.

**Comment by aodhol** [comment]
But delegation or some means of knowing the lifecycle stage is surely
needed to keep the UI in sync with what’s going on? I have a spinner on my
button for example, how would I know to remove it I’d say the user cancels?

**Comment by demerino** [comment]
@aodhol This makes sense. In this case, we would likely need to add a _new_ generic lifecycle event that isn't coupled to `app switching` or `presentation/dismissal`. We'll look into this.

**Comment by aodhol** [comment]
@demerino shall I leave this open then?

**Comment by demerino** [comment]
Yes, we appreciate the feedback!

**Comment by demerino** [comment]
@aodhol `4.14.0` has added new BTAppSwitchDelegate methods which should work across all possible app switch scenarios.

Switch: http://braintree.github.io/braintree_ios/Protocols/BTAppSwitchDelegate.html#/c:objc(pl)BTAppSwitchDelegate(im)appContextWillSwitch:

Return: http://braintree.github.io/braintree_ios/Protocols/BTAppSwitchDelegate.html#/c:objc(pl)BTAppSwitchDelegate(im)appContextDidReturn:

**Comment by aodhol** [comment]
@demerino I've tested this and can't get any of the delegate methods to trigger...

**Comment by ancafeurdean09** [comment]
@aodhol did you implement the BTAppSwitchDelegate? I tested myself and it works for me, both of the methods are getting called

**Comment by aodhol** [comment]
Yes, I did implement the delegate..

**Comment by ancafeurdean09** [comment]
I followed the steps described in here: https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4 when I first implemented this and now I just added those methods for testing purposes and I saw it's working fine, at least for me

**Comment by aodhol** [comment]
Yep, followed the exact same steps and none of the delegate methods get
invoked..

**Comment by demerino** [comment]
@ancafeurdean09 @aodhol Thanks for trying out the new methods.

I'm not sure why it isn't working for aodhol. Can you share the methods you implemented and the code snippet where you set the delegate?

**Comment by aodhol** [comment]
`func paypalButtonTapped(_ sender: UIButton) {

        guard let braintreeClient = braintreeClient else {
            return
        }

        let payPalDriver = BTPayPalDriver(apiClient: braintreeClient)
        payPalDriver.viewControllerPresentingDelegate = self
        payPalDriver.appSwitchDelegate = self
        let payPalRequest = BTPayPalRequest(amount: "\(ShoppingBag.sharedInstance.total)")
        payPalDriver.requestOneTimePayment(payPalRequest) { (tokenizedPayPalAccount, error) -> Void in
        
            if let error = error {
                self.showAlert(title: "Error", message: error.localizedDescription)
                Crashlytics.sharedInstance().recordError(error)
            }

            guard let tokenizedPayPalAccount = tokenizedPayPalAccount,
                let customer = Transaction.Customer.from(payPalAccountNonce: tokenizedPayPalAccount) else {
                    return
            }

            (sender as? LoadingButton)?.showSpinner()
            
            BraintreeUtils.postNonceToServer(transaction: transaction) { response, error in
                
                (sender as? LoadingButton)?.hideSpinner()
                
                // ....
            }
        }
    }`

**Comment by demerino** [comment]
I don't see the new _optional_ delegate methods: `appContextWillSwitch:` and `appContextDidReturn:`.

```
    func appContextWillSwitch(_ appSwitcher: Any) {
        print("appContextWillSwitch")
    }
.....
```

**Comment by aodhol** [comment]
@demerino that was the problem :[ Thanks, and sorry!
