### ISSUE TITLE
Swift 3 not working delegate 

### ISSUE THREAD

**Issue by ominfowaveIOS** [braintree/braintree_ios#385]
please see attach screenshots

we are added Braintree Paypal  checkout 
but Delegate not work in swift 3 
![screen shot 2018-01-29 at 4 19 20 pm](https://user-images.githubusercontent.com/24219479/35506810-a117d6d0-0510-11e8-8f42-fc1eadc8e960.png)

**Comment by demerino** [comment]
To clarify, you did add the two required delegate methods discussed in our docs?

https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4#implementing-delegate-protocols

```
// MARK: - BTViewControllerPresentingDelegate

func paymentDriver(_ driver: Any, requestsPresentationOf viewController: UIViewController) {
    present(viewController, animated: true, completion: nil)
}

func paymentDriver(_ driver: Any, requestsDismissalOf viewController: UIViewController) {
    viewController.dismiss(animated: true, completion: nil)
}
```

**Comment by ominfowaveIOS** [comment]
@demerino demerino thanks

**Comment by demerino** [comment]
Let us know if you have any other questions.
