### ISSUE TITLE
ApplePay and PayPal donations

### ISSUE THREAD

**Issue by AndreiBoariu** [braintree/braintree_ios#387]
Hey guys, 

Any way to implement paypal and applepay donations ?
We have a nonprofit organization in US, and from iOS app, we just want to enable donations via both services.

Any idea ? any help ?

Thank

**Comment by demerino** [comment]
ApplePay: Visit https://developer.apple.com/support/apple-pay-nonprofits/ and setup your organization. **"The only additional steps are to get your nonprofit organization approved to accept donations with Apple Pay and to use the "Donate with Apple Pay" button."**

PayPal: For PayPal donations, the recommendation is to use a website with the PayPal donations button ( https://www.paypal.com/us/webapps/mpp/donations and https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/donate_step_1/ ) in `SFSafariViewController`.

Let us know if you have more questions.

**Comment by crookedneighbor** [comment]
I'm going to close this, because I think your question has been answered. Feel free to comment here if you need further assistance.

**Comment by AndreiBoariu** [comment]
Thanks @demerino @crookedneighbor  for help!

We just got approval from PayPal for our nonprofit organization.
Trying to figure out next steps.

I will write in any case here.

Thanks
