### ISSUE TITLE
Pods/Braintree/BraintreeCore/BTAPIClient.m:251:22: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior

### ISSUE THREAD

**Issue by zerodiff** [braintree/braintree_ios#389]
### General information

* SDK/Library version: 4.10.1
* Environment: NA, compile problem
* iOS Version and Device: Minimum build target 9.0, iOS SDK 11.2
* Integration type and version: Cocoapods 1.4.0, 1.3.1

### Issue description

In BTAPIClient.m and the latest Xcode (and xcodebuild) Version 9.2 (9C40b), what was once a warning seems to now be a compile error for all properties in callbacks. These are lines 248 to 263:

```            } else {
                configuration = [[BTConfiguration alloc] initWithJSON:body];
                if (!_braintreeAPI) {
                    NSURL *apiURL = [configuration.json[@"braintreeApi"][@"url"] asURL];
                    NSString *accessToken = [configuration.json[@"braintreeApi"][@"accessToken"] asString];
                    _braintreeAPI = [[BTAPIHTTP alloc] initWithBaseURL:apiURL accessToken:accessToken];
                }
                if (!_http) {
                    NSURL *baseURL = [configuration.json[@"clientApiUrl"] asURL];
                    if (self.clientToken) {
                        _http = [[BTHTTP alloc] initWithBaseURL:baseURL authorizationFingerprint:self.clientToken.authorizationFingerprint];
                    } else if (self.tokenizationKey) {
                        _http = [[BTHTTP alloc] initWithBaseURL:baseURL tokenizationKey:self.tokenizationKey];
                    }
                }
            }
```

Compile errors are for the `_braintreeAPI` and `_http` variables. I think the easy solution is to replace with `self.braintreeAPI` and `self.http`, and if I do this it compiles and works.

The full compile error for each is `Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior`.

**Comment by bluk** [comment]
We are working on a fix. Thanks for the report.

**Comment by demerino** [comment]
@zerodiff `4.11.0` should fix this issue. Let us know if you still have problems.

**Comment by vlondon** [comment]
The same is in BTUIKCardNumberFormField textFieldDidEndEditing method in 4.13.0 version
<img width="1524" alt="screen shot 2018-03-28 at 10 58 09" src="https://user-images.githubusercontent.com/2144180/38022357-31216dd4-3277-11e8-8102-8c6949f726ad.png">

**Comment by wubingwell** [comment]
@demerino Where to get the 4.11.0?  The latest version is 4.10.0 in Cocoapods.
