### ISSUE TITLE
official support for react native/ionic

### ISSUE THREAD

**Issue by jamesdixon** [braintree/braintree_ios#390]
Hi, is there any official support for React Native and/or Ionic on the Braintree dev roadmap?

**Comment by jamesdixon** [comment]
@demerino what's the best way to collect feedback/gauge interest so this could make it onto the roadmap. There are loads of Ionic/React Native developers out there, so I can't imagine this wouldn't be wanted.

**Comment by skunkworks** [comment]
One of the avenues for us to gauge interest is via GitHub Issues like this. I'm going to leave this issue open for others to chime in on whether this is something the community wants.

**Comment by jamesdixon** [comment]
Thanks @skunkworks! Would it make sense to open a duplicate issue on the android repo just in case someone ends up there instead?

**Comment by mattbanach** [comment]
We'd love official support!

**Comment by sestevens** [comment]
Unfortunately, we don't have plans to add support for React Native/Ionic at this time, so we're going to close this issue for now.
