### ISSUE TITLE
Duplicate cards appearing in available card section

### ISSUE THREAD

**Issue by BMcS** [braintree/braintree_ios#391]
### General information

* SDK/Library version: pod 'BraintreeDropIn', '~> 5.3'
* Environment: Production
* iOS Version and Device: iOS 11.3
* Integration type and version: CocoaPods 1.3.1

### Issue description

When displaying the dropin UI for braintree, multiple instances of the same credit card are displayed. In the attached example, two for master card, two for Visa. Both should only appear once.

![img_119449105567-1](https://user-images.githubusercontent.com/5587582/36753050-34c5fa98-1bc2-11e8-957e-c00e7c25fd75.jpeg)

**Comment by demerino** [comment]
This should be fixed in Drop-in [6.1.0](https://github.com/braintree/braintree-ios-drop-in/releases/tag/6.1.0).
