### ISSUE TITLE
No Payment Option After Passing ClientToken to BTDropInController in iOS.

### ISSUE THREAD

**Issue by glennposadas** [braintree/braintree_ios#393]
### General information

* SDK/Library version: **4.12.0**
* Environment: Sandbox
* iOS Version and Device: iOS 11.x (iPhone X Simulator and iPhone 7 plus real device)
* Integration type and version: Cocoapods 

Hi,

1, I get no Payment Option after passing `clientToken` to BTDropInController in iOS.

2. **BUT** when I do hardcode the `clientToken` and that `clientToken` is from your Hello-Client sample (https://developers.braintreepayments.com/start/hello-client/ios/v4), there is a payment method on the DropIn.

3. When hardcoding the `clientToken` generated from our server using Postman, it does not work as well.

4. When I generated a `clientToken` from our server using the iOS app without passing it to the BTDropInController` yet, and share that to my colleague (Android Developer), his Android app shows up the Payment option which is PayPal.

Here's my simple code.

```
private func showBraintreeDropInWithToken(_ clientToken: String, subscription: Subscription) {
        let request = BTDropInRequest()
        let dropIn = BTDropInController(authorization: clientToken, request: request) { (controller, result, error) in
            if let error = error {
                self.showAlert("Payment gateway request failed. \(error.localizedDescription)", withCallBack: {
                    controller.dismiss()
                })
                return
            }
            
            if let result = result {
                if result.isCancelled {
                    controller.dismiss()
                    return
                }
                // Use the BTDropInResult properties to update your UI
                // result.paymentOptionType
                // result.paymentMethod
                // result.paymentIcon
                // result.paymentDescription
            }
        }
        
        self.tabBarController?.present(dropIn!, animated: true, completion: nil)
    }
```

**Comment by demerino** [comment]
@glennposadas Client tokens can be generated with (or without) a `customer_id`.
- With a customer: Will vault the payment methods to be reused later
- Without a customer: Will not include previously tokenized payment methods

See the docs to reference how to create a client token with a customer: https://developers.braintreepayments.com/reference/request/client-token/generate/ruby#customer_id

Let me know if that information helps.

**Comment by demerino** [comment]
Also, can you make sure you've pulled in the `PayPal` dependency in your Podfile. https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/ios/v4#cocoapods

`pod 'Braintree/PayPal'`

**Comment by glennposadas** [comment]
OMG! Haha! Adding ```pod 'Braintree/PayPal'``` worked. It's sad cause I spent many hours last Friday figuring this problem out 😢.  THANK YOU SO MUCH! How I wish you had a time to reply much much earlier :D

**Comment by demerino** [comment]
@glennposadas Glad it worked. Let us know if there is anything we can do to make it clearer in the [docs](https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/ios/v4#cocoapods).
