### ISSUE TITLE
Date and Cvv field cuts down in DropinUi

### ISSUE THREAD

**Issue by umairqureshi6** [braintree/braintree_ios#394]
### General information

* SDK/Library version: Braintree DropinUI version 6.1.0
* Environment: Sandbox
* iOS Version and Device: iOS 11.2.6 on iPhone 6 or iPhone 6s Plus Simulator
* Integration type and version: Cocoapod 1.4.0

### Issue description
i am intregating braintree dropinUi, when asking user for credit card information, date and cvv field ui is not showing properly
can be seen in the attached image

![simulator screen shot - iphone 6s plus - 2018-03-19 at 11 40 03](https://user-images.githubusercontent.com/1284455/37582161-60c4ac42-2b6d-11e8-86c5-75bd9a29d15e.png)

**Comment by demerino** [comment]
@umairqureshi6 I was unable to recreate the issue running `iOS 11.2` using the `iPhone 6s Plus Simulator`. See my attached screenshot.

Does this issue appear on other simulators and iOS versions as well? Is there any other information you can share and are you customizing and of the fonts/colors?

![simulator screen shot - iphone 6s plus - 2018-03-19 at 09 40 40](https://user-images.githubusercontent.com/7817434/37609705-0bc20a58-2b5b-11e8-95f9-4e59c994ffbc.png)

**Comment by demerino** [comment]
Closing, create a new issue here if you're still having problems: https://github.com/braintree/braintree-ios-drop-in/issues
