### ISSUE TITLE
ios paypal 

### ISSUE THREAD

**Issue by daisys77** [braintree/braintree_ios#397]
i am trying to create ios app with paypal store page. my problem is i can not get the generated item button take me to the paypal page. my code works fine on android and browser. can i show you my code hwlp me fix this page.

**Comment by demerino** [comment]
@daisys77 I'm not sure what you're exact issue is. Only Drop-in will generate the button for you. For a custom integration when you make your own button and add a handler to start the flow you can review the guide: https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4

Feel free to share your relevant code snippets if you're still having issues. Happy to answer any other questions.

**Comment by daisys77** [comment]
I am creating query mobile app using 1 page html method. I upload some of my PayPal store code. The web browser version works. But only need now to create the iOS app version. I tried the app on my iPhone and emulator, the button don’t take me to PayPal they are not functioning.

Thank you

Zara 
https://codepen.io/taz23212/pen/jzpGep

**Comment by daisys77** [comment]
Hi I managed to fix the code to get the buttons to work. I have different issue when I remove a item from the basket, it tells me to continue shopping. When I click the button takes me to paypal page and also another issue my view cart doesn’t work takes me to my home page. Can you please help me fix these issues.

Thank you
Kaz

**Comment by demerino** [comment]
Let us know if you're still having issues. If you are, please share your Braintree iOS related code snippets.
