### ISSUE TITLE
iOS Paypal Braintree

### ISSUE THREAD

**Issue by umair2ooo** [braintree/braintree_ios#399]
iOS paypal braintree taking too much time when tap on paypal button in Dropin UI, and after payment back on checkout screen, also taking too much time.
How can I fix this ?

**Comment by demerino** [comment]
@umair2ooo Which version of Drop-in are you using and what what environment do you see the issue in? Once we have additional info we can look into this issue more.

**Comment by crookedneighbor** [comment]
@umair2ooo Going to close this from inactivity, but please comment here if you still need assistance and we'll re-open it.
