### ISSUE TITLE
download project and fail to run

### ISSUE THREAD

**Issue by yellowTiger** [braintree/braintree_ios#402]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version: 

### Issue description

download project and it can't work .
Otherwise ,It is too slow  for me to git clone the project

**Comment by crookedneighbor** [comment]
Please reach out to our support team with the details about your integration. We'll need more information about how you are downloading and what is not working.

https://articles.braintreepayments.com/forms/contact
