### ISSUE TITLE
Wait long time to display the PayPal Page?

### ISSUE THREAD

**Issue by kevinlee85** [braintree/braintree_ios#404]
### General information

* SDK/Library version: 4.15.0
* Environment: Sandbox
* iOS Version and Device: iOS10.4
* Integration type and version: CocoaPods 1.1.1,
### Issue description

I am using Braintree to trigger PayPal payment.
let payPalDriver = BTPayPalDriver(apiClient: strongBraintreeClient)
        payPalDriver.viewControllerPresentingDelegate = self
        payPalDriver.appSwitchDelegate = self
        
        // Specify the transaction amount here. "2.32" is used in this example.
        let request = BTPayPalRequest(amount: "\(money)")
        request.currencyCode = "USD"
        
        payPalDriver.requestOneTimePayment(request) 
...

Above code will be called after I press my customed PayPal button.

But I need to wait some seconds to show up the PayPal SaferViewController.

Do you know how to make it response quickly?

Or I have tried appSwitchDelegate, but it now is called at all.

Thank you in advance.

**Comment by demerino** [comment]
Does this issue occur on all networks for you and your customers? 

The average delay when setting up the PayPal flow is around ~2 seconds. How long are the delays that you are experiencing?

**Comment by kevinlee85** [comment]
Yes. Almost 2 seconds. What delay should have one progress loading prompt.

**Comment by kaiserabliz** [comment]
I am experiencing the same issue, I thought it is the simulator but when I test on my device still there is a delay, a visual feedback would be nice. Thanks. By the way, I am having this issue with the paypal button came with BraintreeDropIn view.

**Comment by demerino** [comment]
@kaiserabliz We can look into some visual feedback for the Drop-in solution. For custom solutions, the feedback would be up to the merchant. In that case, my suggestion would be to show a spinner just before starting the PayPal flow and stopping the spinner when the `appContextWillSwitch` delegate method is called (or an error is received in the callback). https://github.com/braintree/braintree_ios/blob/master/BraintreeCore/Public/BTAppSwitch.h#L103

**Comment by kaiserabliz** [comment]
Thanks for the response @demerino. How do I detect Paypal button click on BTDropin view to trigger my spinner? Is there any notification I should observe?  I checked documentations but did not spot anything regarding this. 
Thanks in advance.

**Comment by brendan-p** [comment]
Hello, are there any updates regarding a visual feedback when launching PayPal from the DropIn UI? On rare occasions in can take up to ~10 seconds, and a non-blocking UI can create problems with users during the wait. 
Thanks.

**Comment by kaiserabliz** [comment]
Hi @brendan-p, for this issue @demerino suggested to show a spinner but in order trigger this spinner we need to somehow detect if user triggers PayPal flow in BTDrop-in which we can't know as far as I know. I am still waiting.
Thanks.

**Comment by demerino** [comment]
Ah, in the Drop-in case you're correct that the event isn't available. We'll look into a way to bubble up the events when showing and hiding the PayPal SFViewController.

**Comment by scannillo** [comment]
Hi - in [Braintree Drop-In v8.1.1](https://github.com/braintree/braintree-ios-drop-in/blob/master/CHANGELOG.md#811-2020-07-14), we added an activity indicator (spinner) to show the loading of PayPal, Venmo, and 3DS flows.
