### ISSUE TITLE
Value of type 'ClassNameHere' has no member 'apiClient'

### ISSUE THREAD

**Issue by connorcowling** [braintree/braintree_ios#406]
### General information

* SDK/Library version: 4.16
* Environment: Sandbox
* iOS Version and Device: iOS 11.4 on an iPhone 8 -->
* Integration type and version: CocoaPods

Code as per website docs:

`
    import BraintreeDropIn 
    import Braintree

    class NewCheckout: BTViewControllerPresentingDelegate {

     func paymentDriver(_ driver: Any, requestsPresentationOf viewController: UIViewController) {
         present(viewController, animated: true, completion: nil)
     }

     func paymentDriver(_ driver: Any, requestsDismissalOf viewController: UIViewController) {
         dismiss(animated: true, completion: nil)
     }

     func setupPaymentFlowDriver() {
        self.paymentFlowDriver = BTPaymentFlowDriver(apiClient: self.apiClient)
         self.paymentFlowDriver.viewControllerPresentingDelegate = self
     }

    }
`
 

    

**_Error : Value of type 'NewCheckout' has no member 'apiClient'_**

**Comment by demerino** [comment]
You'll need to create a `self.apiClient` first. It doesn't _need_ to be a class property. Try something like this:

```
 func setupPaymentFlowDriver() {
    let apiClient = BTAPIClient(authorization: "<#CLIENT_AUTHORIZATION#>")
    self.paymentFlowDriver = BTPaymentFlowDriver(apiClient: apiClient)
    self.paymentFlowDriver.viewControllerPresentingDelegate = self
 }
```

Then you can
