### ISSUE TITLE
Use of unresolved identifier 'Braintree'

### ISSUE THREAD

**Issue by miteshkhatri** [braintree/braintree_ios#408]
Hi,

I am using the braintree using the cocoapods in my swift ios application. I successfully installed the braintree in my ios app. my pod file structure is:

```
target 'appName' do
 pod 'GoogleMaps'
  pod 'GooglePlaces'
#  use_frameworks!

  pod 'AFNetworking', '~> 2.6.0'
  pod 'CardIO'
  pod 'NSURL+QueryDictionary', '~> 1.0'
  pod 'PureLayout'
  pod 'FLEX'
  pod 'InAppSettingsKit'
  pod 'iOS-Slide-Menu'
  
#  pod "BraintreeDropIn", :path => "./"

#  pod 'Braintree/Apple-Pay'
  pod 'Braintree/PayPal'
#  pod 'Braintree/Venmo'

end
```

I added below header file in bridge file:

```
#import "BraintreeCore.h"
#import "BraintreePayPal.h"
#import "Braintree.h"

```
Now when I try to use in my code it says 
` Braintree.setReturnURLScheme("com.your-company.Your-App.payments")`
> Use of unresolved identifier 'Braintree'

So please suggest.

**Comment by skunkworks** [comment]
You have a mix of v3 and v4 SDK code here.

Please import `Braintree/Core` and `Braintree/PayPal` in your Podfile:

```
pod 'Braintree/Core'
pod 'Braintree/PayPal'
```

and the correct call is `BTAppSwitch.setReturnURLScheme()`

Please see the documentation [here](https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4)
