### ISSUE TITLE
Last payment method not showing

### ISSUE THREAD

**Issue by driveweyus** [braintree/braintree_ios#409]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version: 

### Issue description

Hello there,

I have tried everything possible i can find online on how to get last payment method to show up on the drop in ui and it still isn't working. Please help.

**Comment by skunkworks** [comment]
Hi,

Please open up a ticket under the [Braintree iOS Drop In](https://github.com/braintree/braintree-ios-drop-in) repo.

In the meantime, please verify that you're using a client token to authorize with Braintree, and make sure that the client token is generated with a customer ID. Thanks!
