### ISSUE TITLE
Braintree Production Error: This merchant account is not permitted to create Merchant Initiated Billing Agreement.

### ISSUE THREAD

**Issue by dipayan92Innofied** [braintree/braintree_ios#410]
### General information

* SDK/Library version: 4.15.0
* Environment: Production
* iOS Version and Device: iOS 11 , iPhone 6
* Integration type and version: CocoaPods

### Issue description

<
BrainTree Production Error: This merchant account is not permitted to create Merchant Initiated Billing Agreement.
I am using Braintree iOS Pod.We have customized PayPal button and it was working fine with Sandbox key but this problem is occurring with Production key.If you want I can provide you with these keys further.I am also sending you the code snippet and the error Message as well.The code was used to open the PayPal page from where a token will be generated to make the payment.

 let braintreeClient = BTAPIClient(authorization: BrtaintreeConstants.production.tokenizationKey)!
    let payPalDriver = BTPayPalDriver(apiClient: braintreeClient)
    payPalDriver.viewControllerPresentingDelegate = self
    payPalDriver.appSwitchDelegate = self
    
    // ...start the Checkout flow
    startActivityLoader(viewController: self)
    guard let amount = amount else {return}
    let payPalRequest = BTPayPalRequest(amount: String(amount))
    startActivityLoader(viewController: self)
    
    payPalDriver.requestBillingAgreement(payPalRequest) { (tokenizedPayPalAccount, error) in
      self.stopActivityLoader(viewController: self)
      if error == nil{
        if let email = tokenizedPayPalAccount?.email , let type = tokenizedPayPalAccount?.type , let nonce = tokenizedPayPalAccount?.nonce{
          let payPalModel = PayPalModel(with: email, type: type, nonce: nonce)
          self.performSegue(withIdentifier: PaymentMethodsVCSegues.paymentVC.rawValue, sender: payPalModel)
        }
      }else{
        self.showAlert(withMessage: (error?.localizedDescription)!)
      } 

<================================Error=========================================>

Error Domain=com.braintreepayments.BTHTTPErrorDomain Code=2 "client error" UserInfo={com.braintreepayments.BTHTTPURLResponseKey=<NSHTTPURLResponse: 0x10cbb0450> { URL: https://api.braintreegateway.com:443/merchants/gn6w34nrwjvgd5w5/client_api/v1/paypal_hermes/setup_billing_agreement } { Status Code: 422, Headers {
    "Cache-Control" =     (
        "no-cache"
    );
    "Content-Encoding" =     (
        gzip
    );
    "Content-Security-Policy" =     (
        "frame-ancestors 'self'"
    );
    "Content-Type" =     (
        "application/json; charset=utf-8"
    );
    Date =     (
        "Tue, 17 Jul 2018 11:58:31 GMT"
    );
    "Strict-Transport-Security" =     (
        "max-age=31536000; includeSubDomains"
    );
    "Transfer-Encoding" =     (
        Identity
    );
    Vary =     (
        "Accept-Encoding, Origin"
    );
    "X-BroxyId" =     (
        "02-1531828709.337-110.225.25.219-226752853"
    );
    "X-Content-Type-Options" =     (
        nosniff
    );
    "X-Frame-Options" =     (
        SAMEORIGIN
    );
    "X-Request-Id" =     (
        "02-1531828709.337-110.225.25.219-226752853"
    );
    "X-Runtime" =     (
        "1.237271"
    );
    "X-XSS-Protection" =     (
        "1; mode=block"
    );
} }, NSLocalizedFailureReason=client error, com.braintreepayments.BTHTTPJSONResponseBodyKey=<BTJSON:0x10d0c03e0 value:{
    error =     {
        debugId = c87bf69f3bef;
        errorMessage = "Authorization error --- REFUSED_MARK_REF_TXN_NOT_ENABLED:This merchant account is not permitted to create Merchant Initiated Billing Agreement";
        errorName = "AUTHORIZATION_ERROR";
        paypalHttpStatus = 403;
    };
}>}

>

**Comment by crookedneighbor** [comment]
Looks like your PayPal account is not setup to create billing agreements. Please [contact our support team for help setting this up](https://articles.braintreepayments.com/forms/contact).
