### ISSUE TITLE
"BraintreeCore.h" not found

### ISSUE THREAD

**Issue by williamli** [braintree/braintree_ios#414]
### General information

* SDK/Library version: 4.17.0
* Environment: NA
* iOS Version and Device: iOS11
* Integration type and version: Carthage 0.30.1

### Issue description

I followed the Carthage installation mentioned in the README file.

> Add github "braintree/braintree_ios" to your Cartfile

and then I

If you're building for iOS, tvOS, or watchOS

1. Create a Cartfile that lists the frameworks you’d like to use in your project.

2. Run carthage update. This will fetch dependencies into a Carthage/Checkouts folder, then build each one or download a pre-compiled framework.

3. On your application targets’ General settings tab, in the “Linked Frameworks and Libraries” section, drag and drop each framework you want to use from the Carthage/Build folder on disk.

![screen shot 2018-08-22 at 08 22 32](https://user-images.githubusercontent.com/179761/44435837-8a868b80-a5e4-11e8-9978-7fbd6c62b80f.png)

4. On your application targets’ Build Phases settings tab, click the + icon and choose New Run Script Phase. Create a Run Script in which you specify your shell (ex: /bin/sh), add the following contents to the script area below the shell: `/usr/local/bin/carthage copy-frameworks`
Add the paths to the frameworks you want to use under “Input Files". For example:
Add the paths to the copied frameworks to the “Output Files”. For example:

![screen shot 2018-08-22 at 08 23 48](https://user-images.githubusercontent.com/179761/44435875-b86bd000-a5e4-11e8-949b-cbed35b1c425.png)

But when I tried to `#import "BraintreeCore.h"` in my AppDelegate.m file, I get BraintreeCore.h not found error directly inside the editor.

**Comment by williamli** [comment]
Instead of (step 3)

> On your application targets’ General settings tab, in the “Linked Frameworks and Libraries” section, drag and drop each framework you want to use from the Carthage/Build folder on disk.

I dragged and dropped the frameworks directly into the project in the left panel:
![screen shot 2018-08-22 at 08 41 30](https://user-images.githubusercontent.com/179761/44436334-316c2700-a5e7-11e8-9335-d634cf8c9b5b.png)

and then instead of 

> #import "BraintreeCore.h"

I used

> #import "BraintreeCore/BraintreeCore.h"

Not sure if this is wrong and will break my project in the long run...

**Comment by williamli** [comment]
hmmm, turns out I don't need to have the libraries shown on the left 

I just need to replace
`#import "BraintreeCore.h`

with 

`#import "BraintreeCore/BraintreeCore.h"`

**Comment by Ravi-Nagarro07** [comment]
I am having this issue.

#import "BraintreeCore/BraintreeCore.h" this is not working.
