### ISSUE TITLE
`fetchPaymentMethodNonces` doesn't return ApplePay

### ISSUE THREAD

**Issue by itsmeichigo** [braintree/braintree_ios#416]
### General information

* SDK/Library version: 4.17.0 - BraintreeDropIn: 6.4.1
* Environment: Sandbox and Production
* iOS Version and Device: iOS 11.3.1 on iPhone X
* Integration type and version: CocoaPods 1.5.3

### Issue description

We have integrated Braintree ApplePay and added ApplePay as the default payment method but Braintree iOS SDK fails to return ApplePay when method `fetchPaymentMethodNonces: completion:` is called. The same issue can be found when Braintree Dropin UI doesn't show ApplePay as one of the used payment methods, while other methods like credit cards, Venmo, Paypal work just fine.

We have also investigated this issue on the server side and found that Braintree PHP SDK returns Apple Pay as default method for that same account just fine, so we suspect that this is an issue with the iOS SDK only. Please help investigate and address this.

Thank you,

**Comment by crookedneighbor** [comment]
This is expected. While Apple Pay _can_ be vaulted on the server, it should only be used for [recurring billing or transactions with partial or delays shipments](https://developers.braintreepayments.com/guides/apple-pay/client-side/ios/v3#vaulting-apple-pay-cards).

For new transactions initiated by the customer, Apple requires the customer to re-auth Apple Pay each time.
