### ISSUE TITLE
Apple Pay Client-Side documentation has an error in Swift

### ISSUE THREAD

**Issue by Nonepse** [braintree/braintree_ios#417]
### General information

* SDK/Library version: N/A
* Environment: N/A
* iOS Version and Device: N/A
* Integration type and version: N/A

### Issue description

In the Client-Side documentation of Apple Pay [I see this method](https://developers.braintreepayments.com/guides/apple-pay/client-side/ios/v4#create-a-pkpaymentrequest):
```objective-c
- (void)setupPaymentRequest:(void (^)(PKPaymentRequest * _Nullable, NSError * _Nullable))completion
```
converted to:
```swift
func setupPaymentRequest(completion: (PKPaymentRequest?, Error?))
```
This is the syntax for a tuple, not a closure. I think it should be:
```swift
func setupPaymentRequest(completion: @escaping (PKPaymentRequest?, Error?) -> Void)
```

**Comment by crookedneighbor** [comment]
I've forwarded your feedback to our docs team. They'll get the error sorted out.

In the future, you can contact them directly by using the "Give us some Feedback on this Page" button at the bottom of the page.
