### ISSUE TITLE
Xcode 10.0 error

### ISSUE THREAD

**Issue by loveTheDark** [braintree/braintree_ios#418]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version:

**Comment by Epreuve** [comment]
@loveTheDark If you're having an issue, please complete the issue template so we can attempt to replicate.

**Comment by loveTheDark** [comment]
Sorry, this is my first time to write issue. My problem is that after updating Xcode 10.0, braintree_ios has a lot of error reporting.

**Comment by Epreuve** [comment]
Could you share the errors you're seeing?

**Comment by loveTheDark** [comment]
Error:

**Comment by loveTheDark** [comment]
Error:
1.
~/Pods/Braintree/BraintreePayPal/PayPalOneTouch/Models/PPOTRequest.m:170:47: This block declaration is not a prototype

2.
~/Pods/Braintree/BraintreeCore/BTAnalyticsMetadata.m:35:99: 'kCLAuthorizationStatusAuthorizedAlways' is only available on iOS 8.0 or newer

and more....

**Comment by loveTheDark** [comment]
pod 'Braintree', '~> 4.8.2’
