### ISSUE TITLE
Replace `#if DEBUG` in headers by `#ifdef DEBUG`

### ISSUE THREAD

**Issue by lukaskukacka** [braintree/braintree_ios#420]
### General information

* SDK/Library version: Any (4.17.0)
* Environment: Any
* iOS Version and Device: Any
* Integration type and version: CocoaPods 1.5.3

### Issue description

Please consider replacing `#if DEBUG` in headers by more common `#ifdef DEBUG`

#### The difference

-  `#ifdef DEBUG` evaluates to true (code we will be in) when `DEBUG` is defined
    - It is common to define `DEBUG=1` in debug builds, don't define anything (no `DEBUG=0`) in release builds
- `#if DEBUG` evaluates to true if `DEBUG` is defined as `1`

By "common" I mean common in iOS development. For example Xcode's Obj-C project templates are using this concept.

![screen shot 2018-09-27 at 10 59 39](https://user-images.githubusercontent.com/2315799/46135113-c1376d80-c244-11e8-8b7e-5d7831e8e6f5.png)

#### How does it work now?

Construct `#if DEBUG` is used to provide some methods in headers in DEBUG mode only.

- If `DEBUG=1` is defined, the code will _be_ compiled in
- If `DEBUG=0` is defined, the code will _not be_ compiled in
    - If _no_ `DEBUG` is defined at all, it will by default be evaluated as `0`, turning the condition to `#if 0` -> code will not be compiled in

#### What is the problem?

In short: strict compiler flags.

The fallback of non-defined value to `0` is actually the problem. With stricter compiler settings using `-Wundef` flag ([docs](https://www.cleancss.com/explain-command/gcc/4801)), this behaviour actually raises a warning.

When used together with `-Werror` (treat warnings as errors, [docs](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html), warning is actually treated as error.

As a result, using Braintree causes *non-debug builds to fail* for project with this strict compiler settings.

##### Wrap import by pragma ignore
In Obj-C it is technically possible to wrap all imports of Braintree SDK with pragma ignore (`#pragma clang diagnostic ignored ...`). However this is not even possible when using Braintree as a module in Swift, where we don't make the import explicitly ourselves.

##### Treat -Wundef still just as error
It is possible to opt-out `-Wunder` from `-Werror` by `-Wno-error=undef` flag to still keep `-Wunder` just as error. However this is not ideal as it disables this behavior also for the project, not just for the Braintree SDK.

**Comment by jackellenberger** [comment]
This seems like a reasonable request. If you have the time feel free to submit a PR swapping the directives, otherwise we'll add it to our todo's and update this issue when the fix is ready for release!
