### ISSUE TITLE
V4.10 tokenizeCard Got 'Expiration date is required ' when nonce is used by the server

### ISSUE THREAD

**Issue by xuaninbox** [braintree/braintree_ios#421]
### General information

* SDK/Library version: 4.10
* Environment: Production
* iOS Version and Device: 12
* Integration type and version:  CocoaPods

### Issue description

When our backend receive the tokenizeCard nonce and try to create a payment method, the backend return "Expiration date is required" Error.

iOS:

```
var parameters = ["expiration_month": expirationMonth, "expiration_year": expirationYear, "cvv": cvv, "billing_address": ["postal_code": postalCode]] as [String: Any]
let card = BTCard(parameters: parameters)
cardClient.tokenizeCard(card) { tokenizedCard, error in

    >>> Send tokenizedCard?.nonce to backend

}
```

Backend:

```
gateway.paymentMethod.create({
      customerId,
      paymentMethodNonce,
      options: {
        verifyCard: true
      }
    }, callbackFunction)
```

Failed with:

```
ErrorResponse {
     errors: 
      ValidationErrorsCollection {
        validationErrors: {},
        errorCollections: [Object],
        imageUrl: 'https://assets.braintreegateway.com/payment_method_logo/unknown.png' },
     params: { paymentMethod: [Object], merchantId: 'XXX' },
     message: 'Expiration date is required.',
     success: false,
     paymentMethod: 
      UnknownPaymentMethod {
        validationErrors: {},
        errorCollections: [Object],
        imageUrl: 'https://assets.braintreegateway.com/payment_method_logo/unknown.png' } }
```

The backend and iOS haven't been changed in the last 6 month and this issue only start to show up 1 or 2 days ago. Android also works without ant issue. Is there a deprecation on the older sdk that caused this issue?

Thanks!

**Comment by crookedneighbor** [comment]
I'm concerned about:

> The backend and iOS haven't been changed in the last 6 month and this issue only start to show up 1 or 2 days ago.

So I'm going to re-open this for a little bit of further investigation.

**Comment by xuaninbox** [comment]
@skunkworks verifyCard option has been set to true from day one and without any issue, It's only recently that this error starts to appear. The nonce generated by the cardClient.tokenizeCard method seems no longer include the exp datas thats why when the backend creates the user, the error appear.

A quick question:

Does the iOS sdk calls the Braintree backend when .tokenizeCard is used? could that have changed recently?

**Comment by demerino** [comment]
This initialization of the card is incorrect. 
```var parameters = ["expiration_month": expirationMonth, "expiration_year": expirationYear, "cvv": cvv, "billing_address": ["postal_code": postalCode]] as [String: Any]
let card = BTCard(parameters: parameters)``` 

Reviewing the implementation: https://github.com/braintree/braintree_ios/blob/master/BraintreeCard/BTCard.m#L40-L44

You need to pass `expiration_date` formatted with a `/`.

I'm curious where you found the code snippet above to create a `BTCard` like that? 

Instead, I suggest just creating a blank `BTCard` and setting each property manually or reviewing how the `parameters` method works.

**Comment by xuaninbox** [comment]
https://github.com/braintree/braintree_ios/blob/87d7516a9ad05d058672ccccc812f0c4544f0571/BraintreeCard/BTCard.m

This is changed in the new version, we are using 4.10. If this is no longer supported, shouldn’t there be a deprecation notice?

**Comment by demerino** [comment]
I'm not seeing where passing this will work based on your link:
```
var parameters = ["expiration_month": "12", "expiration_year": "2020", "cvv": cvv, "billing_address": ["postal_code": postalCode]] as [String: Any]
```

The required format is:
```
var parameters = ["expiration_date": "12/2020, "cvv": cvv, "billing_address": ["postal_code": postalCode]] as [String: Any]
```

**Comment by xuaninbox** [comment]
I changed it to expiration_date and it's now working. Its very strange that it stoped working only recently, we have been using this "expiration_month" and "expiration_year" from the start.

Closing, thanks guys for the help
