### ISSUE TITLE
Fail to build in Xcode new build system

### ISSUE THREAD

**Issue by liroyan** [braintree/braintree_ios#425]
### General information

* SDK/Library version: 4.19.0
* Environment: Debug
* iOS Version and Device: iOS 12.0 Simulator iPhone X
* Integration type and version: CocoaPod 1.5.3
### Issue description

We want to enable new build system in Xcode 10.0. However it's failing and complaining:
error: Build input file cannot be found: 'XXX/Developer/Xcode/DerivedData/{OUR-APP}/Build/Products/Debug-iphonesimulator/Braintree/Braintree-UI-Localization.bundle/Braintree-UI-Localization'

Full error description:
`CopySwiftLibs XXX/Library/Developer/Xcode/DerivedData/{OUR-APP}/Build/Products/Debug-iphonesimulator/Braintree/Braintree-UI-Localization.bundle (in target: Braintree-Braintree-UI-Localization)
    cd XXX/Pods
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk
    builtin-swiftStdLibTool --copy --verbose --sign - --scan-executable XXX/Library/Developer/Xcode/DerivedData/{OUR-APP}/Build/Products/Debug-iphonesimulator/Braintree/Braintree-UI-Localization.bundle/Braintree-UI-Localization --scan-folder /Users/XXX/Library/Developer/Xcode/DerivedData/{OUR-APP}/Build/Products/Debug-iphonesimulator/Braintree/Braintree-UI-Localization.bundle/Frameworks --scan-folder /Users/XXX/Library/Developer/Xcode/DerivedData/{OUR-APP}/Build/Products/Debug-iphonesimulator/Braintree/Braintree-UI-Localization.bundle/PlugIns --platform iphonesimulator --toolchain /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain --destination /Users/XXX/Library/Developer/Xcode/DerivedData/{OUR-APP}/Build/Products/Debug-iphonesimulator/Braintree/Braintree-UI-Localization.bundle/Frameworks --strip-bitcode --resource-destination /Users/XXX/Library/Developer/Xcode/DerivedData/{OUR-APP}/Build/Products/Debug-iphonesimulator/Braintree/Braintree-UI-Localization.bundle --resource-library libswiftRemoteMirror.dylib --strip-bitcode-tool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip --emit-dependency-info XXX/Library/Developer/Xcode/DerivedData/{OUR-APP}/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Braintree-Braintree-UI-Localization.build/SwiftStdLibToolInputDependencies.dep
`

**Comment by demerino** [comment]
We're unable to reproduce the issue. Can you try clearing your Derived Data? `File` -> `Workspace Settings` then navigate to your derived data and clear the files. Also try cleaning your build folder `Product` -> `Clean Build Folder`.

Let us know if that helps.

**Comment by liroyan** [comment]
Yeah tried that already. Didn't fix the issue. This same error happened in Xcode 9 too when we first tried to use the new build system. Now that new build system is the new default build system, we really want to use it.

**Comment by demerino** [comment]
Our projects use the `New Build System` and are compiling. Can you give us any additional information so we can reproduce the issue?

![screen shot 2018-10-23 at 1 42 52 pm](https://user-images.githubusercontent.com/7817434/47389428-8e5c8a00-d6c9-11e8-8f6d-932e71a9dfcf.png)

**Comment by liroyan** [comment]
Sorry for the delayed reply. What additional information do you think would be helpful?

**Comment by thecodiac** [comment]
Showing Recent Messages
CopySwiftLibs /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music\ Player.app (in target: Music Player)
    cd /Users/stephenbrewer/Desktop/Music\ Player
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk
    builtin-swiftStdLibTool --copy --verbose --sign E457D8C4F512B4D2F3F958D53615E5033E9036FC --scan-executable /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music\ Player.app/Music\ Player --scan-folder /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music\ Player.app/Frameworks --scan-folder /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music\ Player.app/PlugIns --platform iphoneos --toolchain /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain --destination /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music\ Player.app/Frameworks --strip-bitcode --resource-destination /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music\ Player.app --resource-library libswiftRemoteMirror.dylib --strip-bitcode-tool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip --emit-dependency-info /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Intermediates.noindex/Music\ Player.build/Debug-iphoneos/Music\ Player.build/SwiftStdLibToolInputDependencies.dep

Requested Swift ABI version based on scanned binaries: 6
libswiftsimd.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftsimd.dylib
libswiftDispatch.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftDispatch.dylib
libswiftCoreImage.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftCoreImage.dylib
libswiftUIKit.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftUIKit.dylib
libswiftDarwin.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftDarwin.dylib
libswiftMediaPlayer.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftMediaPlayer.dylib
libswiftos.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftos.dylib
libswiftCoreGraphics.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftCoreGraphics.dylib
libswiftAVFoundation.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftAVFoundation.dylib
libswiftCoreData.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftCoreData.dylib
libswiftMetal.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftMetal.dylib
libswiftCoreFoundation.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftCoreFoundation.dylib
libswiftCoreAudio.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftCoreAudio.dylib
libswiftObjectiveC.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftObjectiveC.dylib
libswiftFoundation.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftFoundation.dylib
libswiftQuartzCore.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftQuartzCore.dylib
libswiftCore.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftCore.dylib
libswiftCoreMedia.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftCoreMedia.dylib
libswiftRemoteMirror.dylib is up to date at /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/libswiftRemoteMirror.dylib
Probing signature of /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftsimd.dylib
/usr/bin/codesign -r- --display /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftsimd.dylib
/Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftsimd.dylib: code object is not signed at all

Codesigning /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftsimd.dylib
/usr/bin/codesign --force --sign E457D8C4F512B4D2F3F958D53615E5033E9036FC --verbose /Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftsimd.dylib
/Users/stephenbrewer/Library/Developer/Xcode/DerivedData/Music_Player-gloyklstybigcngbgjuoyfmwbjbh/Build/Products/Debug-iphoneos/Music Player.app/Frameworks/libswiftsimd.dylib: errSecInternalComponent

error: Failed with exit code 1

**Comment by thecodiac** [comment]
I am having the same issue, I cant get past exit code 1. Any suggestions?

**Comment by amanps247** [comment]
Same issue. My app was working fine but after a few days the "exit code 1" issue started to occur and i couldn't get past it since.

**Comment by demerino** [comment]
Is anyone still have issues with this in `Xcode 10.2`?

**Comment by jesphinpt** [comment]
Any workarounds. I am facing the same in Xcode 12.5.1
