### ISSUE TITLE
Xcode 10, Braintree 3.9.10 -> implementing deprecated method

### ISSUE THREAD

**Issue by kvkvkvkvkvkv** [braintree/braintree_ios#427]
### General information

* SDK/Library version: 3.9.10
* Environment: Sandbox, Production
* iOS Version and Device: 10, any device
* Integration type and version: CocoaPod 1.5.3

### Issue description

Building with Xcode 10, hit "implementing deprecated method" on functions below:

- (BTPayPalButton *)payPalButtonWithDelegate:(id<BTPayPalButtonDelegate>)delegate {

- (void)tokenizeCardWithNumber:(NSString *)cardNumber
               expirationMonth:(NSString *)expirationMonth
                expirationYear:(NSString *)expirationYear
                    completion:(void (^)(NSString *nonce, NSError *error))completionBlock {

**Comment by hollabaq86** [comment]
Hi @kvkvkvkvkvkv, we deprecated these two functions:

- instead of `payPalButtonWithDelegate:`, please see `paymentButtonWithDelegate:`
- instead of `tokenizeCardWithNumber:expirationMonth:expirationYear:completion:`,  please see `tokenizeCard:completion:`

Let us know if you have any other questions.

**Comment by kvkvkvkvkvkv** [comment]
Hi @hollabaq86 , understand both methods have been deprecated, however this build error was caused by the existence of these methods in Braintree.h (pod Braintree version 3.9.10, which is a dependency from Braintree/Data it seems). 

Any solution? please advise.

**Comment by kvkvkvkvkvkv** [comment]
It's okay, seems like the SDK we are using have been deprecated, shall upgrade to the latest then.

**Comment by marconealberto** [comment]
I just followed the docs: https://developers.braintreepayments.com/start/hello-client/ios/v3#ios-sdk-setup and it led me to the same error. Something is wrong if a simple pod install give you this error.

**Comment by scannillo** [comment]
Hello @marconealberto . An issue with pod install seems unrelated to this thread. Feel free to reach out to our support team if you have issues with your integration https://help.braintreepayments.com/, or create a new GitHub issue on this repo with more information on the setup that you have and the error you get if you feel this is an SDK issue. Thanks!

**Comment by malkabani** [comment]
Hello
it is not working.
