### ISSUE TITLE
objc[35743]: Class PPRMOCMagnesNetworkManager is implemented in both...

### ISSUE THREAD

**Issue by xieweizhi** [braintree/braintree_ios#428]
### General information

* SDK/Library version: 4.20.0
* Environment: Sandbox
* iOS Version and Device: iPhone X 12.1 
* Integration type and version:  CocoaPods 1.6.0.beta.2
* Xcode Version 10.1 (10B61)

### Issue description

There are many console logs while running the app.

```
objc[35743]: Class PPRMOCMagnesNetworkManager is implemented in both /Users/weizhi/Library/Developer/CoreSimulator/Devices/F4DB5292-D607-43EE-A3E3-6FCCCBF5CDC0/data/Containers/Bundle/Application/3367854B-9957-45E6-A9EB-1CEF5D0EA49C/Castlery.app/Frameworks/Braintree.framework/Braintree (0x106c28258) and /Users/weizhi/Library/Developer/CoreSimulator/Devices/F4DB5292-D607-43EE-A3E3-6FCCCBF5CDC0/data/Containers/Bundle/Application/3367854B-9957-45E6-A9EB-1CEF5D0EA49C/xxx.app/xxx (0x104cbb328). One of the two will be used. Which one is undefined.

same as PPRMOCMagnesDynamicDataCollector, PPRMOCMagnesCoreDataCollector and more.
```

**Comment by billwerges** [comment]
Hi @xieweizhi,

Thanks for bringing this to our attention, we should be able to get a fix for this released this week.

**Comment by demerino** [comment]
This should be fixed in `4.20.2`

**Comment by xieweizhi** [comment]
@demerino , Same issue in version 4.21.0.  :(

**Comment by billwerges** [comment]
Hi @xieweizhi,

We are not seeing this issue in 4.21.0. Can you try running `Product -> Clean Build Folder` in Xcode, and then re-compiling, to see if that clears up the issue for you?

**Comment by xieweizhi** [comment]
Hey @billwerges 
I tried, but it didn't help.
