### ISSUE TITLE
'BraintreePayPal/BraintreePayPal.h' file not found

### ISSUE THREAD

**Issue by 1037390459** [braintree/braintree_ios#431]
### General information

* SDK/Library version: 4.17.0 
* Environment: Is this issue in Sandbox or Production? 
* iOS Version and Device:  iOS 9.3 on an iPhone 6s 
* Integration type and version: CocoaPods 1.4.0 

### Issue description
I run the pod install, and then open the xworkspace and selecte the Demo target it comes this build error saying that 'BraintreePayPal/BraintreePayPal.h' file not found;But the file exist in the project.

**Comment by hollabaq86** [comment]
Please reach out to our support team with more information about your integration so we can troubleshoot what is going wrong. https://help.braintreepayments.com/
