### ISSUE TITLE
ld: library not found for -lBraintree

### ISSUE THREAD

**Issue by zouqilin** [braintree/braintree_ios#432]
### General information
react-native info
Environment:
  OS: macOS 10.14.2
  Node: 8.12.0
  Yarn: 1.12.3
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338
Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

### podfile
```
platform :ios, '9.0'

target 'MyProj' do
  # use_frameworks!
  pod 'Stripe', '~> 11.2.0'
  pod 'Braintree'
  pod 'BraintreeDropIn'
  pod 'Braintree/Apple-Pay'
  pod 'Braintree/PayPal'
  pod 'Braintree/DataCollector'
  pod 'CardIO'
end
```

### Issue description
I integrited braintree to My React Native Project. then compiled it in XCode. but failed with following errors
```
ld: warning: directory not found for option '-L/Users/me/Code/projs/MyProj/ios/MyProj Dev'
ld: library not found for -lBraintree
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Some special settings in File> Project Settings
Building Setting was set to `Legacy Build System`
Advanced > Build Location -> Custom was chosen and set to `Relative to Workspace`
Advanced > Build Location -> Custom -> Products was set to `build/Build/Products`
Advanced > Build Location -> Custom -> Intermediates was set to `build/Build/Intermediates.noindex `                                           
and I tried these settings with default value. but failed to compile with the same error.

**Comment by zouqilin** [comment]
Thanks. I compiled it successfully.
Indeed. I built my app by opening the `.xcodeproj` file because I had no idea about the difference
between `.xcodeproj` and `.xcworkspace`

**Comment by attilakrupl** [comment]
What if you are using CMAKE?

**Comment by sestevens** [comment]
@attilakrupl Could you open a new issue with more details about the issue you're running into? I'm not entirely sure what you're asking.

**Comment by attilakrupl** [comment]
> @attilakrupl Could you open a new issue with more details about the issue you're running into? I'm not entirely sure what you're asking.

Thank you the issue has been resolved.

**Comment by akildemir** [comment]
@attilakrupl lol but how?

**Comment by attilakrupl** [comment]
Apologies, it's not relevant anymore.
