### ISSUE TITLE
Task failed with exit code 65:

### ISSUE THREAD

**Issue by zalihm** [braintree/braintree_ios#434]
Unable to install using Carthage

*** Building scheme "BraintreeAmericanExpress" in Braintree.xcworkspace
*** Building scheme "Braintree3DSecure" in Braintree.xcworkspace
*** Building scheme "BraintreeApplePay" in Braintree.xcworkspace
*** Building scheme "BraintreeCard" in Braintree.xcworkspace
*** Building scheme "BraintreeCore" in Braintree.xcworkspace
*** Building scheme "BraintreeDataCollector" in Braintree.xcworkspace
*** Building scheme "BraintreePaymentFlow" in Braintree.xcworkspace
Build Failed
	Task failed with exit code 65:

in Carthage/Checkouts/braintree_ios
his usually indicates that project itself failed to compile

**Comment by hollabaq86** [comment]
Thanks for reaching out! Can you provide the following information?

- Braintree SDK version
- Carthage version
- Xcode version
- Environment (sandbox vs production)

**Comment by zalihm** [comment]
Added github "braintree/braintree-ios-drop-in" in cartfile

BaintreeSDK 

Checking out braintree-ios-drop-in at "7.0.0"
Checking out braintree_ios at "4.21.0"

carthage  version 0.31.2
xcode 9.4
sandbox (its crashed in Carthage update itself )

**Comment by zalihm** [comment]
sorry, I didn't notice that this require Xcode. 10 
I have checked the drop-in UI spec which demands Xcode 9+
there it needs the update
https://github.com/braintree/braintree-ios-drop-in
