### ISSUE TITLE
Braintree not compiling in Xcode 10.1 using Objective - C code

### ISSUE THREAD

**Issue by kirti0525** [braintree/braintree_ios#436]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version:

**Comment by demerino** [comment]
@kirti0525 what error are you seeing? I'm able to compile in Xcode 10.1

**Comment by kirti0525** [comment]
@demerino '@return' command used in a comment that is attached to a method returning void
This is the error I am getting while compiling

**Comment by waris117** [comment]
Hi
i am using Brain Tree in react native app using https://www.npmjs.com/package/react-native-braintree-dropin-ui' On running app in xcode, gives following error. any one can help, what can be issue?
BTDataCollector.h' file not found

**Comment by demerino** [comment]
@kirti0525 Do you have a line number or class where this is coming from?

**Comment by demerino** [comment]
Closing. If this is still a problem, please open a new issue with additional information.
