### ISSUE TITLE
Drop dialog does not disappear

### ISSUE THREAD

**Issue by delphiy** [braintree/braintree_ios#439]
Hi,
Drop in shows successfully and it shows options for payment and everything but if choose cancel button or select payment method from bottom popup . Nothing happened . The main problem drop dialog does not dismiss.

Add card works perfect .

**Comment by billwerges** [comment]
Hi @delphiy,

The payment selection view controller does not dismiss itself. You are responsible for handling it's dismissal in the `handler` method when you create a `BTDropInController`.

Example:
```
BTDropInController *dropIn = [[BTDropInController alloc] initWithAuthorization:someAuthorizationString
                                                                       request:someDropInRequest
                                                                       handler:^(BTDropInController * _Nonnull __unused dropInController, BTDropInResult * _Nullable result, NSError * _Nullable error) {
    // Process *result
    [dropInController dismissViewControllerAnimated:YES completion:nil];
}];
```
