### ISSUE TITLE
dyld: library not loaded

### ISSUE THREAD

**Issue by xuefanzhang** [braintree/braintree_ios#442]
### General information

* SDK/Library version: 4.21.0
* Environment: Sandbox
* Xcode version: 10.1
* Integration type and version: Carthage 0.31.2

### Issue description

I added `github "braintree/braintree_ios"` to cartfile, then linked all the framework libraries in xcode under project target -> General -> Linked Frameworks and Libraries (see attached image)

When trying to run the project, I get 
```
dyld: Library not loaded: @rpath/BraintreePayPal.framework/BraintreePayPal
  Referenced from: /Users/xuefan/Library/Developer/CoreSimulator/Devices/F5097715-F116-4A7A-8827-A6626EC6468E/data/Containers/Bundle/Application/E7988397-5929-4C25-B3BC-17210A1D7548/Trim.app/Trim
  Reason: image not found
```
Could you please advise on how I may resolve the issue? Thank you in advance.

![screen shot 2019-01-22 at 4 11 27 pm](https://user-images.githubusercontent.com/2301245/51573955-716a5b00-1e60-11e9-836c-8a16f769f4dd.png)

**Comment by billwerges** [comment]
Hi @xuefanzhang,

Can you ensure that you are adding the `copy-frameworks` step to your project's Build Phase in Xcode.

Instructions for this can be found under step 8 of the Carthage Quick Start Guide: https://github.com/Carthage/Carthage#quick-start

**Comment by xuefanzhang** [comment]
![screen shot 2019-01-24 at 11 29 40 am](https://user-images.githubusercontent.com/2301245/51703522-641daf80-1fcb-11e9-9649-dac44fd1e45f.png)

@billwerges Thanks for helping take a look. It's there. The other frameworks I've added via Carthage are working fine so perhaps it's not Carthage.

**Comment by billwerges** [comment]
Hi @xuefanzhang,

Can you verify that the Braintree frameworks have also been added to the input and output file sections of the run script? More details can be found in the Carthage documentation.

When completed, your run script should like something like this(not including other frameworks you may be using):

<img width="693" alt="screen shot 2019-01-24 at 1 40 30 pm" src="https://user-images.githubusercontent.com/43414092/51704155-eb741e80-1fdd-11e9-94a2-921ce56b02c4.png">

**Comment by xuefanzhang** [comment]
Hi @billwerges - yeah those are there as well.

**Comment by xuefanzhang** [comment]
@billwerges do you or others have suggestion on what I should look into next :( I think i did cover the steps. Perhaps there is some integration issue with Carthage?

**Comment by billwerges** [comment]
@xuefanzhang would it be possible to include a screenshot showing the `Input Files` and `Output Files` that are being passed to the `copy-frameworks` run script?

**Comment by billwerges** [comment]
@xuefanzhang, it looks like `BraintreePayPal.framework` is missing from your Output Files section. Can you try adding it and see if it resolves your issue?
