### ISSUE TITLE
No browser for PayPal on iOS 10.x

### ISSUE THREAD

**Issue by mwoollard** [braintree/braintree_ios#443]
### General information

* SDK/Library version: 4.22.0
* Environment: Sandbox
* iOS Version and Device: Reproduced on iOS 10.3.3 / iPhone 6 device + iOS 10.1 iPhone 7 Simulator
* Integration type and version: CocoaPods 1.5.3

### Issue description

We are using Braintree to implement PayPal purchases using the `BTPayPalDriver` class. This is working perfectly for iOS 11 and later but for iOS 10.x the browser never appears and the callback passed to `requestOneTimePayment` is never called. Is this a known issue on iOS 10.x or is there some additional configuration needed that I've not found in the docs? We are currently targeting iOS 10 and later so need to resolve this issue.

**Comment by demerino** [comment]
@mwoollard I just tested using `iOS 10.1 iPhone 7 Simulator` and SFSafariViewController appeared as expected. Is an error being returned in the callback or anything else in the xcode logs?

**Comment by mwoollard** [comment]
Thanks for response - there are no logs or any clues I'm afraid, however we have another solution for our requirements now so am closing as may have been down to way we are using the SDK as you cannot reproduce and no other reports.
