### ISSUE TITLE
BTPayPalAccountNonce billingAddress is nil

### ISSUE THREAD

**Issue by aodhol** [braintree/braintree_ios#444]
### General information

* SDK/Library version:  4.22.0
* Environment: Sandbox & Production
* iOS Version and Device: iOS 12.1, iPhone 6
* Integration type and version: CocoaPods 1.5.3

### Issue description

When inspecting the BTPayPalAccountNonce I get back after attempting to make a PayPal transaction, I notice that the billing address is always nil. Is this expected?

```swift
let payPalDriver = BTPayPalDriver(apiClient: braintreeClient)
// ... 
let payPalRequest = BTPayPalRequest(amount: "10.99")
payPalRequest.currencyCode = "GBP"
payPalRequest.isShippingAddressRequired = true
payPalDriver.requestOneTimePayment(payPalRequest) { (tokenizedPayPalAccount, error) -> Void in 
 print("Billing address: \(tokenizedPayPalAccount.billingAddress)")
}
```

**Comment by demerino** [comment]
This is expected. The user's billing address details are not available to all merchants; [contact PayPal](https://articles.braintreepayments.com/guides/payment-methods/paypal/setup-guide#contacting-paypal-support) for details on eligibility and enabling this feature. Alternatively, use the `shippingAddress` like you're doing above.

Let us know if you have any other questions.

**Comment by aodhol** [comment]
thanks @demerino
