### ISSUE TITLE
Postal code using number pad only

### ISSUE THREAD

**Issue by MaiquanNguyen** [braintree/braintree_ios#445]
### General information

* SDK/Library version: Braintree (4.22.0) and BraintreeDropIn (7.0.0)
* Environment: Both sandbox and production
* Integration type and version: CocoaPods 1.5.3

### Issue description

Postal code on iOS drop-in UI are now using number pad keyboard type so we can only input number to it. But we want to input letters too since our customer mostly in UK and the use both number and letters for postal code
![1](https://user-images.githubusercontent.com/4607287/52683135-7ceb0680-2f74-11e9-935d-27119209ec3b.png)

**Comment by scannillo** [comment]
Hello! You can specify which `UIKeyboardType` you would like to use for the postal code form field by setting the `postalCodeFormFieldKeyboardType` property on the `BTUIKAppearance` class.

Check that property out in line 46-47 in the[ header file for `BTUIKAppearance`](https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeUIKit/Public/BTUIKAppearance.h).

For future questions on setting up any of our SDKs, feel free to contact tech support https://help.braintreepayments.com/.
