### ISSUE TITLE
How to get the first six digits?

### ISSUE THREAD

**Issue by xieweizhi** [braintree/braintree_ios#449]
The braintree-web supports it recently. 
As discussed here [#419](https://github.com/braintree/braintree-web/issues/419).

Will braintree_ios support it? 

### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version:

**Comment by demerino** [comment]
Yes, we will be adding support for accessing the BIN number.

**Comment by xieweizhi** [comment]
@demerino Thanks for the reply:)

**Comment by demerino** [comment]
This is available as of `4.24.0`: https://github.com/braintree/braintree_ios/blob/master/BraintreeCard/Public/BTCardNonce.h#L26-L29
