### ISSUE TITLE
How to implement in-app payment

### ISSUE THREAD

**Issue by wutieguo** [braintree/braintree_ios#450]
I am developing a Barber app now.  
I want that customer can pay to the barber directly with my app. 
How can I implement it?
I tried to use Stripe,  but there are many issues such as identity verification or creating stripe account.  
so I am finding the best SDK that barber can register his card and customer can pay to barber's card. 
I am not sure that Braintree is a solution to my issue.
If anyone knows how to configure it with Braintree, please help me.

**Comment by crookedneighbor** [comment]
Please reach out to our support team. They'll be able to help you figure out if Braintree is the right solution for you: https://help.braintreepayments.com/
