### ISSUE TITLE
how to pay with credit cards

### ISSUE THREAD

**Issue by maajian** [braintree/braintree_ios#451]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version: 

### Issue description

[cardClient tokenizeCard:card completion:^(BTCardNonce *tokenized, NSError *error) {
        if (error) {
            self.progressBlock(error.localizedDescription);
            NSLog(@"Error: %@", error);
            return;
        }
    }];

This method is just to judge the type of card? Then how to pay?

**Comment by scannillo** [comment]
Hi again :)

Inside the completion block of `tokenizeCard` you'll want to send the resulting `nonce` to your server. See this [doc](https://developers.braintreepayments.com/guides/credit-cards/client-side/ios/v3.

Next you'll need to create a `transaction.sale()` on your server to create a credit card transaction. See this [doc](https://developers.braintreepayments.com/guides/credit-cards/server-side/node). 

For further questions specific to your integration contact our tech support team!
You can fill out the online form: https://help.braintreepayments.com/
Or you can call: 877.434.2894
