### ISSUE TITLE
[Xcode 10.2 / Swift 5] Crash on iOS 12.2

### ISSUE THREAD

**Issue by darecki** [braintree/braintree_ios#452]
### General information

* SDK/Library version: 4.23.0
* Environment: Sandbox (should apply to production as well)
* iOS Version and Device: iPhone Xs Max, iOS 12.2
* Integration type and version: Carthage 0.32.0

### Issue description
When the app is built and compiled with Xcode 10.2 using Swift 5 there is a crash on opening the app with the following error message:

`objc[57185]: Swift class extensions and categories on Swift classes are not allowed to have +load methods`

The stack trace leads to `[BTPayPalDriver load]`

Note that it works on an iOS 12.1.4.

**Comment by braintreeps** [comment]
Hi @darecki,

The Braintree SDK doesn't currently have any Swift extensions or categories for the `BTPayPalDriver` class. Is your app extending this class?

**Comment by darecki** [comment]
Hi @braintreeps 
Thank you for responding.

No, my app is not extending this class and actually, I don't have any own method named `load`. 

I believe it's [this](https://github.com/braintree/braintree_ios/blob/045672d364b0416887867eec87ff55a248dfdf4c/BraintreePayPal/BTPayPalDriver.m#L51) method that's causing the problem, even though it's Obj-C. Maybe that's because my app is written in Swift and I'm importing your library?

I'm also attaching a screenshot:
![stack](https://user-images.githubusercontent.com/3084606/55456210-c7891680-55e6-11e9-95bd-aee94594969a.jpg)

I'd like to share with you another project that had a similar issue. Please take a look at how they resolved it: https://github.com/pmusolino/Wormholy/pull/52

I hope that helps.
Thank you!

**Comment by paolutus** [comment]
Hi, same problem for me with the same configuration except I'm using swift 4 instead of swift 5.

**Comment by demerino** [comment]
Does this error occur in the simulator?

**Comment by darecki** [comment]
Yes, it also happens for example on simulator of iPhone Xs Max running iOS 12.2

**Comment by darecki** [comment]
Weird thing, but after updating other libs that issue is no more there in my app. Apparently the stack trace was somehow misleading.
@paolutus can you please check if updating all other libs to newest versions also helps you?
I guess in my case it was [SwinjectStoryboard](https://github.com/Swinject/SwinjectStoryboard/pull/117) that was causing this issue.

@braintreeps  I'm closing this issue as it's resolved for me. Thanks for your help.

**Comment by demerino** [comment]
Good to know, thanks for the update @darecki

**Comment by paolutus** [comment]
@darecki I was using SwinjectStoryboard too. After having updated to the last release of SwinjectStoryboard the issue disappeared.
Maybe the stacktrace of Xcode was misleading.
