### ISSUE TITLE
Won't build in Xcode 10.2 iOS 12.2

### ISSUE THREAD

**Issue by holgersindbaek** [braintree/braintree_ios#453]
I've downloaded the braintree_ios repo and I'm trying to build the demo with the iOS deployment target set to 12.2, but it's giving me build errors:

![Screenshot 2019-04-08 at 12 43 32](https://user-images.githubusercontent.com/698979/55718417-f09d1300-59fb-11e9-99ef-646ae7de99ff.jpg)

I did this because I'm trying to use braintree_ios as a pod in my app, but I can't get it to work on iOS 12.2. 

Does anyone else have an issue with using the Braintree iOS pod in iOS 12.2? Will the Braintree iOS library be updated to work with iOS 12.2?

**Comment by scannillo** [comment]
I just did a fresh pull of the braintree_ios repo, followed by a `pod install`, and have the demo app running fine on an iPhone Xr simulator running iOS 12.2. 

Is your clone of the repo up to date, as well as the other pods it depends on?

**Comment by holgersindbaek** [comment]
If you set the deployment target to 12.2, then it won't build and you'll get the errors seen in the image.

**Comment by scannillo** [comment]
Right. So our SDK uses some features that are deprecated after iOS 11.0 (example; `PKAddressFieldAll` and`PKContactField`). Until we remove support for these features, your deployment target has to be 10.9 or *lower*. The app can still be run on iOS 12.2, but with the deployment target still supporting lower iOS versions.

**Comment by holgersindbaek** [comment]
From what I can see, all apps have to be build with iOS 12.0+ deployment target start April 1 this month (https://www.macrumors.com/2018/09/12/apple-ios-12-sdk-required-march-2019/). Am I misunderstanding something?

**Comment by janvennemann** [comment]
I suspect this is due to this line which treats all warnings as errors:

https://github.com/braintree/braintree_ios/blob/73e780284547c3f659d8ab58546d227e5fa36563/Braintree.podspec#L22

**Comment by holgersindbaek** [comment]
@janvennemann You're right. I'm using a local version now where I've commented that line out and it seems to work. Thanks!

**Comment by wndxlori** [comment]
No sure closing this is the right thing to do.  Either the code needs to be updated, or the podspec needs to be relaxed, or people will keep running into this issue.
