### ISSUE TITLE
3DS 2.0 Unable to Compile

### ISSUE THREAD

**Issue by Logicoeur** [braintree/braintree_ios#454]
### General information

* SDK/Library version: 4.23
* Environment: Swift + Obj-C
* iOS Version and Device: 12.0 iPhone X Simulator
* Integration type and version: Cocoapods 1.6.1

### Issue description

Pulling in the new 3DS 2.0 branch causes some compiler errors in Xcode 10.2 and the above. Specifically in the CardinalMobile Module (ConfigParameters.h and ThreeDS2Service.h)

"Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)"

![Screen Shot 2019-04-11 at 3 37 47 PM](https://user-images.githubusercontent.com/6384490/56306572-d4daf080-6110-11e9-9c87-8c3e016c38bb.png)
![Screen Shot 2019-04-17 at 12 52 04 PM](https://user-images.githubusercontent.com/6384490/56306591-e0c6b280-6110-11e9-9164-c75e6e8c5db3.png)
![Screen Shot 2019-04-17 at 12 57 27 PM](https://user-images.githubusercontent.com/6384490/56306601-e45a3980-6110-11e9-944d-1f4588531d97.png)

I have to unlock the header files, and add the specifiers to get it to compile.

**Comment by demerino** [comment]
@Logicoeur  Thanks for taking the new branch for a spin, we'll look into these issues.

**Comment by demerino** [comment]
Pushed a commit that fixes the issue while we notify Cardinal to get it fixed in their SDK: https://github.com/braintree/braintree_ios/commit/fffd7de3e0f40fc22892c360991164c02e52d9c3

Let us know if there are any other issues with your integration/testing.
