### ISSUE TITLE
Error in 3D-secure Interface

### ISSUE THREAD

**Issue by RexNexstream** [braintree/braintree_ios#455]
### General information

* SDK/Library version: 4.17.0
* Environment: Production
* iOS Version and Device: More than 1 device 
* Integration type and version: CocoaPods 1.5.3

### Issue description
Get error below when try to perform 3D-secure :

![WhatsApp Image 2019-04-19 at 1 20 30 PM](https://user-images.githubusercontent.com/12932221/56408481-477dd480-62a7-11e9-81a5-6226a8cb0ac3.jpeg)

Please advise and assist on this. Thanks

**Comment by hollabaq86** [comment]
Hi @RexNexstream please [contact Support](https://help.braintreepayments.com/) referencing this issue along with the following information )if possible):
- your merchant ID,
- the time the verification was attempted, 
- the amount of the attempted 3DS verification, 
- the BIN of the card that was used. 

They will be able to assist you.
