### ISSUE TITLE
Braintree without AppSwitch?

### ISSUE THREAD

**Issue by willsmillie** [braintree/braintree_ios#458]
### General information

* SDK/Library version: Latest CocoaPods Version
* Environment: Sandbox
* iOS Version and Device: iOS 12
* Integration type and version: CocoaPods

### Issue description

I was wondering if there is a way to incorporate BrainTree without AppSwitch, similar to the now deprecated [PayPal sdk](https://github.com/paypal/PayPal-iOS-SDK). I'm building a static library and AppSwitch kind of kills the convenience and general flow of the UX.

**Comment by demerino** [comment]
@willsmillie The SDK will not switch to the PayPal app, it will always open in a browser, mostly SFSafariViewController or SFAuthenticationSession depending on the OS Version on the device. This is required for security reasons. Let us know if you have any other questions.
