### ISSUE TITLE
Keyboard style on postal code input

### ISSUE THREAD

**Issue by mylogon341** [braintree/braintree_ios#459]
### General information

* SDK/Library version: Braintree (4.23.0), BraintreeDropIn (7.1.0)
* Environment: Sandbox
* iOS Version and Device: iPhone 7 iOS 12.1
* Integration type and version: Cocoapods

### Issue description

When the user is selecting to pay via cred card, tapping on "Postal Code" presents a number pad. In the UK, postal codes are alpha numeric. Is this a config issue on the front end or back end, or is this an actual bug? 
Thanks.

**Comment by scannillo** [comment]
Hello. In Drop-In you can set the `sharedTheme.postalCodeFormFieldKeyboardType` to be the keyboard of your choosing from Apple's `UIKeyBoardType` which you can find [here](https://developer.apple.com/documentation/uikit/uikeyboardtype?language=objc). 

You would set that for the [light theme here](https://github.com/braintree/braintree-ios-drop-in/blob/e8167e3fe078dbac45dbfb262888b705fc1fe050/BraintreeUIKit/Helpers/BTUIKAppearance.m#L35) and the [dark theme here](https://github.com/braintree/braintree-ios-drop-in/blob/e8167e3fe078dbac45dbfb262888b705fc1fe050/BraintreeUIKit/Helpers/BTUIKAppearance.m#L55) in the `BTUIKAppearance.m` file.

**Comment by mylogon341** [comment]
Ah. Many thanks. I will try that immediately.
