### ISSUE TITLE
NSLocationAlwaysUsageDescription

### ISSUE THREAD

**Issue by platinum7919** [braintree/braintree_ios#463]
### General information

* SDK/Library version: 4.23.0
* Environment: Production
* iOS Version and Device: = iOS 12.2 on an iPhone XR
* Integration type and version: CocoaPods

### Issue description

When submitting the app to appstore (even testflight) there is a warning:

> Dear Developer,
>
>We identified one or more issues with a recent delivery for your app, xxxxxx. Your delivery was successful, but you may wish to correct the following issues in your next > delivery:
>
>ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
>
>After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
>
>Best regards,
>The App Store Team

I believe this originated from [BTAnalyticsMetadata](https://github.com/braintree/braintree_ios/blob/master/BraintreeCore/BTAnalyticsMetadata.m). what is the recommended usage description (NSLocationAlwaysUsageDescription) should we use in this case. (ie. why is braintree getting the lat and long of the user)

**Comment by billwerges** [comment]
Hi @platinum7919,

Thanks for bringing this to our attention. We will be removing this API usage in a future update.

**Comment by demerino** [comment]
This was removed from `BTAnalyticsMetadata` in `4.24.0`.

**Comment by timonchev** [comment]
How disable request of location for Braintree? We want remove NSLocationWhenInUseUsageDescription from app or disable location request, but get same warning from Apple..

**Comment by scannillo** [comment]
@timonchev this was removed in `4.24.0` version of our SDK. Please update to that version or higher.
