### ISSUE TITLE
Configure archive step to produce a fat binary framework

### ISSUE THREAD

**Issue by hasanPrestoq** [braintree/braintree_ios#465]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version: 

### Issue description

I would like to be able to quickly create a fat binary framework (as described in the link below).
If I do this locally, I will loose all configuration on each update.

https://medium.com/allatoneplace/writing-custom-universal-framework-in-xcode-9-and-ios-11-7a63a2ce024a

**Comment by sestevens** [comment]
@hasanPrestoq Could you give us more information about what you're trying to achieve? Why are you trying to produce a fat binary framework?

**Comment by hasanPrestoq** [comment]
Sure.
I want to be able to use Carthage: https://github.com/Carthage/Carthage
to create my product, and so far just doing a Carthage update seems to be failing to create my Braintree framework.
So I pulled the project using git, and went to build the framework in Xcode.
The issue there is that it builds for the target platform, and I want a single framework that I can use for simulator and device use.

The provided link shows how to configure the archive step to produce a fat framework that will achieve this goal.

Thanks for your quick response.

**Comment by hasanPrestoq** [comment]
And just now I have been able to compile using Carthage, so I believe this can be closed.
