### ISSUE TITLE
Can not be validated by App Store Connect

### ISSUE THREAD

**Issue by pcjbird** [braintree/braintree_ios#468]
### General information

* SDK/Library version: Braintree (4.25.1) BraintreeDropIn (7.2.0)
* Environment: Production
* iOS Version and Device:  All
* Integration type and version: CocoaPods 1.7.4

### Issue description

When I integrate Braintree in my iOS App and submit it to AppStore, however the binary can not be validated by App Store Connect, and Apple send me email shown as following:

> ITMS-90562: Invalid Bundle - The app submission can not be successfully recompiled from bitcode due to missing symbols during linking. You can try to reproduce and diagnose such issues locally by following the instructions from: https://developer.apple.com/library/archive/technotes/tn2432/_index.html
> 
> ITMS-90562: Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.
> 
> Best regards,
> 
> The App Store Team

It works very well if I remove the Braintree integration.

**Comment by scannillo** [comment]
Hi @pcjbird, could you try doing an ad-hoc distribution in Xcode and send us the output of IDEDistribution.standard.log? This would be the best way for us to help investigate. Instructions here: https://developer.apple.com/library/archive/technotes/tn2432/_index.html.

**Comment by ds12g** [comment]
I seem to be running into the same issue as well. I will attach the log file. It seems to be related somehow to the CardinalMobile  framework;

[IDEDistribution.standard.log](https://github.com/braintree/braintree_ios/files/3408871/IDEDistribution.standard.log)

**Comment by pcjbird** [comment]
Yeah, the same to @ds12g ,  it seems to be related to CardinalMobile framework. @scannillo

**Comment by sestevens** [comment]
Thanks for providing the logs, @ds12g. We're looking into the issue and will update here once we know more.

**Comment by ds12g** [comment]
Awesome, thanks @sestevens

**Comment by sestevens** [comment]
**UPDATE**: This seems to be an issue with the latest version of the CardinalMobile framework. We've reached out to Cardinal for support, and we'll update here once we have more information.

**Comment by pcjbird** [comment]
Looking forward to further information, thanks for your updating for the progress. @sestevens

**Comment by jamesyorke** [comment]
Same issue here ✋. Thanks for these updates!

**Comment by sestevens** [comment]
**UPDATE**: We believe version 4.26.1 resolves this issue. Please try updating and let us know if the issue is still occurring.

**Comment by pcjbird** [comment]
Nice & Great, the version 4.26.1 has resolved this issue, really awesome technical support. @sestevens
