### ISSUE TITLE
facing issue in braintree

### ISSUE THREAD

**Issue by zeeshaneureka93** [braintree/braintree_ios#469]
<img width="1226" alt="Screen Shot 2019-08-01 at 6 38 46 PM" src="https://user-images.githubusercontent.com/39118827/62298113-d3e58900-b48b-11e9-92bb-bae129725243.png">

**Comment by scannillo** [comment]
Hello @zeeshaneureka93. Our GH issues has a template with information that you should fill out that will be helpful for us to better understand your issue. Can you provide this information?

--------------------------------------------
* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version: 


To help us quickly reproduce your issue, include as many details as possible, such as logs, steps to reproduce, and so on.

**Comment by zeeshaneureka93** [comment]
sdk library version : Braintree (4.25.1)
Environment: sandbox. its compile time issue,i am not able to compile project
ios version : 11 ,device : iphone 8
cocoapods : 1.6.0.beta.2

**Comment by zeeshaneureka93** [comment]
i am attaching screen shots for header search path and other linker flag also from project build settings.
<img width="1176" alt="Screen Shot 2019-08-02 at 10 52 41 AM" src="https://user-images.githubusercontent.com/39118827/62347616-afcd8a80-b513-11e9-9384-f2149dec1876.png">
<img width="1142" alt="Screen Shot 2019-08-02 at 10 51 55 AM" src="https://user-images.githubusercontent.com/39118827/62347639-cb389580-b513-11e9-8497-2564afeec790.png">

**Comment by scannillo** [comment]
Hello. @cooperbarth and I here from Braintree. You shouldn't need to 

Some ideas:
- Are you trying to compile in the workspace and not the project?
- Did you run pod install prior?
- Did you try clearing your derived data and trying again?

**Comment by zeeshaneureka93** [comment]
no, i am trying to build it inside project. i have added it as a dependency using cocoapods.
also i had run pod install.

**Comment by scannillo** [comment]
It is hard for us to help a ton when we can't reproduce your issue yet. Can you send over your podfile?

**Comment by zeeshaneureka93** [comment]
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'AppDoing' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks

pod 'Alamofire', '~> 4.0'
pod 'SwiftyJSON'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

pod 'BraintreeDropIn'
pod 'Braintree/PayPal'
pod 'Braintree/Venmo'

# cards
pod 'AnimatedCollectionViewLayout'

#CreditCardForm is iOS framework that allows developers to create the UI which replicates an actual Credit Card.
pod 'CreditCardForm'
pod 'Stripe'

#SnapKit is a DSL to make Auto Layout easy on both iOS and OS X.
pod 'SnapKit', '~> 3'
#pod 'SnapKit', '~> 4.0'

#pod 'IQKeyboardManagerSwift', '~> 4.0.8'
pod 'IQKeyboardManagerSwift', '~> 5.0'

#A beautiful and flexible text field control implementation of "Float Label Pattern". Written in Swift.
pod 'SkyFloatingLabelTextField', '~> 2.0.0'

#A drop-in replacement for UISegmentedControl mimicking the style of the segmented control
#used in Google Currents and various other Google products
pod 'HMSegmentedControl'

#DLRadioButton is an easy to use and highly customizable radio buttons control for iOS. It's a subclass of UIButton, and works smoothly with both Objective-C and Swift.
pod 'DLRadioButton', '~> 1.4'

#Network abstraction layer written in Swift.
pod 'Moya', '~> 8.0.5'

#Map objects through SwiftyJSON in combination with Moya
pod 'Moya-SwiftyJSONMapper', '~> 2.2.0' 

#Swift Logging Utility for Xcode & Google Docs
pod 'QorumLogs'

#Replacement for Apple's Reachability re-written in Swift with closures
pod 'ReachabilitySwift', '~> 3'

#Quickly reproduce the dropdown UIPickerView / ActionSheet functionality on iOS
pod 'ActionSheetPicker-3.0'

#This is a selection of custom page controls to replace UIPageControl, inspired by a dribbble found here
pod 'PageControls/SnakePageControl'


#iOS Country picker with flags and optionally phone numbers written in Swift
pod 'MRCountryPicker'

pod 'AWSS3'

#A lightweight, pure-Swift library for downloading and caching images from the web.
pod 'Kingfisher', '~> 3.0'

#A custom reusable slider control with 2 thumbs (range slider).
pod 'MARKRangeSlider'

#A Swift framework for parsing, formatting and validating international phone numbers. Inspired by Google's libphonenumber.
#pod 'PhoneNumberKit', '~> 2.0'
pod 'PhoneNumberKit', '~> 2.1'

#Swift image slideshow with circular scrolling, timer and full screen viewer
pod 'ImageSlideshow'
pod 'ImageSlideshow/Kingfisher'

pod 'FAPaginationLayout'
pod 'HSCycleGalleryView'

# for the Google Places API for iOS and use it to install the API and its dependencies:
#pod 'GooglePlaces'
#pod 'GooglePlacePicker'
#pod 'GoogleMaps'

pod 'GooglePlaces', '~> 2.4'
pod 'GooglePlacePicker', '~> 2.4'
pod 'GoogleMaps', '~> 2.4'
#A drop-in replacement for UILabel that supports attributes, data detectors, links, and more
pod 'TTTAttributedLabel'

#pod 'ImageSlideShowSwift'

#fave-button for like button animation
#pod 'FaveButton', '~> 2.0.3'

#For Twitter post with image and text
pod 'Fabric'
pod 'TwitterKit'
pod 'ICSPullToRefresh'

#Easy access to iOS address book
pod 'APAddressBook/Swift'

# A Swift Binding Framework
#pod 'Bond', '6.10.2'

#Google Analytics
pod 'GoogleAnalytics'
pod 'Google/Analytics'

# Application Loader/ HUD
pod 'PKHUD', '~> 5.0'

#ToolTip PopUP
pod 'EasyTipView', '~> 1.0.2'

pod "GTProgressBar"
end

**Comment by zeeshaneureka93** [comment]
here is my podfile. i also tried by updating cocoapods but still same issue.
[Podfile.zip](https://github.com/braintree/braintree_ios/files/3475668/Podfile.zip)

**Comment by zeeshaneureka93** [comment]
any update on this issue ?

**Comment by scannillo** [comment]
Hi. We are still unable to replicate your case. Also, you are using braintree-ios-drop-in, so you can find more conversations regarding that [repository here](https://github.com/braintree/braintree-ios-drop-in). 

> no, i am trying to build it inside project. 

When using Cocoapods you need to work in the `.xcworkspace` not the `.xcodeproj`.

I would try removing these pods, and starting fresh. There are good instructions [on cocoapods.org here](https://guides.cocoapods.org/using/using-cocoapods.html). Also, when using Cocoapods you don't need to manually handle header search paths.

**Comment by sestevens** [comment]
@zeeshaneureka93 Were you able to resolve this issue?
