### ISSUE TITLE
Custom permission altert?

### ISSUE THREAD

**Issue by deda9** [braintree/braintree_ios#470]
Hallo Guys,

Thank you for that effort for that SDK, I've been searching for a while in the documentation and the closed issue before about how can I customize the permission alert? Is there any way to customize this alert? Thank you for support :)

<img width="335" alt="Screen Shot 2019-08-05 at 10 08 32 PM" src="https://user-images.githubusercontent.com/6483622/62491952-a3745680-b7cd-11e9-826f-88dab2b1d574.png">

**Comment by scannillo** [comment]
Hello @deda9. No, we don't offer a way to customize these alerts.

**Comment by deda9** [comment]
@scannillo Thank you :))

**Comment by deda9** [comment]
Thank you @scannillo,
What about if we need to reduce the number of the taps for the user and we need to directly forward the user into Paypal page without showing this alert? Is it possible?

**Comment by scannillo** [comment]
No, the alert requesting information is required.

**Comment by developer-mobile-apple** [comment]
https://github.com/braintree/braintree_ios/issues/496

**Comment by developer-mobile-apple** [comment]
@scannillo : can you please take a look at https://github.com/braintree/braintree_ios/issues/496.
Also, one more question, is this same applies for Android or this is case for iOS guideline?

**Comment by sestevens** [comment]
@developer-mobile-apple This alert is specific to iOS. As I mentioned, we unfortunately do not have control over when it is presented.
