### ISSUE TITLE
BTPostalAddress Locality Property Not Respecting _Nonnull Annotation

### ISSUE THREAD

**Issue by springstephen** [braintree/braintree_ios#472]
### General information

* SDK/Library version: 4.17
* Environment: Production
* iOS Version and Device: iOS 12.4 - iPad Pro (12.9-inch, 3rd generation)
* Integration type and version: Carthage
* Language: Objective-c

### Issue description

The locality property on BTPostalAddress is marked as _Nonnull, but sometimes value is nil. I'm experiencing this when calling the requestBillingAgreement method on BTPayPalDriver. A BTPayPalAccountNonce object is provided in callback. It's the billingAddress property on the nonce that has the locality property that is marked as _Nonnull, but sometimes is nil. Unfortunately this is causing our app to crash because we are putting this value in a dictionary.

**Comment by sestevens** [comment]
Hi @springstephen. We'll investigate this issue. Thanks for bringing it to our attention!

**Comment by sestevens** [comment]
We corrected the nullability annotations for `BTPostalAddress` in [version 4.3.0](https://github.com/braintree/braintree_ios/releases/tag/4.30.0).
