### ISSUE TITLE
Typo in the path to derived data in Rakefile

### ISSUE THREAD

**Issue by martianplatypus** [braintree/braintree_ios#474]
### General information

* SDK/Library version: 4.26.3
* Environment: Production
* iOS Version and Device: N/A
* Integration type and version: Carthage 0.33.0
* Ruby version: 2.5.1 (rbenv)
* Rbenv: 1.1.2

### Issue description

In the task clean within the name space carthage, the path to derived data contains a typo that causes rake to be aborted.

Update the path to `~/Library/Developer/Xcode/DerivedData`

### Actual behavior
When clean is executed: `bundle exec rake carthage:clean` the following error occurs:
``` 
$ rm -rf Carthage && rm Cartfile && rm Cartfile.resolved && rm -rf ~/Library/Developers/Xcode/DerivedData
rm: Cartfile.resolved: No such file or directory
rake aborted!
Command failed with non-zero exit status pid 44279 exit 1:
$ rm -rf Carthage && rm Cartfile && rm Cartfile.resolved && rm -rf ~/Library/Developers/Xcode/DerivedData
/Users/martianplatypus/Dev/github/braintree_ios/Rakefile:43:in `run!'
/Users/martianplatypus/Dev/github/braintree_ios/Rakefile:128:in `block (2 levels) in <top (required)>'
/Users/martianplatypus/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/Users/martianplatypus/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
Tasks: TOP => carthage:clean
(See full trace by running task with --trace)
```

### Expected behavior

When clean is executed, derived data is wiped out along with other carthage folders and files and the execution is not aborted.

**Comment by martianplatypus** [comment]
Also, If the goal is to clean Carthage, would make sense to clean its cache in `~/Library/Caches/org.carthage.CarthageKit` ?

`run! 'rm -rf Carthage && rm Cartfile && rm Cartfile.resolved && rm -rf ~/Library/Developer/Xcode/DerivedData' && rm -rf ~/Library/Caches/org.carthage.CarthageKit`

**Comment by sestevens** [comment]
Hi @martianplatypus! `rake carthage:clean` is meant to be run as part of our release script. There's a previous step that creates a Cartfile in our demo app to verify that the SDK can be imported successfully with Carthage. If you run `rake sanity_checks` you'll see that everything runs fine.

Is there a reason you're trying to run `rake carthage:clean` on its own?

**Comment by martianplatypus** [comment]
Hi @sestevens, thanks for the quick update. 

I ran `rake carthage:clean` out of curiosity, that's when the execution failed and I noticed the derived data path was different than the standard. 

The SDK is working flawlessly in my app. Feel free to close this issue if no other tasks are executing `clean` internally or if the path is right in your CI machines.
