### ISSUE TITLE
Can't distribute app - failed to compile CardinalMobile.armv7.xar

### ISSUE THREAD

**Issue by JordanGrigg** [braintree/braintree_ios#478]
### General information

* SDK/Library version: 4.27.1
* Environment: Production
* iOS Version and Device: Any
* Integration type and version: Cocoapods 1.7.5

### Issue description

When trying to distribute app from xcode, I reach the 'compiling bitcode' stage, before receiving a non-zero exit exception from ipatool with the below error.
This has only occurred since updating to the latest Braintree SDK, but it has been a while since last performing a build action.
Is the mentioned CardinalMobile connected to Braintree, or is it coincidental and the problem lies elsewhere?

Thanks,
     Jordan

`ipatool failed with an exception: #<CmdSpec::NonZeroExcitException: Command exited with pid 22086 exit 1:
/Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -o /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/ipatool20190902-20603-1nbz83s/thinned-out/armv7/Payload/[app name].app/Frameworks/CardinalMobile.framework/CardinalMobile --generate-dsym /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/ipatool20190902-20603-1nbz83s/thinned-out/armv7/Payload/[app name].app/Frameworks/CardinalMobile.framework/CardinalMobile.dSYM --strip-swift-symbols /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/ipatool20190902-20603-1nbz83s/thinned-in/armv7/Payload/[app name].app/Frameworks/CardinalMobile.framework/CardinalMobile
Stdout:
    Debug: SDK path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk
    Debug: PATH: ['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin', '/Applications/Xcode.app/Contents/Developer/usr/bin']
    Debug: Using: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo
    MachoInfo: cd /
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo" "-info" "/var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/ipatool20190902-20603-1nbz83s/thinned-in/armv7/Payload/[app name].app/Frameworks/CardinalMobile.framework/CardinalMobile"
    -= Output =-
    Non-fat file: /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/ipatool20190902-20603-1nbz83s/thinned-in/armv7/Payload/[app name].app/Frameworks/CardinalMobile.framework/CardinalMobile is architecture: armv7
    Exited with 0
    Debug: Command took 0 seconds
    Debug: Using: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dwarfdump
    GetUUID: cd /
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dwarfdump" "-u" "/var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/ipatool20190902-20603-1nbz83s/thinned-in/armv7/Payload/[app name].app/Frameworks/CardinalMobile.framework/CardinalMobile"
    -= Output =-
    UUID: 34033C3F-BB41-35F9-A19F-ABC38A2D6E13 (armv7) /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/ipatool20190902-20603-1nbz83s/thinned-in/armv7/Payload/[app name].app/Frameworks/CardinalMobile.framework/CardinalMobile
    Exited with 0
    
    Debug: Command took 0 seconds
    Debug: Using: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/segedit
    ExtractXAR: cd /
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/segedit" "/var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/ipatool20190902-20603-1nbz83s/thinned-in/armv7/Payload/[app name].app/Frameworks/CardinalMobile.framework/CardinalMobile" "-extract" "__LLVM" "__bundle" "/var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/CardinalMobilefppxR4/CardinalMobile.armv7.xar"
    -= Output =-
    Exited with 0
    
    Debug: Command took 0 seconds
    Debug: Bitcode bundle version: 1.0
    Debug: Setting platform to: iOS
    Debug: Using: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
    Debug: Using: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
    Clang: cd /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/tempDLLEQP
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" "-cc1" "-triple" "thumbv7-apple-ios9.0.0" "-emit-obj" "-disable-llvm-passes" "-target-abi" "apcs-gnu" "-mfloat-abi" "soft" "-Os" "-mllvm" "-arm-bitcode-compatibility" "-mllvm" "-fast-isel=0" "-x" "ir" "01" "-o" "01.o"
    -= Output =-
    Exited with 0
    
    Debug: Command took 0 seconds
    Clang: cd /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/tempDLLEQP
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" "-cc1" "-triple" "thumbv7-apple-ios9.0.0" "-emit-obj" "-disable-llvm-passes" "-target-abi" "apcs-gnu" "-mfloat-abi" "soft" "-Os" "-mllvm" "-arm-bitcode-compatibility" "-mllvm" "-fast-isel=0" "-x" "ir" "02" "-o" "02.o"
    -= Output =-
    Exited with 0
    
    Debug: Command took 0 seconds
    Clang: cd /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/tempDLLEQP
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" "-cc1" "-triple" "thumbv7-apple-ios9.0.0" "-emit-obj" "-disable-llvm-passes" "-target-abi" "apcs-gnu" "-mfloat-abi" "soft" "-Os" "-mllvm" "-arm-bitcode-compatibility" "-mllvm" "-fast-isel=0" "-x" "ir" "03" "-o" "03.o"
    -= Output =-
    Exited with 0
    
    Debug: Command took 0 seconds
    Clang: cd /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/tempDLLEQP
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" "-cc1" "-triple" "thumbv7-apple-ios9.0.0" "-emit-obj" "-disable-llvm-passes" "-target-abi" "apcs-gnu" "-mfloat-abi" "soft" "-Os" "-mllvm" "-arm-bitcode-compatibility" "-mllvm" "-fast-isel=0" "-x" "ir" "04" "-o" "04.o"
    -= Output =-
    Exited with 0
    
    Debug: Command took 0 seconds
    Clang: cd /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/tempDLLEQP
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" "-cc1" "-triple" "thumbv7-apple-ios9.0.0" "-emit-obj" "-disable-llvm-passes" "-target-abi" "apcs-gnu" "-mfloat-abi" "soft" "-Os" "-mllvm" "-arm-bitcode-compatibility" "-mllvm" "-fast-isel=0" "-x" "ir" "05" "-o" "05.o"
    -= Output =-
    Exited with 0
    
    Debug: Command took 0 seconds
    Clang: cd /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/tempDLLEQP
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" "-cc1" "-triple" "thumbv7-apple-ios9.0.0" "-emit-obj" "-disable-llvm-passes" "-target-abi" "apcs-gnu" "-mfloat-abi" "soft" "-Os" "-mllvm" "-arm-bitcode-compatibility" "-mllvm" "-fast-isel=0" "-x" "ir" "06" "-o" "06.o"
    -= Output =-
    Exited with 0
    
    Debug: Command took 0 seconds
    Clang: cd /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/tempDLLEQP
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" "-cc1" "-triple" "thumbv7-apple-ios9.0.0" "-emit-obj" "-disable-llvm-passes" "-target-abi" "apcs-gnu" "-mfloat-abi" "soft" "-Os" "-mllvm" "-arm-bitcode-compatibility" "-mllvm" "-fast-isel=0" "-x" "ir" "07" "-o" "07.o"
    -= Output =-
    Exited with 0
    
    Debug: Command took 0 seconds
    error: Clang: cd /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/tempDLLEQP
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" "-cc1" "-triple" "thumbv7-apple-ios9.0.0" "-emit-obj" "-disable-llvm-passes" "-target-abi" "apcs-gnu" "-mfloat-abi" "soft" "-Os" "-mllvm" "-arm-bitcode-compatibility" "-mllvm" "-fast-isel=0" "-x" "ir" "08" "-o" "08.o"
    -= Output =-
    Intrinsic has incorrect argument type!
    void (i8*, i8, i32, i1)* @llvm.memset.p0i8.i32
    fatal error: error in backend: Broken module found, compilation aborted!
    Exited with 70
    
    
    error: Failed to compile bundle: /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/CardinalMobilefppxR4/CardinalMobile.armv7.xar
    
    error: Clang: cd /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/tempDLLEQP
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" "-cc1" "-triple" "thumbv7-apple-ios9.0.0" "-emit-obj" "-disable-llvm-passes" "-target-abi" "apcs-gnu" "-mfloat-abi" "soft" "-Os" "-mllvm" "-arm-bitcode-compatibility" "-mllvm" "-fast-isel=0" "-x" "ir" "21" "-o" "21.o"
    -= Output =-
    error: error reading '21'
    1 error generated.
    Exited with 1
    
    
    error: Failed to compile bundle: /var/folders/fh/tdvp3gxd4715ldbtddc76mch0000gn/T/CardinalMobilefppxR4/CardinalMobile.armv7.xar
    

Stderr:

>
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:248:in `run'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2463:in `block in CompileOrStripBitcodeInBundle'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2396:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2396:in `CompileOrStripBitcodeInBundle'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2628:in `ProcessIPA'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:3445:in `<main>'`

**Comment by sestevens** [comment]
Hi @JordanGrigg. CardinalMobile is used by the Braintree SDK. I'm having trouble reproducing this error, though. When I archive and distribute an app with the Braintree SDK through Xcode, everything works fine. Are you aware of any specific steps to reproduce?

**Comment by JordanGrigg** [comment]
Resolved by updating to latest xcode version, thank you
