### ISSUE TITLE
Cookies must be enabled to use bank eService - Finnish banks specifically

### ISSUE THREAD

**Issue by lnknguyen-Parkman** [braintree/braintree_ios#483]
### General information

* SDK/Library version: 4.28.0
* Environment: Production
* iOS Version and Device: iOS 12.3.1 - iPhone 6s
* Integration type and version: CocoaPods 1.6.1
* Language: Swift

### Issue description

Finnish banks require cookies to be enabled during 3D authentication. Seems like there is an issue with cookies policies for `SFSafariViewController`.

I attached the screenshots below for 2 cases: Nordea and OP bank.
![op](https://user-images.githubusercontent.com/24432275/64847384-90984180-d617-11e9-8963-05d80500d1a6.png)
![nordea](https://user-images.githubusercontent.com/24432275/64847388-92620500-d617-11e9-85e5-7dd37fe0e73b.png)

**Comment by hollabaq86** [comment]
Hi @lnknguyen-Parkman, thanks for reaching out. Please [contact Support](https://help.braintreepayments.com) with this screenshot and any timestamps or info that can help us identify the card that was used in the verification attempt. We will need to partner with our MPI Service provider Cardinal Commerce to escalate this issue to the card networks and issuing bank(s) that is/are incorrectly requiring cookies.
