### ISSUE TITLE
Venmo integration doesn't work on iOS 13

### ISSUE THREAD

**Issue by evnik** [braintree/braintree_ios#484]
### General information

* SDK/Library version: Braintree/Venmo 4.16.0
* Environment: Production
* iOS Version and Device: iOS 13 GM seed on an iPhone XR
* Integration type and version: CocoaPods 1.6.0

### Issue description

The integration we have in our app works fine on iOS 12 and older and doesn't work on iOS 13. 
1. From the app side we invoke `[BTVenmoDriver authorizeAccountAndVault:completion:]`
1. User is navigated to Venmo app
1. When user is navigated from Venmo app back to our app, the `[UIApplicationDelegate application:openURL:options:]` is called by iOS
1. The app checks if the URL scheme matches to the Braintree scheme and invokes `[BTAppSwitch handleOpenURL:sourceApplication:]` passing both URL and `sourceApplication`
1. There is a check `[sourceApplication hasPrefix:@"net.kortina.labs.Venmo"]` in the `[BTVenmoAppSwitchReturnURL isValidURL:sourceApplication:]`

The issue here is iOS 13 [doesn't set](https://developer.apple.com/documentation/uikit/uiapplicationopenurloptionssourceapplicationkey#discussion) value for the `UIApplicationOpenURLOptionsSourceApplicationKey` when Venmo app navigates to our app:
> If the request originated from another app belonging to your team, UIKit sets the value of this key to the ID of that app. If the team identifier of the originating app **is different** than the team identifier of the current app, the value of the key is `nil`.

Therefore the check on the step 5 returns false and completion block set on the step 1 is not called.

We use relatively old version of Braintree, but I don't see any relevant changes in the [`BTVenmoAppSwitchReturnURL.m`](https://github.com/braintree/braintree_ios/blob/master/BraintreeVenmo/BTVenmoAppSwitchReturnURL.m).

As a temporary fix we forge value of the `sourceApplication` if the URL scheme matches to the Braintree scheme. But we would like to have it fixed on the Braintree iOS SDK side.

**Comment by scannillo** [comment]
Hello @evnik. Thanks for opening this issue. We will investigate and get back to you as soon as we can 👍

**Comment by scannillo** [comment]
Hi again. We were able to replicate what you're seeing. Will post here once we put out a fix! Thank you for bringing this to our attention.

**Comment by demerino** [comment]
This should be fixed in release 4.29.0
