### ISSUE TITLE
Carthage Submodule Integration Results in Dirty Submodule

### ISSUE THREAD

**Issue by dmiluski** [braintree/braintree_ios#485]
### General information

* SDK/Library version: "4.28.0"
* Environment: N/A
* iOS Version and Device: (Occurs in SDK integration)
* Integration type and version: Carthage 0.33.0

### Issue description

When integrating braintree_ios version `4.28.0` we noticed our submodule directories being dirtied on  boostrap.

Given Cartfile.resolved containing
```
github "braintree/braintree_ios" "4.28.0"
```

And installing dependencies via command via submodules
```
#!/usr/bin/env sh

set -eu

PLATFORMS="ios"

carthage bootstrap --no-build --use-ssh --use-submodules --platform "$PLATFORMS" "$@"
```

The integrated submodule is immediately dirty Project Directory:
<img width="542" alt="Screen Shot 2019-09-18 at 8 50 30 AM" src="https://user-images.githubusercontent.com/5083390/65164275-741e4f80-d9f1-11e9-8293-6ea118c315d1.png">

Then Submodule Directory:
<img width="489" alt="Screen Shot 2019-09-18 at 8 52 04 AM" src="https://user-images.githubusercontent.com/5083390/65164382-a0d26700-d9f1-11e9-8440-6d05a55ccd4a.png">

## Why ❓ 
When Carthage dependencies have dependencies themselves, Carthage resolves those versions and pulls in the tree of dependencies in the top level of the project and SYMLinks to the dependency directory.

## Requested Fix
Ignore this file in BT .gitignore

```
# Carthage
#
# Add this line if you want to avoid checking in source code from Carthage dependencies.
Carthage/Checkouts
Carthage/Build
```

**Comment by scannillo** [comment]
Hey @dmiluski. 
> we noticed our submodule directories being dirtied

I don't know what you mean by this.

CardinalMobile is the provider we use for ThreeDSecure verifications. It is not included in our SDK by mistake and therefore we don't want to add it to our SDKs `.gitignore`. You can instead add it to your app's `.gitignore` if you don't want to utilize ThreeDSecure.
