### ISSUE TITLE
isiOSAppAvailableForAppSwitch Is Retrun true Every time

### ISSUE THREAD

**Issue by codal-jayeshk** [braintree/braintree_ios#487]
### General information

* SDK/Library version: 4.27.0
* Environment: Production
* iOS Version and Device: iOS 12.4 
* Integration type and version: Pod

### Issue description

Hello 

I am checking that Venmo app is available for switch but it returns every time true.also I check that I miss anything on setup but I have added URL Types and also I added method in open url in AppDelegate.

  let btClient = BTAPIClient(authorization:token)!
  let venmoDriver = BTVenmoDriver(apiClient: btClient)
  if venmoDriver.isiOSAppAvailableForAppSwitch() {
 }

// returning true every time like also return true if app is not installed

**Comment by scannillo** [comment]
For context, here is the [implementation](https://github.com/braintree/braintree_ios/blob/214c01b8db5fcb965f59ff3f7be56f1536ecf2ef/BraintreeVenmo/BTVenmoDriver.m#L213-L216) of the method `isiOSAppAvailableForAppSwitch`.

I am unable to replicate your issue of having `isiOSAppAvailableForAppSwitch` always returning true. When run on a device without the Venmo app installed, `[self.venmoDriver isiOSAppAvailableForAppSwitch]` returns `NO`. When the app installed, it returns `YES` as expected. 

Can you verify that all of [these steps](https://developers.braintreepayments.com/guides/venmo/client-side/ios/v4) to set up your URL scheme are proper?

Any other additional details to help us replicate will be appreciated!

**Comment by scannillo** [comment]
We release a fix for this with our 4.29.0 release. https://github.com/braintree/braintree_ios/releases/tag/4.29.0
