### ISSUE TITLE
Unable to update braintree

### ISSUE THREAD

**Issue by phannindra** [braintree/braintree_ios#488]
### General information

* SDK/Library version: 4.28.0
* Environment: Sandbox
* iOS Version and Device: macOs 10.14.6
* Integration type and version: Carthage 0.32.0

### Issue description

Xcode version: 10.3

carthage update --platform ios
*** Fetching braintree-ios-drop-in
*** Fetching braintree_ios
*** Downloading binary-only framework CardinalMobile at "https://raw.githubusercontent.com/braintree/braintree_ios/master/Frameworks/CardinalMobile.json"
*** Checking out braintree_ios at "4.28.0"
*** Checking out braintree-ios-drop-in at "7.4.0"
*** xcodebuild output can be found in /var/folders/gk/9z9j8gcd5qq68x2v2tg881nm0000gp/T/carthage-xcodebuild.bPLhgk.log
*** Downloading binary-only framework CardinalMobile at "https://raw.githubusercontent.com/braintree/braintree_ios/master/Frameworks/CardinalMobile.json"
*** Building scheme "BraintreeAmericanExpress" in Braintree.xcworkspace
*** Building scheme "Braintree3DSecure" in Braintree.xcworkspace
*** Building scheme "BraintreeApplePay" in Braintree.xcworkspace
*** Building scheme "BraintreeCard" in Braintree.xcworkspace
*** Building scheme "BraintreeCore" in Braintree.xcworkspace
*** Building scheme "BraintreeDataCollector" in Braintree.xcworkspace
*** Building scheme "BraintreePaymentFlow" in Braintree.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/.../Carthage/Checkouts/braintree_ios/Braintree.xcworkspace -scheme BraintreePaymentFlow -configuration Release -derivedDataPath /Users/phanindra/Library/Caches/org.carthage.CarthageKit/DerivedData/10.3_10G8/braintree_ios/4.28.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/gk/9z9j8gcd5qq68x2v2tg881nm0000gp/T/braintree_ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/…/Carthage/Checkouts/braintree_ios)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/gk/9z9j8gcd5qq68x2v2tg881nm0000gp/T/carthage-xcodebuild.bPLhgk.log

**Comment by scannillo** [comment]
Hi. I had no problems running `carthage update --platform ios` while using the latest carthage version `0.33.0`.I would suggest updating, even though this is likely not the cause of your problem

Have you previously integrated this project with `braintree-ios-drop-in` via Carthage before, or is this your first time? If it isn't your first time, I would try removing the Braintree dependencies from your app and the `Carthage/Build/iOS` and `Carthage/Checkout` directories entirely and trying again.

**Comment by phannindra** [comment]
thanks. It did work for me.
