### ISSUE TITLE
UI API called from background thread

### ISSUE THREAD

**Issue by shial4** [braintree/braintree_ios#491]
### General information

* SDK/Library version: 4.29.0
* Environment: Xcode 11 & iOS 13
* iOS Version and Device: All of them,
* Integration type and version: CocoaPods 1.8.1

### Issue description

**Braintree Core, BTHTTP**
Line 212

```
 // Perform the actual request
    NSURLSessionTask *task = [self.session dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
        [self handleRequestCompletion:data response:response error:error completionBlock:completionBlock];
    }];
    [task resume];
```

**Comment by billwerges** [comment]
Hi @shial4,

This isn't an issue, as `handleRequestCompletion:response:error:completionBlock` is an internal method, and doesn't directly effect UI. Before control leaves this class, we do return back to the original thread here:

https://github.com/braintree/braintree_ios/blob/bc627c5f1a6e123b64cb7305048c1b43752daad6/BraintreeCore/BTHTTP.m#L293
