### ISSUE TITLE
Lost all payment method after payment with apple pay.

### ISSUE THREAD

**Issue by Donhv** [braintree/braintree_ios#492]
i have issue with recent PaymentMethod. When i save a paymentMethod then payment with apple pay, braintree delete all recent paymentMethod get by apiClient fetchPaymentMethodNonces.

**Comment by Donhv** [comment]
Sorry, i only happen in android.

**Comment by sestevens** [comment]
Hi @Donhv, I saw that you closed a [similar issue](https://github.com/braintree/braintree_android/issues/271) in our Android repo. Were you able to resolve this issue on iOS as well?
