### ISSUE TITLE
Pull Request regression 

### ISSUE THREAD

**Issue by rjstelling** [braintree/braintree_ios#493]
The PR: https://github.com/braintree/braintree_ios/pull/430

Was merged last November, however the master branch has regressed and the changes have vanished.

**Comment by billwerges** [comment]
Hi @rjstelling,

From what I can tell, the changes are still present:
https://github.com/braintree/braintree_ios/blob/bc627c5f1a6e123b64cb7305048c1b43752daad6/BraintreeCore/BTAPIClient_Internal.h#L74

Is there something else you're seeing that is different?

**Comment by rjstelling** [comment]
I think some how I ended up with an old version in a project. 

Sorry for the confusion.
