### ISSUE TITLE
Callback for BTAppSwitchDelegate and BTViewControllerPresentingDelegate are never called

### ISSUE THREAD

**Issue by kcw-grunt** [braintree/braintree_ios#494]
### General information
Using cocoapod SDK 4.29.0

### Issue description
When using these delegates :

        let payPalDriver = BTPayPalDriver(apiClient: btAPIClient)
        payPalDriver.viewControllerPresentingDelegate = self
        payPalDriver.appSwitchDelegate = self

We are expecting a callback to manage the views.  But, we get no callback:

extension BraintreePaymentInfoVC: BTAppSwitchDelegate, BTViewControllerPresentingDelegate {
    
    // MARK: - BTAppSwitchDelegate
    
    func appSwitcherWillPerformAppSwitch(_ appSwitcher: Any) {
        NSLog("BRAINTREE: App Switcher will perform switch")
    }
    
    func appSwitcher(_ appSwitcher: Any, didPerformSwitchTo target: BTAppSwitchTarget) {
        NSLog("BRAINTREE: App Switcher did perform switch")
    }
    
    func appSwitcherWillProcessPaymentInfo(_ appSwitcher: Any) {
        NSLog("BRAINTREE: App Switcher will process payment")
    }

Please advise.

**Comment by billwerges** [comment]
Hi @kcw-grunt,

It looks like the method's you've listed above are only related to the `BTAppSwitchDelegate` protocol. When using `BTPayPalDriver`, the `BTViewControllerPresentingDelegate` methods are what will be used. 

Have you implemented 
`func paymentDriver(_ driver: Any, requestsPresentationOf viewController: UIViewController)` 
and 
`func paymentDriver(_ driver: Any, requestsDismissalOf viewController: UIViewController)`?

**Comment by kcw-grunt** [comment]
Thanks for the quick response @billwerges.  I'll report back.

**Comment by sestevens** [comment]
@kcw-grunt Were you able to resolve this issue?

**Comment by deda9** [comment]
I am facing the same issue, neither of those functions are never called, any insights?

**Comment by aayubhagat295** [comment]
I am also facing the same issue, BTViewControllerPresentingDelegate are not called.

**Comment by gfalasca** [comment]
Me too, same issue, BTViewControllerPresentingDelegate not being called. Any news?

**Comment by sestevens** [comment]
@gfalasca Could you open a new issue with steps to reproduce? This issue was closed because the original poster's issue seems to have been resolved. There are a variety of different reasons why a delegate method might not be called. We'll need more information in order to help you troubleshoot.
