### ISSUE TITLE
Duplicate warning in Xcode in BTConfiguration+ApplePay.h

### ISSUE THREAD

**Issue by ethanwa** [braintree/braintree_ios#495]
I have the following in my Pod file and my pods are up to date:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.2'
use_frameworks!

target 'collectors' do
    pod 'Braintree'
    pod 'BraintreeDropIn'
    pod 'Braintree/Venmo'
    pod 'Braintree/Apple-Pay'
end
```

When I build in Xcode, I am getting the following Warning in BTConfiguration+ApplePay.h:

<img width="764" alt="Screen Shot 2019-10-10 at 5 58 13 PM" src="https://user-images.githubusercontent.com/1653780/66609761-e06f1780-eb87-11e9-96e6-23545a84cb96.png">

`Duplicate definition of category 'ApplePay' on interface 'BTConfiguration'`

**Comment by scannillo** [comment]
Hello @ethanwa. It looks like you might be twice importing the Apple Pay module. It'll be helpful if we can get some more details to replicate this issue.

Is your app written in Swift or ObjectiveC? Potentially you're using a bridging header to import Apple Pay, when you don't need to be?

Also removing all of the pods `rm -rf Pods` and then running `pod install` again might help.

Please let us know more details on your integration.

**Comment by ethanwa** [comment]
The bridging header was the problem. Thanks for pointing me in the right direction!
