### ISSUE TITLE
Paypal payment always presenting sign-in alert

### ISSUE THREAD

**Issue by developer-mobile-apple** [braintree/braintree_ios#496]
Hi All,
I'm using Pay with Paypal functionality using the below API of this SDK.
```
 payPalDriver.requestBillingAgreement(request) { (tokenizedPayPalAccount, error) -> Void in
 }
```
But it seems like, it is always asking for sign in permission before presenting PayPal controller in `SFSafariViewController`
Once signed in, it won't ask for credentials again but this alert is redundant every time the user click PayPal button.
![Untitled](https://user-images.githubusercontent.com/33049810/67543008-fb579500-f70c-11e9-824f-f1a97f672429.png)
Ideally, we're expecting this alert at first-time only, is there any way to achieve it?

**Comment by sestevens** [comment]
Hi @developer-mobile-apple 👋 This alert is presented by Apple before starting an `SFAuthenticationSession`. This is not something Braintree has control over.

Here is what Apple says in their [documentation](https://developer.apple.com/documentation/safariservices/sfauthenticationsession) for the `SFAuthenticationSession` `start` method:
> Starts the session after initializing an instance of SFAuthenticationSession. This will trigger the consent dialog.

**Comment by developer-mobile-apple** [comment]
Thanks @sestevens, this helps!
