### ISSUE TITLE
Notify PayPal payment with Braintree on iOS to PayPal IPN

### ISSUE THREAD

**Issue by csimone86** [braintree/braintree_ios#497]
I have a web site where customers can pay with PayPal. Then I have created a paypal IPN where Paypal notify me the results of payment transactions. In my IPN I set as **sold** the goods.

Now I want to replicate the same flow in my new iOS app. I have correctly integrated **[checkout flow](https://developers.braintreepayments.com/guides/paypal/checkout-with-paypal/ios/v4)** with BrainTree in my app. 
The payment works correctly but I do not receive any notification in my IPN. Paypal never notify me the  payment transactions.

I do not understand how to say Paypal  to call my IPN after user complete the payment.

Can anyone helpme please?

Thank you

**Comment by sestevens** [comment]
Hi @csimone86! The Braintree SDK does not directly support PayPal IPNs. I would recommend reaching out to [PayPal Technical Support](https://www.paypal-techsupport.com/s/login/) for assistance.

**Comment by csimone86** [comment]
Hi @sestevens . Thank you. 
Does Braintree SDK support PayPal Webhooks?

In my personal configuration page on BrainTree I can see I can create a New webhook called **Completed** and its description is **A payment using a Local Payment Method has completed**.

But what you mean with "Local Payment Method"?

Thank you

**Comment by sestevens** [comment]
Here's our [overview page](https://developers.braintreepayments.com/guides/local-payment-methods/overview) on Local Payment Methods.

For your question about using webhooks with Braintree, I would recommend reaching out to [Braintree Technical Support](https://help.braintreepayments.com/).

**Comment by csimone86** [comment]
Thank you @sestevens... I have read the overview page you linked to me, and not.... it is not what I need... 
BrainTree does not support IPNs...
 
So, I suppose the only way I can set the goods as sold is handling the result object of the Sale method... ```
Result<Transaction> transactionResult = gateway.Transaction.Sale(new TransactionRequest());
if (transactionResult.IsSuccess())
{
    //.... I set the goods as sold
}
else
{
// ... I suppose something went wrong during the payment. ie.: customer abbandoned transaction, no enough money on credit card., etc...
}
```


Correct?

**Comment by scannillo** [comment]
Hi @csimone86. Please reach out to the PayPal and/or Braintree support links that Susan posted above to point you in the right direction for your integration. 

Support will help troubleshoot your integration, whereas this issues tab is for reporting specific bugs/problems in our `braintree_ios` SDK. Feel free to reference this GH issue when you reach out to them.

**Comment by brega** [comment]
@csimone86 We are running into a similar issue. Did you manage to resolve this with Braintree or Paypal support channels?
