### ISSUE TITLE
Error with Vaultmanager

### ISSUE THREAD

**Issue by tlynchlaw** [braintree/braintree_ios#498]
### General information

* SDK/Library version: 4.30.0
* Environment: Sandbox
* iOS Version and Device: iOS 13 on iPhone 11 (actual device)
* Integration type and version: CocoaPods 1.8.4

### Issue description

Using vaultmanager to edit saved payment methods.  When deleting a method, am getting this error:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
*** First throw call stack:
(0x18664dc30 0x1863680c8 0x1866a65f4 0x1866b0414 0x1865345f0 0x186525e9c 0x102ab0e14 0x102aafa90 0x102ab0c00 0x1898aaffc 0x1898bb8dc 0x186a1dc60 0x18691f7e8 0x186a1ffbc 0x18691f464 0x186a209e8 0x186a204a8 0x105ad9a48 0x105acb2a8 0x105ace084 0x105acd468 0x105adcaac 0x105add418 0x18635aa60 0x186360c78)
libc++abi.dylib: terminating with uncaught exception of type NSException

vaultmanager working fine on the same phone in a different app we built.

**Comment by sestevens** [comment]
Hi @tlynchlaw 👋 Are you referring to the vault manager functionality in [Braintree Drop-In](https://github.com/braintree/braintree-ios-drop-in/)? If so, could you re-open this issue in that repo?

It would also be helpful if you could provide us with steps to reproduce the issue and/or a line number where the error occurs. Setting an [exception breakpoint](https://www.hackingwithswift.com/example-code/xcode/how-to-create-exception-breakpoints-in-xcode) in Xcode might help you get a line number.

I did a quick test in our Drop-In demo app, and I wasn't immediately able to reproduce the issue.

**Comment by tlynchlaw** [comment]
Moving to Braintree Drop-In

**Comment by tlynchlaw** [comment]
I moved it over.  Having some issues today with version 11.2 of Xcode so
will have to work that out before I can find the breakpoint.  Will post in
new location.

**Comment by sestevens** [comment]
Great, thank you!
