### ISSUE TITLE
How to get login customer country code?

### ISSUE THREAD

**Issue by devlove1C** [braintree/braintree_ios#499]
### General information

* SDK/Library version: 4.21.0
* Environment: sandbox
* iOS Version and Device: 13.1
* Integration type and version: Pod version 4.21.0

Issue description 
I try with your SDK, In SDK there is a class "requestBillingAgreement", we are using this class to submit a request to Paypal.

 Below code:-

`payPalDriver.requestBillingAgreement(request, completion: { (response, error) in 
})`

But in the **response** parameter we are not able to get country code.
Please help me how can I get the country code of **Paypal login** customer?

Thanks

**Comment by scannillo** [comment]
Hello @devlove1C. 

The `response` is of type `BTPayPalAccountNonce`. There is a property on `BTPayPalAccountNonce` called [`billingAddress`](https://github.com/braintree/braintree_ios/blob/15fdc458461161c16949adf10467d9af561d71e7/BraintreePayPal/Public/BTPayPalAccountNonce.h#L37) which is a `BTPostalAddress`. From there, you can[ access `countryCodeAlpha2`](https://github.com/braintree/braintree_ios/blob/15fdc458461161c16949adf10467d9af561d71e7/BraintreeCore/Public/BTPostalAddress.h#L33).

**Comment by devlove1C** [comment]
Hello **@scannillo.** 

Thanks for the response, actually my apps requirements to know to PayPal user country, I already know the above answer but when the user did not add billing address and the shipping address so it provides "null". And maybe the user adds multiple addresses so that's why we want to know user country code, and it's not compulsory in PayPal account user to add shipping & billing address. And about PayPal account type because we want to know for calling, a user which account used personal vs business.
I have tried this Paypal Account to get country code 
**qa7-user@mainst.com** 
Thanks

**Comment by scannillo** [comment]
Hi @devlove1C. The country code attached to the shipping or the billing addresses w, hich mentioned above, are the only places in the `requestBillingAgreement` callback that you can access the country code.

Here's a link on information for [detecting a user's locale](https://www.hackingwithswift.com/example-code/system/how-to-detect-which-country-a-user-is-in) in iOS, if that helps you.

Also, we currently do not return information regarding whether the underlying PayPal account used in a billing agreement is personal or business.
