### ISSUE TITLE
Deprecated UIWebView API usage ITMS-90809 Braintree3dsecure

### ISSUE THREAD

**Issue by agustr** [braintree/braintree_ios#503]
### General information

* SDK/Library version: 4.30.2
* Environment: production
* iOS Version and Device: not applicable I think
* Integration type and version: Carthage 0.34.0

### Issue description

I think my app is getting the apple warning ITMS-90809 because of braintree_ios/Braintree3DSecure/BTWebViewController.m

I can not find any other culprit in my project.

**Comment by sestevens** [comment]
Hi @agustr 👋 Please make sure you are not including the `Braintree3DSecure` framework in your project. This is a deprecated module. If your app supports 3DS, you should use the `BraintreePaymentFlow` framework.

Please let us know if this resolves the issue.

**Comment by agustr** [comment]
Thank you for your swift and effective response. I will remove the Braintree3DSecure post haste.
