### ISSUE TITLE
Discrepancy in payment flow for guest and logged in user

### ISSUE THREAD

**Issue by RupaliHeady** [braintree/braintree_ios#504]
### General information
* SDK/Library version: BraintreeDropIn- 7.0.0, Braintree- 4.21.0
* Environment: Production
* iOS Version and Device: on all supported app OS (min: iOS 11)
* Integration type and version: CocoaPods 1.8.3

### Issue description

I am using BraintreeDropIn SDK to perform payments with Paypal, credit/debit card.

Our app is used by guest and registered user to place orders.

I am getting Braintree client token from server side.
At server side, Braintree token generation with Braintree npm package is done as below
1) Guest user- generate brain tree token 
2) Registered user: generate brain tree token by considering customer id

At iOS app end, I am getting different behaviours for credit card payment below
1) Guest user: If user entered valid Billing Street address,  zip code, valid card details(Card no, expiration date, CVV), then order is placed successfully. Credit card postal code(present on Braintree DropIn UI credit card screen) doesn't matter.

2) Registered user: If user entered wrong Billing Street address,  zip code, valid card details(Card no, expiration date, CVV, postal code), then order is placed successfully. Billing street address and zip code doesn't matter.

On our production Braintree account, AVS and CVV checks are enabled
AVS Enabled for following:
● Postal Code verification for any transaction.
● Street Address does not match for any transaction.
● Issuing bank does not support AVS for any transaction

We are not able to find out why there is discrepancy in payment flow for guest and logged in user.
Please provide your inputs on below points:
1) Why AVS is bypassed for registered user (if user entered wrong street address, zip code in billing information, still order placed.)
2) Why credit card postal code doesn’t  matter for guest user (user entered wrong postal code on Drop in Credit card screen, still order placed. )
3) Is this discrepancy occurred due to Braintree token generation done on server side (guest user: not considering customer id, registered user: considering customer id for Braintree token generation). 

Server uses:
● Braintree npm package - version 2.15.0

Thanks in Advance.

**Comment by sestevens** [comment]
@RupaliHeady Again, since this isn't an issue with the Braintree SDK itself, but rather a question about card verification and vaulting, could you please reach out to [Braintree Support](https://help.braintreepayments.com/)? Thank you.
