### ISSUE TITLE
Street address field is not present on Drop In UI credit card screen

### ISSUE THREAD

**Issue by RupaliHeady** [braintree/braintree_ios#505]
### General information
SDK/Library version: BraintreeDropIn- 7.0.0, Braintree- 4.21.0
Environment: Production
iOS Version and Device: on all supported app OS (min: iOS 11)
Integration type and version: CocoaPods 1.8.3

### Issue description

I am using BraintreeDropIn SDK to perform payments with Paypal, credit/debit card.

In Braintree doc mentioned that 
We can verify the following fields with the customer’s bank:
- Card number
- Card expiration date
- Street address and postal code
- CVV
If card verification is enabled, the gateway will verify that credit cards are valid and pass any of your configured AVS and CVV rules before they are stored in the Vault. Cards that are not valid will not be stored in the Vault.
Braintree strongly recommends verifying all cards before they are stored in your Vault by enabling card verification for your entire account in the Control Panel.

Reference: https://articles.braintreepayments.com/control-panel/vault/card-verification

On our production Braintree account: credit card verification, AVS and CVV checks are enabled
AVS Enabled for following:
● Postal Code verification for any transaction.
● Street Address does not match for any transaction.
● Issuing bank does not support AVS for any transaction
But On DropIn UI Credit card screen, street address field is not present. Please refer below screenshot for the same.
![ScreenShot15 38 56](https://user-images.githubusercontent.com/56030295/70133500-3f469e00-16ac-11ea-924a-c591a244def9.png)

Due to this, credit card is added in Valut if user entered valid card no, CVV, expiration date, postal code. Street address doesn't verify here. 

Please provide inputs on
1) why street address verification is bypassed.

Thank you In Advance

@sestevens

**Comment by sestevens** [comment]
@RupaliHeady Since this isn't an issue with the Braintree SDK itself, but rather a question about card verification and vaulting, could you please reach out to [Braintree Support](https://help.braintreepayments.com/)?

Incidentally, I noticed that your screenshot is displaying an incorrect font, which is an issue with iOS 13 and versions of Drop-In older than 7.3.0. You might want to update to the latest version of Drop-In.
