### ISSUE TITLE
Building Demo app fails due to calls to deprecated APIs

### ISSUE THREAD

**Issue by thirtified** [braintree/braintree_ios#508]
### General information

* SDK/Library version: 4.30.2
* Environment: does not apply
* iOS Version and Device: Xcode 11.3, iOS Simulator 13.3
* Integration type and version: Cocoapods

### Issue description

Building the Demo app fails due to calls to deprecated `BTUIKAppearance` class methods `darkTheme` and `liteTheme` in `BraintreeDemoDropInViewController.m`.

**Comment by scannillo** [comment]
Hi @thirtified. Thank you for calling this out. 

It seems we didn't yet release the update to the`braintree_ios` Demo app to account for update in `braintree-ios-drop-in` v7.5.0, which deprecates `lightTheme` and `darkTheme`. We will let you know once we do, soon!

As a temp/immediate fix, you could downgrade the version of `braintree-ios-drop-in` that the Demo app is using to 7.4.0 or below or follow suit of the PR you opened.

**Comment by thirtified** [comment]
I took the liberty to send you a PR with the fix, see #509.

**Comment by scannillo** [comment]
Hi @thirtified. This issue in our demo app was fixed in the release of Braintree iOS v4.31.0 (https://github.com/braintree/braintree_ios/releases/tag/4.31.0).
