### ISSUE TITLE
[IOS][Local Payment] Local Payments classes not found

### ISSUE THREAD

**Issue by ClatourAntadis** [braintree/braintree_ios#512]
### General information

* SDK/Library version: 4.26.1
* iOS Version and Device: iOS 12.1
* Integration type and version: CocoaPods 1.6.1

### Issue description

I'm trying to implement the local payments (SoFort) in my application. The problem is that Local Payment classes are not found (BTLocalPaymentRequest, BTLocalPaymentRequestDelegate).

Here is my Podfile :

```
# coding: utf-8
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'pss' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pss
  pod 'XCDYouTubeKit', '~> 2.5'

  pod 'Protobuf', :inhibit_warnings => true

  #Firebase
  pod 'Firebase/Analytics', '~> 6.5.0'
#  pod 'Firebase/Messaging', '~> 6.5.0'

  #Braintree
  pod 'Braintree', '~> 4.26.1'
  pod 'Braintree/PaymentFlow'
  pod 'Braintree/DataCollector'
  pod 'Braintree/Core'
  pod 'Braintree/PayPal'
  pod 'Braintree/Card'
  #pod 'Braintree/UI'

  #AppsFLyer
  pod 'AppsFlyerFramework'

  #pod 'RNDynamicSplash', :path => '../node_modules/react-native-ant-dynamic-splash/ios'

  #pod 'RNAwesomeCardIO', :path => '../node_modules/react-native-awesome-card-io'

  pod ‘Dynamic-Yield-iOS-SDK’

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

I'm working with react-native so I made a react-native module. Here is .h file (RNAntBraintree.h) :

````
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTUtils.h>
#import <React/RCTConvert.h>

#import "BraintreePaymentFlow.h"
#import "BraintreeCore.h"
#import "BraintreePayPal.h"
#import "BraintreeCard.h"
#import "BTDataCollector.h"
#import "PPDataCollector.h"


@interface RNAntBraintree : NSObject <RCTBridgeModule, BTViewControllerPresentingDelegate, BTLocalPaymentRequestDelegate>

@property (nonatomic, strong) BTAPIClient *braintreeClient;
@property (nonatomic, strong) BTPaymentFlowDriver *paymentFlowDriver;
@property (nonatomic, strong) UIViewController *reactRoot;
@property (nonatomic, strong) BTDataCollector *dataCollector;
@property (nonatomic, copy) NSString *merchandId;
@property (nonatomic, copy) NSString *threeDSecureAmount;

@property (nonatomic, strong) RCTResponseSenderBlock callback;

+ (instancetype)sharedInstance;
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation;

@end

````

As it's documented [here](https://developers.braintreepayments.com/guides/local-payment-methods/client-side-custom/ios/v4), I'm implementing the delegate BTLocalPaymentRequestDelegate. But the delegate is not found. Here is the error :
```
Cannot find protocol declaration for 'BTLocalPaymentRequestDelegate'; did you mean 'BTPaymentFlowRequestDelegate'?
```

<img width="1603" alt="Screenshot 2020-01-24 at 14 40 17" src="https://user-images.githubusercontent.com/46489900/73073583-efb86d80-3eb7-11ea-8f5f-533cc773e3a9.png">

In my class file (RNAntBraintree.h) : 

```
#import "RNAntBraintree.h"

@implementation RNAntBraintree {
}

RCT_EXPORT_MODULE();

//SOME CODE

RCT_EXPORT_METHOD(localPyament:(NSString *) paymentType)
{
    self.paymentFlowDriver = [[BTPaymentFlowDriver alloc] initWithAPIClient:self.braintreeClient];
    self.paymentFlowDriver.viewControllerPresentingDelegate = self;
    
    BTLocalPaymentRequest *request = [[BTLocalPaymentRequest alloc] init];
    //etc..
}

//SOME CODE

@end
```

Here is the error : 
```
Use of undeclared identifier 'BTLocalPaymentRequest'
```
<img width="1603" alt="Screenshot 2020-01-24 at 14 40 34" src="https://user-images.githubusercontent.com/46489900/73073533-d4e5f900-3eb7-11ea-90cf-2ccf5013ea3f.png">

Of course I checked if those classes were defined in the Braintree in the Pods Folder :

```
Documents/work/pss  master ✗  [ Stashed ] ▶ tree ios/Pods/Braintree/BraintreePaymentFlow
ios/Pods/Braintree/BraintreePaymentFlow
├── BTPaymentFlowDriver.m
├── BTPaymentFlowDriver_Internal.h
├── BTPaymentFlowRequest.m
├── BTPaymentFlowResult.m
├── LocalPayment
│   ├── BTConfiguration+LocalPayment.m
│   ├── BTLocalPaymentRequest.m
│   ├── BTLocalPaymentResult.m
│   ├── BTPaymentFlowDriver+LocalPayment.m
│   └── BTPaymentFlowDriver+LocalPayment_Internal.h
├── Public
│   ├── BTPaymentFlowDriver.h
│   ├── BTPaymentFlowRequest.h
│   ├── BTPaymentFlowResult.h
│   ├── BraintreePaymentFlow.h
│   ├── LocalPayment
│   │   ├── BTConfiguration+LocalPayment.h
│   │   ├── BTLocalPaymentRequest.h
│   │   ├── BTLocalPaymentResult.h
│   │   └── BTPaymentFlowDriver+LocalPayment.h
│   └── ThreeDSecure
│       ├── BTConfiguration+ThreeDSecure.h
│       ├── BTPaymentFlowDriver+ThreeDSecure.h
│       ├── BTThreeDSecureAdditionalInformation.h
│       ├── BTThreeDSecureLookup.h
│       ├── BTThreeDSecurePostalAddress.h
│       ├── BTThreeDSecureRequest.h
│       └── BTThreeDSecureResult.h
└── ThreeDSecure
    ├── BTConfiguration+ThreeDSecure.m
    ├── BTPaymentFlowDriver+ThreeDSecure.m
    ├── BTPaymentFlowDriver+ThreeDSecure_Internal.h
    ├── BTThreeDSecureAdditionalInformation.m
    ├── BTThreeDSecureAdditionalInformation_Internal.h
    ├── BTThreeDSecureAuthenticateJWT.h
    ├── BTThreeDSecureAuthenticateJWT.m
    ├── BTThreeDSecureLookup.m
    ├── BTThreeDSecurePostalAddress.m
    ├── BTThreeDSecurePostalAddress_Internal.h
    ├── BTThreeDSecureRequest.m
    ├── BTThreeDSecureRequest_Internal.h
    ├── BTThreeDSecureResult.m
    ├── BTThreeDSecureV2Provider.h
    └── BTThreeDSecureV2Provider.m

5 directories, 39 files
```

The BTLocalPaymentRequest is present and also imported in BraintreePaymentFlow.h which is imported in my header module file (RNAntBraintree.h)

The BTLocalPaymentRequestDelegate is defined in BTPaymentFlowDriver.h which is imported in BraintreePaymentFlow.h which is imported in my header module file (RNAntBraintree.h)

I just updated the SDK from the version  ```4.15.0``` to ```4.26.1```. So, to solve the problem I tried to clean the project (Cmd+Shift+k), remove project Derived Data, remove Pods folder and reinstall with the command ```pod install``` but without success.

What should I do ? Has anyone got the same problem ?

Regards,
Christophe Latour

**Comment by scannillo** [comment]
Hi Christopher. Thanks for the thorough breakdown. 

So I just spun up a sample iOS app written in ObjectiveC using the version of Braintree that you specified. When adding 
```
  pod 'Braintree', '~> 4.26.1'
  pod 'Braintree/PaymentFlow'
  pod 'Braintree/Core'
```
to my Podfile, like yours, and including `#import "BraintreePaymentFlow.h"` and `#import "BraintreeCore.h"` in my `ViewController.m`, I am able to access the `BTLocalPaymentRequestDelegate` no problem. I am unable to replicate your problem. 

I wonder if using react native has anything to do with the way dependencies are handled/imported? Also, seems trivial, but can't hurt to restart XCode.

**Comment by ClatourAntadis** [comment]
Hi scannillo,

Thanks for your response.
As you did, I will try to create a new react-native application and try to integrate the SDK. It's probably a dependency problem with react-native. I will keep you inform on this ticket.

Regards,
Christophe Latour

**Comment by ClatourAntadis** [comment]
Hi,

This was effectively on my side. I had the lib Braintree included (via Podfile) in main project and my module with 2 different versions.

You can close the ticket.
