### ISSUE TITLE
4.31.0 Payment failing

### ISSUE THREAD

**Issue by daliadanila** [braintree/braintree_ios#513]
### General information

* SDK/Library version: 4.31.0
* Environment: Sandbox
* iOS Version and Device: iPhone X iOS 12.2 
* Integration type and version: CocoaPods 1.7.4
* Pod file content
  pod 'Braintree', '4.31.0'
  pod 'Braintree/Apple-Pay', '4.31.0'
  pod 'Braintree/DataCollector', '4.31.0'
  pod 'Braintree/PayPalDataCollector', '4.31.0'
  pod 'Braintree/PaymentFlow', '4.31.0'

### Issue description

Hi,

We've just upgraded to 4.31.0 and tried to make a payment using the following details

Card details: 4111 1111 1111 1111

Expiry date: 12/23

CVS: 123

When the web page is supposed to open we get an error saying: "The requested URL was rejected. Please consult with your administrator. Your support ID is "6490293097504989936"

We've also tried installing version 4.30.2 and make the payment using the same card details and the payment completes successfully as expected. I've attached relevant screenshots below.

Could you advise, please?

Thanks,
Dalia

![card details](https://user-images.githubusercontent.com/4118291/74322505-ef571800-4d7b-11ea-8e85-5cd311f8284c.png)
![4 31 0_failure](https://user-images.githubusercontent.com/4118291/74322508-f0884500-4d7b-11ea-8080-9b73b6fe3108.png)
![4 30 2_success](https://user-images.githubusercontent.com/4118291/74322510-f0884500-4d7b-11ea-8bf5-da5800751256.png)

**Comment by sestevens** [comment]
@daliadanila Thanks for reporting this. We are able to reproduce the issue, and we're currently investigating. We'll post here when we have an update.

**Comment by sestevens** [comment]
This issue should be resolved now. We've tested in our end, and everything seems to be working, but please let us know if you're still encountering the error.
