### ISSUE TITLE
Deprecated API Usage UIWebView

### ISSUE THREAD

**Issue by kolja-ec** [braintree/braintree_ios#514]
### General information

* SDK/Library version: 4.11
* Environment: Sandbox
* iOS Version and Device: iOS 13 iPhone 8
* Integration type and version: CocoaPods 1.7.5

Received the following Mail from Apple when using this:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

It seems its related to dependency 'Braintree/3D-Secure'. I searched in xcode for UIWebView and when Braintree/3D-Secure is added to the project there are lots of occurrences of UIWebView but when removed it cant find UIWebView.

**Comment by sestevens** [comment]
Hi @kolja-ec Please update to the latest version of Braintree. The issue with `UIWebView` was resolved in 4.30.2.

**Comment by kolja-ec** [comment]
Hi @sestevens I was asking because i can see multiple occurrences of UIWebView in the latest version of braintree_ios/Braintree3DSecure/
for example in: BTWebViewController.h .

**Comment by sestevens** [comment]
@kolja-ec That module has been deprecated. If you're using 3DS secure, you should include `pod 'Braintree/PaymentFlow'` in your podfile. The deprecated module is `pod 'Braintree/3D-Secure'`, so make sure you're not including that one. It will be removed in the next major version.
