### ISSUE TITLE
Xcode 11.4 showing an AddressBook deprecation

### ISSUE THREAD

**Issue by ethanwa** [braintree/braintree_ios#515]
### General information

* SDK/Library version: 4.32.1
* Environment: Production
* iOS Version and Device: iOS 13.4, Xcode 11.4
* Integration type and version: CocoaPods 1.9.0

### Issue description

When building I am getting the following Target Integrity warning on Braintree:

`<my-project-path>/Pods/Pods.xcodeproj AddressBook is deprecated. Consider migrating to Contacts instead.`

**Comment by scannillo** [comment]
Hello @ethanwa. The Braintree SDK doesn't directly use the AddressBook framework. Could you share details that confirm this issue is coming from Braintree, and not some other dependency in your Pods?

**Comment by ignotusverum** [comment]
@scannillo please find my [PR](#516) - it seems like Braintree SDK is not using `AddressBook` but it's included in .podspec.

**Comment by scannillo** [comment]
Hi. This fix was release in [v4.33.0!](https://github.com/braintree/braintree_ios/releases/tag/4.33.0)
