### ISSUE TITLE
Running Xcode 11.4 Analyze shows an issue in BTJSON.m

### ISSUE THREAD

**Issue by ethanwa** [braintree/braintree_ios#517]
### General information

* SDK/Library version: 4.31 Core
* Environment: Prod
* iOS Version and Device: iOS 13.4
* Integration type and version: CocoaPods

### Issue description

Running Xcode Analyze shows an issue in BTJSON.m line 31 and 34.

`Although the value stored to 'self' is used in the enclosing expression, the value is never actually read from 'self'`

<img width="1160" alt="Screen Shot 2020-04-03 at 3 43 04 AM" src="https://user-images.githubusercontent.com/1653780/78336644-b5c1b280-755d-11ea-8306-be99796634d3.png">

**Comment by sestevens** [comment]
@ethanwa Thanks for reporting this! We should be able to fix this in an upcoming release.

**Comment by sestevens** [comment]
Fixed in version [4.34.0](https://github.com/braintree/braintree_ios/releases/tag/4.34.0).
