### ISSUE TITLE
is there Any braintree IOS Swift 4 Demo app

### ISSUE THREAD

**Issue by ArSquareDev** [braintree/braintree_ios#518]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version:

**Comment by ArSquareDev** [comment]
Is there any Braintree IOS  Demo App in swift 4

**Comment by scannillo** [comment]
Hi @ArSquareDev. The demo app included in this repo is written mostly in ObjectiveC. However, our developer docs have plenty of Swift code examples (https://developers.braintreepayments.com/start/hello-client/ios/v4).
