### ISSUE TITLE
Where take OrderId?

### ISSUE THREAD

**Issue by balkarov** [braintree/braintree_ios#519]
### General information

* SDK/Library version: 4.32.1
* Environment: Sandbox and Production
* iOS Version and Device: any
* Integration type and version: CocoaPods 1.9.1

### Issue description

On server-side client I must put `OrderId` to [TransactionRequest](https://developers.braintreepayments.com/guides/paypal/server-side/dotnet).

In JavaScript client I found this `OrderId` in 
```js
return paypalCheckoutInstance.tokenizePayment(data, function (err, payload) {
        const orderId = data.orderID // <- this
});

```

But in iOS I did not find this field 
```swift
payPalDriver.requestOneTimePayment(request) { (tokenizedPayPalAccount, error) in
}
```

Thank you!

**Comment by balkarov** [comment]
Any help?

**Comment by balkarov** [comment]
@demerino look this [link](https://developers.braintreepayments.com/guides/paypal/server-side/dotnet)

For dot net. And look this line

```c#
OrderId = “Mapped to PayPal Invoice Number”,
```

Where take orderId. 
From iOS client I can send only payment nonce and device data. But where take orderId?

**Comment by demerino** [comment]
This field is optional on the server side: https://developers.braintreepayments.com/reference/request/transaction/sale/dotnet#order_id and should only be needed there and not when tokenizing on the iOS client. Are you having issues getting a nonce on the iOS client?

**Comment by balkarov** [comment]
@demerino thank you. 
Yes, nonce and deviceData I take in iOS clients and send it to server. 
But I do not understand why js client support orderId, but iOS client have not?

**Comment by demerino** [comment]
Can you share a link to the JS docs you are referencing?

**Comment by balkarov** [comment]
@demerino https://developers.braintreepayments.com/guides/paypal/client-side/javascript/v3

**Comment by demerino** [comment]
I don't see a reference to order ID on that page?

**Comment by balkarov** [comment]
@demerino but it has in `data`. You can debug. 
 And it has in server side 
https://developers.braintreepayments.com/guides/paypal/server-side/dotnet

**Comment by demerino** [comment]
Here are the docs for that reference:

**Comment by balkarov** [comment]
@demerino 
I understood, this is an additional information. But where get it? 
Server side supports it, js client supports it. But iOS client does not support? Why?
If I want use this additional information. How to send it from iOS client?

**Comment by demerino** [comment]
The iOS clients do not expose any order ID at this time.

**Comment by hw20101101** [comment]
Shouldn't the order number be passed when sending a transaction request on the iOS side? How does the server know which order transaction was successful?

The previously used `PayPalMobile SDK` can pass the order number, the code is as follows

```
    NSString *tradeNo = dict[@"trade_no"];
    NSDecimalNumber *priceNum = [NSDecimalNumber decimalNumberWithString:packagePrice];
 
    PayPalItem *item1 = [PayPalItem itemWithName:packagesName withQuantity:1 withPrice:priceNum withCurrency:currency withSku:tradeNo];
    NSArray *items = @[item1];
    NSDecimalNumber *subtotal = [PayPalItem totalPriceForItems:@[item1]];
    PayPalPayment *payment = [[PayPalPayment alloc] init];
    payment.items = items;
    payment.amount = subtotal;
    payment.currencyCode = currency;  
    payment.invoiceNumber = tradeNo; 

```

**Comment by sestevens** [comment]
@hw20101101 The Braintree iOS SDK works quite a bit differently from the PayPal Mobile SDK. Instead of passing an order id to the server, you'll need to pass a `nonce`, which represents a tokenized payment method. You can read more about this on the [Braintree docs](https://developers.braintreepayments.com/) or reach out to [Braintree Support](https://help.braintreepayments.com/) if you need additional assistance.

**Comment by hw20101101** [comment]
@sestevens 

Ok thanks a lot
