### ISSUE TITLE
BTThreeDSecureRequestDelegate not calling

### ISSUE THREAD

**Issue by frankemmanuvel** [braintree/braintree_ios#521]
**Is your feature request related to a problem? Please describe.**

I have implemented BT in my application and now I wanted to show a progress loader after user enter the card details and want to close the progress loader after adding the card.

**Describe the solution you'd like**

Looking for delegate methods which calls before validating/adding the card and another delegate method which calls after the process complete.

**Comment by scannillo** [comment]
Hello. Can you provide more specific details on the feature request you're making? Are you using the [drop-in SDK](https://github.com/braintree/braintree-ios-drop-in)? If so, file your issue there.

If you are seeing issues with your `BTThreeDSecureRequestDelegate` not calling, make sure you've properly conformed to the delegate - see our docs [integration docs](https://developers.braintreepayments.com/guides/3d-secure/client-side/ios/v4#custom-ui). With that, you should have enough information to handle your custom UI for showing a spinner.

**Comment by scannillo** [comment]
Moved to Drop In SDK. https://github.com/braintree/braintree-ios-drop-in/issues/221
