### ISSUE TITLE
UIWebview still in Braintree frameworks and files

### ISSUE THREAD

**Issue by SerggioC** [braintree/braintree_ios#523]
I have deleted the previous files and then updated to the latest versions with carthage and I still get the UIWebview everywhere. 
using this line on cartfile
# Braintree
github "braintree/braintree_ios"

What is the problem here?

./Carthage/Checkouts/braintree_ios/Specs/Braintree-Acceptance-Specs/KIFUITestActor+BTWebView.m:- (UIWebView *)_getWebViewOnCurrentScreen:(NSArray *)views
./Carthage/Checkouts/braintree_ios/Specs/Braintree-Acceptance-Specs/KIFUITestActor+BTWebView.m:        if ([NSStringFromClass([view class]) isEqual:@"UIWebView"]) {
./Carthage/Checkouts/braintree_ios/Specs/Braintree-Acceptance-Specs/KIFUITestActor+BTWebView.m:            return (UIWebView*) view;
./Carthage/Checkouts/braintree_ios/Specs/Braintree-Acceptance-Specs/KIFUITestActor+BTWebView.m:        UIWebView* found = [self _getWebViewOnCurrentScreen:view.subviews];
./Carthage/Checkouts/braintree_ios/Specs/Braintree-Acceptance-Specs/KIFUITestActor+BTWebView.m:- (UIWebView *)getWebViewOnCurrentScreen {
./Carthage/Checkouts/braintree_ios/Specs/Braintree-Acceptance-Specs/KIFUITestActor+BTWebView.m:    UIWebView *currentWebView = [self getWebViewOnCurrentScreen];
grep: ./Carthage/Checkouts/braintree_ios/Carthage/Checkouts/CardinalMobile: No such file or directory
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/BraintreeUnionPay.framework.dSYM/Contents/Resources/DWARF/BraintreeUnionPay matches
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/BraintreeAmericanExpress.framework.dSYM/Contents/Resources/DWARF/BraintreeAmericanExpress matches
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/BraintreeApplePay.framework.dSYM/Contents/Resources/DWARF/BraintreeApplePay matches
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/BraintreeVenmo.framework.dSYM/Contents/Resources/DWARF/BraintreeVenmo matches
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/BraintreeCard.framework.dSYM/Contents/Resources/DWARF/BraintreeCard matches
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/BraintreePayPal.framework.dSYM/Contents/Resources/DWARF/BraintreePayPal matches
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/BraintreeCore.framework.dSYM/Contents/Resources/DWARF/BraintreeCore matches
./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/ABCAC6FC-843B-388D-A063-E871F5D1EE0C.bcsymbolmap:__OBJC_PROTOCOL_$_UIWebViewDelegate
./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/ABCAC6FC-843B-388D-A063-E871F5D1EE0C.bcsymbolmap:__OBJC_LABEL_PROTOCOL_$_UIWebViewDelegate
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/BraintreeUI.framework.dSYM/Contents/Resources/DWARF/BraintreeUI matches
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/UberCore.framework.dSYM/Contents/Resources/DWARF/UberCore matches
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/Braintree3DSecure.framework/Braintree3DSecure matches
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/PayPalOneTouch.framework.dSYM/Contents/Resources/DWARF/PayPalOneTouch matches
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/PayPalDataCollector.framework.dSYM/Contents/Resources/DWARF/PayPalDataCollector matches
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/BraintreePaymentFlow.framework.dSYM/Contents/Resources/DWARF/BraintreePaymentFlow matches
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/PayPalUtils.framework.dSYM/Contents/Resources/DWARF/PayPalUtils matches
./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/99C242E4-7465-3786-94DD-05BA2F5CD138.bcsymbolmap:__OBJC_PROTOCOL_$_UIWebViewDelegate
./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/99C242E4-7465-3786-94DD-05BA2F5CD138.bcsymbolmap:__OBJC_LABEL_PROTOCOL_$_UIWebViewDelegate
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/Braintree3DSecure.framework.dSYM/Contents/Resources/DWARF/Braintree3DSecure matches
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/BraintreeDataCollector.framework.dSYM/Contents/Resources/DWARF/BraintreeDataCollector matches
Binary file ./Carthage/Checkouts/braintree_ios/Carthage/Build/iOS/UberRides.framework.dSYM/Contents/Resources/DWARF/UberRides matches
Binary file ./Carthage/Build/iOS/BraintreeUnionPay.framework.dSYM/Contents/Resources/DWARF/BraintreeUnionPay matches
Binary file ./Carthage/Build/iOS/BraintreeAmericanExpress.framework.dSYM/Contents/Resources/DWARF/BraintreeAmericanExpress matches
Binary file ./Carthage/Build/iOS/BraintreeApplePay.framework.dSYM/Contents/Resources/DWARF/BraintreeApplePay matches
Binary file ./Carthage/Build/iOS/BraintreeVenmo.framework.dSYM/Contents/Resources/DWARF/BraintreeVenmo matches
Binary file ./Carthage/Build/iOS/BraintreeCard.framework.dSYM/Contents/Resources/DWARF/BraintreeCard matches
Binary file ./Carthage/Build/iOS/BraintreePayPal.framework.dSYM/Contents/Resources/DWARF/BraintreePayPal matches
Binary file ./Carthage/Build/iOS/BraintreeCore.framework.dSYM/Contents/Resources/DWARF/BraintreeCore matches
./Carthage/Build/iOS/ABCAC6FC-843B-388D-A063-E871F5D1EE0C.bcsymbolmap:__OBJC_PROTOCOL_$_UIWebViewDelegate
./Carthage/Build/iOS/ABCAC6FC-843B-388D-A063-E871F5D1EE0C.bcsymbolmap:__OBJC_LABEL_PROTOCOL_$_UIWebViewDelegate
Binary file ./Carthage/Build/iOS/BraintreeUI.framework.dSYM/Contents/Resources/DWARF/BraintreeUI matches
Binary file ./Carthage/Build/iOS/UberCore.framework.dSYM/Contents/Resources/DWARF/UberCore matches
Binary file ./Carthage/Build/iOS/Braintree3DSecure.framework/Braintree3DSecure matches
Binary file ./Carthage/Build/iOS/PayPalOneTouch.framework.dSYM/Contents/Resources/DWARF/PayPalOneTouch matches
Binary file ./Carthage/Build/iOS/PayPalDataCollector.framework.dSYM/Contents/Resources/DWARF/PayPalDataCollector matches
Binary file ./Carthage/Build/iOS/BraintreePaymentFlow.framework.dSYM/Contents/Resources/DWARF/BraintreePaymentFlow matches
Binary file ./Carthage/Build/iOS/PayPalUtils.framework.dSYM/Contents/Resources/DWARF/PayPalUtils matches
./Carthage/Build/iOS/99C242E4-7465-3786-94DD-05BA2F5CD138.bcsymbolmap:__OBJC_PROTOCOL_$_UIWebViewDelegate
./Carthage/Build/iOS/99C242E4-7465-3786-94DD-05BA2F5CD138.bcsymbolmap:__OBJC_LABEL_PROTOCOL_$_UIWebViewDelegate
Binary file ./Carthage/Build/iOS/Braintree3DSecure.framework.dSYM/Contents/Resources/DWARF/Braintree3DSecure matches
Binary file ./Carthage/Build/iOS/BraintreeDataCollector.framework.dSYM/Contents/Resources/DWARF/BraintreeDataCollector matches

**Comment by demerino** [comment]
References to `UIWebView` are still in the **_deprecated_** BTThreeDSecure module. That module will be removed in the next major version bump. Let us know if you have any other questions or concerns.

**Comment by eXhausted** [comment]
@demerino I can't upload a build for newly created app, because of UIWebView ref.

```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "Koop and Kraft" 6.8.5 (1547). Please correct the following issues, then upload again.

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Best regards,

The App Store Team
```

**Comment by sestevens** [comment]
@eXhausted, please make sure you're using at least version 4.30.2 of Braintree iOS and **not** including the deprecated `BTThreeDSecure` module.

**Comment by eXhausted** [comment]
@sestevens sorry for disturbing, cocoapods didn't remove BTThreeDSecure after I did update somewhy.
