### ISSUE TITLE
Using manual integration I am not able to use BTDropInRequest for showing Cardholder name

### ISSUE THREAD

**Issue by raviprajapat1** [braintree/braintree_ios#526]
I am using BT [manual integration](https://github.com/braintree/braintree_ios/blob/master/Docs/Manual%20Integration.md), I am not able to use BTDropInRequest for showing Cardholder name.

**Integration Details (please complete the following information):**
 - SDK/Library Version: 4.33.0
 - Environment: Sandbox
 - iOS Version: iOS 13.1
 - Device iPhone 11 Pro Max
 - Integration type & version: Manually Integration

**Describe the bug**

I am integrate the Braintree SDK manually, but there are some basic classes not found for eg. I wanted `BTDropInRequest` to customize my request to show hide CardHolder name according to my application requirement but unfortunately I am not able to see the `BTDropInRequest` class which does this kind of customization.

Please guide me if I missed something apart from the [manual integration](https://github.com/braintree/braintree_ios/blob/master/Docs/Manual%20Integration.md) doc

**Expected behavior**

As like integrating Braintree using Cocoapod or Carthage, the manual integration is also allow me to customize the `BTDropInRequest`

**Screenshots**

**Comment by scannillo** [comment]
Your concern was already addressed in the other issue you opened https://github.com/braintree/braintree_ios/issues/525#issuecomment-622358493
