### ISSUE TITLE
BTViewControllerPresentingDelegate & BTAppSwitchDelegate are not called.

### ISSUE THREAD

**Issue by aayubhagat295** [braintree/braintree_ios#530]
BTViewControllerPresentingDelegate & BTAppSwitchDelegate are not called.

**Comment by sestevens** [comment]
Hi @aayubhagat295, could you provide us with a few more details, such as the version of Braintree iOS you're using and steps we can follow to reproduce the issue?

**Comment by aayubhagat295** [comment]
- SDK/Library Version: [4.33.0]
 - Environment: [Sandbox]
 - iOS Version: [iOS 11.0] 
- Device [iPhone 5s]

**Comment by aayubhagat295** [comment]
I am using this code - 

        let payPalDriver = BTPayPalDriver(apiClient: self.braintreeClient)
        payPalDriver.viewControllerPresentingDelegate = self


        let request = BTPayPalRequest(amount: "1.00")

        payPalDriver.requestOneTimePayment(request) { (tokenizedPayPalAccount, error) -> Void in
            guard let tokenizedPayPalAccount = tokenizedPayPalAccount else {
                if let error = error {
                    // Handle error
                } else {
                    // User canceled
                }
                return
            }
            print("Got a nonce! \(tokenizedPayPalAccount.nonce)")
        }

But delegate not called

**Comment by scannillo** [comment]
Hello @aayubhagat295 - did you consult our[ developer docs](https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4) to ensure you properly set up your app for app switch and that you properly implemented the `viewControllerPresentingDelegate` and `appSwitchDelegate` delegate protocols?

**Comment by scannillo** [comment]
You should reach out to our support team  (https://help.braintreepayments.com) for help troubleshooting your specific integration. If you instead find an _issue_ with the SDK, please report it here!

**Comment by aayubhagat295** [comment]
> Hello @aayubhagat295 - did you consult our[ developer docs](https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4) to ensure you properly set up your app for app switch and that you properly implemented the `viewControllerPresentingDelegate` and `appSwitchDelegate` delegate protocols?

yes, i properly implemented delegate methods & i preferred developer doc.

    func paymentDriver(_ driver: Any, requestsPresentationOf viewController: UIViewController) {
        present(viewController, animated: true, completion: nil)
    }

    func paymentDriver(_ driver: Any, requestsDismissalOf viewController: UIViewController) {
        viewController.dismiss(animated: true, completion: nil)
    }

**Comment by aayubhagat295** [comment]
Can you please suggest where i am wrong?
