### ISSUE TITLE
old paypal_sdk improvement

### ISSUE THREAD

**Issue by TianTeng6661** [braintree/braintree_ios#531]
Hello, I want to use your PayPal SDK at present. However, due to Apple's current audit, uiwebview is not allowed in the package. However, through inspection, it is found that the. A file of our old PayPal SDK contains uiwebview, although we have moved the resources to the Braintree at present_ On IOS, but for the convenience of the public, if you have permission, you can update it for the last time, replacing the old uiwebview with wkwebview. Thank you very much. If you have any information, please contact: tianteng6661@163.com , thank you again.

**Comment by scannillo** [comment]
Which PayPal SDK are you referring to? Can you provide a link? This issues tab is for the Braintree SDKs.

**Comment by sestevens** [comment]
@TianTeng6661 The [PayPal iOS SDK](https://github.com/paypal/PayPal-iOS-SDK) is deprecated and we are not able to update it.

**Comment by TianTeng6661** [comment]
o  yes  thanks
