### ISSUE TITLE
in sdk this type of issue come

### ISSUE THREAD

**Issue by sagarmodi61** [braintree/braintree_ios#532]
-canOpenURL: failed for URL: "com.venmo.touch.v2://x-callback-url/vzero/auth" - error: "This app is not allowed to query for scheme com.venmo.touch.v2"

**Comment by sestevens** [comment]
@sagarmodi61 If your app supports Pay with Venmo, you'll need to [allowlist the Venmo queries scheme in your Info.plist](https://developers.braintreepayments.com/guides/venmo/client-side/ios/v4#whitelist-venmo-url-scheme). If your app doesn't support Pay with Venmo, you can ignore this console message.
