### ISSUE TITLE
Paypal alert prompt picks Product Name from build settings rather than Bundle Display Name

### ISSUE THREAD

**Issue by userException** [braintree/braintree_ios#534]
![Simulator Screen Shot - iPhone 11 - 2020-08-06 at 21 37 51](https://user-images.githubusercontent.com/3499123/89555308-82ee3a80-d82d-11ea-99c4-71628fb1c86c.png)

Braintree is picking the name in the quotes ("<Product Name>" wants to use paypal.com.....) from the "Product Name" build setting of the app. I have a white-labelled app for which we reuse most of the code with some minor modifications to satisfy multiple clients. Hence the Product Name setting is same across all the implementations. What changes is, the bundle display name which is the actual app name. One more reason is, the white-labeled builds are automated from a CI machine and we don't want to include this manual step to change the product name for every new implementation and break the automated flow.

Is there a way we can supply a custom name rather than Braintree picking up the Product name by itself?

**Comment by billwerges** [comment]
Hi @userException,

That popup is presented and controlled by iOS, the Braintree SDK has no role in setting the text. To the best of my knowledge, there is no way to customize the message.
