### ISSUE TITLE
SecTrustEvaluate is deprecated in iOS 13.0 and up

### ISSUE THREAD

**Issue by 15joeybloom** [braintree/braintree_ios#536]
**Integration Details (please complete the following information):**
 - SDK/Library Version: 4.35.0
 - iOS Version: iOS 14.0
 - Integration type & version: CocoaPods 1.9.1

**Describe the bug**
SDK does not compile in Xcode 12.0 beta release 6 due to this line: https://github.com/braintree/braintree_ios/blob/50d28cca423cd5f2e96b3d5937b83c44f100c305/BraintreePayPal/PayPalUtils/PPOTURLSession.m#L120
'SecTrustEvaluate' is deprecated: first deprecated in iOS 13.0
Replace 'SecTrustEvaluate' with ‘SecTrustEvaluateWithError'

**Comment by scannillo** [comment]
Hi @15joeybloom - we are working on a major version bump (v5) of the braintree_ios SDK. In v5, the PayPal One Touch framework will be removed.

Temporarily, I would not treat the deprecation warning as a compiler error so you can still use the SDK until we get a new version out.

**Comment by scannillo** [comment]
Looking now - I notice we also use this function in our `BraintreeCore` module. I will keep this GH issue open so we can let you know when a release is out with this update.

**Comment by scannillo** [comment]
Hi - circling back on this. You can instead add: `pod 'Braintree', :inhibit_warnings => true` to your Podfile. With this, you'll still be able to treat your apps deprecation warnings as errors if you choose.

**Comment by sestevens** [comment]
Hi @15joeybloom, we just released a [beta version](https://github.com/braintree/braintree_ios/releases/tag/5.0.0-beta1) of the SDK that should resolve this deprecation warning. I'll leave this issue open until these changes are in GA.

Resources:
- [SPM integration instructions](https://github.com/braintree/braintree_ios/tree/5.0.0-beta1#swift-package-manager-v5-beta)
- [Version 5 migration guide](https://github.com/braintree/braintree_ios/blob/5.0.0-beta1/V5_MIGRATION.md)

**Comment by sestevens** [comment]
This has been fixed in [version 5.0.0](https://github.com/braintree/braintree_ios/releases/tag/5.0.0). Please see our [migration guide](https://github.com/braintree/braintree_ios/blob/5.0.0/V5_MIGRATION.md) for steps to upgrade your integration.
