### ISSUE TITLE
How iOS passes orderId to PHP

### ISSUE THREAD

**Issue by hw20101101** [braintree/braintree_ios#540]
SDK/Library Version: 4.35.0

<img width="1129" alt="WX20200915-174939@2x" src="https://user-images.githubusercontent.com/9107226/93195478-e13b0100-f77b-11ea-903f-d2876ad85e61.png">
<img width="1139" alt="WX20200915-174902@2x" src="https://user-images.githubusercontent.com/9107226/93195548-f2840d80-f77b-11ea-8b49-a52ff9beba6b.png">

**Comment by scannillo** [comment]
Hi @hw20101101 - please fill out our issue template next time you open an issue. Also - what I _think_ is a similar question, has already been answered here https://github.com/braintree/braintree_ios/issues/519.

> Only open an issue here if you think you've found an issue with our SDK. If you need help troubleshooting your integration, reach out to Braintree Support at https://help.braintreepayments.com.
