### ISSUE TITLE
SwiftUI support?

### ISSUE THREAD

**Issue by basememara** [braintree/braintree_ios#541]
Is there a native SwiftUI view to use, or a sample of how to integrate into a SwiftUI-only app?

**Comment by sestevens** [comment]
Hi @basememara, this SDK doesn't include any SwiftUI views. There are a few payment flows, such as PayPal, that involve presenting view controllers, which are passed to the caller through delegate methods. It's up to you to determine how to present these view controllers, either using UIKit or SwiftUI.
