### ISSUE TITLE
Remove Deprecated Valid Architectures Build Setting

### ISSUE THREAD

**Issue by denni01** [braintree/braintree_ios#542]
**Integration Details (please complete the following information):**
 - SDK/Library Version: 4.34.0 and possibly lower
 - Environment: Production
 - Xcode Version: 12.0+
 - iOS Version: N/A
 - Device: N/A
 - Integration type & version: Carthage 0.36.0

**Describe the bug**
Apple has removed support for the Valid Architectures build setting which is causing carthage builds to fail. The path forward is to use the Excluded Architectures build setting instead. See release notes [here](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes#BuildSystem) in the 'Build System' section.

For more information, see [this](https://github.com/Carthage/Carthage/issues/3019) carthage thread which describes the problem and interim solutions in depth.

**To Reproduce**
1. Build the project using carthage using Xcode 12.0 or later

**Expected behavior**
The project should build successfully

**Screenshots**
N/A

**Comment by scannillo** [comment]
Hi - I am not able to replicate the issue using Braintree v4.35.0. I am using the Xcode 12 GM and a Cartfile of `github "braintree/braintree_ios"`. I tested by including the framework `BraintreeCore`, and my app runs/builds fine.

I also tried a sample app with Braintree v4.34.0 and don't see the issue you're reporting.

Which Braintree frameworks are you including? Can you provide more detailed steps so we can try to replicate this issue?

**Comment by denni01** [comment]
Hey @scannillo,

The build issue that i'm referencing occurs when building dependencies using carthage from the command line. Here's some steps to reproduce.

1. Create a new working directory.
2. Create a Cartfile with a single line: `github "braintree/braintree_ios"`
3. Run the command `carthage bootstrap`.
4. The first framework that isn't `CardinalMobile` should error out with a lipo command. It should look roughly like this:

`
/usr/bin/xcrun lipo -create /Users/username/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/braintree_ios/4.35.0/Build/Intermediates.noindex/ArchiveIntermediates/BraintreeApplePay/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/BraintreeApplePay.framework/BraintreeApplePay /Users/username/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/braintree_ios/4.35.0/Build/Products/Release-iphonesimulator/BraintreeApplePay.framework/BraintreeApplePay -output /Users/username/Developer/scratch/braintree-build/Carthage/Build/iOS/BraintreeApplePay.framework/BraintreeApplePay
`

The reason that this build is failing is because of duplicate arm64 architectures in the resulting binaries. You can actually look at which architectures are in each binary with the `lipo -archs` command against each of the paths after before the `-output` flag above. This can be resolved by adding `arm64` to Excluded Architectures build setting. I've tested this locally and the project builds correctly.

You may want to double check that you are actually using the Xcode 12 command line tools. You can check this by running `xcode-select -p` or checking in Xcode Preferences under Locations -> Command Line Tools

**Comment by billwerges** [comment]
Hi @denni01,

The Braintree project is not currently defining a value for the `Valid Architecture` build configuration, so there are no changes we can make related to this. The issue as it currently stands is that Carthage does not support Xcode 12, this is not specific to our project.

**Comment by denni01** [comment]
Hi @billwerges,

I'd like to reopen this issue since I believe it was closed without truly understanding the problem. The Braintree project does define a value for `Valid Architecture`. You may not see this if you opened the project with Xcode 12. Furthermore, this is not an issue with Carthage and is an issue with your project since you aren't using the new build setting `Excluded Architectures`.

Please follow the steps above and read through the Carthage thread to understand why this is a problem for consumers who use Carthage with your SDK.

**Comment by billwerges** [comment]
We are not defining a value for the Valid Architecture build configuration, the values that are displayed in Xcode 11 are the defaults the IDE uses (you can also check `Braintree.xcodeproj/project.pbxproj` and see that the `VALID_ARCHS` key is not present)

**Comment by alvinchongry** [comment]
#542
