### ISSUE TITLE
Deprecated on 'unarchiveObjectWithData:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead

### ISSUE THREAD

**Issue by GeoHouseShip** [braintree/braintree_ios#544]
**Integration Details:**
 - SDK/Library Version: Braintree (4.36.0)
 - Environment: Production
 - iOS Version: iOS 12.0
 - Integration type: CocoaPods

**Describe the bug**
Pods/Braintree/BraintreePayPal/PayPalUtils/PPOTSimpleKeychain.m:121:35: 'unarchiveObjectWithData:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead. It lead the compile build error.

**Screenshots**
<img width="1139" alt="Screenshot 2020-10-09" src="https://user-images.githubusercontent.com/72585915/95531454-089b8b80-0a13-11eb-9b16-b2930d332c48.png">

**Comment by garfieldmypet** [comment]
Hi, we are seeing the same issue not being able to compile on Xcode12 . We are using pod BraintreeDropIn version 8.1.1 . Please help, has been stuck at debugging this same error for 2 days.

**Comment by garfieldmypet** [comment]
@scannillo We are seeing this as errors and not warnings, will your suggestion solve this problem?

**Comment by scannillo** [comment]
Hi - here is reference for `inhibit_warnings` if that helps (https://guides.cocoapods.org/syntax/podfile.html#inhibit_all_warnings_bang). Did you try it out?

**Comment by kajz3reczka** [comment]
@scannillo when iOS target is set to 12.0. This is not a warning. It's error
<img width="850" alt="Zrzut ekranu 2020-11-3 o 10 07 38" src="https://user-images.githubusercontent.com/10168974/97966660-6c1f9b80-1dbc-11eb-944b-feedf53d9321.png">

**Comment by sestevens** [comment]
We just released a [beta version](https://github.com/braintree/braintree_ios/releases/tag/5.0.0-beta1) of the SDK that removes the `PayPalUtils` module, so this deprecation warning should no longer be an issue. I'll leave this issue open until these changes are in GA.

Resources:
- [SPM integration instructions](https://github.com/braintree/braintree_ios/tree/5.0.0-beta1#swift-package-manager-v5-beta)
- [Version 5 migration guide](https://github.com/braintree/braintree_ios/blob/5.0.0-beta1/V5_MIGRATION.md)

**Comment by sestevens** [comment]
This has been fixed in [version 5.0.0](https://github.com/braintree/braintree_ios/releases/tag/5.0.0). Please see our [migration guide](https://github.com/braintree/braintree_ios/blob/5.0.0/V5_MIGRATION.md) for steps to upgrade your integration.
