### ISSUE TITLE
non-public selectors in App: setErrorDetail:, setTransactionID:

### ISSUE THREAD

**Issue by tuyen-vuduc** [braintree/braintree_ios#545]
**Integration Details (please complete the following information):**
 - SDK/Library Version: 8.1.1
 - Environment: Production
 - iOS Version: iOS 13.0
 - Device: Any
 - Integration type & version: Xamarin

**Describe the bug**
I am using the latest versions of Naxam.BraintreeDropIn.iOS (8.1.1) and Naxam.BraintreePayPal.iOS (4.35.0) in my Xamarin app. Everything works fine, but Apple does not accept my app bundle:

"ITMS-90338: Non-public API usage - The app references non-public selectors in App: setErrorDetail:, setTransactionID:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/"

Prior versions are working and I can upload them to the app store as well.
I searched for the mentioned symbols (setErrorDetails and setTransactionID) both are contained in the following assembly:
Naxam.CardinalMobile.iOS.dll

https://github.com/NAXAM/braintree-ios-binding/issues/7

**To Reproduce**
It's the last step when submitting app to Apple for review.

**Expected behavior**
No error on Apple Store's submission

Thank you.

**Comment by sestevens** [comment]
Hi @tuyen-vuduc 👋  Was this issue resolved? I see that the [corresponding issue](https://github.com/NAXAM/braintree-ios-binding/issues/7) in  NAXAM/braintree-ios-binding was closed.

**Comment by tuyen-vuduc** [comment]
@sestevens,

There was an issue with the Xamarin binding library.

Thank you.
