### ISSUE TITLE
Double-quoted include in framework header warnings appear in Xcode 12+

### ISSUE THREAD

**Issue by elliottwilliams** [braintree/braintree_ios#546]
Hi! I noticed an issue with Braintree's headers that has appeared in recent versions of Xcode. Nothing critical, and it can be worked around by a build setting, but I wanted to bring it to your attention :)

**Integration Details:**
 - SDK/Library Version: Latest (4.36.0)
 - iOS Version: iOS 14.0 / Xcode 12.0 (12A7208)
 - Integration type & version: Carthage 0.35.0

**Describe the bug**
Braintree's framework headers use quote-imports, not bracket-imports. Apple doesn't like this, because it means that a project with a header of the same name could override one of Braintree's headers unexpectedly. There's been a warning setting about this for awhile (CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER), but it appears to have been turned on by default in recent Xcodes. This means that integrating Braintree in a new project will produce a bunch of warnings at compile-time, or, if a user has enabled Treat Warnings as Errors, importing Braintree will fail their build.

Users can work around this issue by manually setting CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER=NO.

The fix is likely going to require replacing all imports in headers with their bracketed equivalents. For instance, all the imports in https://github.com/braintree/braintree_ios/blob/master/BraintreeCore/Public/BraintreeCore.h would be replaced with `#import <BraintreeCore/HEADER_NAME.h>`, etc.

**To Reproduce**
1. Create a new project.
    * Type: iOS App. Language: Objective-C
    * This is reproducible in Swift projects, too, but only when Swift generates a bridging header, so it's easier to repro using objc directly
2. Link and embed BraintreeCore.framework [using Carthage](https://github.com/braintree/braintree_ios#carthage)
3. In the project's build settings, enable "Treat Warnings as Errors" (GCC_TREAT_WARNINGS_AS_ERRORS=YES)
    * Not necessary to reproduce the issue, but makes it more dramatic
4. Add `#import <BraintreeCore/BraintreeCore.h>` to AppDelegate.m
5. Build

**Expected behavior**
Builds successfully without errors

**Actual behavior**
Errors like

    While building module 'BraintreeCore' imported from /Users/emw/Desktop/brainworms-objc/brainworms-objc/AppDelegate.m:9:
    In file included from <module-includes>:1:
    /Users/emw/Desktop/brainworms-objc/Carthage/Build/iOS/BraintreeCore.framework/Headers/BraintreeCore.h:9:9: error: double-quoted include "BTAPIClient.h" in framework header, expected angle-bracketed instead [-Werror,-Wquoted-include-in-framework-header]
    #import "BTAPIClient.h"
            ^~~~~~~~~~~~~~~
            <BraintreeCore/BTAPIClient.h>

Full build log: https://github.com/braintree/braintree_ios/files/5454230/Build.brainworms-objc_2020-10-28T11-40-07.txt

**Example project**
[brainworms-objc.zip](https://github.com/braintree/braintree_ios/files/5454233/brainworms-objc.zip)

**Comment by sestevens** [comment]
Hi @elliottwilliams, thanks for reporting this issue! We'll take a look at the problem and post any updates here.

**Comment by sestevens** [comment]
Hi @elliottwilliams, we just released a [beta version](https://github.com/braintree/braintree_ios/releases/tag/5.0.0-beta1) of the SDK that should resolve any errors around quoted includes. I'll leave this issue open until these changes are in GA.

Resources:
- [SPM integration instructions](https://github.com/braintree/braintree_ios/tree/5.0.0-beta1#swift-package-manager-v5-beta)
- [Version 5 migration guide](https://github.com/braintree/braintree_ios/blob/5.0.0-beta1/V5_MIGRATION.md)

**Comment by elliottwilliams** [comment]
@sestevens Thanks so much!

**Comment by infowolfe** [comment]
@sestevens would it be possible to backport the fix for this to 4.x series? Currently running into it on Ionic and can't upgrade to 5.0 due to a mess of dependencies.

**Comment by sestevens** [comment]
@infowolfe Possibly, but I'm not sure how soon we would get to it. We would certainly be open to reviewing a PR if it's something you're interested in tackling.

**Comment by infowolfe** [comment]
The mistake's mine, I ran `gem install cocoapods` instead of installing from brew. The 1.10 cocoapods automatically fixes it for ionic users.

**Comment by sestevens** [comment]
This has been fixed in [version 5.0.0](https://github.com/braintree/braintree_ios/releases/tag/5.0.0). Please see our [migration guide](https://github.com/braintree/braintree_ios/blob/5.0.0/V5_MIGRATION.md) for steps to upgrade your integration.
