### ISSUE TITLE
Mac DTK (Big Sur) gives an error while compiling Braintree via Pods with iOS project in Xcode

### ISSUE THREAD

**Issue by ethanwa** [braintree/braintree_ios#547]
Anyone at Braintree have the Mac DTK? When I try and build my iOS app project (NOT Mac app) with the following Pods:

`pod 'Braintree'`
`pod 'BraintreeDropIn'`

I get this error:

`ld: in /.../Pods/Braintree/BraintreePayPal/PayPalDataCollector/Risk/libPPRiskMagnesOC.a(PPRMOCMagnesConstants.o), building for iOS Simulator, but linking in object file built for iOS, file '/.../Pods/Braintree/BraintreePayPal/PayPalDataCollector/Risk/libPPRiskMagnesOC.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by scannillo** [comment]
Hello @ethanwa - thanks for using Braintree. 

It looks like you are using DropIn. A duplicate issue for the same error you're seeing exists [here](https://github.com/braintree/braintree-ios-drop-in/issues/233).

The current solution is to add the setting EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64 in your build configuration.

We're still waiting to hear back from our Magnes Risk team to see if they have any additional thoughts/ updates on their end. 

I will close this issue, and you can track the existing issue linked above.
