### ISSUE TITLE
Remove +load in BTPayDriver 

### ISSUE THREAD

**Issue by shanksGuo** [braintree/braintree_ios#548]
** question
[BTPayDriver load] method take 13ms in my native device when app launches.(See pic below)

<img width="2197" alt="Screen Shot 2020-11-10 at 14 44 37" src="https://user-images.githubusercontent.com/8662571/98637715-c348e180-2363-11eb-9ade-a9a0d39a34f0.png">

** suggestion
remove +load in BTPayDriver, use it when nessary. Further, remove all +load method to keep code in control, because when I optimize the app launch, I found +load method has a big negative effect on app launch.

**Comment by sestevens** [comment]
Hi @shanksGuo, thanks for raising this issue! We'll take a look at ways to reduce the time the `load` method takes to run or see if we can remove it altogether.

**Comment by shanksGuo** [comment]
Thanks in advance, waiting for your optimization.

**Comment by sestevens** [comment]
Hi @shanksGuo, we just released a [beta version](https://github.com/braintree/braintree_ios/releases/tag/5.0.0-beta1) of the SDK that reduces the amount of work being done in the `load` method in `BTPayPalDriver`. I'll leave this issue open until these changes are in GA.

If you want to try it out, here is the [version 5 migration guide](https://github.com/braintree/braintree_ios/blob/5.0.0-beta1/V5_MIGRATION.md).

**Comment by scannillo** [comment]
👋  Hello - since Braintree v5 has been released to GA, I am going to close this issue.
