### ISSUE TITLE
Callback for BTAppSwitchDelegate and BTViewControllerPresentingDelegate are never called

### ISSUE THREAD

**Issue by xujiali08** [braintree/braintree_ios#549]
### **_General information_**
Using cocoapod SDK 4.36.1

### **_Issue description_**
When using these code and delegates :

----
```
- (void)tappedCustomPayPal {
    BTPayPalDriver *payPalDriver = [[BTPayPalDriver alloc] initWithAPIClient:self.apiClient];
    payPalDriver.viewControllerPresentingDelegate = self;
    [payPalDriver authorizeAccountWithCompletion:^(BTPayPalAccountNonce * _Nullable tokenizedPayPalAccount, NSError * _Nullable error) {
        if (tokenizedPayPalAccount) {
            self.progressBlock(@"Got a nonce 💎!");
            NSLog(@"%@", [tokenizedPayPalAccount debugDescription]);
            self.completionBlock(tokenizedPayPalAccount);
        } else if (error) {
            self.progressBlock(error.localizedDescription);
        } else {
            self.progressBlock(@"Canceled 🔰");
        }
    }];
}

- (void)paymentDriver:(__unused id)driver requestsPresentationOfViewController:(UIViewController *)viewController {
    [self presentViewController:viewController animated:YES completion:nil];
}

- (void)paymentDriver:(__unused id)driver requestsDismissalOfViewController:(UIViewController *)viewController {
    [viewController dismissViewControllerAnimated:YES completion:nil];
}
```
-----

Then, we get no callback: no  _requestsPresentationOfViewController_ and no _requestsDismissalOfViewController_

### **_Others_**

I can't get callbacks even with your demo.

**Comment by sestevens** [comment]
Hi @xujiali08, the PayPal flow only uses `BTViewControllerPresentingDelegate` on iOS 10 and earlier. On iOS 11+, we use `SFAuthenticationSession`, which can be presented without a call to `presentViewController`, so calling the `BTViewControllerPresentingDelegate` methods isn't necessary.

On iOS 10 and earlier, `SFAuthenticationSession` is not available, so we use `SFSafariViewController`, which must be presented and dismissed by the merchant in the `BTViewControllerPresentingDelegate` methods.

This is a bit confusing right now, but we're planning to drop support for iOS 11 and below when we do our next major version bump of the SDK, at which point we'll remove the `viewControllerPresentingDelegate` property from `BTPayPalDriver`.

**Comment by sestevens** [comment]
If your app doesn't support iOS 10 or below, you don't need to implement `BTViewControllerPresentingDelegate` for the PayPal flow. (It may still be required for other payment methods.)

**Comment by sestevens** [comment]
I'm closing this issue, but let us know if you need any additional help!

**Comment by xujiali08** [comment]
> If your app doesn't support iOS 10 or below, you don't need to implement `BTViewControllerPresentingDelegate` for the PayPal flow. (It may still be required for other payment methods.)

Okay, I see, my problem now is that after the payment page dismissed, it took me two seconds to get paymentMethodNonce, during which time I couldn't find the right place to add loding to let the user know that we were waiting for the payment result.

**Comment by scannillo** [comment]
Hi @xujiali08 - you can conform to the `BTAppSwitchDelegate` protocol which receives messages when switching to the PayPal checkout flow. Please [see our docs about it here](https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4#implementing-delegate-protocols).

**Comment by siddarth-byte** [comment]
> Hi @xujiali08 - you can conform to the `BTAppSwitchDelegate` protocol which receives messages when switching to the PayPal checkout flow. Please [see our docs about it here](https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4#implementing-delegate-protocols).

@scannillo  BTAppSwitchDelegate has been removed in v5. https://github.com/braintree/braintree_ios/blob/master/V5_MIGRATION.md
