### ISSUE TITLE
I am unable to access the paymentMethod property from the BTDropInResult object.

### ISSUE THREAD

**Issue by rapidmon17** [braintree/braintree_ios#558]
I have code where I need to pass along the nonce to my backend. But the result object doesn't expose the paymentMethod property. During debug, I can see it's there, and I can even see the Nonce, but I can't access it programmatically.

```
if self.showDropIn {
                    BTDropInRepresentable(authorization: token, handler: { controller, result, error in
                        // check for error or result
                        // send tokenized payment method to your server
                        print(result.paymentMethod ?? "No results") // Can't access or find property paymentMethod
                        let res : BTDropInResult = result!
                        print(error ?? "No errors")
                        print(res.paymentMethod ?? "No results") // Can't access or find property paymentMethod
                        print(controller)
                        self.showDropIn = false
                    }).edgesIgnoringSafeArea(.vertical)
                }
```

**Comment by scannillo** [comment]
Hello @rapidmon17 - I'm not sure what you mean by you can see that the nonce is there, but can't access it programmatically.

`BTDropInResult` has a [`paymentMethod` property ](https://github.com/braintree/braintree-ios-drop-in/blob/e043d10b4f8359b08d762364bc3f8cb242ada6dd/BraintreeDropIn/Public/BTDropInResult.h#L28-L29)on it exposing the nonce.

Did you check the `error` for more information?

**Comment by rapidmon17** [comment]
@scannillo  this is what I mean. Please see the screenshot below. As you can see from the watchlist, there's an available paymentMethod property. But when I try to access it by doing res.paymentMethod I get a compile error saying that no such property exists. 

Even reading your documentation shows that this property should be there. 
http://cocoadocs.org/docsets/Braintree/4.6.0/Classes/BTDropInResult.html

[https://imgur.com/a/3jTTm5G](https://imgur.com/a/3jTTm5G)

**Comment by rapidmon17** [comment]
@scannillo here's another screenshot of me trying to access the paymentMethod property from the result object. But as you can see it isn't there. But I can see it during debug in the watchlist section.

[Screeshot trying to get the PaymentMethod property](https://imgur.com/a/XeKPgqF)

**Comment by rapidmon17** [comment]
@scannillo also forgot to mention that there were no errors. The error object was nil.

**Comment by rapidmon17** [comment]
@scannillo  I am such an idiot. So I only imported BraintreeDropIn. I forgot to import Braintree as well.
That solved my problem.
