### ISSUE TITLE
Memory leak when using BTPayPalDriver

### ISSUE THREAD

**Issue by omerozk** [braintree/braintree_ios#563]
**Integration Details (please complete the following information):**
 - SDK/Library Version: 4.33.0
 - Environment: Production
 - iOS Version: iOS 14.2
 - Device: iPhone 12 (Simulator)
 - Integration type & version : CocoaPods 1.9.3

**Describe the bug**
I did the exact same implementation as the [braintree documentation](https://developers.braintreepayments.com/guides/paypal/checkout-with-paypal/ios/v4). 
Everything works no problem but when checking memory management after opening and closing several time the paypal controller, I realize that most of the object created on the method `startCheckout()` (the method from the documentation) are kept in memory.

For information it has no impact on my app controllers or whatsoever the retain cycle happen in the library Itself I think

**To Reproduce**
1. Open and close several time paypal controller - start and cancel checkout several time
2. Check memory leaks

**Expected behavior**
One instance of `BTPaypalDriver` & `BTAPIClient` and released after dismissing BTPaypalDriver controller.

**Screenshots**

Before launching BTPaypalDriver:
![before](https://user-images.githubusercontent.com/11772701/102514607-f9792f80-408c-11eb-9001-6a19b1c8c98d.png)

After 1 opening and cancelling the BTPaypalDriver controller:
![after-1-time](https://user-images.githubusercontent.com/11772701/102514621-fc742000-408c-11eb-92ed-df07ed427d65.png)

After 2 opening and cancelling the BTPaypalDriver controller:
![after-2-time](https://user-images.githubusercontent.com/11772701/102514620-fc742000-408c-11eb-99a6-3e933bf7660a.png)

After 3 opening and cancelling the BTPaypalDriver controller:
![after-3-time](https://user-images.githubusercontent.com/11772701/102514623-fd0cb680-408c-11eb-8288-8dd2843582f6.png)

**Comment by victor-yn** [comment]
I just checked and I confirm I'm having the same results on my side. I'm invoking the Checkout with PayPal Flow, dismiss it and the related objects seem to never be released.

**Comment by sestevens** [comment]
This has been fixed in [version 5.0.0](https://github.com/braintree/braintree_ios/releases/tag/5.0.0). Please see our [migration guide](https://github.com/braintree/braintree_ios/blob/5.0.0/V5_MIGRATION.md) for steps to upgrade your integration.
