### ISSUE TITLE
Unable to archive project which use BraintreeDataCollector or PayPalDataCollector

### ISSUE THREAD

**Issue by JonathanDowning** [braintree/braintree_ios#576]
**Integration Details (please complete the following information):**
 - SDK/Library Version: master branch/commit hash `acf23311388bc6be10f9a1b7740c77fa3a42c1f5`
 - Environment: N/A
 - iOS Version: N/A
 - Device: N/A
 - Integration type & version: Swift Package Manager

**Describe the bug**
Xcode cannot archive `BraintreeDataCollector` or `PayPalDataCollector` (or targets which depend on these).

These targets depend on `xcframeworks`, I suspect this is not a coincidence. 

Xcode emits the following error for each target:

`BraintreeDataCollector`:
> 'kDataCollector.h' file not found

`PayPalDataCollector`:
> No such module 'PPRiskMagnes'

**To Reproduce**
1. In Terminal, from the project directory: `git checkout acf23311388bc6be10f9a1b7740c77fa3a42c1f5` (or pull the current master branch)
2. `open Package.swift`
3. Select either `PayPalDataCollector` or `BraintreeDataCollector` from the schemes dropdown
4. Click Product > Archive
5. See error

**Expected behavior**
The project should archive successfully

**Screenshots**
<img width="1611" alt="Screen Shot 2021-01-06 at 16 15 59" src="https://user-images.githubusercontent.com/2230175/103821250-cbf42600-503b-11eb-94c5-b906b26a378e.png">
<img width="1611" alt="Screen Shot 2021-01-06 at 16 16 14" src="https://user-images.githubusercontent.com/2230175/103821252-cc8cbc80-503b-11eb-812b-dee4737bb2dd.png">

**Comment by scannillo** [comment]
Hi @JonathanDowning - thank you for opening this issue and providing detail. I am able to replicate the issue. We will keep you posted as we work on a fix.

**Comment by scannillo** [comment]
Hey @JonathanDowning - after some investigating, multiple sources can confirm this is an Xcode bug. A report has been filed for it [here](https://bugs.swift.org/browse/SR-13803).

Related issues:
- [Swift forums](https://forums.swift.org/t/binary-dependency-fails-on-archive/40780/7)
- [Apple dev forums](https://developer.apple.com/forums/thread/662247)

We'll keep you posted when we release a workaround.

**Comment by JonathanDowning** [comment]
Hey @scannillo ! Thank you very much for your assiduousness in looking into this bug. I too suspected this was a bug related to binary dependencies in SPM. (Sigh!)

A super thanks goes to you and the team for being receptive to my feedback :) 

Are you planning on waiting for this issue to be resolved with Xcode before shipping 5.0, or will this be a "known issue".

**Comment by scannillo** [comment]
We very much welcome and appreciate your feedback! Please keep it coming if you have more.

As of right now our workaround is - if we expose the binary targets as product libraries and the app also includes them, we're able to archive successfully.

**Comment by JonathanDowning** [comment]
Given my desire to rid our project of Carthage, this is agreeable. I'm hesitant to suggest waiting for an Xcode fix since who knows when this could be. (Murphy's law is Xcode 12.4 beta is released next week with a fix)

**Comment by sestevens** [comment]
This fix is released in 5.0.0-beta2.

**Comment by sestevens** [comment]
This has been fixed in [version 5.0.0](https://github.com/braintree/braintree_ios/releases/tag/5.0.0). See our [Swift Package Manager guide](https://github.com/braintree/braintree_ios/blob/master/SWIFT_PACKAGE_MANAGER.md) for instructions and required workarounds. See our [migration guide](https://github.com/braintree/braintree_ios/blob/5.0.0/V5_MIGRATION.md) for steps to upgrade your integration.

**Comment by JetForMe** [comment]
I do not believe this is fixed in 5.0.0. We're trying to use the iOS drop-in 9.0.2, which has braintree-ios 5.0.3 as a dependency, and we're running into `No such module 'PPRiskMagnes'` when archiving (builds just fine). So far the workaround has not worked for us.

**Comment by YKV** [comment]
I'am getting the same error on Xcode 12.5. I used a provided [workaround](https://github.com/braintree/braintree_ios/blob/master/SWIFT_PACKAGE_MANAGER.md) and [this](https://github.com/braintree/braintree-ios-drop-in/issues/317#issuecomment-815005747), but no luck. **Braintree 5.3.2 and BraintreeDropIn 9.0.2**

**Comment by JackoPlane** [comment]
@sestevens Can we have an update on how folks and work around this issue?

**Comment by sestevens** [comment]
Let's move this conversation over to #679. From what we can tell, the archive issues occurring now are specific to `PPRiskMagnes`, whereas this issue involved any binary dependency.

We're able to reproduce the archive issues intermittently, but cleaning and re-building seems to resolve them. We'll continue investigating and post any additional findings in #679.
