### ISSUE TITLE
BTDropInController is nil if we use "CLIENT_TOKEN_FROM_SERVER"

### ISSUE THREAD

**Issue by SerggioC** [braintree/braintree_ios#578]
BTDropInController is nil if we use "CLIENT_TOKEN_FROM_SERVER" for authorization. 
swift 
```
let dropIn = BTDropInController(authorization: "CLIENT_TOKEN_FROM_SERVER", request: dropInRequest) { (controller, result, error) in
.... 
}
```
dropin is nil after this instantiation. Which is not what you have in the documentation:

> 
> Try it now
> We generated a demo client token for you so you can jump right in. This is for testing purposes only!
> 
> Objective-C
> Swift
> 
> Copy
> Copied
> let clientToken = "CLIENT_TOKEN_FROM_SERVER"
> let clientToken = "CLIENT_TOKEN_FROM_SERVER"
> The above demo client token is for temporary use. You must change this client token in order to process payments with your Braintree sandbox or production account.

Is there another sandbox token we can use for testing porpuse?

Thank you.

**Comment by crookedneighbor** [comment]
Looks like something happened with our docs where the client token is no longer being generated. We'll take a look at that. 

In the meantime, you can investigate with the [tokenization key](https://developers.braintreepayments.com/guides/authorization/tokenization-key/ios/v4) in the demo app: https://github.com/braintree/braintree_ios/blob/88b362daffd2e69c8a8bc95bbf7700a51f861495/Demo/Application/Base/BraintreeDemoContainmentViewController.m#L128

**Comment by crookedneighbor** [comment]
We're updating the docs to show a demo tokenization key instead. Because of this, I'm going to go ahead and close this issue (since there's no further SDK work that needs to be done here)
