### ISSUE TITLE
located in a country (i.e. India) where PayPal does not allow USD payments but only payments using the local currency

### ISSUE THREAD

**Issue by shravanteegala** [braintree/braintree_ios#597]
i got below message 
"We’re sorry, the merchant doesn’t accept payments in your currency. Please return to the merchant and choose another way to pay".

If a customer is receiving this message, it means they are located in a country (i.e. India) where PayPal does not allow USD payments but only payments using the local currency.

**Comment by crookedneighbor** [comment]
Please contact our support team about this: https://help.braintreepayments.com/

**Comment by shravanteegala** [comment]
> Please contact our support team about this: https://help.braintreepayments.com/

i already contacts them, but they are not give appropriate solution.

**Comment by crookedneighbor** [comment]
> i already contacts them, but they are not give appropriate solution.

What did they tell you to do?

My assumption here is that you need to have your Braintree gateway set up to accept INR as well as your PayPal account.

**Comment by shravanteegala** [comment]
> > i already contacts them, but they are not give appropriate solution.
> 
> What did they tell you to do?
> 
> My assumption here is that you need to have your Braintree gateway set up to accept INR as well as your PayPal account.

Yes, it might be how i can reslove it.

**Comment by crookedneighbor** [comment]
That is what I assume needs to happen here. Regardless, the issue isn't in the SDK, so I'd be sure to follow up on the support ticket you opened. Feel free to reference this Github issue in your ticketl
