### ISSUE TITLE
PayPal does not allow USD payments from using India(INR) default currency issue ?

### ISSUE THREAD

**Issue by shravanteegala** [braintree/braintree_ios#598]
Hi ,
I got below issue.i having india(INR) country default currency.
![Screenshot 2021-02-01 at 11 44 40 PM](https://user-images.githubusercontent.com/13646977/106500893-5e2b0500-64e8-11eb-82fb-f36122dac7fa.png)

How can I resolve it.

**Comment by crookedneighbor** [comment]
Let's keep this in the original issue you opened (#597)
