### ISSUE TITLE
Apple Pay entitlement is required even when not used

### ISSUE THREAD

**Issue by sergey-sportsetter** [braintree/braintree_ios#60]
Using Braintree 3.4.0, v.zero drop-in UI

Upon submission to Apple, got the message:
>App contains references to [Apple Pay] in 'SportSetter', but is missing the required entitlement '.com.apple.developer.in-app-payments'

Previously, this entitlement was not necessary

**Comment by indisee** [comment]
have same issue with iTC — upload build and get mail from apple. Do not use any of ApplePay set up or usage code, xcode's capabilities and developer.apple.com do not have ApplePay enabled. 
Is there some workaround to prevent this warning?
Braintree (3.4.2)

**Comment by jemmons** [comment]
+1

**Comment by xinghengwang** [comment]
Is this issue getting fixed soon? 
What is the work around?

**Comment by burnto** [comment]
Yes we are working on a fix and will update here shortly.

**Comment by burnto** [comment]
Hi all, apologies for the delay. We have a solution for this that we're doing some final verification on. Expect a commit and an update here soon.

**Comment by mickeyreiss** [comment]
@burnto's fix is now on master as of https://github.com/braintree/braintree_ios/commit/e142286234522a05f183b563bbad0c60c2537f88.

**Comment by burnto** [comment]
Starting in e142286 (which will be part of a tagged release in the next few days), Apple Pay is only part of the Braintree iOS build when the optional `Braintree/Apple-Pay` subspec is specified in your `Podfile`. 

The basic tests are [pretty](https://github.com/braintree/braintree_ios/blob/e142286234522a05f183b563bbad0c60c2537f88/Rakefile#L149-L151) [simple](https://github.com/braintree/braintree_ios/blob/e142286234522a05f183b563bbad0c60c2537f88/Rakefile#L160-L162), if a little coarse, and just use `nm` to check for symbols that look suspiciously like Apple's. Of course the real test is whether your app submission results in a warning, so once you get a chance to update, please let us know if you encounter further issues.

Thanks all!

**Comment by lupugabriel** [comment]
Hi everybody... i added to my podfile:

pod "Braintree"
pod "Braintree/Enable-Apple-Pay"

and i have this error: 

[!] Unable to satisfy the following requirements:
- `Braintree/Enable-Apple-Pay` required by `Podfile`

Can you help?

**Comment by burnto** [comment]
Hi @lupugabriel - as noted in #83, this was an inaccuracy in the README that I fixed in 36e90bf9a225f2baa40ab6f6cdaca7ef5641efd4. Let us know if `Braintree/Apple-Pay` works for you, and if you have any further issue, and thanks again for posting this issue.

**Comment by mickeyreiss** [comment]
Closing as this is resolved in the latest release. Feel free to re-open, if you experience any continued issues with `Braintree/Apple Pay`.
