### ISSUE TITLE
List of bundled third party open source code

### ISSUE THREAD

**Issue by ebfikus** [braintree/braintree_ios#61]
The SDK documentation should include a list of all bundled open source software. Apps that use the Braintree SDK include copies of this third-party software and attribution may be required to comply with the various open source licenses. For example, I believe both 1Password and card.io have an MIT license, which requires a copyright notice to be included in all copies.

**Comment by qiudushu** [comment]
can   you  tell  me  how  to  change status ????
![_2015-09-23_ 2_00_47](https://cloud.githubusercontent.com/assets/8954445/10039911/4883bebe-6209-11e5-9022-0365fad5b394.png)

I want OnLine

**Comment by intelliot** [comment]
The Braintree iOS SDK no longer includes 1Password, card.io, or the PayPal mSDK.
