### ISSUE TITLE
"Skipping duplicate build file" warning v5.0.0

### ISSUE THREAD

**Issue by eseay** [braintree/braintree_ios#624]
**Integration Details (please complete the following information):**
 - SDK/Library Version: 5.0.0
 - Environment: Production
 - iOS Version: iOS 14.3 (18C61)
 - Device: Simulator & physical device (iPhone 12 Pro)
 - Integration type & version: SPM (Xcode 12.3)

**Describe the bug**
We are using the PayPal integration within our app and have brought in the following modules via SPM:
- BraintreeCore
- BraintreePayPal
- PPRiskMagnes
- PayPalDataCollector

When building the app for either Simulator or my physical device, Xcode emits a warning that says the following (twice in the build log output, once in the Xcode project navigator):

```
Skipping duplicate build file in Copy Files build phase: /Users/{home_folder}/Library/Developer/Xcode/DerivedData/{scheme_name}-griegwwgeebsckabjzpvjqvfdvua/SourcePackages/checkouts/braintree_ios/Frameworks/PPRiskMagnes.xcframework/ios-arm64_armv7/PPRiskMagnes.framework

Skipping duplicate build file in Copy Files build phase: /Users/{home_folder}/Library/Developer/Xcode/DerivedData/{scheme_name}-griegwwgeebsckabjzpvjqvfdvua/SourcePackages/checkouts/braintree_ios/Frameworks/PPRiskMagnes.xcframework/ios-arm64_armv7/PPRiskMagnes.framework
```

**To Reproduce**
This occurs each time I build, after clearing DerivedData, cleaning, etc. I have checked the `.pbxproj` for duplicate references to no avail.

**Expected behavior**
I would expect that the compiler does not emit a warning. If this is actually a non-issue, I'd expect that the SPM documentation indicate either a workaround of a note that it's a "known issue." Seeing as this is just a warning, the build succeeds, but main concern is just that when it comes time to release this version of the app and export it for App Store submission that I do not run into issues with the upload process.

**Comment by sestevens** [comment]
👋  This warning was fixed in [version 5.0.1](https://github.com/braintree/braintree_ios/releases/tag/5.0.1). Thanks for the report!
