### ISSUE TITLE
Migration from BraintreeDropIn Pod to SPM?

### ISSUE THREAD

**Issue by ethanwa** [braintree/braintree_ios#626]
Hi, can you add instructions on how to migrate from the BraintreeDropIn Pod to SPM with the 5.0 release?

My app currently just uses the following Pods with v4:

```
pod 'Braintree'
pod 'BraintreeDropIn'
```

Thanks!

**Comment by scannillo** [comment]
Hi @ethanwa - BraintreeDropIn support for SPM is currently in development. You can follow[ this issue](https://github.com/braintree/braintree-ios-drop-in/issues/155) to track its progress!
