### ISSUE TITLE
Support simulation of PayPal One Touch errors via fake-wallet 

### ISSUE THREAD

**Issue by mobitar** [braintree/braintree_ios#63]
This is the URL that's generated when I press the PayPal button (I'm currently testing on the simulator with the fake-wallet app):

`
com.paypal.ppclient.touch.v1://authenticate?payload=redacted&x-source=com.redacted&x-success=com.redacted.payments://success&x-cancel=com.redacted.payments://cancel
`

**Comment by intelliot** [comment]
Enhancements are no longer being added to the `3.x` branch. For enhancement requests on the latest version of the Braintree iOS SDK, please open new issues. Thanks!
