### ISSUE TITLE
Duplicated symbols for architecture x_86_64 when using -ObjC linker flag

### ISSUE THREAD

**Issue by mbuchetics** [braintree/braintree_ios#638]
**Integration Details:**
 - Braintree SDK Version: 5.0.0
 - Environment: Sandbox & Production
 - iOS Version: -
 - Device: -
 - Integration type & version: Swift Package Manager 5.0.0

**Describe the bug**
When integrating using SPM, building a project fails when using the `-ObjC` linker flag. Removing the flag works but it is necessary for certain other frameworks (Firebase) so this is not a viable solution.

```
duplicate symbol '_stepperSessionArray' in:
    /Users/matthias/Library/Developer/Xcode/DerivedData/Example-cnsfbbnhrbtmnlfhnwkhopuzojru/Build/Products/Debug-iphonesimulator/libKountDataCollector.a(KountAnalyticsViewController.o)
    /Users/matthias/Library/Developer/Xcode/DerivedData/Example-cnsfbbnhrbtmnlfhnwkhopuzojru/Build/Products/Debug-iphonesimulator/libKountDataCollector.a(StoreUIContolsData.o)
duplicate symbol '_sliderSessionArray' in:
    /Users/matthias/Library/Developer/Xcode/DerivedData/Example-cnsfbbnhrbtmnlfhnwkhopuzojru/Build/Products/Debug-iphonesimulator/libKountDataCollector.a(KountAnalyticsViewController.o)
    /Users/matthias/Library/Developer/Xcode/DerivedData/Example-cnsfbbnhrbtmnlfhnwkhopuzojru/Build/Products/Debug-iphonesimulator/libKountDataCollector.a(StoreUIContolsData.o)
duplicate symbol '_buttonSessionArray' in:
    /Users/matthias/Library/Developer/Xcode/DerivedData/Example-cnsfbbnhrbtmnlfhnwkhopuzojru/Build/Products/Debug-iphonesimulator/libKountDataCollector.a(KountAnalyticsViewController.o)
    /Users/matthias/Library/Developer/Xcode/DerivedData/Example-cnsfbbnhrbtmnlfhnwkhopuzojru/Build/Products/Debug-iphonesimulator/libKountDataCollector.a(StoreUIContolsData.o)
duplicate symbol '_pageControlSessionArray' in:
    /Users/matthias/Library/Developer/Xcode/DerivedData/Example-cnsfbbnhrbtmnlfhnwkhopuzojru/Build/Products/Debug-iphonesimulator/libKountDataCollector.a(KountAnalyticsViewController.o)
    /Users/matthias/Library/Developer/Xcode/DerivedData/Example-cnsfbbnhrbtmnlfhnwkhopuzojru/Build/Products/Debug-iphonesimulator/libKountDataCollector.a(StoreUIContolsData.o)
```

**To Reproduce**
1. Open the `SPMTest` example
2. Got to `Build Settings` and add `-ObjC` to `Other Linker Flags`.
3. Try and build the project.

**Comment by sestevens** [comment]
@mbuchetics Thanks for reporting this! I was able to replicate the issue in a sample app that integrates directly with `KountDataCollector.xcframework`, so it seems like this issue lies there. I passed this report on to our partners at Kount. We'll update this issue when we have more information from them.

**Comment by scannillo** [comment]
Hi @mbuchetics - we released a new version of the [Braintree iOS SDK v5.3.0](https://github.com/braintree/braintree_ios/releases/tag/5.3.0), which includes an updated version of Kount v4.1.4.

Please try updating and let us know if the issue resolves. We were able to get things working using this new version along with deleting derived data.

**Comment by mbuchetics** [comment]
That sounds great. I will try to use it once the Drop-In SDK also provides SPM support.

**Comment by scannillo** [comment]
Hi @mbuchetics - we are going to close this issue, since we were able to resolve this issue in a sample app. If you run into any additional issues, please let us know or open a new issue!
