### ISSUE TITLE
Multiple commands produce '..../Debug-iphonesimulator/XCFrameworkIntermediates/KountDataCollector'

### ISSUE THREAD

**Issue by yeradis** [braintree/braintree_ios#657]
Just by upgrading the Braintree SDK from version 4.37.0 to 5.3.0 causes the following issue at compile time:

```
error: Multiple commands produce '..../Debug-iphonesimulator/XCFrameworkIntermediates/KountDataCollector':
1) That command depends on command in Target 'Braintree-framework' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
2) That command depends on command in Target 'Braintree-library' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
```

Upgrading Braintree SDK Version to 5.3.0 from 4.37
Integration type & version: Cocoapods 1.10.1

Right now I have two targets in the project, the main target and App Clip target

Dependencies are specified in this way:

```
target 'MainTarget' do
    use_frameworks!
    platform :ios, '13.4'
    
    pod 'Braintree/Core', '~> 5.3.0', :inhibit_warnings => true
    pod 'Braintree/Card', '~> 5.3.0', :inhibit_warnings => true
    pod 'Braintree/ApplePay', '~> 5.3.0', :inhibit_warnings => true
    pod 'Braintree/DataCollector', '~> 5.3.0', :inhibit_warnings => true
end

target 'AppClipTarget' do
  use_modular_headers!
  platform :ios, '14.1'
  
  pod 'Braintree/Core', '~> 5.3.0', :inhibit_warnings => true
  pod 'Braintree/Card', '~> 5.3.0', :inhibit_warnings => true
  pod 'Braintree/ApplePay', '~> 5.3.0', :inhibit_warnings => true
  pod 'Braintree/DataCollector', '~> 5.3.0', :inhibit_warnings => true
end       
```

the only change is the version number, previous was 4.37 and now its 5.3.0
with 4.37 project builds without issue, but setting to 5.3.0 project fails to compile

**Comment by sestevens** [comment]
Hey @yeradis, this looks like a CocoaPods issue. I see a couple similar reports on the CocoaPods GitHub repo:
- https://github.com/CocoaPods/CocoaPods/issues/10106
- https://github.com/CocoaPods/CocoaPods/issues/9973
I'd suggest following along with those issues to see if there's a resolution or workaround.

**Comment by scannillo** [comment]
👋  Hi @yeradis - I am going to close this issue since it is a known CocoaPods issue.
