### ISSUE TITLE
Add payment verified status 

### ISSUE THREAD

**Issue by yawaraym** [braintree/braintree_ios#658]
**Is your feature request related to a problem? Please describe.**
After authorization, I need to know if that user has verified payment status or not, but there is no property in BTPaypalAccountNonce class for that.

```
payPalDriver.authorizeAccount() { (tokenizedPayPalAccount, error) in
    print(tokenizedPayPalAccount)
}
```

**Describe the solution you'd like**
We can get that simply using userInfo api from paypal and all other properties are there except this one.
[PAYPAL API LINK](https://developer.paypal.com/docs/api/identity/v1/)

**Comment by sestevens** [comment]
Hi @yawaraym, the SDK doesn't have access to this field, so it's not as easy as simply adding a property to the SDK. Unfortunately, adding this isn't something we can do at this time.
