### ISSUE TITLE
the issue about duplicate symbol '_kAppId'

### ISSUE THREAD

**Issue by fengyupianzhou** [braintree/braintree_ios#660]
When I add the Braintree SDK by Podfile, because Tencent’s QQ SDK already exists in my project, When I execute the build, an error is reported, The log is as follows:

duplicate symbol '_kAppId' in:  /Users/aw/Downloads/iOSDK/myiOS/MySDKSample/Pods/Braintree/BraintreePayPal/PayPalDataCollector/Risk/libPPRiskMagnesOC.a(PPRMOCMagnesConstants.o)
Users/aw/Downloads/iOSDK/myiOS/MySDKSample/MySDKSample/QQ/TencentOpenAPI.framework/TencentOpenAPI(libTencentOpenApi_IOS.a-arm64-master.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Hope to get help, thanks!

**Comment by scannillo** [comment]
Hi - which version of the SDK are you using? If you're using v4, we released a fix for this in [v4.37.1](https://github.com/braintree/braintree_ios/releases/tag/4.37.1). 

However, we recommend upgrading to [v5](https://github.com/braintree/braintree_ios/releases/tag/5.3.0). v5 uses a Swift version of PPRiskMagnes and also avoids this duplicate symbols issue.

**Comment by fengyupianzhou** [comment]
thx, compile successfully
