### ISSUE TITLE
BTDataCollector collectDeviceData returns empty json {}

### ISSUE THREAD

**Issue by yeradis** [braintree/braintree_ios#661]
BTDataCollector.collectDeviceData returns empty json {}

 - Braintree SDK Version: 4.37.1
 - Environment: Production
 - iOS Version: iOS 14.4.2 but its happening on lower versions too
 - Device: iPhone 6s, 12 Pro Max
 - Integration type & version: CocoaPods 1.10.1

**Describe the bug**

BTDataCollector `collectDeviceData` returns empty json `{}` on Release builds

Development builds returns more information like:`{"device_session_id":"***********", "fraud_merchant_id":"********"}`

**Comment by sestevens** [comment]
Hi @yeradis, it sounds to me like your merchant account may not be set up for this. Please reach out to [Braintree Support](https://help.braintreepayments.com/) for assistance.

**Comment by yeradis** [comment]
@sestevens this was closed too fast

I want to add more information, the Android version of the app is able to get this information for the production build
Its merchant account at Braintree configured per device operating system?

**Comment by scannillo** [comment]
Hi @yeradis - I tried a sample app with v4.37.1 of the Braintree SDK and am not able to replicate this issue in a release or debug build on both simulator and device.

Are you using the same merchant account for both Android and iOS applications? I still think reaching out to our Support team will be your best bet in getting this resolved.

**Comment by yeradis** [comment]
@scannillo thanks for reaching out, 

The merchant account is the same on both platform, this is something we have been using since 2015 at least, the data collection is something that we have been using since last year

What I have noticed on this issue with BTDataCollector is that only dataCollectorDidStart get called,  dataCollectorDidComplete or didFailWithError is never called :(

About contacting the Support team, its already done

Thanks for your time
