### ISSUE TITLE
Venmo Vault implementation

### ISSUE THREAD

**Issue by jbatra-umeey** [braintree/braintree_ios#686]
Integration Details

Braintree SDK Version: 5.3.0
Environment: : Sandbox
iOS Version: : iOS 13.4.1
Device: [e.g. iPhone 12] : iPhone 7
Integration type & version: Cocoapods 1.10.1

**Describe the bug**
Not able to test Venmo vault in a sandbox environment. It shows a similar behavior 
Also, there is no information on the difference between a client token and a `Braintree client token with a customer ID`

```
import "BraintreeVenmo.h"

class ViewController: UIViewController {

    var venmoDriver : BTVenmoDriver?
    var venmoButton : UIButton?
    var apiClient : BTAPIClient!

    override func viewDidLoad() {
        super.viewDidLoad()

        self.apiClient = BTAPIClient(authorization: "<#CLIENT_AUTHORIZATION#>")
        self.venmoDriver = BTVenmoDriver(apiClient: self.apiClient)
       
    }

    func tappedButton() {
            // To vault the Venmo account, change this to true and use a Braintree client token with a customer ID

        self.venmoDriver?.authorizeAccountAndVault(true, completion: { (venmoAccount, error) in

            guard let venmoAccount = venmoAccount else {
                print("Error: \(error)")
                return
            }

            // You got a Venmo nonce!
            print(venmoAccount.nonce)
        }
    }
}
```

**To Reproduce**
1. Add code for Venmo vault implementation
2. Run the application
3. See the behavior

**Expected behavior**
Vault flow should be different from the non-vault flow

<img width="1167" alt="Screenshot 2021-05-25 at 2 12 20 PM" src="https://user-images.githubusercontent.com/75033678/119467708-6347e480-bd63-11eb-8d14-73e6d6a8d079.png">

**Comment by scannillo** [comment]
👋  Hello @jbatra-umeey. Please see our [V5_MIGRATION ](https://github.com/braintree/braintree_ios/blob/master/V5_MIGRATION.md#venmo)guide which calls out that the `authorizeAccount` methods on `BTVenmoDriver` have been replaced with a `tokenizeVenmoAccount` method.

If you are starting a new integration, see our [developer docs](https://developers.braintreepayments.com/guides/venmo/client-side/ios/v5#custom-integration).
