### ISSUE TITLE
 How to pass a customer ID in `authorizeAccountAndVault `

### ISSUE THREAD

**Issue by jbatra-umeey** [braintree/braintree_ios#687]
Integration Details

Braintree SDK Version: 4.37.1
Environment: : Sandbox
iOS Version: : iOS 13.4.1
Device: [e.g. iPhone 12] : iPhone 7
Integration type & version: Cocoapods 1.10.1

Describe the bug
In continuation to issue https://github.com/braintree/braintree_ios/issues/686
Wanted to understand how to pass the Braintree client token with a customer ID. Right now, I only have a client sandbox token
I came across this link https://articles.braintreepayments.com/guides/payment-methods/venmo?&&_ga=1.246385924.1043934551.1618820075#testing

 ```
 self.venmoDriver?.authorizeAccountAndVault(true, completion: { (venmoAccount, error) in

            guard let venmoAccount = venmoAccount else {
                print("Error: \(error)")
                return
            }

            // You got a Venmo nonce!
            print(venmoAccount.nonce)
        }
```
    

To Reproduce
Add code for Venmo vault implementation as per documentation https://developers.braintreepayments.com/guides/venmo/client-side/ios/v4
Run the application
See the behavior

Expected behavior
Vault flow should be different from the non-vault flow if `vault` is enabled and a `customer ID` is passed

**Comment by sestevens** [comment]
Hey @jbatra-umeey, your server will need to supply the customer ID when [generating the client token](https://developers.braintreepayments.com/start/hello-server/ruby#generate-a-client-token). Please reach out to [Braintree Support](https://help.braintreepayments.com/) with any additional questions like this -- they'll be happy to help!
