### ISSUE TITLE
The Swift Package Manager is running into a lot of endless checkout/fetch loops for this package.

### ISSUE THREAD

**Issue by bjensen1** [braintree/braintree_ios#688]
**Integration Details (please complete the following information):**
 - Braintree SDK Version: 5.3.2
 - Environment: n/a
 - iOS Version: n/a
 - Device: n/a
 - Integration type & version: Swift Package Manager in Xcode 12.5

**Describe the bug**
In the past couple days, I can't get this package to load into the project in a stable way. Other packages in the workspace are fetching and loading without an issue.

**To Reproduce**
1. Add the package dependency
2. "Workspace Integrity Couldn't load project braintree_ios" is shown in the Xcode build errors, or else it will do an endless loop of "(fetching...)" and "(checking out...)" (see screenshot).

**Expected behavior**
I'd expect it to only fetch and check out once on launch.

**Screenshots**
<img width="342" alt="CheckingOut" src="https://user-images.githubusercontent.com/74669381/119743174-83040900-be46-11eb-9bf9-cdcb4f96e9ae.png">

**Comment by scannillo** [comment]
👋  Hello @bjensen1 - I just created a blank XCode app project and included `braintree_ios` via SPM. I didn't encounter any issues in doing so. Can you either provide more specific replication instructions or try removing, cleaning, and then re-adding the `braintree_ios` dependency entirely from your application?

**Comment by bjensen1** [comment]
I'll keep researching. I've certainly tried every combo of removing, cleaning, re-adding, rebooting, and everything else I can think of. It's entirely likely that this is an Xcode bug, but I thought it would be worth posting to see if the Braintree team knew of an issue. For what it's worth, I can't fix it by removing and adding the package again, but I can fix it by reverting the pbxproj file changes. However, when I do this, the library version reverts to 5.3.1 and doesn't have the issue anymore. Is there any chance something could just be off about this most recent 5.3.2 package release?

**Comment by sestevens** [comment]
@bjensen1 Could you try creating a brand new Xcode project and including Braintree 5.3.2 via SPM? That might tell us if the issue is specific to your project (maybe a conflict with another dependency?) or a more general project with the Braintree Swift package.

**Comment by scannillo** [comment]
👋  @bjensen1 - since we haven't heard back from you with additional concerns - we are going to close this issue.
