### ISSUE TITLE
Remove Excluded architectures flag

### ISSUE THREAD

**Issue by DagAgren** [braintree/braintree_ios#690]
Is there any chance of getting the framework correctly built for both x86_64 and arm64 on simulator? The EXCLUDED_ARCHS flag added to the podspec causes various problems when developing on M1, and is preventing various testing and build system improvements we want to make in our project.

**Comment by scannillo** [comment]
👋  Hey @DagAgren - thank you for opening this issue. Currently, we are blocked by our ThreeDSecure provider (CardinalMobile.xcframework) from providing full arm64 simulator support. However, this is definitely something we will look into for the rest of the Braintree modules.

[Running Rosetta](https://medium.com/codex/simple-way-to-use-cocoapods-on-m1-ac9e22cf7e1c) on the M1 Mac allows things to work OK for me. Are you not running Rosetta? Also sharing the specific console errors you see will be helpful for us to get started on this. Thank you!

**Comment by DagAgren** [comment]
Rosetta only works in some cases. It breaks when trying to add a standalone test target, and possibly also causes problems with having dependencies in SwiftPM.

Basically it seems that forcing simulator builds to be x86 works mostly by accident, Xcode as a whole does not really work with this setup.

**Comment by scannillo** [comment]
Hi - we removed the `EXCLUDED_ARCH` flags from our Podspec in our latest release [v5.5.0](https://github.com/braintree/braintree_ios/releases/tag/5.5.0) 🎊 . Please check out the release notes.
