### ISSUE TITLE
Cannot build for x86-64 iOS Simulator. arm64 error with PPRiskMagnes.MagnesSDK.

### ISSUE THREAD

**Issue by anutting** [braintree/braintree_ios#707]
**Integration Details (please complete the following information):**
 - Braintree SDK Version: 5.4 
 - iOS Version: 12 
 - Xcode Version: 12.5 
 - Device: iPhone 12 Simulator 
 - Integration type & version: CocoaPods 1.9.3 

**Describe the bug**
Description of what the bug is. Please include as many details as possible.

Build is failing:

Pods/Braintree/Frameworks/PPRiskMagnes.xcframework/ios-arm64/PPRiskMagnes.framework/PPRiskMagnes, building for iOS Simulator-x86_64 but attempting to link with file built for iOS-arm64
Undefined symbols for architecture x86_64:
  "type metadata accessor for PPRiskMagnes.MagnesSDK", referenced from:
      static Braintree.PPDataCollector.generateClientMetadataID(_: Swift.String?, disableBeacon: Swift.Bool, data: [Swift.String : Swift.String]?) -> Swift.String in PPDataCollector.o
  "dispatch thunk of static PPRiskMagnes.MagnesSDK.shared() -> PPRiskMagnes.MagnesSDK", referenced from:
      static Braintree.PPDataCollector.generateClientMetadataID(_: Swift.String?, disableBeacon: Swift.Bool, data: [Swift.String : Swift.String]?) -> Swift.String in PPDataCollector.o
  "dispatch thunk of PPRiskMagnes.MagnesSDK.setUp(setEnviroment: PPRiskMagnes.MagnesSDK.Environment, setOptionalAppGuid: Swift.String, setOptionalAPNToken: Swift.String, disableRemoteConfiguration: Swift.Bool, disableBeacon: Swift.Bool, magnesSource: PPRiskMagnes.MagnesSDK.MagnesSource) throws -> ()", referenced from:
      static Braintree.PPDataCollector.generateClientMetadataID(_: Swift.String?, disableBeacon: Swift.Bool, data: [Swift.String : Swift.String]?) -> Swift.String in PPDataCollector.o
  "dispatch thunk of PPRiskMagnes.MagnesSDK.collectAndSubmit(withPayPalClientMetadataId: Swift.String, withAdditionalData: [Swift.String : Swift.String]) throws -> PPRiskMagnes.MagnesResult", referenced from:
      static Braintree.PPDataCollector.generateClientMetadataID(_: Swift.String?, disableBeacon: Swift.Bool, data: [Swift.String : Swift.String]?) -> Swift.String in PPDataCollector.o
  "dispatch thunk of PPRiskMagnes.MagnesResult.getPayPalClientMetaDataId() -> Swift.String", referenced from:
      static Braintree.PPDataCollector.generateClientMetadataID(_: Swift.String?, disableBeacon: Swift.Bool, data: [Swift.String : Swift.String]?) -> Swift.String in PPDataCollector.o
ld: symbol(s) not found for architecture x86_64

**To Reproduce**
1. Add Pod 'Braintree' to Podfile
2. pod install
3. build for simulator

**Expected behavior**
Expected a successful build

This is a react native project so I'm not really versed in iOS build stuff. arm64 is set as an excluded arch in my build settings but apparently there's some file still being built for arm64.

**Comment by anutting** [comment]
The React Native part isn't really relevant. The MagnesSDK is not looking at the EXCLUDED_ARCHS setting that I have set up in Xcode. config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"

**Comment by scannillo** [comment]
👋 Hello - are you on an M1 or Intel Mac?

**Comment by gbkwiatt** [comment]
Having same issue on M1 Mac Mini, works fine on Intel machines

**Comment by scannillo** [comment]
Currently, we can only support the Rosetta workaround on M1 machines. For me so far, using Rosetta on the M1 mac has been working fine with CocoaPods and I am able to run on a simulator OK.

We are still blocked on adding full support for the M1, [see this issue](https://github.com/braintree/braintree_ios/issues/564).  [This issue ](https://github.com/braintree/braintree_ios/issues/690)will also be updated once we can remove the `EXCLUDED_ARCHS` from the Podspec. I am going to close this issue in favor of tracking in the two I just linked.

**Comment by vishaldhanotiyapersistent** [comment]
is any updated on this issue? I am still facing this issue in react native brain tree drop ui integration.

**Comment by scannillo** [comment]
@vishaldhanotiyapersistent - please open an issue in our [DropIn repo](https://github.com/braintree/braintree-ios-drop-in) including steps to replicate and specifics on your machine and integration.
