### ISSUE TITLE
No such module 'PPRiskMagnes'

### ISSUE THREAD

**Issue by kokluch** [braintree/braintree_ios#711]
**Integration Details (please complete the following information):**
 - Braintree SDK Version: 5.4.2
 - Environment: Production
 - iOS Version: iOS 14.6
 - Xcode Version: Xcode 12.5.1
 - Device: iPhone 12
 - Integration type & version: Swift Package Manager

**Describe the bug**
According to v5.4.2 changelog, no more workaround is required to work with binary target, however I still get error : "No such module 'PPRiskMagnes'" building PayPalDataCollector.

**To Reproduce**
1. Create new app project.
2. Add braintree_ios in Xcode Swift Package tab. 
3. Select "BraintreeCore" and "BraintreePayPal" dependencies to add to the app target.
4. Add "import BraintreePayPal" in one app file.
5. Build the project. -> It fails building PayPalDataCollector target inside PPDataCollector.swift file at import line "No such module 'PPRiskMagnes'"

**Expected behavior**
I would expect it to build or the SWIFT_PACKAGE_MANAGER.md to have a section for v5.4.2

**Comment by scannillo** [comment]
You still need to include `PayPalDataCollector` alongside `BraintreePayPal`. We will update our README / guides to make this more clear!

**Comment by scannillo** [comment]
Our README was updated to call out this requirement [here](https://github.com/braintree/braintree_ios/commit/0fbb555b7bd890471967fb0fee78230a2967fb5b).

Thank you for opening this issue! We appreciate the help and feedback.

**Comment by kokluch** [comment]
Thanks for the update and quick support.
