### ISSUE TITLE
Link broken Hello Client

### ISSUE THREAD

**Issue by leijdekkers** [braintree/braintree_ios#720]
Link is broken:

https://developer.paypal.com/braintree/docs/ios/start/hello-client/

**Comment by sarahkoop** [comment]
Hi @leijdekkers - The updated link for that developer docs page should be: https://developer.paypal.com/braintree/docs/start/hello-client/ios/v5

Could you let us know where the broken link was found so that we can update?

**Comment by scannillo** [comment]
I think in the README here - https://github.com/braintree/braintree_ios/blob/master/README.md#documentation

**Comment by leijdekkers** [comment]
Correct! Thanks for fixing it!

**Comment by scannillo** [comment]
[Fixed! ](https://github.com/braintree/braintree_ios/commit/91f9bba8d5fd149de42424850be153e7be668343)Thank you for opening this issue and bringing this to our attention.
