### ISSUE TITLE
Issues building to test device using SwiftPM

### ISSUE THREAD

**Issue by kunal30xi** [braintree/braintree_ios#726]
**Integration Details (please complete the following information):**
 - Braintree SDK Version: 5.4.3
 - Environment: Production
 - iOS Version: 14.4.2
 - Xcode Version: 12.5.1
 - Device: iPhone Xs Max
 - Integration type & version: Swift Package Manager

**Describe the bug**
We recently migrated from Carthage to SwiftPM to pull in the Braintree SDK Libraries for leveraging Venmo. Following the instructions, we are pulling in the following BraintreeCard, BraintreeCore, BraintreeDataCollector, BraintreeVenmo and PayPalDataCollector.

When deploying the code to our test device, we are seeing a crash with the following message printed to the console:

dyld: Library not loaded: @rpath/PPRiskMagnes.framework/PPRiskMagnes
  Referenced from: /private/var/containers/Bundle/Application/FCCD38CA-B3A2-4258-B925-29988B3580C0/MyApp.app/Frameworks/AFPPaymentProviders.framework/AFPPaymentProviders
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/FCCD38CA-B3A2-4258-B925-29988B3580C0/MyApp.app/Frameworks/AFPPaymentProviders.framework/Frameworks/PPRiskMagnes.framework/PPRiskMagnes: code signature in (/private/var/containers/Bundle/Application/FCCD38CA-B3A2-4258-B925-29988B3580C0/MyApp.app/Frameworks/AFPPaymentProviders.framework/Frameworks/PPRiskMagnes.framework/PPRiskMagnes) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

The way our project workspace is setup is the following:
MyApp.workspace
--- AFPPaymentProviders.xcodeproject (Contains references to Braintree SDK)
--- App Target (references AFPPaymentProviders.xcodeproject)

**Expected behavior**
App should deploy and run without any issues.

**Comment by scannillo** [comment]
👋  Hello. v5.4.3 should resolve the `PPRiskMagnes` issue you're seeing. I recommend removing all references to the Braintree SDK, cleaning derived data, and then trying to re-add the framework via SPM.

Also FWIW - if Venmo is the only payment method your app is using Braintree for, then you only need to check the box for`BraintreeVenmo`.

**Comment by kunal30xi** [comment]
Thanks for the quick response. We have a server side integration with BrainTree through which we are authorizing Venmo transactions. According to the docs located in the link, we are required to send both the payment nonce and the client device data to authorize Venmo transactions. 

https://developer.paypal.com/braintree/docs/reference/request/transaction/sale/java

```
Customer device information. Required in the following cases:

When using Premium Fraud Management Tools
When creating one-time Vaulted PayPal transactions
When creating Venmo transactions
This value will contain a Device Session ID as the unique identifier for a customer device. If using Kount Custom, it will also contain a Fraud Merchant ID as the unique, numeric identifier for your Kount account. For Fraud Protection, PayPal, and Venmo transactions, this value will also include a PayPal Correlation ID. Provide the full string received from the Braintree client SDK.
```

Similarly, on the client side, https://developer.paypal.com/braintree/docs/guides/venmo/client-side

```
For Swift Package Manager and Carthage integrations, include the BraintreeCore, BraintreeVenmo, PayPalDataCollector, and PPRiskMagnes frameworks.
```

There does not appear to be a way to collect deviceData without pulling in PayPalDataCollector which then in turn includes PPRiskMagnes.

I did attempt to Clear Derived Data and try to deploy to our test device again while pulling in the Braintree iOS SDK 5.4.3 via SwiftPM and continue to see the same error in the console.

```
dyld: Library not loaded: @rpath/PPRiskMagnes.framework/PPRiskMagnes
Referenced from: /private/var/containers/Bundle/Application/FCCD38CA-B3A2-4258-B925-29988B3580C0/MyApp.app/Frameworks/AFPPaymentProviders.framework/AFPPaymentProviders
Reason: no suitable image found. Did find:
/private/var/containers/Bundle/Application/FCCD38CA-B3A2-4258-B925-29988B3580C0/MyApp.app/Frameworks/AFPPaymentProviders.framework/Frameworks/PPRiskMagnes.framework/PPRiskMagnes: code signature in (/private/var/containers/Bundle/Application/FCCD38CA-B3A2-4258-B925-29988B3580C0/MyApp.app/Frameworks/AFPPaymentProviders.framework/Frameworks/PPRiskMagnes.framework/PPRiskMagnes) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```

**Comment by scannillo** [comment]
> There does not appear to be a way to collect deviceData without pulling in PayPalDataCollector which then in turn includes PPRiskMagnes.

Ah, yes you are correct here! To collect device data - you will need the `PayPalDataCollector` module.

Can you confirm you're on XCode 12.5+ and Braintree v5.4.3+? On Xcode 12.5.1 and Braintrew v5.4.3, I am not able to replicate this. I'm able to include and import `BraintreeVenmo` and `PayPalDataCollector` just fine.

**Comment by kunal30xi** [comment]
I'm using Xcode 12.5.1 and using Braintree 5.4.3

See attached snippet from Package.resolved
```
      {
        "package": "Braintree",
        "repositoryURL": "https://github.com/braintree/braintree_ios",
        "state": {
          "branch": null,
          "revision": "6126bb91817ab82021962d4cb66bfc9839f1bb84",
          "version": "5.4.3"
        }
      }
```

Some additional information:
Running this confirmation on the iOS Simulator seems to work without issue. However, running this same config (Debug) on a test device is where I run into the error message I described above.

Additional updates:
I did come up with a workaround that seems to address my problem. By manually pulling in the PPRiskMagnes.framework and link  it to my App Target, the app deploys without any problems. This does not appear to be a good long term solve though. And when adding the `braintree_ios` repositoryURL via SwiftPM, I don't find PPRiskMagnes listed.

**Comment by scannillo** [comment]
Thanks for this additional context. So, I am still not able to replicate (using a real device iOS 14.4) in Debug mode with the above frameworks imported. I know you mentioned iOS 14.4.2, but I highly doubt the patch version could cause this issue - feel free to test on both though.

```
Reason: no suitable image found. Did find:
/private/var/containers/Bundle/Application/FCCD38CA-B3A2-4258-B925-29988B3580C0/MyApp.app/Frameworks/AFPPaymentProviders.framework/Frameworks/PPRiskMagnes.framework/PPRiskMagnes
```

This log ^ is a little suspicious to me. See how it is coming from `AFPPaymentProviders.framework`. What is that? That isn't provided by the Braintree SDK. Is that also including Magnes? Also - our SPM integration brings in the Magnes `.xcframework`, this log is specifying the `.framework` format.

Can you include the braintree modules into a new/ blank app and see if you can still replicate? The issue might be something going on with your app setup / other dependencies.

**Comment by kunal30xi** [comment]
I'm going to try and get you a new / blank app that re-produces the issue. The workaround that I referred to does not seem to work when archiving the app for the App Store. After browsing through the Swift forums, it would appear that the issue I'm running into is related to this:

https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953/51

**Comment by scannillo** [comment]
👋  Hi - since we still can't replicate, we can't help you much. Can you provide a sample app for us to replicate? Also, did you check to see if the `AFPPaymentProviders.framework` is introducing the problem?

**Comment by scannillo** [comment]
Hi @kunal30xi - I am going to close this issue, due to inactivity.
