### ISSUE TITLE
PPRiskMagnes not available on Watch OS

### ISSUE THREAD

**Issue by EmDee** [braintree/braintree_ios#731]
**Integration Details (please complete the following information):**
 - Braintree SDK Version: 5.4.3
 - Environment: Both
 - iOS Version: 14.0 / Watch target: 7.1
 - Xcode Version: 12.5.1
 - Device: Watch simulator
 - Integration type & version: SPM

**Describe the bug**
This is more a question or possibly feature request than a bug report. I want to collect device data as described [here](https://developer.paypal.com/braintree/docs/guides/premium-fraud-management-tools/client-side/ios/v4), however, the device data should be collected on a Apple Watch target.

Currently I'm getting a "no library for this platform was found" error. I assume the PPRiskMagnes framework simply does not include the watch target.

Would a Watch target be possible?

**To Reproduce**
1. Add `BraintreeCore`, `BraintreePayPal`, and `PayPalDataCollector` to the Watch extension via SPM
2. Build

**Expected behavior**
Being able to successfully build and collect device data for PayPal on the Watch.

**Screenshots**

**Comment by scannillo** [comment]
👋  Hi @EmDee - so, I am going to close this issue for now. Feel free to open a new issue of type "Feature Request" for adding WatchOS support. As of now, this is not on our roadmap.

**Comment by EmDee** [comment]
Sad, but understandable.
