### ISSUE TITLE
American Express Cards are cut off in BTDropInSelectPaymentMethodViewController

### ISSUE THREAD

**Issue by Pretz** [braintree/braintree_ios#74]
![ios simulator screen shot jan 9 2015 3 12 27 pm](https://cloud.githubusercontent.com/assets/35043/5687426/36ada432-9812-11e4-9379-6cbcbb947aec.png)

Reproduction steps:
- Open `BTDropInViewController` for an account with several credit cards in the vault, including an American Express
- Select "Change payment method"
- The last two digits of the card are not visible when shown in the list

Is there a way I can override the localized strings in my application to change the display to **Amex**? It looks like `BTUILocalizedString` will only look in the `Braintree-UI-Localization` bundle.

Due to differences in the margin of the card graphic, the text is not cut off in `BTDropInViewController` itself when showing a single payment method.

**Comment by burnto** [comment]
Thanks @Pretz - we'll fix this.

**Comment by demerino** [comment]
We're aware of this issue and working on a fix.

**Comment by demerino** [comment]
Take a look at `4.4.0`+. We've added a new Drop-In component and exposed our UI components (along with styling). In the new Drop-In this issue should no longer occur. More info [here](https://github.com/braintree/braintree_ios/blob/master/Docs/Drop-In-Update.md).
