### ISSUE TITLE
PayPal balance update

### ISSUE THREAD

**Issue by salahelsayed99** [braintree/braintree_ios#745]
- Braintree SDK Version: [5.4.4]
 - Environment: [Sandbox]
 - iOS Version: [e.g. iOS 14.7]
 - Xcode Version: [e.g. Xcode 15]
 - Device: [e.g. iPhone 6 s plus]
 - Integration type: [CocoaPods]

I am facing an issue in the balance of the user's test, i got a nonce from the sdk and everything is going fine but the balance in  the personal paypal account never change

**Comment by scannillo** [comment]
Only open an issue here if you think you've found an issue with our SDK. If you need help troubleshooting your integration, reach out to Braintree Support at https://help.braintreepayments.com.
