### ISSUE TITLE
Translucent Nav Bar on 3DSv2 Challenge Screen

### ISSUE THREAD

**Issue by JavierSilvaFreeNow** [braintree/braintree_ios#748]
- Braintree SDK Version: 5.4.4
 - Environment: Sandbox
 - iOS Version: iOS 15.0
 - Xcode Version: Xcode 13.0
 - Device: iPhone Xr (& also Simulators)
 - Integration type & version: Swift Package Manager

**Describe the bug**
Hello, my team is attempting to migrate from v4 & CocoaPods to v5 & SPM, and while we were testing the SCA 3DS flows on our app, we noticed that the navigation bar had become translucent.

This seems to be caused by Apple's decision for iOS 15 to make the `UINavigationBar` use the `scrollEdgeAppearance` property value instead of the `standardAppearance`. ([Source](https://developer.apple.com/forums/thread/683265))

**To Reproduce**
1. Integrate the latest SDK version via SPM to a project, using Xcode 13 & iOS 15.
2. Have a 3D Secure integration available as described [here](https://developer.paypal.com/braintree/docs/guides/3d-secure/configuration).
3. Trigger a 3DS Challenge using one of the test cards found [here](https://developer.paypal.com/braintree/docs/guides/3d-secure/testing-go-live).
4. The Challenge screen's navigation bar appears translucent.

**Expected behavior**
The Challenge screen's navigation bar should be visible, so that both its title & "Cancel" buttons are readable.

**Screenshots**
![Simulator Screen Shot - iPhone 8 - 2021-10-25 at 14 18 19](https://user-images.githubusercontent.com/77627826/138693590-69ac3897-333f-4cf8-854c-630d2fb3a47f.png)

Let me know if you need any additional info. Thank you!

**Comment by scannillo** [comment]
👋  Hi @JavierSilvaFreeNow - [v5.5.0 of `braintree_ios`](https://github.com/braintree/braintree_ios/releases/tag/5.5.0) was released, and contains a fix for the transparent toolbar on iOS 15 for SPM integrations. Check it out!

**Comment by scannillo** [comment]
I am going to close this issue now that v5.5.0 adds arm64 support. Thank you for opening this issue, and please let us know if you run into additional troubles!

**Comment by JavierSilvaFreeNow** [comment]
Hi @scannillo 👋 sorry for the late reply! I didn't have a chance to check the update until recently. Thanks again for the effort!
