### ISSUE TITLE
Shell Script Error on Build

### ISSUE THREAD

**Issue by charlieMonroe** [braintree/braintree_ios#75]
Hi,

I've just added the latest version of Braintree SDK for iOS via CocoaPods to my project and it fails to build with the following error:

```
PhaseScriptExecution Copy\ Pods\ Resources build/Navigator.build/Debug-iphonesimulator/Navigator.build/Script-3C1B787CC10C4FCA9B2868FD.sh
    cd /Users/***USER***/Development/Cocoa/navigator-ios/Navigator
    /bin/sh -c /Users/***USER***/Development/Cocoa/navigator-ios/Navigator/build/Navigator.build/Debug-iphonesimulator/Navigator.build/Script-3C1B787CC10C4FCA9B2868FD.sh

/Users/***USER***/Development/Cocoa/navigator-ios/Navigator/build/Debug-iphonesimulator/Braintree-Drop-In-Localization.bundle
/Users/***USER***/Development/Cocoa/navigator-ios/Navigator/build/Debug-iphonesimulator/Braintree-UI-Localization.bundle
building file list ... rsync: link_stat "/Users/***USER***/Development/Cocoa/navigator-ios/Navigator/build/Debug-iphonesimulator/Braintree-Drop-In-Localization.bundle" failed: No such file or directory (2)
rsync: link_stat "/Users/***USER***/Development/Cocoa/navigator-ios/Navigator/build/Debug-iphonesimulator/Braintree-UI-Localization.bundle" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

Any idea what might be wrong?

I’ve tried cleaning the project, manually removing all intermediate files, completely reinstalling all pods, etc.

Thanks!

**Comment by burnto** [comment]
Hi @charlieMunroe. Are you using the latest version of the CocoaPods gem?
And Xcode 6?

On Monday, January 12, 2015, charlieMonroe <notifications@github.com> wrote:

> Hi,
>
> I've just added the latest version of Braintree SDK for iOS via CocoaPods
> to my project and it fails to build with the following error:
>
> PhaseScriptExecution Copy\ Pods\ Resources build/Navigator.build/Debug-iphonesimulator/Navigator.build/Script-3C1B787CC10C4FCA9B2868FD.sh
>     cd /Users/***USER***/Development/Cocoa/navigator-ios/Navigator
>     /bin/sh -c /Users/***USER***/Development/Cocoa/navigator-ios/Navigator/build/Navigator.build/Debug-iphonesimulator/Navigator.build/Script-3C1B787CC10C4FCA9B2868FD.sh
>
> /Users/***USER***/Development/Cocoa/navigator-ios/Navigator/build/Debug-iphonesimulator/Braintree-Drop-In-Localization.bundle
> /Users/***USER***/Development/Cocoa/navigator-ios/Navigator/build/Debug-iphonesimulator/Braintree-UI-Localization.bundle
> building file list ... rsync: link_stat "/Users/***USER***/Development/Cocoa/navigator-ios/Navigator/build/Debug-iphonesimulator/Braintree-Drop-In-Localization.bundle" failed: No such file or directory (2)
> rsync: link_stat "/Users/***USER***/Development/Cocoa/navigator-ios/Navigator/build/Debug-iphonesimulator/Braintree-UI-Localization.bundle" failed: No such file or directory (2)
> done
>
> sent 29 bytes  received 20 bytes  98.00 bytes/sec
> total size is 0  speedup is 0.00
> rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
> Command /bin/sh failed with exit code 23
>
> Any idea what might be wrong?
>
> I’ve tried cleaning the project, manually removing all intermediate files,
> completely reinstalling all pods, etc.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/braintree/braintree_ios/issues/75>.
>


--

**Comment by charlieMonroe** [comment]
Hi,

using CocoaPods v0.35.0 (not using the 0.36 beta, since it's still a beta) and Xcode 6.1.1, using iOS 8.1 SDK, targetting iOS 7.1...

**Comment by burnto** [comment]
Ok cool, thanks. We'll look into this today.

On Monday, January 12, 2015, charlieMonroe <notifications@github.com> wrote:

> Hi,
>
> using CocoaPods v0.35.0 (not using the 0.36 beta, since it's still a beta)
> and Xcode 6.1.1, using iOS 8.1 SDK, targetting iOS 7.1...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/braintree/braintree_ios/issues/75#issuecomment-69589062>
> .
>


--

**Comment by intelliot** [comment]
@charlieMonroe: Have you changed the default Derived Data directory?

Xcode -> Preferences… -> Locations -> Derived Data

Try setting the location to `Default`, and under `Advanced…`, choose `Unique`.

When I build my projects, the `PhaseScriptExecution Copy\ Pods\ Resources` looks like this:

```
PhaseScriptExecution Copy\ Pods\ Resources /Users/[MY_USERNAME_HERE]/Library/Developer/Xcode/DerivedData/[PROJECT_NAME]-[RANDOM-LOOKING_STRING]/Build/Intermediates/Cardstore.build/Debug-iphonesimulator/Cardstore.build/Script-[RANDOM-LOOKING_STRING].sh
    cd /Users/[MY_USERNAME_HERE]/Downloads/[PROJECT_NAME]
    /bin/sh -c /Users/[MY_USERNAME_HERE]/Library/Developer/Xcode/DerivedData/[PROJECT_NAME]-[RANDOM-LOOKING_STRING]/Build/Intermediates/[PROJECT_NAME].build/Debug-iphonesimulator/[PROJECT_NAME].build/Script-[RANDOM-LOOKING_STRING].sh

/Users/[MY_USERNAME_HERE]/Library/Developer/Xcode/DerivedData/[PROJECT_NAME]-[RANDOM-LOOKING_STRING]/Build/Products/Debug-iphonesimulator/Braintree-Drop-In-Localization.bundle
/Users/[MY_USERNAME_HERE]/Library/Developer/Xcode/DerivedData/[PROJECT_NAME]-[RANDOM-LOOKING_STRING]/Build/Products/Debug-iphonesimulator/Braintree-UI-Localization.bundle
```

If that doesn't work and doesn't lead to something that does, we'd like some additional information:
1. Have previous versions of the Braintree SDK worked for you?
2. What exactly do you have in your `Podfile`? And are you using `, :head`?
3. What's the output when you open Terminal and run `pod --version`?

Thanks!

**Comment by charlieMonroe** [comment]
@intelliot : That does the trick, that would never occur to me. I have also solved this by checking out just `Braintree/API` instead of the entire `Braintree` since I don't really need the UI and it allows me to keep my original Derived Data directory location and the issue is with the drop-in localization bundles... It's disappointing it doesn't work with any Derived Data location, but oh well...

I guess we can close this issue now. Thanks for your help!

**Comment by burnto** [comment]
Sweet - thanks @intelliot! :horse_racing: :boom:
