### ISSUE TITLE
PPRiskMagnes is not compiled with Xcode 13

### ISSUE THREAD

**Issue by scalessec** [braintree/braintree_ios#757]
**Integration Details (please complete the following information):**
 - Braintree SDK Version: 5.5.0
 - Environment: All
 - iOS Version: 15.1
 - Xcode Version: 13.1 (13A1030d)
 - Device: All
 - Integration type & version: Carthage 0.38.0 (we're current blocked from using SPM because of #735)

**Describe the bug**
After compiling the Braintree dependencies with Carthage, we're receiving the following warning when building the application:

> /MyProject/Carthage/Build/iOS/PPRiskMagnes.framework/Modules/PPRiskMagnes.swiftmodule/Project/arm64-apple-ios.swiftsourceinfo' is either malformed or generated by a different Swift version. Note that it uses an unstable format and may leak internal project details, it should not be distributed alongside modules

It appears that `PPRiskMagnes` might have been compiled with an older version of Xcode/Swift. Can you confirm that this is safe to ship to production? We're currently blocked by #735 and we were planning to use Carthage as a workaround until the issue is fixed.

**Comment by scannillo** [comment]
👋  Hi @scalessec - are you using an Intel or M1 Mac?

**Comment by scalessec** [comment]
Hey @scannillo, this is on an Intel Mac. We managed to get the warning to go away by adding the `--use-xcframeworks` flag when building with Carthage (we were previously using the older `copy-frameworks` approach). Not entirely sure why this works, but it does. I'll close the ticket. Thanks!
