### ISSUE TITLE
Undefined symbols for architecture x86_64 - BraintreeApplePay

### ISSUE THREAD

**Issue by JavierSilvaFreeNow** [braintree/braintree_ios#759]
**Integration Details (please complete the following information):**
 - Braintree SDK Version: 5.5.0
 - Environment: Production
 - iOS Version: iOS 15
 - Xcode Version: 13.0
 - Device: iPhone 8 (Simulator)
 - Integration type & version: Swift Package Manager

**Describe the bug**
When building the project after adding the dependency, we get this error:
```
Undefined symbols for architecture x86_64:
  "___llvm_profile_runtime", referenced from:
   ___llvm_profile_runtime_user in BraintreeApplePay.o
ld: symbol(s) not found for architecture x86_64
```

After a bit of browsing we found this [Swift bug report](https://bugs.swift.org/browse/SR-14788) with a similar error log, and long story short, if the Code Coverage option is turned on for the target that is adding the package, the build process will fail.

**To Reproduce**
1. Add the package to the intended target
2. Turn Code Coverage on for said target via the Scheme Editor (Product -> Scheme -> Edit Scheme -> Select Test options -> Enable Code Coverage)
3. Build the project

**Expected behavior**
Project should build successfully

I'm not sure if there's anything that can be done from your side, but I figured creating the report doesn't hurt and might be beneficial for others encountering the same issue. 
Thank you.

**Comment by scannillo** [comment]
👋  Hello @JavierSilvaFreeNow - thanks for opening this GH issue. I am on Xcode 13.1 (and an Intel Mac) and I can't replicate this issue. Are you on an M1 Mac? Also - is your target written in Obj-C or Swift?

**Comment by JavierSilvaFreeNow** [comment]
Hi @scannillo thanks for checking on it. I'm not on an M1 Mac yet, however my target does have both Obj-C and Swift. I did some experimentation and noticed that we had linked the dependency to two targets - an internal library project and the main app; removing the dependency from one of them seems to have solved the issue.

While I have you here, I have a quick question: is the framework built with Bitcode enabled? We started getting some warnings from the CI builds after updating the library.
Thanks again!

**Comment by scannillo** [comment]
👋  I am going to close this issue since it has resolved on your end. Regarding the Bitcode issue, please open a new GH issue, or comment in this [issue](https://github.com/braintree/braintree_ios/issues/756#issuecomment-989402482) if that is similar to the bitcode issue you are having.
