### ISSUE TITLE
Crashes in new Xcode 6.1.1 project on Pay via Venmo

### ISSUE THREAD

**Issue by johngraham262** [braintree/braintree_ios#76]
When I create a new project in Xcode, there's no "Bundle display name" set in the `Info.plist` file. This doesn't matter to me, but the Braintree lib uses it when [setting the Venmo app switch parameters](https://github.com/braintree/braintree_ios/blob/master/Braintree/Venmo/BTVenmoAppSwitchRequestURL.m#L20).

`[[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleDisplayName"]` returns nil and causes a crash because it won't add nil to a dictionary. I can trivially fix this by adding a "Bundle display name" in my `Info.plist` file, but it probably shouldn't crash out of the box, or at least offer a more useful error output about how to add the "Bundle display name" myself.

I'm testing in sandbox mode on an iOS 8 device with a new project created from the newest production Xcode, 6.1.1.

**Comment by burnto** [comment]
Thanks @johngraham262 - we'll fix this.
