### ISSUE TITLE
 Getting error 'Symbols tool failed' during submitting app on App Store

### ISSUE THREAD

**Issue by ravi-lirisoft** [braintree/braintree_ios#763]
**Integration Details (please complete the following information):**
 - Braintree SDK Version: 5.4.4
 - Environment: Production
 - iOS Version: iOS 14.0
 - Xcode Version: Xcode 13.1
 - Device: Any iOS Device
 - Integration type & version:  [Manual Integration](https://github.com/braintree/braintree_ios/blob/4.x/Docs/Manual%20Integration.md)

**Describe the bug**

### Unable to submit the app on App Store, getting following Error:

`2021-12-10 13:32:22 +0000 [MT] Step "<IDEDistributionSymbolsStep: 0x7fe947d693a0>" failed for distribution item "libKountDataCollector.a" with error "Error Domain=IDEFoundationErrorDomain Code=1 "Symbols tool failed" UserInfo={NSLocalizedDescription=Symbols tool failed}"`

**Note: I did follow the [Manual Integration](https://github.com/braintree/braintree_ios/blob/4.x/Docs/Manual%20Integration.md) steps from document which provides in the older releases.**

**To Reproduce**
1. Archive the app
2. Export iPA using distribution environment
3. Submit app on iTunes to avail on TestFlight
4. Above error is throwing.

**Expected behavior**
If I am able to archive and exporting IPA. Then it should be able to submit on iTunes.

I didn't see any documentation for integrating the latest the SDK, It would be great if you can provide or please let me know if anything need to configure for SDK v5.4.4

**Comment by sarahkoop** [comment]
Hi @ravi-lirisoft thanks for using the Braintree iOS SDK. This SDK does not support Manual Integration. Please use one of the three supported package managers: SPM, CocoaPods, or Carthage.

We don't see this error when uploading a sample app to TestFlight using a package manager. Feel free to re-open this issue if you are still seeing this error when using a package manager.
