### ISSUE TITLE
SCA challenge crash

### ISSUE THREAD

**Issue by dmazzoni** [braintree/braintree_ios#769]
**Integration Details:**
 - Braintree SDK Version: 5.5.0
 - Environment: Production
 - iOS Version: iOS 12.2.0 - 15.2.0
 - Xcode Version: Xcode 12.5
 - Integration type & version: CocoaPods 1.11.2
 - Development Processor Type: Intel

**Describe the bug**
On our production app, crashes are occurring to some users when they are routed to the SCA challenge. The stack trace is the following:

```
Crashed: com.apple.root.background-qos
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010

0  Braintree                      0x3010c -[BTThreeDSecureV2Provider callFailureHandlerWithErrorDomain:errorCode:errorUserInfo:failureHandler:] + 95 (BTThreeDSecureV2Provider.m:95)
1  Braintree                      0x303f4 -[BTThreeDSecureV2Provider cardinalSession:stepUpDidValidateWithResponse:serverJWT:] + 124 (BTThreeDSecureV2Provider.m:124)
2  CardinalMobile                 0x231f4 -[CardinalSession sendValidationResponse:andJWT:] + 536
3  CardinalMobile                 0x2290c __51-[CardinalSession stepUpUserInputWithResponseData:]_block_invoke + 912
4  CardinalMobile                 0x18630 __119-[CMCentinelController centinelStepUpRequestWithJWT:stepUpResponse:consumerSessionId:transactionId:baseURL:completion:]_block_invoke + 396
5  libdispatch.dylib              0x2924 _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x4670 _dispatch_client_callout + 20
7  libdispatch.dylib              0x15f00 _dispatch_root_queue_drain + 684
8  libdispatch.dylib              0x16608 _dispatch_worker_thread2 + 164
9  libsystem_pthread.dylib        0x10b8 _pthread_wqthread + 228
10 libsystem_pthread.dylib        0xe94 start_wqthread + 8
```

The issue seems similar to what #584 reported for a Braintree v4 integration; I'm opening a separate issue, as we are using Braintree v5.

**To Reproduce**
The stack trace was reported through Crashlytics; we could not reproduce the issue, which appears to not be systematic.

**Comment by sarahkoop** [comment]
Hi @dmazzoni - Thanks for reporting this. We have followed up with our MPI provider (CardinalMobile) and reported this crash to them.  Please comment if you get more information on replicating this crash.  We will post an update here when we have more info.

**Comment by dmazzoni** [comment]
I couldn't replicate it yet, but it seems that it is caused by `BTThreeDSecureV2Provider`'s `failureHandler` block being `nil` when `-cardinalSession:stepUpDidValidateWithResponse:serverJWT:` is invoked. Do you think there's a way to work around it in `BTThreeDSecureV2Provider`?

**Comment by dmazzoni** [comment]
I found some additional information which may be worth reporting to Cardinal.

I noticed that on Crashlytics we have a non-fatal with domain `com.braintreepayments.BTThreeDSecureFlowErrorDomain` and code `0` sent by a device that then reported the crash with the same timestamp of the non-fatal.

Given that the `NSError` logged in the Crashlytics non-fatal is only propagated by the invocation of `failureHandler`, the block could not have been `nil` at that time. Given that the crash apparently happened immediately after, could it be possible that `-cardinalSession:stepUpDidValidateWithResponse:serverJWT:` was for some reason erroneously invoked twice by Cardinal? That would explain the crash, as `failureHandler` is reset to `nil` after the first invocation.

**Comment by sarahkoop** [comment]
Thank you for providing those additional details! We will pass this information on to help with the investigation.

**Comment by krunk4ever** [comment]
We're also seeing about 10 crashes a day with on iOS SDK 4.34.0

**Comment by Dearich** [comment]
thank you, because I have the same crash when I try to cancel 3DS, also maybe you know why delegate methods does not call for check when 3DS will show and dismiss ? @sarahkoop

**Comment by sshropshire** [comment]
> thank you, because I have the same crash when I try to cancel 3DS, also maybe you know why delegate methods does not call for check when 3DS will show and dismiss ? @sarahkoop

@Dearich this sounds like a separate issue. Could you [provide steps](https://github.com/braintree/braintree_ios/issues/new?assignees=&labels=&template=bug_report.md) for what you're experiencing? We'll take a look.
