### ISSUE TITLE
BTPaymethodMethod_Mutable auto property synthesis

### ISSUE THREAD

**Issue by jskidd3** [braintree/braintree_ios#77]
![screen shot 2015-01-13 at 00 54 25](https://cloud.githubusercontent.com/assets/2090415/5714318/e5ce5b2e-9abe-11e4-8997-3712d102f992.png)

Any ideas why I am seeing this? The project is a Swift project but I have built a bridging header which is working fine but this file is showing an error.

**Comment by burnto** [comment]
Hi @jskidd3 - I'm not seeing this locally with a fresh Swift project and bridging header. Can you verify that you're on the latest Braintree pod (3.5.0) and Xcode (6.1.1)? Thanks.

**Comment by jskidd3** [comment]
@burnto Thanks for the reply. Oh, no I'm on Braintree pod 3.0.1? But that's the latest version I get when running pod update on the directory. I am on Xcode 6.1.1. How do I update the pod to 3.5.0?

**Comment by burnto** [comment]
Hi @jskidd3 - yep 3.0.1 is ~6 months old. We later updated to ensure Swift compatibility. To upgrade:

1. Edit your Podfile to specify a specific or minimum version. In your case, you probably want to allow any 3.x version using the "optimistic operator" (`~>`):

    ```ruby
    pod 'Braintree', '~> 3.0'
    ```

    See the [Podfile docs](http://guides.cocoapods.org/using/the-podfile.html) for details.

2. Run `pod update Braintree` to update to the latest Braintree pod allowed within the bounds of what you specified in your Podfile. If you do this today with the Podfile entry above, this would install `3.5.0`.

Hope this helps! :goat: :sunglasses: :hamburger:

**Comment by jskidd3** [comment]
@burnto Damn! I'd put `~> 3.0.0` makes sense now! Thanks so much for your help!
