### ISSUE TITLE
'unarchiveObjectWithData:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead

### ISSUE THREAD

**Issue by HanzlaRafique** [braintree/braintree_ios#770]
Hi Braintree Team, I hope you are doing well. Please guide me, I'm facing the same issue while build/run my project.

- platform :ios, '10.0'
- Xcode Version: 12.5
- Device: iPhone 7
- Simulator: 8,X,12 or Any
- Integration type: CocaPods

Please find the attached screenshot. Let me know if you required additional information. I'm waiting your kind response.

Thank you

<img width="968" alt="Screenshot 2021-12-24 at 1 22 54 AM" src="https://user-images.githubusercontent.com/53652998/147289488-cd0e1421-dcc7-46f5-ad9d-7d40b0dd82c9.png">

**Comment by scannillo** [comment]
This was addressed in the v5 major version release (see [notes here](https://github.com/braintree/braintree_ios/blob/master/CHANGELOG.md#500-beta1-2020-12-01)). Please update your integration.
