### ISSUE TITLE
Unable to add payment method because getting this message - Cannot provide expiration_date if you are also providing expiration_month and expiration_year.

### ISSUE THREAD

**Issue by ravi-lirisoft** [braintree/braintree_ios#772]
**Integration Details:**
 - Braintree SDK Version: 5.4.4
 - Environment: Production
 - iOS Version: iOS 14.0
 - Xcode Version: Xcode 13.0
 - Device: iPhone 12
 - Integration type & version: Manual Integration
 - Development Processor Type: Intel

**Describe the bug**

Below error is getting while making checkout or vaulting the credit card

**Cannot provide expiration_date if you are also providing expiration_month and expiration_year.**

**To Reproduce**

Here is the code snippet what I am using to tokenizing the card

   ```
 BTAPIClient *braintreeClient = [[BTAPIClient alloc] initWithAuthorization:creditCardInfo[@"clientToken"]];
    BTCardClient *cardClient  = [[BTCardClient alloc] initWithAPIClient:braintreeClient];
    BTCard *card = [[BTCard alloc] init];
    card.number = creditCardInfo[@"cardNumber"];
    card.expirationMonth = creditCardInfo[@"expMonth"];
    card.expirationYear = creditCardInfo[@"expYear"];
    card.cvv = creditCardInfo[@"cvv"];

```

When tokenizing the card. Getting nonce properly but when this nonce using to checkout below error is throwing..
**Cannot provide expiration_date if you are also providing expiration_month and expiration_year.**

Error: 

**Expected behavior**

It shouldn't send all three parameter expiration_date, expiration_month and expiration_year.

OR 

Please correct me if I am doing wrong implementation.

**Screenshots**
Here is the snapshot what is sending by the SDK it might help to better understanding of the issue

<img width="1050" alt="code" src="https://user-images.githubusercontent.com/68231364/148034054-39b86312-a77f-4c41-9958-c1391077697d.png">
<img width="604" alt="console" src="https://user-images.githubusercontent.com/68231364/148034072-52610bba-ad86-4fa8-beba-47bb92d66028.png">

**Comment by sarahkoop** [comment]
Hi @ravi-lirisoft - Thanks for using the Braintree iOS SDK. Are you able to successfully tokenize/transact with any other test card numbers? See our list of supported test cards [here](https://developer.paypal.com/braintree/docs/guides/credit-cards/testing-go-live/php#valid-card-numbers). In the meantime, we are looking into this issue further and will post an update here when we have a fix.

**Comment by ravi-lirisoft** [comment]
Yes, I am able to tokenize the card and getting the nonce but unfortunately not able to make transaction using this nonce.

The server is getting following error
**Cannot provide expiration_date if you are also providing expiration_month and expiration_year**

Please let me know if you need more clarification?

**Comment by sarahkoop** [comment]
HI @ravi-lirisoft - We have created a [branch](https://github.com/braintree/braintree_ios/tree/fix_expiration_date_tokenize) with a potential fix. Feel free to test your integration against that branch to confirm it resolves your issue.
