### ISSUE TITLE
libKountDataCollector.a messes with isIdleTimerDisabled?

### ISSUE THREAD

**Issue by JetForMe** [braintree/braintree_ios#777]
**Integration Details (please complete the following information):**
 - Braintree SDK Version: dropin 9.3.0
 - Environment: [e.g. Sandbox or Production]
 - iOS Version: 15.2
 - Xcode Version: 13.2.1
 - Device: iPhone SE (and others)
 - Integration type & version: Swift Package Manager 5.5
 - Development Processor Type: M1

**Describe the bug**
Our app has a live streaming component, and we have code in there to disable the idle timer when a livestream is playing. Unfortunately, *something* is re-enabling it.

Searching through the entire source base of our app and our dependencies, there are no unexpected references to `isIdleTimerDisabled`. However, searching the binaries produces the following results:

```
$ ag --search-binary isIdleTimerDisabled …project-btahrkmjjfdolqatefsxegnpulhn/SourcePackages 
Binary file …project-btahrkmjjfdolqatefsxegnpulhn/SourcePackages/checkouts/braintree_ios/Sources/BraintreeDataCollector/Kount/libKountDataCollector.a matches.
Binary file …project-btahrkmjjfdolqatefsxegnpulhn/SourcePackages/checkouts/braintree_ios/Frameworks/XCFrameworks/KountDataCollector.xcframework/ios-arm64_x86_64-simulator/libKountDataCollector.a matches.
Binary file …project-btahrkmjjfdolqatefsxegnpulhn/SourcePackages/checkouts/braintree_ios/Frameworks/XCFrameworks/KountDataCollector.xcframework/ios-arm64_armv7/libKountDataCollector.a matches.
```

**Expected behavior**
It doesn't seem to me that anything in Braintree needs to touch `isIdleTimerDisabled`. But I'm not even sure it's actually touching it. I figured you guys could take a look at your code and see. 

Thanks!

**Comment by sarahkoop** [comment]
Hi @JetForMe - Thanks for using the Braintree iOS SDK. We are looking into this and will post an update here when we have more information.

**Comment by sarahkoop** [comment]
@JetForMe - Are you including the `BraintreeDataCollector` framework and using a Kount Custom Integration for device data collection? 

The Kount library is no longer receiving updates, and integrations should migrate to using `PayPalDataCollector` instead.  See our [developer docs](https://developer.paypal.com/braintree/docs/guides/premium-fraud-management-tools/client-side#collecting-device-data) for how to use `PayPalDataCollector`.

**Comment by JetForMe** [comment]
Thanks, I'll look into making sure we don't have it. This was just a shot in the dark, based on a crude search of our sources and dependencies. It seems we've found another possible culprit, as well. Thanks!
