### ISSUE TITLE
Remove .lock files

### ISSUE THREAD

**Issue by jonathannorris** [braintree/braintree_ios#78]
You should remove both the Podfile.lock and Gemfile.lock files, I was unable to run 'pod install' before removing both.

**Comment by mickeyreiss** [comment]
The `Podfile.lock` and `Gemfile.lock` files are only necessary for SDK development. They should not impact SDK integration in any way.

What task were you trying to accomplish when you ran into this?

**Comment by jonathannorris** [comment]
I was trying to do a pod install on the project to install all the dependancies, I was unable to do a pod install on the folder until I removed both.

**Comment by mickeyreiss** [comment]
What do you mean by "on the project"?

If you are integrating `Braintree` into your app, you do not need to download any external dependencies.

**Comment by burnto** [comment]
Closing this because it looks like it has been answered. @jonathannorris please reply if you have further questions on this topic, or feedback on the integration or documentation.
