### ISSUE TITLE
3DS version 2 challenge authentications timing out

### ISSUE THREAD

**Issue by antonio91end** [braintree/braintree_ios#794]
**Integration Details:**
 - Braintree SDK Version: 5.4.1
 - Environment: Sandbox
 - iOS Version: 15.2
 - Xcode Version: 13.2.1
 - Device: iPhone 8 (sim)
 - Integration type & version: CocoaPods 1.11.2
 - Development Processor Type:  M1

**Describe the bug**
3DS v2 Challenge Authentications seem to be timing out.

We've implemented 3DS version 2 as per your documentation. When noticed that when testing cards that require a challenge, there seems to be a time out issue.  More specifically, when we call `[paymentFlowDriver startPaymentFlow:threeDSecureRequest...`, the completion block is called after 5 minutes or so returning:

`Error Domain=com.braintreepayments.BTThreeDSecureFlowErrorDomain Code=0 "" UserInfo={NSLocalizedDescription=}`

Also saw from my console the following which may help.

```
Task <0D5E1026-8FE3-45B3-ADDA-BC92F5EE1214>.<1> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2103, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <0D5E1026-8FE3-45B3-ADDA-BC92F5EE1214>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <0D5E1026-8FE3-45B3-ADDA-BC92F5EE1214>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://cmsdk.cardinalcommerce.com/stag_logs, NSErrorFailingURLKey=https://cmsdk.cardinalcommerce.com/stag_logs, _kCFStreamErrorDomainKey=4}
```

Upon further investigation, we noticed that the timeout happens when this call is performed from your SDK (BTThreeDSecureV2Provider.m)

```
[self.cardinalSession continueWithTransactionId:lookupResult.lookup.transactionID
                                            payload:lookupResult.lookup.PAReq
                                didValidateDelegate:self]; 
```

No-challenge transactions seem to be working as expected, however.

Could you help us debug what the issue may be? 

Many thanks!

**Comment by jaxdesmarais** [comment]
Hello @antonio91end - Thanks for reaching out and using the iOS SDK. I was just able to test the 3D Secure v2 flow in our demo app using the card number `4000000000001091` and am not seeing any delay in the completion block or when launching the webview and returning to the app after the 3D Secure verification in sandbox.

That said, we only return that error code if the cardinal SDK times out. Would you be able to confirm if you are still seeing this issue? Additionally can you confirm the test card you are using to replicate this error?

**Comment by antonio91end** [comment]
@jaxdesmarais 

I have just replicated the issue with the following cards
* 4000 0000 0000 1091 
* 5200 0000 0000 1096
* 3400 0000000 1098

But I think it's basically happening with all "challenge" authentication scenarios. Almost feels like Cardinal is failing to present the webview?

**Comment by antonio91end** [comment]
Just to update, we also just have seen the following log output from Cardinal:

```
{
        "error" : "20605",
        "detail" : "Invalid Payload passed to Continue.",
        "timestamp" : "1646749427000"
}
```

**Comment by jaxdesmarais** [comment]
Hello @antonio91end - thanks for reaching back out with those details. I have tested the cards you sent over ~5 times each in our demo app (located in this repository) and am getting the callback and webview each time as expected. Are you able to provide additional troubleshooting steps that we can take to replicate this error on our end or a sample project as we have not yet been able to replicate?

**Comment by antonio91end** [comment]
hi @jaxdesmarais 

I’ve found and fixed the issue. Cardinals 3DS v2 challenge view presentation does not go through your delegate functions to show or dismiss the views. Instead, they seem to hijack the main UIApplication window, get the rootViewController and call present on it. Our rootViewController has overrides for the present function (`override public func present(_ `) with custom business logic that was essentially blocking Cardinal’s request to present their view.

Honestly,  not the nicest way to do this, presentation logic should be handed over to developers just as you guys do it with v1. I suggest you at least add some documentation regarding this going forward as there was none available. 

Thanks.
