### ISSUE TITLE
"Change Payment Method" option issues

### ISSUE THREAD

**Issue by 08irfan** [braintree/braintree_ios#82]
I have noticed two issues with "Change Payment Method" option in DropIn UI.
1) It disappears some times and some times it appears. Actually I accidentaly figured out that the option is present in UI, but is invisible because of font color. The font color turns white, hence making it invisible on white background.
2) Suppose we have multiple payment methods added and i select a payment method other than default for payment, on making a transaction the amount is deducted from the default payment method, not the selected one.

**Comment by mickeyreiss** [comment]
I think this issue was addressed via a number of other support channels. Feel free to re-open if there are any bugs in the SDK that should be addressed. Thanks!

**Comment by 08irfan** [comment]
"Change Payment Method" button font color becomes white for the first time and becomes invisible on white background. When i remove app from recents and reopen the app color of "Change Payment Method" becomes normal...
