### ISSUE TITLE
APPLE FLAG on Private method 

### ISSUE THREAD

**Issue by dipkasyap** [braintree/braintree_ios#821]
**TMS-90338: Non-public API usage** - The app references non-public symbols in Frameworks/Braintree.framework/Braintree: _SFAuthenticationErrorDomain. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Integration Details (please complete the following information):**
 - Braintree SDK Version:  4.22.0
 - Environment:  Production
 - iOS Version: all
 - Xcode Version:13 + 
 - Device: All

**Comment by EdwinAlvrdo** [comment]
Same issue hare at - Braintree/Card (4.37.1): - Braintree/Core and i have a deadline release

The app references non-public symbols in Payload/<APP_NAME>/Frameworks/Braintree.framework/Braintree: _SFAuthenticationErrorDomain With error code STATE_ERROR.VALIDATION_ERROR.11 for id ca0e03ba-f063-4b3f-941c-c2d77744c64b

**Comment by jaxdesmarais** [comment]
Hello @EdwinAlvrdo and @dipkasyap -

Thanks for reporting this issue. It appears that Apple introduced a bug into the private API string compare list. According to this [Apple forum thread](https://developer.apple.com/forums/thread/127678?page=2) at around 6pm Central (4pm Pacific) June 6th people started reporting this issue.

Later in the thread an Apple engineer indicated around 1am Central (11pm Pacific) that the [issue has been resolved](https://developer.apple.com/forums/thread/127678?page=6) and that folks should try resubmitting. If you are still running into issues, it may be best to reach out to Apple as they may have missed some of the strings that should not have been in the private API compare list.

Please do let us know if you continue running into issues after resubmitting.
