### ISSUE TITLE
iOS v5 SDK: Not possible to get card details

### ISSUE THREAD

**Issue by cadrilo** [braintree/braintree_ios#828]
**Context**
* SDK/Library version 5.xx
* Environment: any

**Description**
After the migration of the SDK from v4 to v5, it is not possible to get information about card details when displaying payment methods using a custom UI. This feature is only supported when using Braintree DropIn.

Before SDK v5 it was possible to get the payment method nonces by calling the `fetchPaymentMethodNonces` method of `BTAPIClient`. As of SDK v5 this method is no longer available, and the only option is to call `BTDropInResult.mostRecentPaymentMethod` but this method only retrieves the information of the last payment method.

Another way to get this information is to build our UI using Dropin, but in my case this option is not possible due to product requirements.

For this reason I would like to know if you have plans to add this feature in the next versions of the SDK so we can update our library version and remove the legacy code.

Thanks in advance

**Comment by sshropshire** [comment]
Hey @cadrilo thanks for using the Braintree SDK for iOS. The `fetchPaymentMethodNonces` method should still be [available on BTAPIClient](https://github.com/braintree/braintree_ios/blob/1bc44683f8e52479e890c35a66eee9138281864a/Sources/BraintreeCore/Public/BraintreeCore/BTAPIClient.h#L96) in v5. Can you post an example code snippet of what's breaking your migration?

**Comment by cadrilo** [comment]
Hey @sshropshire Thanks for your answer. You are completely right, I have explained myself wrong. My problem was that, after upgrading to version 5, the protocol `BTPaymentMethodNonce` did not showed any public property with info of the payment method.

After going deep into the SDK, I could notice that both `BTCardNonce` and `BTPayPalAccountNonce` which inherit from `BTPaymentMethodNonce` do have the public properties necessary to display the detailed info for each payment method. 

In my case I could resolve it getting the type and casting them.

Thanks
