### ISSUE TITLE
Unable to satisfy the following requirements: Braintree/Enable-Apple-Pay required by Podfile

### ISSUE THREAD

**Issue by lupugabriel** [braintree/braintree_ios#83]
Hi everybody... i added to my podfile:

pod "Braintree"
pod "Braintree/Enable-Apple-Pay"

and i have this error:

[!] Unable to satisfy the following requirements:

Braintree/Enable-Apple-Pay required by Podfile
Can you help?

**Comment by burnto** [comment]
Hi @lupugabriel, apologies, the README is incorrect. It should be just "Braintree/Apple-Pay". I've corrected this in 36e90bf9a225f2baa40ab6f6cdaca7ef5641efd4. Thanks for reporting this issue!
