### ISSUE TITLE
Error Processing Message Request

### ISSUE THREAD

**Issue by naxel** [braintree/braintree_ios#846]
**Integration Details:**
 - Braintree SDK Version: 5.11.0
 - Environment: Production
 - iOS Version: 15.5
 - Xcode Version: 13.4.1
 - Device: iPhone XR
 - Integration type & version: CocoaPods 1.11.3
 - Development Processor Type: Intel

**Describe the bug**
I have found an issue with payment via Mastercard cards from Monobank (Ukraine). It uses 3ds2 (2.1.0). It seems to be the same issue is on the Android platform.
On the Security Checkout screen, after pressing the button “Продовжити” (“Continue”), it is immediately finishing the 3DS verification with an error message:
```
Internal Error. 
```

After debugging, I have found what Braintree SDK send request:
```
POST https://centinelapi.cardinalcommerce.com/V1/Order/JWT/StepUp
```
And the response contains (decoded JWT):
```
{
  "iss": "5c895f87791eef31e82cd694",
  "iat": 1660034913,
  "exp": 1660042113,
  "jti": "76dd58bc-dfff-42fe-a7de-2e3021e823e7",
  "ConsumerSessionId": "0_4065d0ef-2d49-4cde-8830-d6cb3ded830e",
  "aud": "f72b1599-6f81-4406-8ead-72ffd2e1ffc4",
  "Payload": {
    "CRes": "",
    "Successful": false,
    "ErrorNumber": 1001,
    "ErrorDescription": "Error Processing Message Request"
  }
}
```
Why does it happen, and what does it mean?
Is it possible to handle this error?
Thank you!

**Screenshots**

![photo_2022-08-09 12 13 39](https://user-images.githubusercontent.com/1148505/183611888-975fe33c-8f2e-4d4d-a275-17a4ce1d0625.jpeg)
![photo_2022-08-09 12 15 15](https://user-images.githubusercontent.com/1148505/183612207-61453b04-d7db-48f9-9a0e-45f7a52c639b.jpeg)

**Video**

https://user-images.githubusercontent.com/1148505/183612432-d431474b-0746-463c-aaab-bfa983956613.mp4

Analytics data that sends to https://cmsdk.cardinalcommerce.com/prod_logs:
```
[
  {
    "data": [
      {
        "event": "CardinalConfigure",
        "detail": "Cardinal Session Configured",
        "timestamp": "1660034875000"
      },
      {
        "event": "CardinalInit",
        "detail": "Cardinal Session Setup Started",
        "timestamp": "1660034875000"
      },
      {
        "event": "CardinalConfigure",
        "detail": "Cardinal Session Lasso Start",
        "timestamp": "1660034875000"
      },
      {
        "event": "CardinalInit",
        "detail": "Cardinal Session Lasso Complete",
        "timestamp": "1660034876000"
      },
      {
        "event": "CardinalInit",
        "detail": "Cardinal Session Setup Complete with Reference ID: 0_4065d0ef-2d49-4cde-8830-d6cb3ded830e",
        "timestamp": "1660034876000"
      },
      {
        "event": "CardinalContinue",
        "detail": "Cardinal Session SetpUpDelegate Set",
        "timestamp": "1660034892000"
      },
      {
        "event": "CardinalContinue",
        "detail": "Cardinal Session Continue Started with TransactionID: jkH3mGPZzw0Cy5u0foz1.",
        "timestamp": "1660034892000"
      },
      {
        "event": "CardinalContinue",
        "detail": "Cardinal Session Continue with SDK Controller Screen",
        "timestamp": "1660034892000"
      },
      {
        "event": "CardinalContinue",
        "detail": "Cardinal Session StepUpUserInput Started",
        "timestamp": "1660034911000"
      },
      {
        "event": "CardinalContinue",
        "detail": "Cardinal Session StepUpUserInput Completed with TransactionID: jkH3mGPZzw0Cy5u0foz1",
        "timestamp": "1660034913000"
      },
      {
        "error": "1001",
        "detail": "Error Processing Message Request",
        "timestamp": "1660034913000"
      },
      {
        "event": "CardinalContinue",
        "detail": "Cardinal Session On Validated",
        "timestamp": "1660034913000"
      }
    ],
    "sessionid": "0_4065d0ef-2d49-4cde-8830-d6cb3ded830e",
    "application": "CardinalMobileSdk_iOS",
    "identifier": "e3ca59de-c8c4-4a6b-8cc1-5867e31e7424",
    "mutator": "CardinalLoggerV1",
    "version": "2.2.5-3"
  }
]
```

**Comment by jaxdesmarais** [comment]
Hello @naxel -

Would you mind reaching out to our [Technical Support team](https://developer.paypal.com/braintree/help) for this issue? They will need additional information about your account to investigate this issue further. Those details should not be shared over GitHub to protect your Production account.

I am going to close this issue on our end as the Technical Support team is the best point of contact for this issue.
