### ISSUE TITLE
Braintree/PayPal is not including the main Braintree clas

### ISSUE THREAD

**Issue by Reflejo** [braintree/braintree_ios#86]
I'd like to use Braintree/Paypal subspec and not include the Drop-In stuff. The problem is that the subspec doesn't include the `Braintree/*.{m,h}` files. I see two possible solutions here:

a. Include `"Braintree/*.{m,h}"` to the PayPal subspec source_files
b. Create a "Default" subspec with only `s.source_files = "Braintree/*.{m,h}"` and include `Braintree/Default` from the PayPal subspec

Thoughts?

**Comment by mickeyreiss** [comment]
Which specific classes or methods are you interested in using? Maybe I can guide you to an integration method that will already work for you.

For background: right now, only the main `Braintree` pod is documented publicly; we consider direct usage of the PayPal subspec an "advanced" integration. In the next major revision, we intend to make it much easier to pick and choose code for the payment methods you care about.

**Comment by Reflejo** [comment]
@mickeyreiss I was just talking about the generic `Braintree` class a.k.a the "Front door to the Braintree SDK". But I see what you are saying. Probably that class makes some assumptions that I'm breaking by not importing the DropIn stuff.

**Comment by mickeyreiss** [comment]
Yes, the `Braintree` class is currently built in such a way that it assumes you use _all_ aspects of v.zero.

In this case, I suspect that initializing a `BTPaymentProvider` or `BTPaymentButton` directly will do the trick:

```objectivec
  BTClient *client = [[BTClient alloc] initWithClientToken:YOUR_CLIENT_TOKEN];
  // Be sure to retain the paymentProvder
  self.paymentProvider = [[BTPaymentProvider alloc] initWithClient:self.client];
  self.paymentProvider.delegate = delegate;
  [self.paymentProvider createPaymentMethod:BTPaymentProviderTypePayPal];
```

**Comment by Reflejo** [comment]
@mickeyreiss Yeah I tried that before but the problem is that `BTPaymentProvider` (I'd guess this is part of the "Braintree/Payments" subspec) is not included in `PayPal` subspec.

**Comment by mickeyreiss** [comment]
For PayPal Touch without Drop In, `Braintree/Payments` is the right way to go. I should have mentioned this when I suggested initializing `BTPayment{Button,Provider}` directly.

 `Braintree/PayPal` is already a dependency of `Braintree/Payments`, so it is not possible to add `s.dependency "Braintree/Payments"` to the `PayPal` subspec.

**Comment by Reflejo** [comment]
Yeah that makes sense. I'm gonna use `/Payments`, thanks for the help.

**Comment by mickeyreiss** [comment]
:+1:
