### ISSUE TITLE
Build fails when using `xcodebuild` with custom `CONFIGURATION_BUILD_DIR`

### ISSUE THREAD

**Issue by j3k0** [braintree/braintree_ios#880]
**Integration Details:**
 - Braintree SDK Version: 5.14.0
 - iOS Version: iOS 12.0
 - Xcode Version: Xcode 12.5
 - Integration type & version: CocoaPods 1.11.3
 - Development Processor Type: M1

**Describe the bug**
Build fails when building XCode project in command-line (CI environment) with a custom CONFIGURATION_BUILD_DIR parameter. The error is: `SOME_PATH/Braintree.modulemap` not found.

**To Reproduce**
1. include the Braintree framework with CocoaPod in the app.
2. Compile with `xcodebuild -workspace PROJECT.xcworkspace -scheme MY_SCHEME -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone SE (3rd generation)" build CONFIGURATION_BUILD_DIR=/CUSTOM_DIR/build/emulator SHARED_PRECOMPS_DIR=/CUSTOM_DIR/build/sharedpch`

**Expected behavior**
The project should build when using a custom build directory.

**Discussion and proposed fix**
The issue is that the build script assumes that `${PODS_CONFIGURATION_BUILD_DIR}/Braintree` is always equal to `${BUILT_PRODUCTS_DIR}`, so uses both interchangeably.

For instance, in `platforms/ios/Pods/Target Support Files/Pods-DemoSX/Pods-DemoSX.debug.xcconfig`:
```
OTHER_CFLAGS = $(inherited) -fmodule-map-file="${PODS_CONFIGURATION_BUILD_DIR}/Braintree/Braintree.modulemap"
```

While in the Build Phase "_copy generated compability headers_" copies it to `${BUILT_PRODUCTS_DIR}/${PRODUCT_MODULE_NAME}.modulemap`.

The fix is to update the added Build Phase "_copy generated compability headers_" to use the same path:

<img width="1292" alt="Screen Shot 2022-10-18 at 13 39 43" src="https://user-images.githubusercontent.com/191881/196408787-255f14f8-31f0-4262-a5e3-4fab32f00b29.png">

**Comment by j3k0** [comment]
Notice I got a similar issue with `Braintree-umbrella.h` -- I fixed that and the "Output files" section, to the following:

<img width="1240" alt="Screen Shot 2022-10-18 at 14 18 57" src="https://user-images.githubusercontent.com/191881/196415880-396be26e-1020-4103-9a35-60b3e45dd79c.png">

**Comment by mattwylder** [comment]
👋 Hi there! Thanks for using the Braintree SDK. We were unable to reproduce these errors by importing Braintree through Cocoapods into brand new new Obj-C and Swift test apps. `xcodebuild` without the custom build directories works. This appears to be a known [Cocoapods issue](https://github.com/CocoaPods/CocoaPods/issues/10675). Please follow and contribute to their issue.
