### ISSUE TITLE
Remove Objective-C classes `+load` method in BTDataCollector to improve app startup time. 

### ISSUE THREAD

**Issue by aarka116** [braintree/braintree_ios#899]
**Is your feature request related to a problem? Please describe.**

We have noticed that Braintree SDK does [some initialization](https://github.com/braintree/braintree_ios/blob/218f5a2f085c3359ccf2638165c89bcdb0c670c7/Sources/BraintreeDataCollector/BTDataCollector.m) using Objective-C classes `+ (void)load` method. 
Since iOS runs `+load` essentially before app's `main()`  our app startup time is increased by ~10ms. 

<img width="351" alt="Screen Shot 2022-12-01 at 11 53 03 PM" src="https://user-images.githubusercontent.com/24439396/205130803-1b75a638-2d7c-4e2e-8c8c-532493847ea8.png">

**Describe the solution you'd like**

Remove current initialization from `+load` methods and move the code to a later in app's cycle or lazily initialize only when necessary so apps startup time is improved.

**Comment by scannillo** [comment]
👋 Hello @aarka116 - thanks for opening this issue with us. Currently we have two `DataCollector` modules available. 

One is `BTDataCollector`, which is in Objective-C and was meant for our legacy merchants who used [Kount Custom ](https://developer.paypal.com/braintree/docs/guides/premium-fraud-management-tools/client-side#kount-custom-integration)for fraud management. Kount integrations are no longer supported, and `BTDataCollector` is being removed in the next major version (V6) of the SDK (see [deprecation PR](https://github.com/braintree/braintree_ios/pull/895)).

The other module is `PayPalDataCollector` which, in Braintree iOS V5, is the recommended one you use. It is written in Swift and doesn't not perform any operations on app load. You should simply call `collectPayPalDeviceData()` ([code](https://github.com/braintree/braintree_ios/blob/218f5a2f085c3359ccf2638165c89bcdb0c670c7/Sources/PayPalDataCollector/Public/PayPalDataCollector/PPDataCollector.swift#L46-L52)) before submitting your nonce to your server for Transaction (see [docs](https://developer.paypal.com/braintree/docs/guides/premium-fraud-management-tools/client-side#implementation)).

Let me know if that clears things up and provides you a path forward.

**Comment by aarka116** [comment]
Thanks for the detailed explanation @scannillo. We'll make the switch to use `PayPalDataCollector. collectPayPalDeviceData()` from `BTDataCollector.collectDeviceData()`. 

quick question here, is `PayPalDataCollector` considered as complete replacement for `BTDataCollector`? 

Also wanted to check on the release timeline of the first v6 version where `BTDataCollector` is removed from the SDK? to watch out for and upgrade sooner as merely having the file would affect app launch due to nature of +load method.

**Comment by scannillo** [comment]
👍 Happy to help. We don't have a date yet, but likely early 2023 will be our first beta release of V6. If you have any other questions / concerns please let us know!
