### ISSUE TITLE
Is there any way of checking for Paypal Touch?

### ISSUE THREAD

**Issue by Reflejo** [braintree/braintree_ios#90]
Is there any *public* way to check if paypal touch is installed before starting the flow?. I could always use canOpenURL with the paypal scheme but I was wondering if you guys thought on any "official" way of checking this.

Or better: Is there any way to predict if the flow will use the paypal app or the modal?

**Comment by mickeyreiss** [comment]
Not currently.

Workaround: What if you tried calling `-[BTPaymentProvider createPaymentMethod:options]` allowing only app switch?

**Comment by Reflejo** [comment]
The problem with the workaround is that I have to create a delegate just to get the error. Any chance to make `appSwitchAvailableForClient` public?

**Comment by Reflejo** [comment]
We could assume that if requestsPresentationOfViewController is called then the app is not available and set a flag somewhere. But I'd rather have a more functional approach and have a way to predict the flow.

**Comment by mickeyreiss** [comment]
The supported way to do this right now is by recording invocations to `-paymentMethodCreatorWillPerformAppSwitch:`. The easiest way to achieve this is via a `BOOL` `@property` in the class that conforms to `BTPaymentMethodCreationDelegate`.

We will try to iron this out in the next major revision of the SDK.
