### ISSUE TITLE
Drop UI forever loading

### ISSUE THREAD

**Issue by chaitubndr07** [braintree/braintree_ios#92]
Drop UI stopped working with same credentials which worked before.
It loads forever, I was not clear about the issue, since UI is handled based on client token.

Console displays error message 
"negative or zero item sizes are not supported in the flow layout"

Is there any possibility to fix this issue from my end. Please suggest if available.

**Comment by nirinchev** [comment]
I've hit the same issue - when running an empty app with the sample token from the 'Hello Client' guide in the simulator, I get a 'Connection Error' alert. When I run the app on device, it just loads indefinitely.

In both cases, I get the "negative or zero item sizes are not supported in the flow layout" error message in the console.

**Comment by mickeyreiss** [comment]
Thanks for the report. We believe that there is currently an issue affecting the iOS SDK in sandbox only and we are investigating.

**Comment by mickeyreiss** [comment]
Also please note that "negative or zero item sizes are not supported in the flow layout" is due to an unrelated known bug in `BTPaymentButton` (#65).

**Comment by mickeyreiss** [comment]
@chaitubndr07 @nirinchev We've deployed changes to our sandbox API server configuration that should fix this issue. Can you please try again?

**Comment by mickeyreiss** [comment]
Please also note our official status site incident: https://status.braintreepayments.com/incidents/ypbc8csb6hpk

**Comment by nirinchev** [comment]
I can confirm that it now works as expected. Kudos for the fast response.

**Comment by mickeyreiss** [comment]
Thanks for the confirmation.

**Comment by mickeyreiss** [comment]
I've proposed a PR to prevent this type of issue in the future: #94.

**Comment by chaitubndr07** [comment]
Thanks @mickeyreiss for the response, it works
