### ISSUE TITLE
Apple Pay forever loading

### ISSUE THREAD

**Issue by jesprqrd** [braintree/braintree_ios#93]
Calling tokenizeApplePayPayment in sandbox currently never calls the completion block. Related to #92?

**Comment by mickeyreiss** [comment]
Yes, I believe this is one and the same with #92. Can you please try again now?

**Comment by jesprqrd** [comment]
Works now. Thanks!

**Comment by mickeyreiss** [comment]
:sweat_smile:

**Comment by mickeyreiss** [comment]
I've proposed a PR to prevent this type of issue in the future: #94.
