### ISSUE TITLE
4.x.x version support

### ISSUE THREAD

**Issue by userException** [braintree/braintree_ios#942]
On the iOS Braintree SDK(https://github.com/braintree/braintree_ios) GitHub page it is written that version 4.x.x will be unsupported from Feb 2023.
I have two questions:
1. Will this be unsupported after the end of Feb 2023 or starting Feb 2023
2. When it is unsupported, will the payments also stop working if the app is still using the SDK or is it just that you guys won't entertain any issues with this version?

**Comment by scannillo** [comment]
👋 Hi @userException. Thank you for the question. In that [section](https://github.com/braintree/braintree_ios#versions) of the README, we link out to our [developer documentation](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/ios/v5) that has more detail on what the different SDK statuses mean. 

Our "unsupported" versions are defined as:

* No longer supported by Braintree developers or Braintree Support. 
* Processing for these SDKs can be suspended at any time.
* No longer receive security updates.

You can also see a nice timeline of when an SDK version will go through the various statuses, this way you can plan for its deprecation and upgrade accordingly.

**Comment by scannillo** [comment]
> 1. Will this be unsupported after the end of Feb 2023 or starting Feb 2023

The later.

> 2. When it is unsupported, will the payments also stop working if the app is still using the SDK or is it just that you guys won't entertain any issues with this version?

The later. However if a vulnerability comes up with an unsupported version, processing may be suspended at any time. I think this is unlikely for braintree_ios v4 anytime soon, but still good to upgrade as soon as you can.
