### ISSUE TITLE
`Braintree/Apple-Pay` required by `Podfile`

### ISSUE THREAD

**Issue by anthonylai** [braintree/braintree_ios#95]
Hi,

  With Braintree (3.6.0-rc3), wanted to add apple-pay, added the following in Podfile:

pod 'Braintree'
pod 'Braintree/Apple-Pay'

Got the following error when running pod install:
Analyzing dependencies

CocoaPods 0.36.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

[!] Unable to satisfy the following requirements:

- `Braintree/Apple-Pay` required by `Podfile`
- `Braintree/Apple-Pay` required by `Podfile`
- `Braintree/Apple-Pay` required by `Podfile`

Installing Braintree without Apple-Pay works as expected.

Please assist.

**Comment by mickeyreiss** [comment]
Duplicate with #91. To summarize, `Braintree/Apple-Pay` will only come into existence once `3.6.0` is tagged and released.

@intelliot and I are working on deploying version `3.6.0` right now :innocent: .

**Comment by mickeyreiss** [comment]
I think this is a similar to #91. Can you try again now that 3.6.0 is fully released?

Apologies for the temporary discrepancy between our docs and the code.
