### ISSUE TITLE
Property description

### ISSUE THREAD

**Issue by NoceloEder** [braintree/braintree_ios#96]
Im trying integrate this SDK (via cocoapods), but I get following error in header "BTPaymentMethod_Mutable.h":

*Auto property synthesis will not synthesize property 'description' beacause it is 'readwrite' but it will be synthesized 'readonly' via another property.*

Actually Im using in my Pod file :
 **pod 'Braintree', '~> 3.0.0'**

**Comment by mickeyreiss** [comment]
Duplicate with https://github.com/braintree/braintree_ios/issues/77.

(Solution: Change your specified version to something more recent, like `~> 3.5`.)

I've also gone ahead and updated [our docs site](https://developers.braintreepayments.com/ios+ruby/sdk/client/setup#installation), to remove the misleading `~> 3.0.0` bit.

**Comment by mickeyreiss** [comment]
I'm also updating [this page](https://developers.braintreepayments.com/ios+ruby/start/hello-client), which may have led to the confusion.
