### ISSUE TITLE
Provisioning profile "iOS Team Provisioning Profile: com.w.Wardrobe" doesn't match the entitlements file's value for the com.apple.developer.in-app-payments entitlement.

### ISSUE THREAD

**Issue by bhanudhimanHF** [braintree/braintree_ios#962]
### Braintree SDK Version

5.20.1

### Environment

Sandbox

### Xcode Version

14.1

### OS Version & Device

16.0.2

### Integration type

CocoaPods

### Development Processor

Intel

### Describe the bug

I just created merchant ID in apple developer and linked with Braintree but when I was added it to Apple Pay merchant id it will showing a error given as below in screen shot:-

### To reproduce

I just created merchant ID in apple developer and linked with Braintree but when I was added it to Apple Pay merchant id it will showing a error

### Expected behavior

I just created merchant ID in apple developer and linked with Braintree but when I was added it to Apple Pay merchant id it will showing a error

How can I fixed thing I'm trying to build new merchant id again and again but I'm not getting to fixed this thing please help me out.

This is my code:-
 let applePayClient = BTApplePayClient(apiClient: self.braintreeClient!)
 ```
applePayClient.paymentRequest { (paymentRequest, error) in
       guard let paymentRequest = paymentRequest else {
            completion(nil, error)
            return
        }
        paymentRequest.requiredBillingContactFields = [.postalAddress]
        paymentRequest.merchantIdentifier = "merchant.merchant.com.HF.wardrobe"
        paymentRequest.countryCode = "AU"
        paymentRequest.currencyCode = "AUD"
        paymentRequest.merchantCapabilities = .capability3DS
        paymentRequest.paymentSummaryItems =
         [
             PKPaymentSummaryItem(label: "COMPANY NAME", amount: 40),
         ]
  }
```

### Screenshots

![Screen Shot 2023-02-28 at 12 51 28 PM](https://user-images.githubusercontent.com/103092605/221782860-5243e052-00df-4e8a-94d4-d4582255fb39.png)

![Screen Shot 2023
![File](https://user-images.githubusercontent.com/103092605/221783527-fb00086f-d549-4ea2-a66b-fe880f83420b.jpg)

-02-28 at 12 54 38 PM](https://user-images.githubusercontent.com/103092605/221782915-6c1ac1e8-c347-4d2f-b6a2-645c836611d6.png)

**Comment by scannillo** [comment]
Please follow our [documentation](https://developer.paypal.com/braintree/docs/guides/apple-pay/configuration) on how to configure Apple Pay permissions for your app. You should also reference [Apple's docs ](https://developer.apple.com/documentation/passkit/apple_pay/setting_up_apple_pay)for this setup, as well.
