### ISSUE TITLE
Unable to test venmo with test card accounts.

### ISSUE THREAD

**Issue by HimanDhawan** [braintree/braintree_ios#966]
### Braintree SDK Version

5.16.0

### Environment

Sandbox

### Xcode Version

Version 14.0 

### OS Version & Device

iPhone 13

### Integration type

CocoaPods

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

Unable to add test accounts for venmo mentioned in https://developer.paypal.com/braintree/docs/reference/general/testing#payment-method-nonces.
We have to add real cards in order to test payments for sandbox. 
How we can have test accounts for testing venmo in sandbox?

### To reproduce

1. Integrate Venmo.
2. Switch app to venmo
3. Add cards mentioned in the above link.
4. Error while adding cards.

### Expected behavior

There should not be any error while adding test cards.

**Comment by scannillo** [comment]
👋 Hi @HimanDhawan - thanks for using the Braintree iOS SDK.

To test Venmo in sandbox, you will need production funding instruments linked in a Venmo account. These transactions, when initiated from the Braintree SDK in sandbox, will not be charged.

For further questions/help on testing your integration, please instead contact Braintree Developer Support - https://developer.paypal.com/braintree/help. Please also see our [docs](https://developer.paypal.com/braintree/docs/guides/venmo/testing-go-live#sandbox-testing) on testing Venmo integrations.

This GH Issues forum is for bugs/ issues & feature requests specific to the iOS SDK. In the future, if you encounter SDK-specific bugs, feel free to open a new issue here.
