### ISSUE TITLE
A bad crash of SIGSEGV

### ISSUE THREAD

**Issue by DoneLiu** [braintree/braintree_ios#987]
### Braintree SDK Version

4.35.0

### Environment

Production

### Xcode Version

Xcode 14.1

### OS Version & Device

iPhone 12 - iPhone 16.1

### Integration type

CocoaPods

### Development Processor

Intel

### Describe the bug

![image](https://user-images.githubusercontent.com/15603425/227419963-ed9851e7-9465-4eb7-99d4-d020682dd287.png)

### To reproduce

a bad crash online of SIGSEGV, how can i solved it ?

### Expected behavior

can i upgrade idk's version to resolve it ? what the version is ?

### Screenshots

![image](https://user-images.githubusercontent.com/15603425/227420054-a4c93fb3-b021-44ae-b1ba-139b25994476.png)

**Comment by jaxdesmarais** [comment]
Hello @DoneLiu -

You will need to update to v5 of the SDK. It is worth noting [v4.35.0](https://github.com/braintree/braintree_ios/blob/4.35.0/CHANGELOG.md) was released August 10, 2020. Additionally v4 of our SDK is unsupported as of February 2023 ([as noted here](https://github.com/braintree/braintree_ios#versions)). Please let us know if you are still running into issues after updating to v5 of the SDK.
