### ISSUE TITLE
No security policy for vulnerability disclosure

### ISSUE THREAD

**Issue by yhkaplan** [braintree/braintree_ios#992]
### Is your feature request related to a problem? Please describe.

As a payments SDK, please provide a `SECURITY.md` file with information on how to disclose vulnerabilities.

https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

**Comment by scannillo** [comment]
👋 Hi @yhkaplan - thank you for submitting this request to the Braintree iOS SDK.

Currently, our repo just uses the default issue template for reporting security vulnerabilities. But we can and should update this to be more specific to our product.
![Screenshot 2023-03-29 at 9 31 16 AM](https://user-images.githubusercontent.com/35243507/228572530-7f9cbce5-3016-4c62-a18b-83fe84609876.png)

**Comment by yhkaplan** [comment]
@scannillo Thanks for the quick reply! What is the private contact information I should use then? Because GitHub Issues are public, I think the more common practice is to look for instructions in the the security policy under the Security tab first.

**Comment by scannillo** [comment]
I am going to close this issue as our team just doesn't have the capacity to look into this across all of our public repos. Please raise security concerns to https://developer.paypal.com/braintree/help, or via our GitHub issues forums if appropriate.

**Comment by hollabaq86** [comment]
@yhkaplan if you don't feel comfortable reporting a vulnerability via the issue workflow Sammy presented, you can always submit a report via [HackerOne](https://hackerone.com/paypal?type=team).
